### ISSUE TITLE
Is it possible to generate multiple docs and pages for one project

### ISSUE THREAD

**Issue by zhaobenx** [swaggo/swag#1000]
**Problems I met**

Suppose that I want to create different versions of api in one project, so I want to make several separate swagger pages.

e.g. /api/v1/swagger/index.html, api/v2/swagger/index.html

But for now, it seems that `swag.swag` is a global variable, and cannot register for twice.  Is there any elegant way to have multiple pages by tags or packages?
 https://github.com/swaggo/swag/blob/a76cfa3cf8d0740ad3587693d94c93480706376f/swagger.go#L22-L33

**Possible solution**
No idea. Now I have to generate docs separately and serve them in static html.

**Comment by ubogdan** [comment]
There is no way doing that at this time.

Duplicate #32, #949.

**Comment by eduardo-mior** [comment]
I have the same problem.
I have internal documentation for my team and I have public documentation for other companies to consume. How can I solve?

**Comment by ubogdan** [comment]
You can contribute to the project. :p
