### ISSUE TITLE
Wrong defination generation for struct that has embedding and a json tag.

### ISSUE THREAD

**Issue by PrashantRaj18198** [swaggo/swag#1013]
**Describe the bug**
Defination generated is wrong when another struct (child struct) has been embedded in the struct (parent struct) without an explicit field and contains a json tag, the generator ignores the json tag and plugs all the fields of the child struct into the parent struct which is not the case when you marshal the object. After mashaling, you get all the fields inside the json tag name.
For example,
[In this fork of swag](https://github.com/PrashantRaj18198/swag/blob/73dcafe6dcf8730f175c8bd4e42d590f541fb8fc/testdata/pet/web/handler.go#L20) we can see the `Category` struct to be embedded in the `Pet` struct without an explicit field and the the json tag is `category`. This should produce all the fields of `Category` in this format `Pet.Category.CategoryField`. But this instead generates the spec in the format `Pet.CategoryField`, `Pet.AnotherCategoryField`.

**To Reproduce**
1. Clone the fork
2. Do `cd testdata/pet`
3. Do `swag init`
4. Go to the generated `swagger.json` and see the defination for `web.Pet`

**Expected behavior**
Build the correct defination that refectls the json structure.

**Screenshots**
Screenshots for the example
![image](https://user-images.githubusercontent.com/23168997/135404333-6a4c9676-a544-44fa-a84d-bab9a19a49c0.png)
![image](https://user-images.githubusercontent.com/23168997/135404410-9633cfe4-1982-4bb3-865e-42064c2ef6a4.png)

**Your swag version**
1.7.1
**Your go version**
1.17.1 linux/amd64

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Chrome
 - Version: Version 92.0.4515.159 (Official Build) (64-bit)

**Additional Context**
[Playground link I used to create the json marshalled structure](https://play.golang.org/p/4o2oC9PSHEg)

**Comment by sdghchj** [comment]
json tag will be ignored for embedded struct

**Comment by wu0407** [comment]
same issue with kubernetes pod defination that miss `metadata` filed.
https://github.com/kubernetes/api/blob/b3fcc5e80fda1a43a3ad2e0dfb89a8572584959e/core/v1/types.go#L3877-L3896

expected like this:
```
            "metadata": {
                "name": "ratings-v1-c9599c9c9-nq6jf",
                "generateName": "ratings-v1-c9599c9c9-",
                "namespace": "default",
                "selfLink": "/api/v1/namespaces/default/pods/ratings-v1-c9599c9c9-nq6jf",
                "uid": "5ab6a970-39fb-46d9-a59f-9613a0b4d520",
                "resourceVersion": "326430122",
                "creationTimestamp": "2021-08-03T02:36:18Z",
                "labels": {
                    "app": "ratings",
                    "pod-template-hash": "c9599c9c9",
                    "version": "v1"
                },
                "annotations": {
                    "sidecar.istio.io/inject": "true"
                },
                "ownerReferences": [
                    {
                        "apiVersion": "apps/v1",
                        "kind": "ReplicaSet",
                        "name": "ratings-v1-c9599c9c9",
                        "uid": "695025b4-002e-4b59-bb8b-79c9f33c5d6b",
                        "controller": true,
                        "blockOwnerDeletion": true
                    }
                ],
```

But get:

```
 {
      "annotations": {
        "additionalProp1": "string",
        "additionalProp2": "string",
        "additionalProp3": "string"
      },
      "apiVersion": "string",
      "clusterName": "string",
      "creationTimestamp": "string",
      "deletionGracePeriodSeconds": 0,
      "deletionTimestamp": "string",
      "finalizers": [
        "string"
      ],
      "generateName": "string",
      "generation": 0,
      "kind": "string",
      "labels": {
        "additionalProp1": "string",
        "additionalProp2": "string",
        "additionalProp3": "string"
      },
```

**Comment by ubogdan** [comment]
Changing the embedded struct output is considered a breaking change, and it's not an option we can consider.
