### ISSUE TITLE
Dynamic API Info not propagating

### ISSUE THREAD

**Issue by josephzidell** [swaggo/swag#1018]
**Describe the bug**
Following the example for setting API info dynamically, in `main.go` in `main()`, the information is not propagating into the generated `.json` and `.yaml` files.
```go
func main() {
	docs.SwaggerInfo.Version = "0.0.1"
	docs.SwaggerInfo.Host = "localhost"
	docs.SwaggerInfo.BasePath = "/api/v1"
	// ...
}
```

**To Reproduce**
1. Add `docs.SwaggerInfo.Version = "0.0.1"` to `main()`
2. Run `swag init`

**Expected behavior**
The `swagger.json` and `swagger.yaml` files have the version, host, and base path.

**Screenshots**
<img width="410" alt="image" src="https://user-images.githubusercontent.com/1812443/136328425-5914d974-6752-4651-97a4-a9b800a88daa.png">

<img width="336" alt="image" src="https://user-images.githubusercontent.com/1812443/136328604-7b49cd3d-0349-4aa7-9208-2b1b647688da.png">

**Your swag version**
1.7.3

**Your go version**
1.17.1

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome/Firefox
 - Version: Latest versions

**Additional context**
When importing the `docs` package, the readme shows `import "./docs"`, which does not work. I have to `import "<full_path>/docs`. Not sure if that makes a difference.

**Comment by ubogdan** [comment]
@josephzidell, I have no clue what you expect to see in the `Readme.md`  to clarify this. 

Would you mind contributing with a PR regarding this matter?
