### ISSUE TITLE
Omitting host returns Internal Server Error (500)

### ISSUE THREAD

**Issue by akshay196** [swaggo/swag#1019]
**Describe the bug**
When I omit `host` field in a Gin based application and try to access API documentation using `localhost:5000/swagger/index.html` I get `Fetch error Internal Server Error doc.json`. Screenshot attached.

Received 500 in the application log:
```
[GIN] 2021/10/07 - 13:20:11 | 500 |        9.59µs |       127.0.0.1 | GET      "/swagger/doc.json"
```

As per the Swagger 2.0 specification, **host and schemes can be omitted for a more dynamic association. In this case, the host and scheme used to serve the API documentation will be used for API calls.** ([reference](https://swagger.io/docs/specification/2-0/api-host-and-base-path#omit))

**To Reproduce**
1. Develop Gin application with no host specified.
```
// @title App
// @version 0.1
// @description application description

// @BasePath /

// @securityDefinitions.apikey Token
// @in header
// @name Authorization
func main() {
	app := gin.Default()
        //...
}
``` 
2. Run `swag init`
3. Then run your application
4. Visit `localhost:5000/swagger/index.html` (application is running at localhost:5000)
5. See error in browser

**Expected behavior**
The API documentation should not return 500. The host and scheme used to serve the API documentation will be used for API calls.

**Screenshots**
![Screenshot from 2021-10-07 13-26-58](https://user-images.githubusercontent.com/16691314/136343497-6db89882-72cb-4434-bef2-609954622492.png)

**Your swag version**
v1.7.3

**Your go version**
1.16.5

**Desktop (please complete the following information):**
 - OS: Linux/Fedora
 - Browser: Firefox
 - Version:

**Comment by akshay196** [comment]
This [comment](https://github.com/swaggo/swag/issues/830#issuecomment-725587162) solved this issue.

**Comment by volkansolak** [comment]
Hi, i am having this problem too. How did you analyze it?

**Comment by samozturk** [comment]
You need to import docs package in your main package. 
docs package is created by swagger when you `swag init`.

**Comment by beijJxy** [comment]
> You need to import docs package in your main package. docs package is created by swagger when you `swag init`.

Thank you so much

**Comment by Anorboyev-Xayrullo** [comment]
You need to import docs package in your main package.
docs package is created by swagger when you swag init.
