### ISSUE TITLE
Error when parsing URL parameters (params)

### ISSUE THREAD

**Issue by adrien3d** [swaggo/swag#1024]
**Describe the bug**
`swag init` fails when trying to parse URL parameters

**To Reproduce**
1. Define route:
```
// GetEntities to get all entities
// @Produce json
// @Param id path string true "Entity ID"
// @Param limit path int true "Limit" default(100)
// @Param order path int true "Timestamp order, can be 1 for asc or -1 for desc" default(1)
// @Success 200 {object} []models.Entity
// @Router /v1/entity/{id}/data?limit={limit}&order={order} [get]
// @Security ApiKeyAuth
func (ec EntitiesController) GetEntities(c *gin.Context) {
```
2. Run `swag init`
3. Fails with following message: `ParseComment error in file controllers/entity.go :can not parse router comment "/v1/entity/{id}/data?limit={limit}&order={order}[get]"`

**Expected behavior**
Parsing correctly the route.

**Your swag version**
1.7.3

**Your go version**
1.17.1

**Comment by ubogdan** [comment]
The following definition will add to the URL route ?limit=X
```
// @Param limit path int true "Limit" default(100)
```
