### ISSUE TITLE
Individual tags for same operation with multiple routes.

### ISSUE THREAD

**Issue by pomaretta** [swaggo/swag#1028]
**Is your feature request related to a problem? Please describe.**
I have defined two routes for the same operation, but I need each route to be on his tag group separately.

**Describe the solution you'd like**
I would like to define a tag group before declaring the route.

```
// @Route /some/path [get]
// @Tag SomeGroup
// @Route /some/other/path [get]
// @Tag OtherAwesomeGroup
```

**Describe alternatives you've considered**
I need to have an empty handler declaring a new route for the same functionality.

**Additional context**
I need to duplicate an endpoint on other route and for different tag group on swagger.

**Comment by pomaretta** [comment]
Yeah, I know that you can assign more than one tag for the same operation, the thing is you can't assign a tag for a specific route, but you can handle more than one route for the same operation. My use case, is I have a function that is the same for two routes. What I tried to do is for the same operation define two GET Routes, but when assigning Tags to those routes, will assign all Tags for the two routes, I need to define one tag separately for each route. The quick solution is having a wrapper function that returns the another and create new route definitions.

**Comment by sdghchj** [comment]
I got your point.
At begin, one operation had only one route.  
Later someone wanted two or more routes share the the same elements of one operation.
I think your requirement may lead to other endless requirements such as individual descriptions,consumes,produces,parameters,responses, for multiple routes.
If that, there's no difference, compared to defining two operations.
