### ISSUE TITLE
Body string parse

### ISSUE THREAD

**Issue by bajro17** [swaggo/swag#1035]
**Describe the bug**
I try to use string for body but when try to parse my files I get Unknown Type: primitive

**Screenshots**

![screenshot-127 0 0 1_8080-2021 10 23-09_34_45](https://user-images.githubusercontent.com/16452914/138550624-8adf3771-b659-4a14-8a99-73f7ba866dc5.png)

![Screenshot 2021-10-23 093427](https://user-images.githubusercontent.com/16452914/138550632-453d7bb6-3120-4b32-973c-f034a96e7224.png)

![Screenshot 2021-10-23 112019](https://user-images.githubusercontent.com/16452914/138550668-c1632932-6c0e-4325-a250-5e117ff6d49e.png)

**Your swag version**
1.7.3

**Your go version**
1.17.2

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave

**Comment by ubogdan** [comment]
@bajro17 any updates?
