### ISSUE TITLE
error not resolving host and base path.

### ISSUE THREAD

**Issue by aohan0503** [swaggo/swag#1042]
**Describe the bug**
not resolving host and base path.

**To Reproduce**
1. add comments 
2. swag init 
3. compile
4. see invalid Base URL: {{.Host}}{{.BasePath}}

**Expected behavior**
This:
curl -X GET "https://{{.Host}}{{.BasePath}}/api/version" -H "accept: text/plain"

should be:
curl -X GET "https://localhost:8443/api/version" -H "accept: text/plain"

**Screenshots**
![image](https://user-images.githubusercontent.com/81146139/139838322-ce9e216b-a957-410f-a3f9-541682b24fa4.png)

![image](https://user-images.githubusercontent.com/81146139/139838400-98e96de5-7866-4cec-a2f2-e1eb99b4bf34.png)

**Your swag version**
1.7.4

**Your go version**
 1.16.5

**Desktop (please complete the following information):**

 - OS: macOS
 - Browser: chrome
 - Version: 95.0.4638.54

**Additional context**

**Comment by ubogdan** [comment]
Hi @aohan0503 
 Not sure how you did that, but it doesn't look like the HTML template is rendered through ReadDoc() method.

See: https://github.com/swaggo/swag/blob/master/example/basic/docs/docs.go#L286

Please provide a code example in order to better understand the issue.

**Comment by aohan0503** [comment]
The reason for the error is that I used "{{ }}" annotations in the struct.
An error occurred while reading the swagger document,but swag does not have any error output.

**Comment by ubogdan** [comment]
I hope you did that by mistake. What else can we do here for you?

**Comment by Anddomize** [comment]
thx for this issue, I lost a lot of time for solve this error, but only after reading comments was able to solve the problem. it's very unfortunate that no error is displayed that report about problem.

**Comment by ubogdan** [comment]
@Anddomize This is an Open Source project. Please feel free to update the Readme.md to help the community.
