### ISSUE TITLE
copy the url

### ISSUE THREAD

**Issue by Li-Shuangzhi** [swaggo/swag#1044]
**front end programmers would like to copy the url ,but it isn't allowed us to copy**
![image](https://user-images.githubusercontent.com/60538671/140610047-a7aaae2b-a513-4f95-9dc1-e1b04a1f5cc0.png)

**Comment by ubogdan** [comment]
Oh, that isn't nice. :sweat_smile: 
Swag is an open API generator and the UI you are referring to is developed by this [project](https://github.com/swagger-api/swagger-ui). Please feel free to open an issue there.

Thanks.
