### ISSUE TITLE
Same output for all http Error

### ISSUE THREAD

**Issue by MayukhSobo** [swaggo/swag#1046]
**Describe the bug**
I am getting the same output for all the error codes in the example field. 

**To Reproduce**
Code used
```
// @Failure 400,500,404,401 {object} httputil.HTTPError
```

**Screenshots**
<img width="752" alt="Screenshot 2021-11-09 at 1 02 07 PM" src="https://user-images.githubusercontent.com/8527634/140881210-fa281cea-e56c-47ae-82a3-fd5a68c7ec3e.png">

**Your swag version**
e.g. 1.7.4

**Your go version**
e.g. go1.17.2 darwin/amd64

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: 15.1

**Comment by ubogdan** [comment]
that's; because the example value is of `httputil.HTTPError` struct is set to 400,"status bad request". Please take a look at your stuct.

**Comment by MayukhSobo** [comment]
How do I take the values for the given error codes?

**Comment by HYY-yu** [comment]
Can you provide more examples ?

**Comment by ubogdan** [comment]
> How do I take the values for the given error codes?

You can only do that if you use different structs definitions for each error code like `type Error404 struct {....`, `type Error500 struct {....`. 

You don't actually need to document with an example for each possible return code. The actual meaning of the Open API definition is to describe what is the response data structure not the data itself.
