### ISSUE TITLE
 `select a spec`  Is there no such function?

### ISSUE THREAD

**Issue by comwls** [swaggo/swag#1051]
Hi I've been using swaggo so well and I'm always grateful for it.

But
It's time to use the `select a spec` function.

But I couldn't find that function.

No matter how much I searched the documentation, I couldn't find it.
![스크린샷 2021-11-16 오후 11 51 53](https://user-images.githubusercontent.com/16363845/142008212-8ea3c5e9-9b7f-48f1-a24a-8a54e1df43d8.png)

Can't this function be implemented?

**Comment by ubogdan** [comment]
Unfortunately, swag is only an OpenAPI doc generator.
