### ISSUE TITLE
Add conditional in commentaries

### ISSUE THREAD

**Issue by ezequiel-aguilera-uala** [swaggo/swag#1052]
Like that
![Captura de Pantalla 2021-11-16 a la(s) 12 39 53](https://user-images.githubusercontent.com/92107069/142016690-bacf6ac2-bb47-47c9-af31-a5ba1856197a.png)

**Comment by ubogdan** [comment]
Can you be a little bit more specific about your request, please?

**Comment by ezequiel-aguilera-uala** [comment]
I mean Swag's comments. It would be nice if there is a way to
interpret them conditionally. For example @if (myVariable) [... Swag
comment]

[image: Logo] <https://www.uala.com.ar/>
Ezequiel Aguilera

Cel. (+54911) 2867-6833

Nicaragua 4677, CABA
<https://maps.google.com/?q=Nicaragua+4677,+CABA&entry=gmail&source=g>

**Comment by ubogdan** [comment]
I really don't see any benefit because swag produces the documentation a step forward of your software is getting built. 
This means `os.Getnv(COUNTRY)` will have no effect at runtime.
