### ISSUE TITLE
$ sign in router path generates parse error

### ISSUE THREAD

**Issue by sam-hoffman** [swaggo/swag#1053]
**Describe the bug**
Our API path includes `$` signs, as they're widely used in the FHIR medical record format. Including the `$` signs in the router comment leads to a swag error:  
```
ParseComment error in file main.go :can not parse router comment "/objects$modifier [get]"
```
**To Reproduce**
Create a `main.go` file with the following content:
```
package swag_test

// @id specialObjectList
// @Summary Special objects listing
// @Router /objects$modifier [get]
// @Description A special listing method...
// @Tags Test
func specialObjectList() {
}
```
Run `swag init`

**Expected behavior**
To have the `/objects$modifier` route correctly registered. 

**Your swag version**
e.g. 1.7.4

**Your go version**
go1.17.2 darwin/amd64

**Desktop (please complete the following information):**
 - OS: macOS 11.3.1

**Additional context**
I believe #551 was a similar issue; I'd be happy to make a similar PR to add a $ sign into the regex if it would be accepted.

**Comment by EmuuGrass** [comment]
try use version 1.6.7

**Comment by ubogdan** [comment]
@sam-hoffman I don't believe "/objects$modifier" is a valid route in OpenAPi spec. This may be the reason we are not accepting $ sign in route definitions.

**Comment by sam-hoffman** [comment]
@ubogdan is there a part of the OpenAPI spec that specifically prohibits `objects$modifier`? It would be super helpful to add, as FHIR is a widely used specification for medical data that calls for `$modifier`

**Comment by ubogdan** [comment]
@sam-hoffman it's not necessary about prohibiting then it's about you won't be able to use the generated definition with swagger-ui to test the API.

Extracted from [paths-and-operations](https://swagger.io/docs/specification/2-0/paths-and-operations/)
```
Swagger supports path templating, meaning you can use curly braces {} to mark parts of a URL as path parameters:

/users/{id}
/organizations/{orgId}/members/{memberId}
/report.{format}

```

**Comment by sam-hoffman** [comment]
We actually do manually add `$` signs in to our generated definitions in order to have our paths display correctly in swagger-ui. We were hoping to avoid having to manually add them.

**Comment by ubogdan** [comment]
I see. According to [rfc3986](https://www.rfc-editor.org/rfc/rfc3986#section-2.3), the provided path "/objects$modifier" contains a special character. 
I feel sorry for you, but this is not a valid issue, and we won't go forward with it.

**Comment by sam-hoffman** [comment]
What about #551, which also added a special character?

**Comment by ubogdan** [comment]
What about it?

**Comment by sam-hoffman** [comment]
It looks like it was accepted and swag now allows a `:` in router paths

**Comment by ubogdan** [comment]
We accepted that pr because It's a well-known practice (used in google API) and we felt like it's nice to have. 
I don't see any benefit to introduce another special character. Why can't you simply use ":"?

**Comment by sam-hoffman** [comment]
I can't use `:` because FHIR, a well known and widely used specification for medical data, uses `$`

**Comment by ubogdan** [comment]
Well, can you prove it?

**Comment by gmontagu** [comment]
Specifically, the FHIR spec defines operations which make use of the $ character.
https://www.hl7.org/fhir/operations.html

**Comment by ubogdan** [comment]
In the end, this is an OSS project , feel free to contribute and break it :smile:.

**Comment by sam-hoffman** [comment]
Nice, thank you :) Will send a PR soon
