### ISSUE TITLE
How to generate an XML attributes

### ISSUE THREAD

**Issue by iTanken** [swaggo/swag#1058]
There is a struct, field `Version` declared `xml:Version,attr` tag, but Version is a node in the generated XML instead of attribute:

```go
type Message struct {
    XMLName xml.Name `json:"-" xml:"MSG" swaggerignore:"true"` // XML Root

    Version string    `json:"Version,omitempty" xml:"Version,attr" example:"1.6"` // Message Version
    Code    string    `json:"Code,omitempty" xml:"Code,omitempty"`                // Status Code
    Time    time.Time `json:"Time,omitempty" xml:"Time,omitempty"`                // Response Time
} //@name MSG
```

### `swag init` generated **Example Value**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<MSG>
    <Version>1.6</Version> <!-- It should be the attribute of MSG. -->
    <Code>0</Code>
    <Time>2021-11-25T09:00:13.660</Time>
</MSG>
```

### This is what I want

```xml
<?xml version="1.0" encoding="UTF-8"?>
<MSG Version="1.6">
    <Code>0</Code>
    <Time>2021-11-25T09:00:13.660</Time>
</MSG>
```

Whether the `swag` supports generating XML attributes, what should I do?

**Comment by ubogdan** [comment]
@iTanken I don't think we are on the same page. Swag doesn't output any XML file.

**Comment by iTanken** [comment]
> @iTanken I don't think we are on the same page. Swag doesn't output any XML file.

```
// @Success 200 {object} Message "Successful information"
```

When the `Message` in the comment is XML struct, XML format will be generated.

**Comment by ubogdan** [comment]
Sorry but, I still don't get it.

**Comment by iTanken** [comment]
> Sorry but, I still don't get it.

Thanks. That does't matter anymore.
