### ISSUE TITLE
SwaggerUIBundle is not defined

### ISSUE THREAD

**Issue by 17-12-20-ll** [swaggo/swag#1071]
![image](https://user-images.githubusercontent.com/34705107/144370908-2900ac2b-c05e-4f4d-b62c-8e7272bb38f2.png)

**Your swag version**
github.com/swaggo/files v0.0.0-20210815190702-a29dd2bc99b2 // indirect
github.com/swaggo/gin-swagger v1.3.3 // indirect
github.com/swaggo/swag v1.7.6 // indirect

**Your go version**
github.com/gin-gonic/gin v1.7.7
go 1.16

**Comment by ubogdan** [comment]
Please open the issue on gin-swagger [issue](https://github.com/swaggo/gin-swagger/issues) tracker.
