### ISSUE TITLE
Swagger 3.0

### ISSUE THREAD

**Issue by sankalpbohra** [swaggo/swag#1074]
Any plans for Swagger 3.0? If not how cookie authentication would be enabled?

**Comment by ubogdan** [comment]
Hi @sankalpbohra,
  At the moment, swag supports only OAS 2.0 specs which don't support cookie authentication. 

We are thinking of supporting OAS 3, but the development road is long and complicated. At the same time, this is an Open Source project, and any contribution is greatly appreciated.

Duplicated: #548.
