### ISSUE TITLE
`.swaggo` file with custom mapping doesn't seem to work

### ISSUE THREAD

**Issue by bradleygore** [swaggo/swag#1076]
**Describe the bug**
I have a directory like this:
```
api/
  api.go //top-level API entry point
  |- v1/
  |- internal/
    |- types/
      |- nullwrappers.go //wrappers for nullable types like sql.NullInt64
  .swaggo //overrides for typing
```

My `.swaggo` file looks like this:
```
// Replace Null* fields types for swagger
Replace api/internal/types.NullInt64 int
Replace api/internal/types.NullInt32 int
Replace api/internal/types.NullString string

// Replace sqlx JSONTest for swagger
Replace github.com/jmoiron/sqlx/types.JSONText string
```

I try to run per this documentation: https://github.com/swaggo/swag#use-global-overrides-to-support-a-custom-type

`swag --overridesFile ./.swaggo init -g ./api/api.go -o ./api/swaggerdocs` (I've tried with and without the `./.swaggo` part)

I get this:
`Incorrect Usage. flag provided but not defined: -overridesFile`

If I run `swag` without `--overridesFile` it doesn't pick up the `.swaggo` file and errors out with unrecognized type if I don't use `swaggertype` tag on the field in question. I'd like to be able to globally set some of these type swaps.

Am I doing something wrong running it this way?

**swag version**
`1.7.6`

**go version**
`1.16.6`

**Desktop:**
`MacOS Big Sur 11.6.1`

**Comment by ubogdan** [comment]
@bradleygore the feature will be available from the v1.7.7 release. If you like to use it earlier you need to build swag from the master branch.

**Comment by bradleygore** [comment]
Ah ok - I didn't catch that @ubogdan. Thanks!

**Comment by ubogdan** [comment]
@bradleygore If you didn't notice, the feature is available in the current version.
