### ISSUE TITLE
Get ParseComment error while defining swaggertype struct 

### ISSUE THREAD

**Issue by Aldiwildan77** [swaggo/swag#1077]
**Describe the bug**
Can't parse the specific struct in another struct using swaggertype, so it gets an error with the message ``ParseComment error in file <path>:ProductVariantRequest is not basic types``

**To Reproduce**
1. Create parent struct
2. Create child struct
3. Define swaggertype in 1 key like ``swaggertype:"object,ProductVariantRequest"``
4. Run ``swag init``

**Expected behavior**
swag able to parse the child-parent 

**Screenshots**
Parent Struct
![image](https://user-images.githubusercontent.com/29916319/146108267-1153de48-fd83-40f7-a680-ec1aecbb5b1a.png)

Child Struct
![image](https://user-images.githubusercontent.com/29916319/146108312-446c47df-7823-4e6f-b038-2b7a5e91612d.png)

**Your swag version**
e.g. 1.7.6

**Your go version**
e.g. 1.17

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 96.0.4664.110

**Comment by ubogdan** [comment]
Have you tried to prefix the struct name with the package name? 

eg  ` swaggertype:"object,main.ProductVariantRequest" `

**Comment by ubogdan** [comment]
Any updates here?

**Comment by ktvbcx** [comment]
I also meet the same problem, and i tried by your step but it didn' work.could you please take a look?
struct
![1662606825813](https://user-images.githubusercontent.com/54368785/189025950-e4fb5cd2-bcbb-47a7-9e7d-69f39036f082.png)
cmd response
![image](https://user-images.githubusercontent.com/54368785/189026017-4bd82e32-f8db-474e-8196-af53f149f0f1.png)



> Have you tried to prefix the struct name with the package name?
> 
> eg `swaggertype:"object,main.ProductVariantRequest"`

**Comment by Jake-Convictional** [comment]
Based on the code, it seems that `swaggertype` only works for primitives and arrays of primitives. It does not actually work for custom structs, it looks like the intent of the `object` swaggertype was for maps only. I agree that this is a frustration, currently looking into how to augment it.

**Comment by itsprdp** [comment]
@ubogdan could we reopen this issue? I don't think this is addressed and I'm running into a similar issue.
