### ISSUE TITLE
Can't generate definitions (models) on struct

### ISSUE THREAD

**Issue by Aldiwildan77** [swaggo/swag#1078]
**Describe the bug**
Can't generate the definitions (models) by defined swag on a struct. 

**To Reproduce**
1. Create struct with an example, name, swaggertype, and swaggerignore
2. Run `swag init`
3. Check the Swagger UI / generated code.

**Expected behavior**
Definitions (models) generated while the struct is not called in any endpoint/controller
![image](https://user-images.githubusercontent.com/29916319/146110346-aade0b19-ac26-47a8-b134-0abf35ff1bf9.png)

**Screenshots**
Defined struct for definitions (models)
![image](https://user-images.githubusercontent.com/29916319/146110367-23bec971-7f1c-4c49-8f0b-cabb04897f08.png)

**Your swag version**
e.g. 1.7.6

**Your go version**
e.g. 1.17

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 96.0.4664.110

**Comment by ubogdan** [comment]
If you don't reference the struct in a router request or response it won't export the definition. This is not a bug.
```go
// @Success      200  {object}  model.Account
// @Param        id   body      mode.Account  true  "Account"

```

**Comment by Aldiwildan77** [comment]
okay but the generated definitions can be filled with the value of JSON, then when I try to check the swagger it can be shown.

so my question is "how to generate definitions (model) without reference to the struct in a router?" @ubogdan

**Comment by ubogdan** [comment]
Unfortunately, this is not possible.

**Comment by icanc0** [comment]
Is there a reason why this isn't possible? i can see many uses where it just simplifies and syncs the logic between frontend and backend.
