### ISSUE TITLE
Allow extensions for structs uses as schema

### ISSUE THREAD

**Issue by nialexander** [swaggo/swag#1080]
**Is your feature request related to a problem? Please describe.**

I want to somehow filter out specific tagged schemes from the openapi specification file. Therefore I need to somehow tag or mark the schemes (basically the structs). For that openapi offers "extensions" starting with `x-`. Unfortunately they do not work for schemes (or at least I am not able to get them to work). Comments also seems to not work for schemes. 

**Describe the solution you'd like**

Allow 
```
// @x-myextension abcdef
type Response struct {
....
}
```
this to work. And attach those extensions to the schema definition.

**Describe alternatives you've considered**

**Comment by ubogdan** [comment]
@nialexander annotation on top of the struct is not recognized as struct comments, and therefore, we don't support them.
