### ISSUE TITLE
version 1.7.7 uses wrong dependencies

### ISSUE THREAD

**Issue by flamedmg** [swaggo/swag#1090]
**Describe the bug**
After upgrading from 1.7.6 to 1.7.7 i got the following message:
go: github.com/swaggo/swag@v1.7.7 requires
        github.com/swaggo/cli@v1.22.2: reading github.com/swaggo/cli/go.mod at revision v1.22.2: unknown revision v1.22.2

Latest version of github.com/swaggo/cli i see in github is 1.22.0

**Expected behavior**
Should upgrade and keep dependencies consistent

**Your swag version**
e.g. 1.7.7

**Your go version**
1.17.5

**Desktop (please complete the following information):**
 - OS: Latest macos
 - Browser: firefox
 - Version: latest

**Comment by ubogdan** [comment]
Not sure what are u talking about .... There is no change in go.mod regarding swago/cli
https://github.com/swaggo/swag/compare/v1.7.6...v1.7.7

**Comment by ubogdan** [comment]
@flamedmg I'm not able to reproduce the issue with go.117 using
 go install github.com/swaggo/swag/cmd/swag@v1.7.7

Anyway, I will fix the issue in go.mod and release a new version.

**Comment by ubogdan** [comment]
v1.7.8 released. Please retest and let us know.

**Comment by flamedmg** [comment]
error gone, thank you!
