### ISSUE TITLE
Support empty responses

### ISSUE THREAD

**Issue by selmanj** [swaggo/swag#11]
According to the [swagger 2.0 docs](https://swagger.io/docs/specification/2-0/describing-responses/), you can describe a response with an empty body by not providing a schema:

> Some responses, such as 204 No Content, have no body. To indicate the response body is empty, do not specify a schema for the response. Swagger treats no schema as a response without a body.

However, using the `@success` tag requires that schema be specified (at least according to the regex here: https://github.com/swaggo/swag/blob/master/operation.go#L190)

Ideally, one could specify a response has no body by being able to write `@success 200 "My description goes here"`

**Comment by easonlin404** [comment]
Maybe we can support like `@Success 200 {string} string	""` or `@Failure 400 {object} web.APIError "" `  to support  an empty body response.

**Comment by easonlin404** [comment]
fix via #14
