### ISSUE TITLE
Is possible to have empty strings in the examples?

### ISSUE THREAD

**Issue by juansalazargenius** [swaggo/swag#1102]
I was trying to add multiple examples to my documentation, one of those is what happen when the string for an json attribute is empty, but when the tag `example` in golang is put as empty i.g. `example:""` the example field in swagger does not appear, any other value made it work, thanks.

This is my golang struct
![2022-01-12_15-17](https://user-images.githubusercontent.com/57112407/149215875-bfaa2e2b-e0de-4df5-ba4c-00af7ebf9bb7.png)

This one is how swagger generates the docs.go
![2022-01-12_15-17_1](https://user-images.githubusercontent.com/57112407/149215524-abfd83d9-bb4c-4757-8c08-2a0b7a49b6e4.png)

And this last one is how I need it to be
![2022-01-12_15-18](https://user-images.githubusercontent.com/57112407/149215585-e1825271-7aab-45f2-9cda-ea21f6e8d982.png)

I'm using `/${GO_PATH}/swag init -g /main.go` to generate the documentation

Thanks in advance.

**Comment by ubogdan** [comment]
It's normal because we are checking the length of the struct tag.

**Comment by ubogdan** [comment]
released in v1.7.9

**Comment by rpedrodasilva10** [comment]
> released in v1.7.9
Hey @ubogdan how are you doing?
If this was merged and released, shouldn't this issue be closed already?
