### ISSUE TITLE
Type Parameters support?

### ISSUE THREAD

**Issue by hhuseyinpay** [swaggo/swag#1104]
Hi, I'm experimenting with generics. I'm getting the following error.

![Screen Shot 2022-01-18 at 16 25 22](https://user-images.githubusercontent.com/14811488/149945777-2bf508f5-3b34-4af0-b633-47ebf06be872.png)
![Screen Shot 2022-01-18 at 16 25 43](https://user-images.githubusercontent.com/14811488/149945816-950742f3-e4c4-4280-86a6-832437dfd7c0.png)

**Comment by ubogdan** [comment]
This is really funny, go1.18 was not released yet.

**Comment by hhuseyinpay** [comment]
"I'm experimenting". It will be released soon so I'm preparing for it :)

**Comment by hhuseyinpay** [comment]
You can check [my repository](https://github.com/hhuseyinpay/go-generic-repository-pattern). By using generics, I'm trying to reduce code duplications for simple CRUD APIs, especially for admin panels.

**Comment by ubogdan** [comment]
The error comes obviously from the fact you are using a swag binary that was built with a go version before 1.18 and the go/parser doesn't recognize generics.

Regarding the project. if you are going to use [DTO](https://en.wikipedia.org/wiki/Data_transfer_object) for request/response I believe it will work fine with current implementation.

**Comment by hhuseyinpay** [comment]
I've cloned the repository and changed the go version in the go.mod file and compiled it and then it worked as expected. Thank you.
