### ISSUE TITLE
Add support for urfave cli Go application

### ISSUE THREAD

**Issue by piavgh** [swaggo/swag#1109]
**Is your feature request related to a problem? Please describe.**

I'm using urfave cli to create my go backend, so the main() function of the code is not used to start the webserver directly.
Instead, it will just create an API cli. Only when the API cli is started, the web server is started

The problem with swaggo is that, we have to add comments above this main() function, so it does not work with a go project with many clis inside

**Describe the solution you'd like**

I want it to integrate easily with cli backend. For example, adding comment to the main() function is not necessary, we can put that comment on any level of code we like

**Describe alternatives you've considered**

At the moment, https://github.com/go-swagger/go-swagger allows me to generate swagger.yaml file with my cli setup. But it lacks the builtin swagger-ui, so I have to set it up on my own => I still prefer swaggo

**Additional context**

**Comment by ubogdan** [comment]
@piavgh You have the option to specify where the main info resides. It doesn't have to be in the main.go file.
```
   --generalInfo value, -g value          Go file path in which 'swagger general API Info' is written (default: "main.go")
```

**Comment by piavgh** [comment]
> @piavgh You have the option to specify where the main info resides. It doesn't have to be in the main.go file.
> 
> ```
>    --generalInfo value, -g value          Go file path in which 'swagger general API Info' is written (default: "main.go")
> ```

Thank you, I will try it

**Comment by ubogdan** [comment]
@piavgh Any updates?

**Comment by piavgh** [comment]
@ubogdan : somehow I still can't make it work.

You can check my project here: https://github.com/piavgh/test-swaggo

I added the General API annotations here: https://github.com/piavgh/test-swaggo/blob/swagger/internal/pkg/builder/server.go#L11

I added the API Operation annotations here: https://github.com/piavgh/test-swaggo/blob/swagger/internal/pkg/service/route.go#L28

But when I run `swag init -g internal/pkg/builder/server.go`, it can generate the `docs` folder, but inside the json file, I can not see any API path => https://github.com/piavgh/test-swaggo/blob/swagger/docs/swagger.json

Can you please check my project and advise if this setup can work with swaggo? Thanks

**Comment by ubogdan** [comment]
Just move the comments at line 26 https://github.com/piavgh/test-swaggo/blob/fdf4d422253547dcecf2f0ed66e3c20520d56604/internal/pkg/service/route.go#L28-L39 and everything should work like a charm.

**Comment by piavgh** [comment]
> Just move the comments at line 26 https://github.com/piavgh/test-swaggo/blob/fdf4d422253547dcecf2f0ed66e3c20520d56604/internal/pkg/service/route.go#L28-L39 and everything should work like a charm.

Thank you very much.
It works now.
