### ISSUE TITLE
outputTypes doesn't appear in cli on MacOS

### ISSUE THREAD

**Issue by Ferrany1** [swaggo/swag#1114]
**Describe the bug**
outputTypes doesn't appear in cli on MacOS

**To Reproduce**
swag init --outputTypes "go,json"

**Expected behavior**
flag provided but not defined: -outputTypes

**Your swag version**
swag -v     
swag version v1.7.8

**Your go version**
go version
go version go1.17.1 darwin/amd64

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Version: 12.1

**Additional context**
Tried to install via go install, go get, and precompiled binary

**Comment by ubogdan** [comment]
This feature is not released yet. (see](https://github.com/swaggo/swag/commits/master)

**Comment by Ferrany1** [comment]
Oh i thought master Readme only contains all release changes.
Can you provide more info about release policy?

**Comment by ubogdan** [comment]
Unfortunately, the number of contributors is not high enough to justify working with the features branches. 

Every PR is merged into master, and it becomes available in the next release. 

There is no fixed date, I plan to do a release every month as soon we gather enough contributions to justify a new version.

**Comment by Ferrany1** [comment]
Okay, good to know
