### ISSUE TITLE
breaking change in latest versions

### ISSUE THREAD

**Issue by gabriel-vasile** [swaggo/swag#1120]
https://github.com/swaggo/swag/blob/7137cd895386d86db391d3cc36e540707d710967/swagger.go#L42

This function used to be:
```go
func ReadDoc() (string, error) {
```

**Comment by ubogdan** [comment]
This has changed when we added support to register multiple doc instances into swag.

**Comment by gabriel-vasile** [comment]
I don't know about that. I'd say getting compile errors after version upgrade is a breaking change.

```go
var f func() (string, error)
f = swag.ReadDoc
```
This code does not compile with the new version.

**Comment by ubogdan** [comment]
@gabriel-vasile I'm sorry to hear that and Yes you are right: a change in one part of a software system that causes other parts to fail is known as a breaking chage.

You need to understand that there are other 5k users using this API generator tool and they have encountered different limitations and we are making these changes for the benefit of our community. 
We don't intend to introduce breaking changes and we are offering support via issue tracker for those that encounter various difficulties.

Thats' been said, is there anything else I can help you with?
