### ISSUE TITLE
Swaggo generates SwaggerInfo var in Mac, but it generates SwaggerInfo_swagger var in Windows 10

### ISSUE THREAD

**Issue by yusrilmr** [swaggo/swag#1132]
**Describe the bug**
In mac, when I execute `swag init`, it generates docs/docs.go as it should.
I can also define in the runtime the host as described in the guideline 
For example: `docs.SwaggerInfo.Host = "petstore.swagger.io"`

However, when I tried it in windows 10, it generates a different variable name, which is `SwaggerInfo_swagger` in docs/docs.go.
As a consequence, I have to update my runtime code to something like `docs.SwaggerInfo_swagger.Host = "petstore.swagger.io"`

**To Reproduce**
1. Use Windows 10 OS
2. Go to your Golang project that has Swaggo installed
3. Execute `swag init`
4. Try to set the host during run time (`docs.SwaggerInfo.Host="petstore.swagger.io"`)
5. It will complain that it cannot find `SwaggerInfo`, where in Mac environment, it works just fine.
6. Then, you have to fix the one in windows by changing it to `SwaggerInfo_swagger`

**Expected behavior**
When generating in Windows 10, the variable name should be `SwaggerInfo` instead of `SwaggerInfo_swagger`.
This difference makes working in a team where we have different PCs (Windows and Mac) a bit more tricky since every time one of us generates the spec, we have to also update the runtime code.

**Screenshots**
In Mac, where it works perfect
<img width="535" alt="Mac 1" src="https://user-images.githubusercontent.com/4738623/153286369-436f38b4-035b-491a-b1e8-ebc13959612b.png">
<img width="394" alt="Mac 2" src="https://user-images.githubusercontent.com/4738623/153286386-5ceae8d3-c5ec-4c2d-802f-20769e69a0e1.png">

In Windows 10, where it somehow adds this `_swagger`
![windows 1](https://user-images.githubusercontent.com/4738623/153286729-7765205d-d7bf-4b6e-a47a-8ef3cbecab58.jpeg)
![windows 2](https://user-images.githubusercontent.com/4738623/153286753-07f670b1-502e-489a-9674-46a48ec70662.jpeg)

**Your swag version**
v1.7.9

**Your go version**
1.17

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: irrelevant
 - Version: irrelevant

**Comment by ubogdan** [comment]
Please use swag 1.7.9-p1 so SwaggerInfo won't have the _swagger prefix.
see https://github.com/swaggo/swag/issues/1126

install via cmd line or download the binary from the release page.
go install github.com/swaggo/swag/cmd/swag@v1.7.9-p1

**Comment by yusrilmr** [comment]
I just tested it and it works. Thanks!
Anw, thanks for the awesome library!
