### ISSUE TITLE
Does swag support specifying the required list in the Model?

### ISSUE THREAD

**Issue by g1eny0ung** [swaggo/swag#1135]
**Is your feature request related to a problem? Please describe.**

Yes. I wanna use https://openapi-generator.tech/ to convert swag generated `swagger.yaml` to TypeScript API client.

But as default, all interfaces' fields in client will be `optional`, for example:

```ts
export interface V1CephFSVolumeSource {
  /**
   * Required: Monitors is a collection of Ceph monitors More info: https://examples.k8s.io/volumes/cephfs/README.md#how-to-use-it
   * @type {Array<string>}
   * @memberof V1CephFSVolumeSource
   */
  monitors?: Array<string>
  /**
   * Optional: Used as the mounted root, rather than the full Ceph tree, default is / +optional
   * @type {string}
   * @memberof V1CephFSVolumeSource
   */
  path?: string
  /**
   * Optional: Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts. More info: https://examples.k8s.io/volumes/cephfs/README.md#how-to-use-it +optional
   * @type {boolean}
   * @memberof V1CephFSVolumeSource
   */
  readOnly?: boolean
  /**
   * Optional: SecretFile is the path to key ring for User, default is /etc/ceph/user.secret More info: https://examples.k8s.io/volumes/cephfs/README.md#how-to-use-it +optional
   * @type {string}
   * @memberof V1CephFSVolumeSource
   */
  secretFile?: string
  /**
   *
   * @type {V1LocalObjectReference}
   * @memberof V1CephFSVolumeSource
   */
  secretRef?: V1LocalObjectReference
  /**
   * Optional: User is the rados user name, default is admin More info: https://examples.k8s.io/volumes/cephfs/README.md#how-to-use-it +optional
   * @type {string}
   * @memberof V1CephFSVolumeSource
   */
  user?: string
}
```

Does swag support specifying the required list in the Model? If supported, it would be very convenient to use these fields.

Ref: https://stackoverflow.com/questions/40113049/how-to-specify-if-a-field-is-optional-or-required-in-openapi-swagger.

**Describe the solution you'd like**

Use `swaggertype:"required"` to express this feature?

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by ubogdan** [comment]
Have you tried to add `required:"true"` into the struct field tag annotation?

**Comment by g1eny0ung** [comment]
> Have you tried to add `required:"true"` into the struct field tag annotation?

How do I add it? I tried:

```go
type ObjectBase struct {
	Namespace string `json:"namespace" required:"true"`
	Name      string `json:"name" required:"true"`
	Kind      string `json:"kind" required:"true"`
	UID       string `json:"uid" required:"true"`
	Created   string `json:"created_at" required:"true"`
}
```

But nothing happened.

**Comment by 714273725** [comment]
> > Have you tried to add `required:"true"` into the struct field tag annotation?
> 
> How do I add it? I tried:
> 
> ```go
> type ObjectBase struct {
> 	Namespace string `json:"namespace" required:"true"`
> 	Name      string `json:"name" required:"true"`
> 	Kind      string `json:"kind" required:"true"`
> 	UID       string `json:"uid" required:"true"`
> 	Created   string `json:"created_at" required:"true"`
> }
> ```
> 
> But nothing happened.

try
```
type ObjectBase struct {
        Namespace string `json:"namespace" validate:"required"`
	···
}
```

it works for me

Ref: https://github.com/swaggo/swag/issues/564#issuecomment-640206514

**Comment by g1eny0ung** [comment]
@714273725 Thanks for your help!
