### ISSUE TITLE
Support for writeonly tag

### ISSUE THREAD

**Issue by tekpriest** [swaggo/swag#1139]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When creating a struct, there should be support for `writeOnly:"true"` the same way there is support for `readOnly:"true" just like how it in swagger docs
![image](https://user-images.githubusercontent.com/16443589/154041145-5abe99dd-7565-464d-89f0-eacdecfb97b1.png)

**Describe alternatives you've considered**
An example of this:
```
type User struct {
  ID string `json:"id" readOnly:"true"`
  Email string `json:"email" format:"email"
  Password string `json:"password" writeOnly:"true" <---
}
```

**Additional context**

**Comment by ubogdan** [comment]
@en1tan This is an open-source project. Please feel free to contribute, and we will be more than happy to assist you with a code review.

**Comment by en1tan** [comment]
>  This is an open-source project. Please feel free to contribute, and we will be more than happy to assist you with a code review.
alright, I will see what I can do 😆

**Comment by en1tan** [comment]
@ubogdan check my PR when you can
