### ISSUE TITLE
String Example Value

### ISSUE THREAD

**Issue by mschneider82** [swaggo/swag#1140]
Hi,

I tried the new example feature for string:
`
// @Param email body string true "message/rfc822" example(Subject: Testmail\r\n\r\nBody Message\r\n)
`
Going to the swagger page it still shows "string" as the default Example Value. Howto change this to the example value? I would like to add a basic test mail as the text (which has a subject header and a message body)

![image](https://user-images.githubusercontent.com/8426497/154281520-29b73bfd-220b-4765-9408-b74968db7d34.png)

**Comment by ubogdan** [comment]
Not sure why do you want to implement rfc822 over HTTP but you should try the following

```go
type Message struct {
    Subject string `example:"Test mail"`
    Body string `example:"Message"`
}
// @consume json
// @Param email body Message true "Json Payload"
```

**Comment by mschneider82** [comment]
A Content-Type of "message/rfc822" indicates that the body contains an encapsulated message, with the syntax of an RFC 822 message. Sending json ist wrong here

A valid Body could be the String:
Subject: Testmail\r\n\r\nBody Message\r\n

It has one Header followed by a newline that indicates that the Body Starts with the Text "Body messeage"

**Comment by ubogdan** [comment]
See OAS 2 specs regarding [parameter object](https://spec.openapis.org/oas/v2.0#parameter-object). 

You are free to use "message/rfc822" or anything else that's not in the specs, but you are on your own.

**Comment by mschneider82** [comment]
I have tried your Message struct, it gives an json record in the "edit Value" field instead of an email.

So its not possible to enter an normal string as body example?

**Comment by mschneider82** [comment]
I got what i want by editing the docs/docs.go file:

```
                     {
-                        "example": "\"Subject: Testmail\\r\\n\\r\\nBody Message\\r\\n\"",
                         "description": "message/rfc822",
                         "name": "email",
                         "in": "body",
                         "required": true,
                         "schema": {
-                            "type": "string"
+                            "type": "string",
+                            "example": "Subject: Testmail\r\n\r\nBody Message\r\n"
                         }
                     }
                     
```

**Comment by mschneider82** [comment]
results in:
![image](https://user-images.githubusercontent.com/8426497/155489242-a4b2a8c3-0ef6-4908-8935-09475fb96011.png)

**Comment by mschneider82** [comment]
@ubogdan  what do you think about the PR ? Other idea is to include the Schema Example as default when body and example is used

**Comment by davidkhala** [comment]
By the issue, I see a great job on schemaExample tag. Meanwhile, will you consider also have this tag available also for 
`@Success`. 

I have no idea on how to set example value for it.

**Comment by ubogdan** [comment]
@mschneider82 The pr looks good so far, You only need to write the unit tests to cover the new code. See the codecov comments here https://github.com/swaggo/swag/pull/1148/files.

**Comment by mschneider82** [comment]
@ubogdan i have covered the new code, please re-run codecov

**Comment by mschneider82** [comment]
Hi @ubogdan i still have the problem that \r\n gets escaped. Do you have an idea how to solve it? My idea would be if the `attrKey` begings with \` and ends with \` (like in golang) there will be no escaping..

**Comment by mschneider82** [comment]
```
// @Param email body string true "message/rfc822" SchemaExample(Subject: Testmail\r\n\r\nBody Message\r\n)
```
gets to:
```
          example: 'Subject: Testmail\r\n\r\nBody Message\r\n'
```
What i need is:
```
          example: "Subject: Testmail\r\n\r\nBody Message\r\n"
```

**Comment by ubogdan** [comment]
It looks like you got defeated by your own unit tests. :smiling_face_with_tear: 
What about replacing '\r' with "\r" and '\n' with "\n" ?

**Comment by mschneider82** [comment]
@ubogdan the PR works with my Example!
