### ISSUE TITLE
Support BearerAuthentication as Security option

### ISSUE THREAD

**Issue by soumiksamanta** [swaggo/swag#1142]
**Is your feature request related to a problem? Please describe.**
swag does not have support to generate security scheme based on [Bearer Authentication](https://swagger.io/docs/specification/authentication/bearer-authentication/)
**Describe the solution you'd like**
Provide option to have bearer auth as security scheme

**Comment by ubogdan** [comment]
True and at the same it's normal because swag is [OAS2 spec](https://swagger.io/specification/v2/) and you are providing the link to [OAS3 spec](https://swagger.io/docs/specification/authentication/bearer-authentication/). 

Duplicate https://github.com/swaggo/swag/issues/1100
