### ISSUE TITLE
First line of template doesn't make sense

### ISSUE THREAD

**Issue by TColl** [swaggo/swag#1154]
As seen [here](https://github.com/swaggo/swag/blob/cd97e7f515e35742907bb188d07d9e192cfa79df/gen/gen.go#L403), the head of the generated file looks like this:

```go
// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs
```
There is no command above that first line.

**Comment by ubogdan** [comment]
@TColl Swag is an open-source project, and you are welcome to fix this misleading comment by contributing with a PR. 

Thanks!

**Comment by TColl** [comment]
@ubogdan done :)
