### ISSUE TITLE
// @Failure 400,403,404,500 {object}  http.MyError

### ISSUE THREAD

**Issue by mesuutt** [swaggo/swag#1155]
Hi 👋  I have a feature request:

I have an error response strcut and I have using this error struct in my responses.
I can add possible error responses with each status code like: 
```
// @Failure 400 {object}  http.MyError
// @Failure 403 {object}  http.MyError
// @Failure 404 {object}  http.MyError
// @Failure 500 {object}  http.MyError
```

I think it should be good if I can specify the all error responses in one line like this:
```
// @Failure 400,403,404,500 {object}  http.MyError
```

**Comment by ubogdan** [comment]
Sorry, I can't figure out if this is a bug or a feature request. Please edit using the template.

**Comment by sdghchj** [comment]
// @Failure default {object}  http.MyError

**Comment by ubogdan** [comment]
@mesuutt Have you figured it out?

**Comment by mesuutt** [comment]
@ubogdan yes, thanks :)
