### ISSUE TITLE
Could swaggo support example value for {string} response?

### ISSUE THREAD

**Issue by ahuigo** [swaggo/swag#1163]
**Is your feature request related to a problem? Please describe.**
I want set  example value for http scucces/failurre string response.

**Describe the solution you'd like**
Such as:
```
// @Failure      400  {string}  string "Argument missing!"
// @Success      200   {string}  string "Good job!"

```
This would generate  apidoc like below:
![image](https://user-images.githubusercontent.com/1781999/159113280-e104db8b-ebfa-437d-85fd-86fbb1064750.png)

But I expected the doc to look something like this： make it show example value，not `string`(the type of value)
![image](https://user-images.githubusercontent.com/1781999/159002818-e51ced9b-5212-4d2f-862c-5888719c1c6f.png)

**Comment by ubogdan** [comment]
So what stops you?

**Comment by ahuigo** [comment]
> So what stops you?

The swag could not show example value of string response. (I've added examples)

**Comment by Hanmur** [comment]
Have you solved the problem? I am encountering this problem too.

**Comment by ubogdan** [comment]
Yes, see [code example](https://github.com/swaggo/swag/blob/2b64f7852f495240d8b8441c49a0450e8a51eab3/operation_test.go#L1824-L1844).

**Comment by ahuigo** [comment]
> Yes, see [code example](https://github.com/swaggo/swag/blob/2b64f7852f495240d8b8441c49a0450e8a51eab3/operation_test.go#L1824-L1844).
It do not support this:
```
comment := `@Success 200 {string} "example value" "description"`
// @success  {code}, {param type} , {example value}, {comment}

```

**Comment by ubogdan** [comment]
Realy, what about 
```
// @Param some_id query int true "Some ID" Example(10)
```

**Comment by ahuigo** [comment]
@ubogdan What about this？It won't break change.
```
comment := `@Success 500 {string} string "description" Example("some inner errors")`
```

**Comment by s-titov** [comment]
@ubogdan he has talked about `@Success` - not about `@Param`. 
I have the same problem. I want to add example to success string response (empty json).

**Comment by ubogdan** [comment]
@s-titov I was hoping it was a mistake. This kind of response is supposed to be JSON, so the type should be {onbject} ReponseStruct. What kind o API are you writing if the 200 OK will give back a plain string?

**Comment by ubogdan** [comment]
Have you tried `@Success 200 {object} nil` ?

There are a lot of examples in unit tests, but I suppose they are for GO developers only.
https://github.com/swaggo/swag/blob/c7cb3fd95a/operation_test.go#L223-L285

**Comment by s-titov** [comment]
@ubogdan 
> Have you tried @Success 200 {object} nil ?

There is no `{}` as example

![image](https://user-images.githubusercontent.com/41398445/166469584-c7a221c0-25a0-463c-9918-2f4fffbedfce.png)

**Comment by asthinasthi** [comment]
This
```
// @Failure      400  {string}  string "Argument missing!"
```

still shows `string` in the **Example Value** instead of "Argument missing!" 

@ahuigo 

Did the syntax change to add example string values?

**Comment by ubogdan** [comment]
have your tried
// @Failure      400  {string}  string "Some Failure" Example("Example value")

**Comment by your-diary** [comment]
This issue should be reopened as this is not completed.
I have exactly the same problem in 2024.

**Comment by mrsimonemms** [comment]
It's not exactly the same, but I achieved what works for me by using:

```go
// @Success		200	"OK"
// @Failure		503 "Service unavailable"
```
