### ISSUE TITLE
(go 1.18) :cannot find type definition: error

### ISSUE THREAD

**Issue by suduaya** [swaggo/swag#1171]
**Describe the bug**
Swag generate fails when parsing an `error` type

**To Reproduce**
```
import (
	...
	// Swagger Dependency
	_ "mypackage"
)

 
// MyHandler My handler handles things
// @Success 200 {object} mypackage.SucessResponse
// @Success 500 {object} error
// @Router /v1/myhandler [post]
func (h *Handler) MyHandler(w http.ResponseWriter, r *http.Request) error {
```

`:cannot find type definition: error`
but `mypackage.SucessResponse` is parsed successfully

if I change `error` to `mypackage.ErrorResponse` (which uses `error`), and import it:
```
import (
	...
	// Swagger Dependency
	_ "mypackage"
)

 
// MyHandler My hander handles things
// @Success 200 {object} mypackage.SucessResponse
// @Success 500 {object} mypackage.ErrorResponse
// @Router /v1/myhandler [post]
func (h *Handler) MyHandler(w http.ResponseWriter, r *http.Request) error {
```

`:cannot find type definition: mypackage.ErrorResponse`
but `mypackage.SucessResponse` is parsed successfully

Any clue why this is happening ? :thinking: 

**Expected behavior**
Expecting `error` to be parsed as a response object

**Your swag version**
v1.8.1

**Your go version**
1.18

**Swagger cmd**
`swag init --parseDependency -g /path/to/api.go`

**Comment by ubogdan** [comment]
Can you please share the "mypackage.ErrorResponse" type definition with us.

**Comment by suduaya** [comment]
@ubogdan

```
type ErrorResponse struct {
	error
	message           string
}
```

**Comment by suduaya** [comment]
> Can you please share the "mypackage.ErrorResponse" type definition with us.

@ubogdan

```
type ErrorResponse struct {
	error
	message           string
}
```

**Comment by Niennienzz** [comment]
This might not be the workaround you're looking for.
But if you don't need to marshal the field of the `error` type, the generation works properly.

```go
type ErrorResponse struct {
	Message string `json:"message"`
	Cause   error  `json:"-"`
}
```

**Comment by suduaya** [comment]
@ubogdan 

Totally forgot to export Error type...
Thanks! Solved! :smile:
