### ISSUE TITLE
Add support for description on security definition

### ISSUE THREAD

**Issue by pmorelli92** [swaggo/swag#1175]
**Is your feature request related to a problem? Please describe.**

The consumers of my API are generating their stubs from my swagger file. However, their generation tool is breaking because they expect my swagger file to have a description for the security definition. This is not a mandatory field on the OpenAPI spec but it would be nice to have support for it so I can have it on my swagger file.

**Describe the solution you'd like**

I want this library to support the option of adding a description to the security definitions.

**Describe alternatives you've considered**

N/A

**Additional context**

I did an implementation #1174

**Comment by pmorelli92** [comment]
This is already on master, so we can close it. Is there any estimative date for the next version release? @ubogdan

**Comment by ubogdan** [comment]
I want to release it by the end of the month, but I'm not sure about it since we have only one contribution for this month.
