### ISSUE TITLE
swagger ui  was blocked when i use ginweb with token authentication  middleware 

### ISSUE THREAD

**Issue by xxlest** [swaggo/swag#1183]
**Describe the bug**

```
g.Use(ginMiddleware.Cors()) // 跨域
tk := common.GetToken()
g.Use(ginMiddleware.Authorize(tk)) //鉴权
g.GET("/api/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
```
```
// Authorize 鉴权.
func Authorize(t *common.Token) gin.HandlerFunc {
	return func(c *gin.Context) {
		for _, b := range common.WhiteListUrl {
			if b == c.Request.URL.Path {
				c.Next()

				return
			}
		}
		// token校验
		tokenValue := c.Request.Header.Get("token")
		if _, err := t.Decode(tokenValue); err != nil { // token校验失败
			c.Abort()
			resp := common.NewRespMsg(common.StatusTokenInvalid, common.MsgFailAuthToken, nil)
			c.JSON(http.StatusOK, resp)

			return
		}
		// token校验成功
		c.Next()
	}
}
```

when i comment “g.Use(ginMiddleware.Authorize(tk))”   http://localhost:8080/api/swagger/index.html wil work. otherwise  swagger web ui will block, showing white

**Your swag version**
 swag version v1.7.4

**Your go version**
go 1.8

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: chrome

anybody meet this issue? 
Maybe I'm not going about it the right way？

**Comment by ericlingit** [comment]
`Authorize(tk)` checks for a token in the request's header, and it's registered as a *global* middleware (at this line `g.Use(ginMiddleware.Authorize(tk))`). You're telling Gin to check for the token for *all* requests, including the request to Swagger web UI.

I'm guessing this is not what you want; you probably want to check for the token only for your API routes. You need to [register the middleware](https://github.com/gin-gonic/gin/issues/2612) on a per route or per route-group basis.

By the way, if the token doesn't pass validation, you should return a 401 http status code: replace `c.JSON(http.StatusOK, resp)` with `c.JSON(http.StatusUnauthorized, resp)`.

**Comment by ericlingit** [comment]
`Authorize(tk)` checks if you're visiting a whitelisted URL, or if you have a token in the request's header. This function is registered as a *global* middleware (at this line `g.Use(ginMiddleware.Authorize(tk))`). You're telling Gin to perform the checks for *all* requests, including the request to Swagger web UI.

Is the web UI address in the whitelist? If it is, are you supplying the token in the request header when you visit the web UI?

You should break this into 2 middlewares: one checks the whitelist, the other checks the token.

By the way, if the token doesn't pass validation, you should return a 401 http status code: replace `c.JSON(http.StatusOK, resp)` with `c.JSON(http.StatusUnauthorized, resp)`.

**Comment by xxlest** [comment]
> `Authorize(tk)` checks if you're visiting a whitelisted URL, or if you have a token in the request's header (you might want to split this into 2 middlewares). This function is registered as a _global_ middleware (at this line `g.Use(ginMiddleware.Authorize(tk))`). You're telling Gin to perform the checks for _all_ requests, including the request to Swagger web UI.
> 
> Is the web UI address in the whitelist? If it is, are you supplying the token in the request header when you visit the web UI?
> 
> By the way, if the token doesn't pass validation, you should return a 401 http status code: replace `c.JSON(http.StatusOK, resp)` with `c.JSON(http.StatusUnauthorized, resp)`.

thanks for you reply, of course i  added "/api/swagger/index.html" into WhiteListUrl, and i also check web find some clue as below
![image](https://user-images.githubusercontent.com/15182487/164258426-4c553f2d-29b5-4276-a65c-02bc1eea9915.png)

**Comment by xxlest** [comment]
> `Authorize(tk)` checks if you're visiting a whitelisted URL, or if you have a token in the request's header (you might want to split this into 2 middlewares). This function is registered as a _global_ middleware (at this line `g.Use(ginMiddleware.Authorize(tk))`). You're telling Gin to perform the checks for _all_ requests, including the request to Swagger web UI.
> 
> Is the web UI address in the whitelist? If it is, are you supplying the token in the request header when you visit the web UI?
> 
> By the way, if the token doesn't pass validation, you should return a 401 http status code: replace `c.JSON(http.StatusOK, resp)` with `c.JSON(http.StatusUnauthorized, resp)`.

i solved it ,i modified Authorize function ,it can works 
`func Authorize(t *common.Token) gin.HandlerFunc {
	return func(c *gin.Context) {
		// 不需要token验证的白名单 strings.HasPrefix(r.URL.Path, "/hello") ||
		for _, b := range common.WhiteListUrl {
			if b == c.Request.URL.Path || strings.Contains(c.Request.URL.Path, "swag") {
				c.Next()

				return
			}
		}
		// token校验
		tokenValue := c.Request.Header.Get("token")
		if _, err := t.Decode(tokenValue); err != nil { // token校验失败
			c.Abort()
			resp := common.NewRespMsg(common.StatusTokenInvalid, common.MsgFailAuthToken, nil)
			c.JSON(http.StatusUnauthorized, resp)

			return
		}
		// token校验成功
		c.Next()
	}
}`
