### ISSUE TITLE
Celler example comments differ of actual code

### ISSUE THREAD

**Issue by qequ** [swaggo/swag#1195]
**Describe the bug**
Most of example functions in celler/controller/examples.go returns in the context a string but the comments state that a json is produced. 

**To Reproduce**
1. Check the comments in celler/controler/examples.go
2. Run example/celler/main.go

**Expected behavior**
the specification should state `@Produce plain` every time that `ctx.String(...)` is used in the code.

**Your swag version**
swag version v1.8.1

**Your go version**
go version go1.18 linux/amd64

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: firefox
 - Version: 99.0 (64-bit)
.

**Comment by ubogdan** [comment]
Merged.
