### ISSUE TITLE
no available executable file

### ISSUE THREAD

**Issue by xuych** [swaggo/swag#1199]
so it turn out  the error of "zsh: command not found: swag",i search executable file in https://github.com/go-swagger/go-swagger/releases,download and place it in my mac bin folder,but did not work,thank for any help
ps:env go 1.18.1 and installed with "brew install go"

**Comment by xuych** [comment]
have solved ^ ^

**Comment by onattech** [comment]
how?

**Comment by fafg** [comment]
how? 2

**Comment by fafg** [comment]
it is installing
![image](https://user-images.githubusercontent.com/9274235/183224599-ada9cb0b-3142-474d-9fc4-1258c232be55.png)

then you need to add to your ~/.profile or ~/.bashrc or ~/.zshrc
export PATH="$HOME/go/bin:$PATH"

this -> $HOME/go/bin is the same as $GOPATH/bin

[]s

**Comment by fafg** [comment]
go install -v github.com/swaggo/swag/cmd/swag@latest

**Comment by minias** [comment]
I hope the link below is helpful.

https://github.com/swaggo/swag/issues/209#issuecomment-1674169858
