### ISSUE TITLE
BasePath Swagger Info in docs.go file not showin, Dockerfile base on golang:alpine swag version v1.8.1

### ISSUE THREAD

**Issue by mnasruul** [swaggo/swag#1204]
![image](https://user-images.githubusercontent.com/29394705/168731193-875b2285-17c8-4388-b3d5-3422bee290ad.png)

go version go1.18.2 linux/amd64

swag version v1.8.1

**Comment by p3nj** [comment]
I have this issue too, don't know what to do now, 
In my case I have defined my `@BasePath` at `main.go`
This will break CI/CD unless manually append `/api` into every endpoints.
```
// @securityDefinitions.apikey  ApiKeyAuth
// @in                          header
// @name                        Authorization
// @BasePath                    /api
func main() {
...
```
However after `swag init` value doesn't applied into `json`

- swag version: `v1.8.1`
- go version: `go version go1.18.2 darwin/arm64`
- `uname -a`: `Darwin Maccie.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64`

**Comment by mnasruul** [comment]
> I have this issue too, don't know what to do now, In my case I have defined my `@BasePath` at `main.go` This will break CI/CD unless manually append `/api` into every endpoints.
> 
> ```
> // @securityDefinitions.apikey  ApiKeyAuth
> // @in                          header
> // @name                        Authorization
> // @BasePath                    /api
> func main() {
> ...
> ```
> 
> However after `swag init` value doesn't applied into `json`
> 
> * swag version: `v1.8.1`
> * go version: `go version go1.18.2 darwin/arm64`
> * `uname -a`: `Darwin Maccie.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64`

Yes, and now i use version 1.7.4, dont use latest
this in my docker file
# RUN go install -v github.com/swaggo/swag/cmd/swag@latest
RUN go install -v github.com/swaggo/swag/cmd/swag@v1.7.4
# &&  go get -u github.com/swaggo/http-swagger && go get -u github.com/alecthomas/template
RUN swag init -g main.go -o Library/Swagger/docs

**Comment by p3nj** [comment]
I've found the solution, 
It turns out `@BasePath` have to place above `@securityDefinitions.apikey` in order to make `basePath` apply to `json`
I created a PR [here](https://github.com/create-go-app/fiber-go-template/pull/133) incase you want to check it out.

**Comment by mnasruul** [comment]
thanks a lot 👌

> I've found the solution, It turns out `@BasePath` have to place above `@securityDefinitions.apikey` in order to make `basePath` apply to `json` I created a PR [here](https://github.com/create-go-app/fiber-go-template/pull/133) incase you want to check it out.
> 
> > > I have this issue too, don't know what to do now, In my case I have defined my `@BasePath` at `main.go` This will break CI/CD unless manually append `/api` into every endpoints.
> > > ```
> > > // @securityDefinitions.apikey  ApiKeyAuth
> > > // @in                          header
> > > // @name                        Authorization
> > > // @BasePath                    /api
> > > func main() {
> > > ...
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > However after `swag init` value doesn't applied into `json`
> > > 
> > > * swag version: `v1.8.1`
> > > * go version: `go version go1.18.2 darwin/arm64`
> > > * `uname -a`: `Darwin Maccie.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64`
> > 
> > 
> > Yes, and now i use version 1.7.4, dont use latest version

**Comment by yuri-potatoq** [comment]
I had the same issue with similar environment (swag version v1.8.1).
I used the command bellow:
```
swag init --parseDependency  --parseDepth 1 -generalInfo main.go -output ./docs/swagger
```

**Comment by mnasruul** [comment]
> I had the same issue with similar environment (swag version v1.8.1). I used the command bellow:
> 
> ```
> swag init --parseDependency  --parseDepth 1 -generalInfo main.go -output ./docs/swagger
> ```

I've solved this by moving // @BasePath                    /api 
on top of // @securityDefinitions.apikey  ApiKeyAuth

like this
// @BasePath                    /api
// @securityDefinitions.apikey  ApiKeyAuth
// @in                          header
// @name                        Authorization
func main() {

**Comment by yuri-potatoq** [comment]
I did that. Still not working.

**Comment by mnasruul** [comment]
send your main.go annotation

**Comment by yuri-potatoq** [comment]
Is some like that.

````
// RevokeConsent godoc
// @Summary      Rekove consent from customers Newsletter!
// @Description  Send kafka event to revoke newsltter consents.
// @Tags         Digital
// @Accept       json
// @Produce      json
// @Param        customer_consent    body      entity.Consent   true  "Customer consent"
// @Param        x-access-token      header    string           true  "JWT Acess Token"
// @Success      200  {object}  entity.Result
// @Failure      400  {object}  HTTPError
// @Failure      404  {object}  HTTPError
// @Failure      500  {object}  HTTPError
// @BasePath  	/v1
// @securityDefinitions.apikey ApiKeyAuth
// @Router   	/revoke [post]
````

**Comment by ubogdan** [comment]
`@BasePath` needs to be declared in the `main.go` file. It's normal to get ignored in the route definition. See the example folder.

**Comment by yuri-potatoq** [comment]
@ubogdan i appreciate your help, my fault about this simples case. It's work perfectly now.
