### ISSUE TITLE
swag -v prints v1.8.1 on version v1.8.2

### ISSUE THREAD

**Issue by pedromfcarvalho** [swaggo/swag#1207]
**Describe the bug**
`swag -v` prints `swag version v1.8.1` on version `v1.8.2`

**To Reproduce**
```
~# rm ~/go/bin/swag 
~# go install github.com/swaggo/swag/cmd/swag@v1.8.2
~# swag -v
swag version v1.8.1
```

**Expected behavior**
`swag -v` should print `swag version v1.8.2` on version `v1.8.2`

**Your swag version**
`1.8.2`

**Your go version**
`1.18.1`

**Desktop (please complete the following information):**
 - OS: Fedora 35

**Additional context**
`version.go` seems to be out of date:
```
const Version = "v1.8.1"
```

**Comment by ubogdan** [comment]
duplicated https://github.com/swaggo/swag/issues/1223
