### ISSUE TITLE
Can I write description in Struct?

### ISSUE THREAD

**Issue by wubiandaxian** [swaggo/swag#1215]
**Is your feature request related to a problem? Please describe.**
Can I write description in Struct? I want put a short desc in struce tag, to explain what\`s the filed mean. But I didn\`t find how to do this in  the official api doc or  examples.
And I trid like this, but it didn`t workd:
``` go
type EmailModel struct {
	ID         int    `db:"id" json:"id" example:"1" description:"主键ID" `
	Receiver   string `db:"receiver" json:"receiver" example:"frewrew@wqe.cpm" description:"收件人"`
	Content    string `db:"content" json:"content" example:"好好学习，天天向上" description:"内容"`
	CreateTime string `db:"create_time" json:"create_time" example:"2022-03-29 17:29:52" description:"创建时间"`
}
```
this is the generating result, it does not include the description field:
``` json
"properties": {
                "content": {
                    "type": "string",
                    "example": "好好学习，天天向上"
                },
                "create_time": {
                    "type": "string",
                    "example": "2022-03-29 17:29:52"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "receiver": {
                    "type": "string",
                    "example": "frewrew@wqe.cpm"
                }
            }
```

**Describe the solution you'd like**
I`m new here, I want to know whice field I should use as a description , does this tool support the func? 

**Describe alternatives you've considered**
nil

**Additional context**
nil

**Comment by zyzhang-aibee** [comment]
+1

**Comment by zyzhang-aibee** [comment]
I found it ,use just like this ![image](https://user-images.githubusercontent.com/45031968/172750793-a716a25b-c704-40a6-969a-810a04afc35a.png)

**Comment by wubiandaxian** [comment]
> I found it ,use just like this ![image](https://user-images.githubusercontent.com/45031968/172750793-a716a25b-c704-40a6-969a-810a04afc35a.png)

666

**Comment by BrianIto** [comment]
This should REALLY be Documented on README.md
