### ISSUE TITLE
Can I use user defined structure in post body parameter?

### ISSUE THREAD

**Issue by wubiandaxian** [swaggo/swag#1217]
**Is your feature request related to a problem? Please describe.**
I want to use a struce in post body parameter, as a json put in Request body, not in Parameters.

**Comment by ubogdan** [comment]
Have you taken a look into the [example](https://github.com/swaggo/swag/blob/master/example/celler/controller/accounts.go#L68) folder ?
```
// @Param        account  body      model.AddAccount  true  "Add account"
```

**Comment by wubiandaxian** [comment]
> Have you taken a look into the [example](https://github.com/swaggo/swag/blob/master/example/celler/controller/accounts.go#L68) folder ?
> 
> ```
> // @Param        account  body      model.AddAccount  true  "Add account"
> ```

I did, but the output will be like this:
``` json
"parameters": [
                    {
                        "description": "EmailModel",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.EmailModel"
                        }
                    }
                ],
```
and what I want is like this:
```json
"requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/definitions/main.EmailModel"
              }
            },
          }
        },
```

Can you see the difference？ I want put parameters in the requestBody

**Comment by ubogdan** [comment]
OK, but is this OAS2 compliant?

**Comment by Nov1kov** [comment]
How to show examples for each path in this case? 
```
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
            example:
              name: Fluffy
              petType: dog
```

As I understood it's impossible to add specific example with "parameters" way.
I tried:
```
      - in: body
        name: some
        schema:
          $ref: '#/components/schemas/Pet'
          example:
            value:
              name: Fluffy
              petType: dog
```
it doesn't override the examples from "components/schemas/Pet".
