### ISSUE TITLE
Support 205 Response Code

### ISSUE THREAD

**Issue by fpmoles** [swaggo/swag#1218]
**Is your feature request related to a problem? Please describe.**
When a delete operation that responds with a 205 'Reset Content', the output swagger doc doesn't set a description, instead its an empty description unlike other response codes.

**Describe the solution you'd like**
Set description to 'Reset Content' like you do with 200 ('OK') and 201 ('Created')

**Describe alternatives you've considered**
Tried a nil object and set a description and it failed

**Additional context**
Go Doc code
`// @Success  205`

Swagger.yaml output
`"205":
          description: ""`

**Comment by ubogdan** [comment]
Have you tried
```go
// @Success 205 {object} nil "Reset Content"
```

**Comment by fpmoles** [comment]
That works, but it should be treated the same as other status codes. Thanks for the response, however

**Comment by ubogdan** [comment]
You mean if the definition is 
`// @Success 205` should automatically set the comment to the status code string value "Reset Content"? Because, If we do that, we will break compatibility in other projects!

**Comment by fpmoles** [comment]
so doing the same thing you do for 200, 201, 400, 404, 500 for the other status codes would break, that is kind of fragile to say the least.

**Comment by ubogdan** [comment]
We don't do anything special for 200, 201, 400, 404, 500 codes. Not sure what are u talking about.

**Comment by fpmoles** [comment]
after the previous comment by ubogdan, not sure I want to be involved with this project
