### ISSUE TITLE
Version file seems to not have been bumped to 1.8.2

### ISSUE THREAD

**Issue by YAPBRAN** [swaggo/swag#1223]
**Describe the bug**
The version seems to not have been bumped for the last release (1.8.2). Running  `swag --version` still outputs: `swag version v1.8.1`.

**To Reproduce**
1. Run `swag --version`

**Expected behavior**
Output: `swag version v1.8.2`

**Your swag version**
1.8.2

**Your go version**
1.18.2

**Desktop (please complete the following information):**
 - OS: Windows (with WSL)
 - Version: 10

**Additional context**
I noticed this when I was trying to understand what version I had installed for generics parsing support.

**Comment by ubogdan** [comment]
That's true. Thanks for letting us know.

**Comment by ubogdan** [comment]
Version bumped in 1.8.3
