### ISSUE TITLE
[BUG] - Cannot find type definition sql.NullTime

### ISSUE THREAD

**Issue by sujit-baniya** [swaggo/swag#1228]
When trying to run command ` swag init --md . --parseVendor`, it gave error 
```go
2022/06/15 10:53:36 ParseComment error in file /user_controller.go :cannot find type definition: sql.NullTime
```

**Comment by shoaibcldcvr** [comment]
How was this resolved? Could you please share the solution? @sujit-baniya

**Comment by sujit-baniya** [comment]
@shoaibcldcvr I'd to use `.swaggo` as in

```go
replace null.String string
replace null.Int64 integer
replace null.Bool boolean
replace sql.NullTime time


```

**Comment by sujit-baniya** [comment]
And complete command I've used is

```shell
swag init --md ./docs --parseInternal  --parseDependency --parseDepth 2 -g api.go
```

**Comment by EAS-Rhys** [comment]
I have tried the above solution with .swaggo file in the root of the project but am still getting this issue.

versions in use:

	github.com/swaggo/files v1.0.1
	github.com/swaggo/gin-swagger v1.6.0
	github.com/swaggo/swag v1.16.2
	
command used:

swag init --md ./docs --parseInternal  --parseDependency --parseDepth 2

error:

ParseComment error in file /Users/morgan/leadgen/data-ms/routes/content.go :cannot find type definition: sql.NullTime
