### ISSUE TITLE
Error when parsing URL parameters with symbol "="

### ISSUE THREAD

**Issue by Dantener** [swaggo/swag#1257]
**Describe the bug**
`swag init` fails when trying to parse URL parameters with symbol "="

**To Reproduce**
1. Define route. "no=" - part of URL, not query param
```
// CheckBalanceHandler godoc
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        identifierNo             path      string                          true  "Card Number"
// @Param        data                     body      CheckBalanceTransactionRequest  true  "params"
// @Success      200                      {object}  CheckBalanceTransactionResponse
// @Failure      401,403,404,405,409,415  {object}  render.GenericError
// @Router       /v1/identifiers/no={identifierNo}/check-balance [post]
```
2. Run `swag init`
3. Fails with following message: `can not parse router comment "/v1/identifiers/no={identifierNo}/check-balance [post]"`

**Expected behavior**
Parsing correctly the route. Need edit router Pattern regexp to `^(/[\w./\-{}+:$=]*)[[:blank:]]+\[(\w+)]`

**Your swag version**
v1.8.1

**Your go version**
v1.18.3

**Comment by ubogdan** [comment]
The `=` sign is a reserved character and you should not use it in the URL path. See https://www.ietf.org/rfc/rfc1738.txt .
