### ISSUE TITLE
Multiple path params with multiple paths leads to unnecessary required params

### ISSUE THREAD

**Issue by Phenix66** [swaggo/swag#1267]
**Describe the bug**
When using multiple paths for a single endpoint, if any of the paths have a path param that is not contained in another path, all of the paths will contain that param and be marked as "required".

**To Reproduce**
Use the [example from the README](https://github.com/swaggo/swag#add-multiple-paths) to generate API specs. The generated spec will mark `group_id` as required for both paths.

**Expected behavior**
Paths that do not contain a path param will have that path param omitted in the generated spec.

**Your swag version**
v1.8.3

**Your go version**
go1.18.4

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4

**Comment by Phenix66** [comment]
I came up with a fix for my team to use in the interim: https://github.com/Phenix66/swag/commit/1b7c1c6cc2cacd641f215fdb7de751895f5b3b9c

If the code looks good enough to actually put up a PR let me know and I'll add tests before throwing it up.

**Comment by edocevol** [comment]
保持关注
mark and wait for solution

**Comment by selankon** [comment]
Same for me. What about add the proposed @Phenix66 fix?

**Comment by Phenix66** [comment]
I went ahead and updated my fork, added a test, and opened a PR. Hopefully the maintainers approve.
