### ISSUE TITLE
user defined struct with private struct support

### ISSUE THREAD

**Issue by mstrYoda** [swaggo/swag#1274]
**Is your feature request related to a problem? Please describe.**

I have many of fiber.Handler as below and I do not want to export request/response types. It would be very good to generate swagger docs for this kind of methods.

```
func GetExchangeCodeForTokenHandler(idmSvc idm.Idm) fiber.Handler {
	type request struct {
		Code        string `json:"code"`
		RedirectURL string `json:"redirectURL"`
	}

	type response struct {
		AccessToken  string `json:"accessToken"`
		RefreshToken string `json:"refreshToken"`
	}

	return func(c *fiber.Ctx) error {
		var req request
		if err := c.BodyParser(&req); err != nil {
			return err
		}

		accessToken, refreshToken, err := idmSvc.ExchangeCodeForToken(req.Code, req.RedirectURL)
		if err != nil {
			return err
		}

		return c.JSON(&response{AccessToken: accessToken, RefreshToken: refreshToken})
	}
}
```

**Describe the solution you'd like**
If can we somehow reference the request/response fields residing in the same file/method as the private field, it can parse that fields too.

**Comment by ubogdan** [comment]
Unfortunately, this is not possible because swag doesn't parse function body.

**Comment by mstrYoda** [comment]
> Unfortunately, this is not possible because swag doesn't parse function body.

I would like to add that functionality

**Comment by ubogdan** [comment]
This is an open-source project, and all contributions are welcome until they try to break things.

Just a question before you jump into writing code, How do intend to handle model conflicts?

This is a code example where request and response models carry the same name inside the function body.

```go
func Handler1 () fiber.Handler {
	type request struct {
		Code        string `json:"code"`
		RedirectURL string `json:"redirectURL"`
	}

	type response struct {
		AccessToken  string `json:"accessToken"`
		RefreshToken string `json:"refreshToken"`
	}
       // code goes here.
}

func Handler2 () fiber.Handler {
	type request struct {
		Code        string `json:"code"`
		OtherString string `json:"otherString"`
	}

	type response struct {
		SomeData  string `json:"someData"`
	}
       // code goes here.
}
```

**Comment by mstrYoda** [comment]
If swag stores all parsed data globally, then may be uniquify by replacing the model name on conflicts with the <packageName> + <functionName> + <modelName>. Or it can be done for all private models as default.

Would not that be a solution?

**Comment by mstrYoda** [comment]
> All private function definitions should have a naming convention for consistency. Naming models using the `packageName + functionName + modelName` pattern sounds like a plan.
> 
> I am looking forward to seeing your code implementation.

I created a PR for this. I would like to get a review from you in your free time @ubogdan 🙏

**Comment by mstrYoda** [comment]
Resolved in: https://github.com/swaggo/swag/pull/1283
