### ISSUE TITLE
Operation sort available?

### ISSUE THREAD

**Issue by Moth13** [swaggo/swag#1297]
Hi,

Currently operations under tags are order by their path method, is there any ways to order them by their ids?

For I can understand, there is new options into swagger to order alpha or specific.
https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/#display operationsSorter, tagsSorter

Thanks,

Regards,

**Comment by ubogdan** [comment]
Please open this issue on echo-swagger , gin-swagger, or whatever middleware you use to render the generated documentation.
