### ISSUE TITLE
Nested Generic Fields

### ISSUE THREAD

**Issue by johan-lejdung** [swaggo/swag#1304]
**Describe the bug**
Nested Generic fields still not supported even after https://github.com/swaggo/swag/pull/1277 and https://github.com/swaggo/swag/pull/1281 on certain occasions.

**To Reproduce**
Have a look at the following repo https://github.com/chaintraced/swaggo-issue-repo
On the `main` branch you will see that it is not working as intended, whilst on the branch [functional-branch](https://github.com/chaintraced/swaggo-issue-repo/tree/functional-branch) it's working beautifully. 

**The only difference** being that the nested generic field is in another package on the [main](https://github.com/chaintraced/swaggo-issue-repo/tree/main) branch, very interesting behaviour.

**Expected behaviour**
I expect the generic field to be properly read and generated

**Your swag version**
I forked the repo to be able to release a version including the latest generic code changes `https://github.com/chaintraced/swag`

**Your go version**
e.g. 1.18.0

**Comment by johan-lejdung** [comment]
@FabianMartin sorry to tag you again. Just thought that this could potentially be interesting for you to know about. Your merged code works beautifully out of the box, but not when the generic field declaration is in another package. The linked repo above should demonstrate the issue well.

**Comment by FabianMartin** [comment]
Hi @johan-lejdung 

Thank you for the test repo. You find the fix in PR https://github.com/swaggo/swag/pull/1305

**Comment by johan-lejdung** [comment]
Much appreciated @FabianMartin, your contributions means a lot 🙏
