### ISSUE TITLE
Generic Fields does not handle Arrays (Type definition of type '*ast.IndexExpr' is not supported yet)

### ISSUE THREAD

**Issue by johan-lejdung** [swaggo/swag#1306]
**Describe the bug**
Generic fields with Arrays still not supported even after https://github.com/swaggo/swag/pull/1305.

**To Reproduce**
Have a look at the following repo https://github.com/chaintraced/swaggo-issue-repo
On the `main` branch's latest commit you will see that it is not working as intended. 

It's outputting
```
Type definition of type '*ast.IndexExpr' is not supported yet. Using 'object' instead.
```

**Expected behaviour**
I expect the generic field to be properly read and generated

**Your swag version**
I forked the repo to be able to release a version including the latest generic code changes `https://github.com/chaintraced/swag`

**Your go version**
e.g. 1.18.0

**Comment by johan-lejdung** [comment]
@FabianMartin I immediately found another case that is not supported 😅

This time I've built the testing repo to hopefully cover some other potential error cases as well, please let me know how I can help further 🙏

**Comment by FabianMartin** [comment]
Hi @johan-lejdung 

Thank you for your tests and your testing repo. This helps a lot to find all potential cases
