### ISSUE TITLE
Add excludes directories

### ISSUE THREAD

**Issue by rsinensis** [swaggo/swag#131]
I use the Visual Studio Code(vscode) with local history plugin, which generates a .history folder to hold the old content, so when I run the swag init command, it checks the folder and reports an error. 

```
2018/05/22 09:40:16 Generate swagger docs....
2018/05/22 09:40:16 Generate general API Info
2018/05/22 09:40:16 ParseFile panic:.history\main_20180423195313.go:1:1: expected 'package', found 'EOF'
panic: ParseFile panic:.history\main_20180423195313.go:1:1: expected 'package', found 'EOF'
```

So I want cli to have a parameter that excludes some directories.

**Comment by pei0804** [comment]
for you #133

**Comment by rsinensis** [comment]
Good. Thank you.

**Comment by easonlin404** [comment]
@rsinensis it's a workaround. we will add cli parameter to support excluded directories.
