### ISSUE TITLE
I got an error when swag init --parseDependency --parseInternal

### ISSUE THREAD

**Issue by HeinKoZin** [swaggo/swag#1312]
**Describe the bug**
**When I run _swag init --parseDependency --parseInternal_**

**I got an error like this:** 
`2022/08/28 14:02:52 Generate swagger docs....
2022/08/28 14:02:52 Generate general API Info, search dir:./
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x104f1e8]

goroutine 1 [running]:
github.com/swaggo/swag.(*PackagesDefinitions).parseFunctionScopedTypesFromFile(0xc0000947f8, 0xc000656b00, {0xc000306508, 0x4}, 0xc00b110e10)`

**To Reproduce**

**Expected behavior**
Swag will generate docs

**Your swag version**
e.g. 1.8.5

**Your go version**
e.g. 1.19.0

**Comment by blackout1208** [comment]
@HeinKoZin did you solve your issue?

**Comment by blackout1208** [comment]
For future reference, this issue occurs due to the new version. Do a fresh go install and afterward, you can remove all the parse arguments: swag init -g file_path

**Comment by sankalpbohra** [comment]
How you fix it.

**Comment by ubogdan** [comment]
duplicate  https://github.com/swaggo/swag/issues/1309

@sankalpbohra please downgrade to 1.8.4 or build swag from source.
