### ISSUE TITLE
Support excluded  directories cli option

### ISSUE THREAD

**Issue by easonlin404** [swaggo/swag#134]
**Is your feature request related to a problem? Please describe.**
https://github.com/swaggo/swag/issues/131 https://github.com/swaggo/swag/issues/131#issuecomment-391562757

**Describe the solution you'd like**
add cli option to support excluded directories.

**Comment by Nerzal** [comment]
Is anyone working on this problem right now? If not i'm gonna implement it

**Comment by easonlin404** [comment]
It's no needs to support for it because swag would search all go files under search dictionary.
