### ISSUE TITLE
[PROPOSAL] Adopt Go 1.19 documentation comment conventions

### ISSUE THREAD

**Issue by mrVanboy** [swaggo/swag#1364]
## Context

We are utilizing Go comments to provide a syntax for a `swag` tool that parses comments in code and generates open API specifications from them.

Go itself has some conventions too how to write comments and especially with [Go 1.19](https://tip.golang.org/doc/go1.19#go-doc), there are some new features that were added to provide standardization around some syntax (like lists or links) that is already widely used.

## Current state

Right now we have a `swag fmt` command that formats comments the next way:
```go
// @Keyword [additianal fields]...
```
and format looks like: `{delimeter}{keyword}{deliemter}{field1}{delimeter}...{fieldN}`

<details>
<summary>Real-code example from the examples directory</summary>

```go
// ShowAccount godoc
// @Summary      Show an account
// @Description  get string by ID
// @Tags         accounts
// @Accept       json
// @Produce      json
// @Param        id   path      int  true  "Account ID"
// @Success      200  {object}  model.Account
// @Failure      400  {object}  httputil.HTTPError
// @Failure      404  {object}  httputil.HTTPError
// @Failure      500  {object}  httputil.HTTPError
// @Router       /accounts/{id} [get]
func (c *Controller) ShowAccount(ctx *gin.Context) {
```

[[src](https://github.com/swaggo/swag/blob/da6d7189244994939dbf15c314d1205240942afd/example/celler/controller/accounts.go#L13-L25)]

</details>

Because Go uses comments to show documentation, the final result is not very friendly to the reader:
1. [Render on pkg.go.dev](https://pkg.go.dev/github.com/swaggo/swag@v1.8.7/example/basic/api). Note that it's a different struct as the celler example [cannot be shown on public pkg.go.dev](https://pkg.go.dev/github.com/swaggo/swag/example/celler) due to missing license in the cellar module root.
2. <details>
	<summary><code>go doc controller.Controller.ShowAccount</code></summary>
	
	```console
	$ cd example/celler && go doc controller.Controller.ShowAccount
	package controller // import "github.com/swaggo/swag/example/celler/controller"

	func (c *Controller) ShowAccount(ctx *gin.Context)
    	ShowAccount godoc @Summary Show an account @Description get string by
    	ID @Tags accounts @Accept json @Produce json @Param id path int true
    	"Account ID" @Success 200 {object} model.Account @Failure 400 {object}
    	httputil.HTTPError @Failure 404 {object} httputil.HTTPError @Failure 500
    	{object} httputil.HTTPError @Router /accounts/{id} [get]
	```

	</details>
3. <details>
	<summary>GoLand documentation render</summary>
	
	![image](https://user-images.githubusercontent.com/19638942/197971086-81930b78-133e-4027-ae09-24d427ea878d.png)
	
	</details>
4. <details>
	<summary>VSCodium documentation render</summary>
	
	![image](https://user-images.githubusercontent.com/19638942/197971834-5e6e1909-bbe2-4254-83d3-d350f99c7f2f.png)
	
	</details>

As you may notice from the examples above, Go concatenates comment lines if they are not divided
by two `\n` characters. In other words, there should be an empty line between paragraphs. And due to that, all swag comments, let's say, are useless for the reader of the documentation due to concatenation.

## Opportunity for improvement

Go has built-in support for [code blocks](https://go.dev/doc/comment#code) inside comments. The definition is:
> Code block ... is a span of indented or blank lines... Gofmt indents all lines in a code block by a single tab...

On top of that, with Go 1.19 support for [lists](https://go.dev/doc/comment#lists) was also added as an extension of the code blocks. It allows backward compatibility with older versions of Go. Lists are defined as:
> A list is a span of indented or blank lines (which would otherwise be a code block, ...) in which the first indented line begins with a bullet list marker or a numbered list marker.

`swag fmt` could indent swag-comment with one or more space characters (or tabd and optionally add list bullet) and allow much more reader-friendly documentation render.

## Proposal

Indent swag comments with tab character (`\t`) to allow better documentation rendering.

Let's show the code changes and result on the same example of the `examples/cellar/controller.Controller.ShowAccount`.

<details>
<summary>Final state</summary>

```go
// ShowAccount godoc
//
//	@Summary      Show an account
//	@Description  get string by ID
//	@Tags         accounts
//
//	@Accept       json
//	@Produce      json
//	@Param        id   path      int  true  "Account ID"
//	@Success      200  {object}  model.Account
//	@Failure      400  {object}  httputil.HTTPError
//	@Failure      404  {object}  httputil.HTTPError
//	@Failure      500  {object}  httputil.HTTPError
//	@Router       /accounts/{id} [get]
func (c *Controller) ShowAccount(ctx *gin.Context) {
```

</details>

<details>
<summary>Diff</summary>

Note that visually there is no change as tab character indentation is aligned with a pace one 😅 

```diff
--- a/example/celler/controller/accounts.go
+++ b/example/celler/controller/accounts.go
@@ -6,22 +6,25 @@ import (
 	"strconv"
 
 	"github.com/gin-gonic/gin"
+
 	"github.com/swaggo/swag/example/celler/httputil"
 	"github.com/swaggo/swag/example/celler/model"
 )
 
 // ShowAccount godoc
-// @Summary      Show an account
-// @Description  get string by ID
-// @Tags         accounts
-// @Accept       json
-// @Produce      json
-// @Param        id   path      int  true  "Account ID"
-// @Success      200  {object}  model.Account
-// @Failure      400  {object}  httputil.HTTPError
-// @Failure      404  {object}  httputil.HTTPError
-// @Failure      500  {object}  httputil.HTTPError
-// @Router       /accounts/{id} [get]
+//
+//	@Summary      Show an account
+//	@Description  get string by ID
+//	@Tags         accounts
+//
+//	@Accept       json
+//	@Produce      json
+//	@Param        id   path      int  true  "Account ID"
+//	@Success      200  {object}  model.Account
+//	@Failure      400  {object}  httputil.HTTPError
+//	@Failure      404  {object}  httputil.HTTPError
+//	@Failure      500  {object}  httputil.HTTPError
+//	@Router       /accounts/{id} [get]
 func (c *Controller) ShowAccount(ctx *gin.Context) {
 	id := ctx.Param("id")
 	aid, err := strconv.Atoi(id)

```
</details>

Render examples:
1. [Render on web](https://bradleyjkemp.dev/godoc-playground/). Copy the `Final State` code block here. It's an older version of the web documentation, but it's enough for demonstration
2. <details>
	<summary><code>go doc controller.Controller.ShowAccount</code></summary>
	
	```console
	$ cd example/celler && go doc controller.Controller.ShowAccount
	package controller // import "github.com/swaggo/swag/example/celler/controller"

	func (c *Controller) ShowAccount(ctx *gin.Context)
	    ShowAccount godoc
	
	        @Summary      Show an account
	        @Description  get string by ID
	        @Tags         accounts
	
	        @Accept       json
	        @Produce      json
	        @Param        id   path      int  true  "Account ID"
	        @Success      200  {object}  model.Account
	        @Failure      400  {object}  httputil.HTTPError
	        @Failure      404  {object}  httputil.HTTPError
	        @Failure      500  {object}  httputil.HTTPError
	        @Router       /accounts/{id} [get]
	
	```

	</details>
3. <details>
	<summary>GoLand documentation render</summary>
	
	
	![image](https://user-images.githubusercontent.com/19638942/197978159-c38e107a-bb07-4a61-9f3d-58ccf407fb96.png)
	
	</details>
4. <details>
	<summary>VSCodium documentation render</summary>
	
	
	![image](https://user-images.githubusercontent.com/19638942/197978305-711f0271-bd7c-4891-b22e-96063c41e318.png)

	
	</details>

## Implementation

It's theoretically quite a simple change, we only need to replace space char ` ` with tab char `\t` at https://github.com/swaggo/swag/blob/0da94ff45862b3da7611a724838158119dd26992/formatter.go#L115

Alternatively, we could also consider utilizing lists, but I do not see it as a huge benefit TBH. And rendering in monospaced font plays nice with tab-indented columns of the swag comments.

**Comment by ubogdan** [comment]
@mrVanboy I believe the annotation was made to be easy to be written. We can go to the next level by making it more friendly in IDE and pkg.go.dev.

Additionally, the parser needs to accept old and new formatting models.

This is an open-source project, and every contribution is welcome. It will be a pleasure to assist you with a CR.

**Comment by mrVanboy** [comment]
Thank's for the quick feedback. To be clear, it's not a request for a change. I would like to collect feedback from maintainers first. If all parties agree on a solution, I'd be glad to send a PR 😄

**Comment by ubogdan** [comment]
@sdghchj Your input is required here.

**Comment by sdghchj** [comment]
Seems just a litte change of  `fmt` command and there is no influence on parsing.

**Comment by mrVanboy** [comment]
Thank you all for such a quick response and for implementing it 🚀 Docs look great now https://pkg.go.dev/github.com/swaggo/swag@master/example/basic/api

Should I close the issue by myself or it will be closed e.g. during the next version release?

**Comment by ubogdan** [comment]
Unfortunately don't have such automation.
