### ISSUE TITLE
Set the host from the command line

### ISSUE THREAD

**Issue by yusrilmr** [swaggo/swag#1365]
**Is your feature request related to a problem? Please describe.**
We have two environments in our setup, which are development and production environments.
Both have different host addresses. Currently, we change the host addresses in the code by using:
```
docs.SwaggerInfo.Host = [host address]
```
However, this requires changes in the code which takes time because it requires some code review processes.
It would be nice if we can set the host addresses in the deployment pipeline.
However, I suppose this requires a new feature in Swaggo where we can set the host address via command line.

**Describe the solution you'd like**
I'd like to be able to set the host dynamically via the command line execution.
Something like:
```
swag init -g cmd/main.go --parseDependency --host "[host address]"
```
This flag specifically: **--host "[host address]"**

Thanks in advance :)

**Comment by ubogdan** [comment]
This can be easily achieved if you read the host from the environment

```go
hostname =  os.Getenv("API_HOST")
if len(hostname) > 0 {
 docs.SwaggerInfo.Host = hostname
}
```

**Comment by yusrilmr** [comment]
> This can be easily achieved if you read the host from the environment
> 
> ```go
> hostname =  os.Getenv("API_HOST")
> if len(hostname) > 0 {
>  docs.SwaggerInfo.Host = hostname
> }
> ```

Yes, you are right. It can be done like so. Thanks!

However, there is also another case that I forgot to mention.
When we set the host via `docs.SwaggerInfo.Host`, 
smh, it does not generate the host property in the generated `swagger.yaml` file.

Is there any way to let it set the host to the `swagger.yaml` file when we use `docs.SwaggerInfo.Host`?

**Comment by ubogdan** [comment]
The swagger.yaml is generated by the swag command and docs.SwaggerInfo.Host is a runtime option that allows you to override that value.
In your case you should setup the "production" hostname in the code comment so te swagger.yaml will contain the right value, and you should use the code to update that value for the rest of the environments.

**Comment by DG-Wangtao** [comment]
I think the best way is **do not set @host**, and then the host will be your browser host.
