### ISSUE TITLE
Error in generate doc in nested struct with using external pkg

### ISSUE THREAD

**Issue by meysamhadeli** [swaggo/swag#1378]
I have a problem with generate doc with cli command `swag init` in root of main my project `product-service` and get this error:
`cannot find type definition: utils.ListResult[int]`. 
in this project I use a external `pkg` with separate `go.mod` file and I get error in generate doc in root of `product-service`.

I get this error only in cli v1.8.7 but it's work currently in v1.8.3!

I have created a sample code in this repository: https://github.com/meysamhadeli/sample-bug-generic-type-swaggo
please take a look.

thanks...

swag version: v1.8.7
go version: 1.19

**Comment by sdghchj** [comment]
`swag init --parseDependency`

**Comment by meysamhadeli** [comment]
> `swag init --parseDependency`

Thanks for helping. it works currently with this command.
