### ISSUE TITLE
is swag cmd support golang generics?

### ISSUE THREAD

**Issue by bigjordon** [swaggo/swag#1383]
code:
func GetModel[T schema.Tabler](ctx context.Context, table T) error {
    _ = table  
    return nil
}

run swag init and occur error:    expected '(', found '[' 

swag version v1.8.0

is swag cmd support generics?

**Comment by sdghchj** [comment]
try the lastest master branch

**Comment by lowang-bh** [comment]
same error : expected '(', found '['
swagger verison : v1.8.8

**Comment by lowang-bh** [comment]
```
hack/build.sh docs
2022/11/25 16:45:41 Generate swagger docs....
2022/11/25 16:45:41 Generate general API Info, search dir:./
2022/11/25 16:45:42 ParseFile error:pkg/common/util.go:29:14: expected '(', found '['

swag --version
swag version v1.8.8
```

**Comment by sdghchj** [comment]
Althougn your swag is version 1.8.x,  I guess it is complied by a  go  version lower than v1.18.
Just try compiling swag with go v1.19 +

**Comment by lowang-bh** [comment]
> Althougn your swag is version 1.8.x, I guess it is complied by a go version lower than v1.18. Just try compiling swag with go v1.19 +

Thanks, my fault, forget to swith go version when use 'go install'.
