### ISSUE TITLE
Tab breaks General API Info

### ISSUE THREAD

**Issue by pboguslawski** [swaggo/swag#1397]
**Describe the bug**

When space is used as separator after `//` and between annotation and description in General API Info comments like
```
	// @termsOfService https://localhost/terms/
	// @contact.name API Support
	// @contact.url https://localhost/support
	// @contact.email support@localhost
```
`swag init` stores this info in doc.json correctly. After `swap fmt` replaces spaces with tabs, executing  `swag init` removes this info from doc.json.

No such problem noticed in other swag comments (i.e. actions).

**Expected behavior**
Tabs and spaces should be allowed in General API Info swag comments.

**Your swag version**
1.8.8

**Your go version**
1.19

**Desktop (please complete the following information):**
 - OS: linux

**Comment by sdghchj** [comment]
Sorry.
It's amazing that the tests have not found the bug.
Here I found another bug:
when it formats
```
// @Param   data	body	web.GenericBodyMulti[[]types.Post, [][]types.Post]
```
it will split `web.GenericBodyMulti[[]types.Post, [][]types.Post]` into two parts by the middle space.

I'll fix these bugs.
