### ISSUE TITLE
swag init --parseDependency is throwing negative shift amount or interface conversion error

### ISSUE THREAD

**Issue by mohanprasathsj** [swaggo/swag#1407]
**Describe the bug**
Recently when I tried to use swag init --parseDependency, I got 2 different errors - "runtime error: negative shift amount" and "interface conversion: interface {} is a string, not int". Both the errors are throwing at .evaluateConstValue in package.go

I tried creating a separate small project and while initializing I got the similar issue but intermittently (not getting repeatedly)

**To Reproduce**
1. Create a package that has a function that calls **interface** 
```
   For Example: func BindContextandResetBindContext(c echo.Context, i interface{}) error {
}
```
2. Use this package in swagger params
For Example:  @Failure      400  {object}  httputil.HTTPError
Above function is implemented in httputil module,

**Screenshots**
![image](https://user-images.githubusercontent.com/10070327/205881236-c05061c4-6ef6-43d2-9447-5833157dc264.png)

![image](https://user-images.githubusercontent.com/10070327/205881579-56d18710-c410-4df9-b20e-f64a1d51576b.png)

**Your swag version**
 v1.8.1

**Your go version**
1.19.1

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
I am currently using Swaggo with Echo Framework

**Comment by wlensinas** [comment]
Hi there, I have the same problem with mgm.DefaultModel vendor [struct](https://github.com/Kamva/mgm/blob/master/model.go)

```
type Ticket struct {
	mgm.DefaultModel   `bson:",inline"`
	Summary            string               `json:"summary,omitempty" bson:"summary"`
	State              string               `json:"state,omitempty" bson:"state"`
	RequestedBy        string               `json:"requested_by" bson:"requested_by"`
	AssignedTo         string               `json:"assigned_to,omitempty" bson:"assigned_to"`
}
```

I try this `swag init --parseDependency --parseInternal` but I have this error:

```
2022/12/07 13:15:23 Generate swagger docs....
2022/12/07 13:15:23 Generate general API Info, search dir:./
panic: runtime error: negative shift amount

goroutine 1 [running]:
github.com/swaggo/swag.(*PackageDefinitions).evaluateConstValue(0xc001299bd0, 0xc00fbdefc0?, 0xc00ef75350?, {0x162c640?, 0xc0012c7440?}, {0x162aba0, 0xc000077840}, 0x2b?)
       /directory/pkg/mod/github.com/swaggo/swag@v1.8.8/package.go:146 +0x101c
github.com/swaggo/swag.(*PackagesDefinitions).EvaluateConstValue(0xc00efbf698?, 0xc001299bd0, 0xc00ec431c0, 0x0)
       /directory/pkg/mod/github.com/swaggo/swag@v1.8.8/packages.go:282 +0x19d
github.com/swaggo/swag.(*PackagesDefinitions).evaluateAllConstVariables(...)
       /directory/pkg/mod/github.com/swaggo/swag@v1.8.8/packages.go:265
github.com/swaggo/swag.(*PackagesDefinitions).ParseTypes(0xc000077840)
       /directory/pkg/mod/github.com/swaggo/swag@v1.8.8/packages.go:110 +0x254
github.com/swaggo/swag.(*Parser).ParseAPIMultiSearchDir(0xc0001ea0c0, {0xc0001e80e0?, 0x1?, 0x0?}, {0x1560139?, 0x7?}, 0x64)
       /directory/pkg/mod/github.com/swaggo/swag@v1.8.8/parser.go:375 +0x3bf
github.com/swaggo/swag/gen.(*Gen).Build(0xc0001b19b0, 0xc0001aa2a0)
       /directory/pkg/mod/github.com/swaggo/swag@v1.8.8/gen/gen.go:182 +0x637
main.initAction(0xc0001d6780?)
        /directory/pkg/mod/github.com/swaggo/swag@v1.8.8/cmd/swag/main.go:158 +0x7bd
github.com/urfave/cli/v2.(*Command).Run(0xc0001838c0, 0xc0001c8580)
        /directory/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5bb
github.com/urfave/cli/v2.(*App).RunContext(0xc0001c44e0, {0x162d458?, 0xc0000260a8}, {0xc000020080, 0x4, 0x4})
        /directory/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb48
github.com/urfave/cli/v2.(*App).Run(...)
        /directory/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /directory/pkg/mod/github.com/swaggo/swag@v1.8.8/cmd/swag/main.go:229 +0x55d
```

**Your swag version:**  v1.8.8

**Your go version:** 1.18.8 darwim/amd64

**Desktop (please complete the following information):**
- **OS:** macOS

**Additional context**
I am currently using Swaggo with [chi](https://pkg.go.dev/github.com/go-chi/chi@v4.1.2)

**Comment by mohanprasathsj** [comment]
I get the same exception when I try to run the example API given by Swag

I ran the basic problem in the Example folder. 

![image](https://user-images.githubusercontent.com/10070327/206322971-13b09d02-a2aa-4205-a2ad-6367b99652c3.png)

**Comment by ubogdan** [comment]
all contributions are welcome.

**Comment by umurpza** [comment]
Same error

swag version: v1.8.8
go version: 1.19.4

**Comment by iamhayder** [comment]
same hare

swag version: v1.8.8
go version: 1.19.4

I solve it by downgrading swag to 1.8.4

**Comment by tmkhoa-dev** [comment]
Thank @iamhayder , I'm facing with this issue also. I downgraded and it worked

**Comment by klesh** [comment]
> same here
> 
> swag version: v1.8.8 go version: 1.19.4
> 
> I solve it by downgrading swag to 1.8.7

Same here

**Comment by ubogdan** [comment]
guys, has anyone tested against v1.8.9-rc2?

**Comment by ubogdan** [comment]
@sdghchj Can you give a hand here?

**Comment by sdghchj** [comment]
> @sdghchj Can you give a hand here?

What can I do?

**Comment by sdghchj** [comment]
> Same here
> 
> swag version: v1.8.9-rc2 go version: 1.19.1
> 
> ```
> 2022/12/08 08:37:19 Generate swagger docs....
> 2022/12/08 08:37:19 Generate general API Info, search dir:./
> 2022/12/08 08:37:19 warning: failed to get package name in dir: ./, error: execute go list command, exit status 1, stdout:, stderr:no Go files in /Users/nicolas.sassi/dev/12-8/bulbasaur
> panic: interface conversion: interface {} is string, not int
> 
> goroutine 1 [running]:
> github.com/swaggo/swag.(*PackageDefinitions).evaluateConstValue(0xc001e54730, 0xc006bf82a0?, 0xc00b7f7e90?, {0x165be80?, 0xc00258b140?}, {0x165a420, 0xc000145800}, 0xc0001d1aa0?)
>        .../go/pkg/mod/github.com/swaggo/swag@v1.8.8/package.go:132 +0x113f
> github.com/swaggo/swag.(*PackagesDefinitions).EvaluateConstValue(0xc00b273698?, 0xc001e54730, 0xc004d6fbc0, 0x0)
>         .../go/pkg/mod/github.com/swaggo/swag@v1.8.8/packages.go:282 +0x19d
> github.com/swaggo/swag.(*PackagesDefinitions).evaluateAllConstVariables(...)
>         .../go/pkg/mod/github.com/swaggo/swag@v1.8.8/packages.go:265
> github.com/swaggo/swag.(*PackagesDefinitions).ParseTypes(0xc000145800)
>         .../go/pkg/mod/github.com/swaggo/swag@v1.8.8/packages.go:110 +0x254
> github.com/swaggo/swag.(*Parser).ParseAPIMultiSearchDir(0xc00020e000, {0xc00020a0e0?, 0x1?, 0x0?}, {0x7ff7bfeff54d?, 0x18?}, 0x64)
>         .../go/pkg/mod/github.com/swaggo/swag@v1.8.8/parser.go:375 +0x3bf
> github.com/swaggo/swag/gen.(*Gen).Build(0xc0001d1950, 0xc0001ce2a0)
>        .../go/pkg/mod/github.com/swaggo/swag@v1.8.8/gen/gen.go:182 +0x637
> main.initAction(0xc0001f8780?)
>         .../go/pkg/mod/github.com/swaggo/swag@v1.8.8/cmd/swag/main.go:158 +0x7bd
> github.com/urfave/cli/v2.(*Command).Run(0xc0001a8d80, 0xc0001f4300)
>         .../go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5dc
> github.com/urfave/cli/v2.(*App).RunContext(0xc0001fc000, {0x165ce90?, 0xc00012c008}, {0xc000132000, 0x5, 0x5})
>         .../go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb7d
> github.com/urfave/cli/v2.(*App).Run(...)
>         .../go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
> main.main()
>         .../go/pkg/mod/github.com/swaggo/swag@v1.8.8/cmd/swag/main.go:229 +0x5c5
> ```

I don't think this log was generated by swag v1.8.9-rc2

**Comment by sdghchj** [comment]
v1.8.8 is a semi-finished version with fatal bug, we had better drop it.

**Comment by ubogdan** [comment]
@sdghchj, if you don't mind please investigate the issue and write a fix. 

My first thing is that even if it doesn't generate the right output/definition it should not crash. So if you can't figure out what is wrong with the implementation ensure type assertion is done via check


```go
str,ok := constantValue.(string)
if !ok {
    return errors.new("Expected string got int")
}
```

**Comment by sdghchj** [comment]
> @sdghchj, if you don't mind please investigate the issue and write a fix.
> 
> My first thing is that even if it doesn't generate the right output/definition it should not crash. So if you can't figure out what is wrong with the implementation ensure type assertion is done via check
> 
> ```go
> str,ok := constantValue.(string)
> if !ok {
>     return errors.new("Expected string got int")
> }
> ```

I have placed a defer recover() on top of these calls to output error lines after v1.8.8。I am sure those guys are still use v1.8.8 according their logs.

**Comment by philicious** [comment]
I confirm 1.8.8 throws me described error and downgrading to v1.8.7 solves it

**Comment by kokosnuss** [comment]
I had the same issue with 1.8.8 on Windows but with upgrading to swag-1.8.9-rc3 it works now!

**Comment by nicolasassi** [comment]
I had the same issue with 1.8.8 on macOS but with upgrading to swag-1.8.9-rc3 it works now!

**Comment by frontierhorizon** [comment]
> 1.8.7

what's the install command for swag version 1.8.7 ?

**Comment by ubogdan** [comment]
v1.8.9 released.

**Comment by vidorifaldy** [comment]
solve using swag v1.8.9
thank you

note: does not work on v1.8.8, but work on v1.8.7

**Comment by 0marq** [comment]
Hello ! Had the same issue, upgrading to v1.8.9 solved it ! Thanks for the release !
