### ISSUE TITLE
BasePath on v1.8.8

### ISSUE THREAD

**Issue by 733amir** [swaggo/swag#1410]
On version 1.8.8 I can't use `@BasePath` to define base path of my API.

**Your swag version**
1.8.8

**Your go version**
1.19.3

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.0.1
 - Browser: Chrome
 - Version: 108.0.53XX.XX

**Comment by sdghchj** [comment]
v1.8.8 is a deprecated version with fault

**Comment by sdghchj** [comment]
v1.8.9 fixed it
