### ISSUE TITLE
Allow response object to be local instead of being a ref

### ISSUE THREAD

**Issue by delisea** [swaggo/swag#1413]
Having response object always re-written with a ref and displaced to definition is a bit over-kill for one time used definition and reduce the readability of the swagger models.

Adding a new type kind alongside "object", "array" and primitives types allowing to disable ref for this response.
For instance "local". 
I have already written the associated commit (no PR yet as it is said to create an issue first) with its test.
There is no impact on the existent as the code allowing it is already in place, it only needed to activate it.
(by adding the ref parameter to operation.parseObjectSchema instead of the sub function operation.getTypeSchema)

I have test all possibility i found in documentation and looking at the code, the actual code doesn't allow this feature.
The closest i got was with:
`// @Success      200  object    any{data=string} "..."`
giving:
```
responses:
        "200":
          description: ...
          schema:
            allOf:
            - type: object
            - properties:
                data:
                  type: string
              type: object
```
Which kind of work, but in addition of the bad looking, doesn't work well with more complex struct.
Doesn't allow to add example/constraint tag neither

Example:
`// @Success      200  local  localType  "..."`
giving:
```
responses:
  "200":
    description: ...
    schema:
      properties:
        Data:
          type: string
      type: object
```

**Comment by sdghchj** [comment]
Actually, we care more about the display effect than the content of the yaml or json file.
If you want it to be more readable, `any` or `interface{}` is enough to generate the content you want. There is no need to introduce a keyword like `local`.

Why we decided to use refs?  Just keep the file size as small as possible.

**Comment by sdghchj** [comment]
Another question, why we use allof to override some fields of a struct?
Because usually a schema of a struct may be shared by many API routers, if we override directly a field of a schema in an API router, another API router which shares the schema will be affected.

**Comment by delisea** [comment]
I totally understand the argument but polluting the models list does impact the display (when you don't want to hide it).
'Any' indeed fix the issue but only partially, if I'm not wrong it is not possible to specify some constraints or example on any with overload of field.
For instance you can't achieve this: (could be also a min-value etc...)
```
responses:
  "200":
    schema:
      properties:
        Data:
          type: string
          example: a data value
      type: object
```
While you doesn't really want it to be listed to the relevant models list

**Comment by sdghchj** [comment]
If you want a more complex struct model, why not explicitly define one?
Response model combination is just a shortcut way to override struct fields, which is an alternative to generic before go v1.8.
We can't do too many things in one comment line, such as example、extension、default、enum、min、max etc...
Since generic is supported from go v1.8, response model combination is deprecated, exists just for compatibility.

**Comment by sdghchj** [comment]
I  got your point, you just want the models displayed alongside the router

**Comment by delisea** [comment]
So i close my PR
