### ISSUE TITLE
'Missing required param comment parameters' on external library that not I need

### ISSUE THREAD

**Issue by vidorifaldy** [swaggo/swag#1430]
I'm trying to create swagger using Swaggo with command

`swag init --parseDependency`
(I have struct on shared library so I have to use this option)

unfortunately, I got this error
![Screenshot_20221222_050546](https://user-images.githubusercontent.com/49903427/209262916-49c8a8a2-7a3a-4b6b-af44-9e45f9d03a74.png)

Is there any option better than I copy the struct to my project?
How to use exclude the library?

thank you

Hope it goes well normally

swag version is v1.8.9
go version is v1.19

**Comment by sdghchj** [comment]
I'm afraid no better way so far.

**Comment by sdghchj** [comment]
Here I want to clarify what is `dependency`. 
Usually, we just want to referece models from external packages which are called `dependency`.
Is there any need to parse API operations in `dependency`? There is no need, I think.
@ubogdan What's your opinion?

**Comment by vidorifaldy** [comment]
yes I need a model from external packages but got an error from another package that I don't need to parse

**Comment by ubogdan** [comment]
> Here I want to clarify what is `dependency`. Usually, we just want to referece models from external packages which are called `dependency`. Is there any need to parse API operations in `dependency`? There is no need, I think. @ubogdan What's your opinion?

The only valid reason may be the API handlers are stored in a `dependecy` package. This will make the development harder and, we should deprecate/remove this in future versions.

**Comment by vidorifaldy** [comment]
@sdghchj I got the insight from this 

<pre>https://github.com/swaggo/swag/issues/1014#issuecomment-1183215509</pre>

and then I change the command from this
`swag init --parseDependecy`
to this
` go mod vendor && swag init  --parseVendor --exclude ./vendor/github.com && rm -rf vendor`

It solved
but, I have a question, is it good or not?

**Comment by sdghchj** [comment]
@vidorifaldy Could you please try the latest PR 1432?

**Comment by vidorifaldy** [comment]
@sdghchj still get the same error

**Comment by sdghchj** [comment]
> @sdghchj still get the same error

It seems impossible.

**Comment by vidorifaldy** [comment]
@sdghchj thank you so much, It solved on v1.8.10

note: another issue after Merged PR 1432 [Issues 1451](https://github.com/swaggo/swag/issues/1451)
