### ISSUE TITLE
How to set the header on swagger?

### ISSUE THREAD

**Issue by JimChung0403** [swaggo/swag#144]
I have a question.

My API need token authentication.
How should I set  header key "Authorization" on swagger doc?

my code:
// @Description api 
// @Accept  json
// @Produce  json
// @Content-Type application/json
// @Param   sendBody body apimodel.ExamplePost true  "body"
// @Success 200 {string} apimodel.Response	"ok"
// @Failure 400 {object} apimodel.Response "Bad Request"
// @Router /v1/example/testpost [post]

**Comment by easonlin404** [comment]
You can reference https://swaggo.github.io/swaggo.io/declarative_comments_format/api_operation.html#security and https://github.com/swaggo/swag/blob/master/testdata/simple2/main.go more detail example.

**Comment by gigibox** [comment]
hi @easonlin404 :
 I tried, it doesn't seem to be working.

"Then, use the security section on the root level or operation level to apply API keys to the whole API or specific operations." from https://swagger.io/docs/specification/2-0/authentication/api-keys/

and ... how to set 
security:
  - APIKeyHeader: []
?? thanks.

**Comment by rametta** [comment]
Does this not work with OAuth2Implicit? My header is not being sent after authentication @easonlin404
