### ISSUE TITLE
How to support custom field names. `form` instead of `validate`

### ISSUE THREAD

**Issue by dumindu** [swaggo/swag#1484]
About https://github.com/swaggo/swag#available

How we can configure to use `form` field name for `validate`, if we use `form` to set validators?

**Comment by ubogdan** [comment]
That's not configurable.

**Comment by dumindu** [comment]
Swagger/swag is supporting Gin. But Gin framework use form tag instead of validate tag

**Comment by ubogdan** [comment]
> Swagger/swag is supporting Gin. But Gin framework use form tag instead of validate tag

We are offering integration for the gin framework.
