### ISSUE TITLE
Cant type in Multitple Query Parameter

### ISSUE THREAD

**Issue by sh0umik** [swaggo/swag#15]
If i Define multiple Query Parameter in Swagger JSON file then i am not able to type in any of them . But if i keep it to one query parameter then i can type .. any fix for that ?

**Comment by easonlin404** [comment]
I have tested swagger ui to  3.5.0 fixed by https://github.com/swaggo/gin-swagger/pull/4 . It's work for multi query parameter to type in any of them.  
Thanks for your contribution. :thumbsup::thumbsup::thumbsup:
