### ISSUE TITLE
invalid method: PURGE

### ISSUE THREAD

**Issue by callMe-Root** [swaggo/swag#1503]
**Describe the bug**
Hi, I am using PURGE method for some of my endpoints, when I swag init I get this error: "invalid method: PURGE"

**To Reproduce**
This is an example for my PURGE endpoint:

<img width="799" alt="resim" src="https://user-images.githubusercontent.com/68336965/224833630-64eb8b59-40f8-42f9-9e1d-917adec59fca.png">

**Expected behavior**
I couldn't find anything related to http methods in the documents, is there a way I can define custom methods to work around this error?

**Your swag version**
swag version v1.8.9

**Your go version**
GOVERSION="go1.18.5"

**Comment by callMe-Root** [comment]
no you are right, its not defined but used conventionally, i cant show you a definition or rfc but for example its predefined in postman or similar tools https://stackoverflow.com/questions/25857508/what-is-the-http-method-purge

i already have a delete endpoint with same path, i need a distinguished method for a function that cleaning cache of application, if you know something more suitable i would like to follow that

**Comment by ubogdan** [comment]
:) try DELETE
