### ISSUE TITLE
When I use swag init with a generic type, I get an error

### ISSUE THREAD

**Issue by amyunfei** [swaggo/swag#1526]
**Describe the bug**
When I use swag init with a generic type, I get an error ```:cannot find type definition: response.Body[string]```

**To Reproduce**
1. No packages at the project root
2. Use the -g parameter, for example```swag init -g ./cmd/main.go -o ./api```
3. Get a warning ```warning: failed to get package name in dir: ./, error: execute go list command, exit status 1, stdout:, stderr:no Go files in [projectPath]```
4. Get an error ```ParseComment error in file [filePath] :cannot find type definition: response.Body[string]```
5. logger
 ```
swag init -g ./cmd/main.go -o ./api
2023/04/02 20:34:41 Generate swagger docs....
2023/04/02 20:34:41 Generate general API Info, search dir:./
2023/04/02 20:34:41 warning: failed to get package name in dir: ./, error: execute go list command, exit status 1, stdout:, stderr:no Go files in /Users/haoyunfei/open-source/glassy-sky
2023/04/02 20:34:41 Generating dto.CreateCategoryRequest
2023/04/02 20:34:41 Generating dto.CreateCategoryResponse
2023/04/02 20:34:41 Generating dto.SuccessEmptyResponse
2023/04/02 20:34:41 Generating dto.ModifyCategoryRequest
2023/04/02 20:34:41 Generating dto.ListRequest
2023/04/02 20:34:41 Generating dto.FilterCategoryRequest
2023/04/02 20:34:41 Generating dto.CreateLabelRequest
2023/04/02 20:34:41 Generating dto.CreateLabelResponse
2023/04/02 20:34:41 Generating dto.ModifyLabelRequest
2023/04/02 20:34:41 Generating dto.FilterLabelRequest
2023/04/02 20:34:41 Generating dto.CreateUserRequest
2023/04/02 20:34:41 Generating dto.CreateUserResponse
2023/04/02 20:34:41 Generating dto.LoginRequest
2023/04/02 20:34:41 ParseComment error in file /Users/haoyunfei/open-source/glassy-sky/internal/admin/handler/user_handler.go :cannot find type definition: response.Body[string]
make: *** [swag] Error 1 
```

**Expected behavior** 
can be successfully generated

**Screenshots**
No go file at the project root
![B6C857B9-2A6A-4762-A399-C28F53B71595](https://user-images.githubusercontent.com/49634451/229353988-bae3488b-6a05-4df6-949f-34085356e239.png)

![image](https://user-images.githubusercontent.com/49634451/229354105-a9d13ad0-3781-499c-a1c7-726f27f6971b.png)

**Your swag version**
1.8.10

**Your go version**
1.20

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.2.1
 - Browser: N/A
 - Version: N/A

**Additional context**
When I create the main.go file in the root of the project, it works fine```swag init -g ./cmd/main.go -o ./api```  
```
// main.go
package main
```
So I guess it's because of this warning ```warning: failed to get package name in dir: ./, error: execute go list command, exit status 1, stdout:, stderr:no Go files in [projectPath]``` 
I just started using it so I don't quite understand why I specified the -g parameter but it still 
```
Generate general API Info, search dir:./
```
So I think this is the cause of the error

**Comment by sdghchj** [comment]
Give more information, please.
Have you import package `response`？

**Comment by amyunfei** [comment]
> 请提供更多信息。 你导入包了吗`response`？
Yes, I have imported the response package.
And without changing the code, I added the main.go file to the root of the project and ran the command 
```swag init -g ./cmd/main.go -o ./api```  it works fine, no warnings and errors, response.Body[string] can be generated correctly.
Once I removed the main.go file from the root of the project, I get warnings and errors ```:cannot find type definition: response.Body[string]```

**Comment by sdghchj** [comment]
If there is no go files in your root dir, you have to explicitly set subdirs with flag `-d`,  just run cmd like:
`swag init -g ./cmd/main.go -d ./pkg,./internal`

**Comment by amyunfei** [comment]
> If there is no go files in your root dir, you have to explicitly set subdirs with flag `-d`, just run cmd like: `swag init -g ./cmd/main.go -d ./pkg,./internal`

@sdghchj Thanks a lot. I think I understand
