### ISSUE TITLE
Parameteres of generated model for request are reordered (shuffled) regarding Go model (struct)

### ISSUE THREAD

**Issue by giganttus** [swaggo/swag#1559]
**Describe the bug**
I expected result of generating documentation to be totally based on "code order". It might sound silly but I prefer to have same order in some fields that I'm customizing by my habit of code structure. I would like to know is there any way to make it with current features of swaggo or its currently impossible ?

**To Reproduce**
Here is description I wrote for my function

```
// CreateAp 		godoc
// @Summary 	        Create Access Point
// @Description 	Create new AP and save in DB
// @Param 		AP body models.CreateAccessPointReq true "Create AP"
// @Accept		json
// @Produce 		json
// @Tags	        AP
// @Sucess		200 {object}
// @Failure 500 	500 {object}
// @Router		/aps [post]
```

This is model that is passed thought Param section (models.CreateAccessPointReq)
```
type CreateAccessPointReq struct {
	Name                 string `json:"name" binding:"max=50"`
	Location             string `json:"location" binding:"max=50"`
	ContactPerson        string `json:"contactPerson" binding:"max=50"`
	Contact              string `json:"contact" binding:"max=50"`
}
```
After documentation is generated my "Example Value" looks like this, as I described it is ordered alphabetically that isn't favourable for me.
```
{
  "contact": "string",
  "contactPerson": "string",
  "location": "string",
  "name": "string"
}
```
**Expected behavior**
I was expecting to get JSON formated like this example (same order as model in code):
```
{
  "name": "string",
  "location": "string",
  "contactPerson": "string",
  "contact": "string"  
}
```

**Your swag version**
2.0

**Your go version**
1.20.3

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Browser: [Mozilla Firefox]
 - Version: [112.0.1 (64-bit)]

**Comment by Nerzal** [comment]
Does this also happen in https://github.com/swaggo/swag/releases/tag/v1.8.12 ?

**Comment by giganttus** [comment]
> Does this also happen in https://github.com/swaggo/swag/releases/tag/v1.8.12 ?

Thats exact version I'm currently using if I'm not wrong. As you can see on screenshoot:
![slika](https://user-images.githubusercontent.com/24629551/232775683-f18563df-472e-42e0-9443-fb13237ee63c.png)

**Comment by sdghchj** [comment]
```
type CreateAccessPointReq struct {
	Name                 string `json:"name" binding:"max=50"  extensions:"x-order=1"`
	Location             string `json:"location" binding:"max=50"  extensions:"x-order=2"`
	ContactPerson        string `json:"contactPerson" binding:"max=50"  extensions:"x-order=3"`
	Contact              string `json:"contact" binding:"max=50"  extensions:"x-order=4"`
}
```

**Comment by shadowgroundz** [comment]
I am facing the same issue. Already added extensions: "x-order=1" and it does not effect to me
