### ISSUE TITLE
Release v1.16.1 generates broken codes in docs.go

### ISSUE THREAD

**Issue by IrvinFan** [swaggo/swag#1564]
**Describe the bug**
There are two issues with the new version v1.16.1 that was released on 4/17/2023

**To Reproduce**
1. `go install -v github.com/swaggo/swag/cmd/swag@latest` (v1.16.1 will be installed as of 4/18/2023)
2. `swag -v` (**issue No. 1**: it shows "v1.8.12" but the version is actually "v1.16.1")
4. `swag init -g server/server.go --parseDependency`
5. `golangci-lint run ./...`

**issue No. 2**: Got errors like:
```
docs/docs.go:144:2: unknown field LeftDelim in struct literal of type "github.com/swaggo/swag".Spec
docs/docs.go:145:2: unknown field RightDelim in struct literal of type "github.com/swaggo/swag".Spec (typecheck)
```

**Your swag version**
1.16.1

**Your go version**
1.20.3

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**

**Comment by UvDream** [comment]
> 

how to solve？

**Comment by book987** [comment]
> > 
> 
> how to solve？

rollback to [1.8.11](https://github.com/swaggo/swag/releases/tag/v1.8.11) and it will not generate `LeftDelim` and `RightDelim`, but make sure v1.8.11 satisfy your need first

**Comment by Nerzal** [comment]
Meh

**Comment by Nerzal** [comment]
This should be fixed

**Comment by IrvinFan** [comment]
I closed this issue because it can be fixed by bumping up the swag version in your app (go.mod).

But the other issue still exists: the version reported by `swag -v` is wrong though. This off course is a lesser issue.

**Comment by Nerzal** [comment]
The version issue will be fixed with the next release. 
The version issue was introduced due to an accident. I pushed a wrong tag, the goproxy picked it up and we had to create a new higher versioned tag to fix the issue
