### ISSUE TITLE
Body data type `file` as binary body

### ISSUE THREAD

**Issue by StevenCyb** [swaggo/swag#1566]
**Describe the bug**
In my API I have an endpoint that accept `octa-stream` with a binary body file. 
I tried to define it like:
```go
// @Summary Image file upload
// @Tags image
// @Accept octet-stream
// @Param file body file true "Image file"
// @Success...
```
But the CLI does not recognise `file` as data type:
```
ParseComment error in file /..../main.go cannot find type definition: file
```

Could it be that Swagger is not able to support file upload without multipart form?

**To Reproduce**
1. Place the above mentioned spec in a file
2. Run `swag init`
4. See error log

**Expected behavior**
That `file` will be resolved and that I can select a file in the swagger ui using the generated swagger json.

**Your swag version**
e.g. v1.8.12

**Your go version**
e.g. 1.20.2

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 13.3.1 (22E261)

**Comment by sdghchj** [comment]
// @Param file formdata file true "Image file"

**Comment by mariusgassen** [comment]
I ran into the same problem and used this as a workaround 

`//	@Param	Content	body	os.File	true`

If you do not want to upload the file as application/formdata 

[OpenAPI Spec 2.0](https://swagger.io/docs/specification/2-0/file-upload/) does not support specifying the raw file as the payload

See in the FAQ on the bottom

> Uploads where the payload is just the raw file contents are not supported in Swagger 2.0, because they are not multipart/form-data. That is, Swagger 2.0 does NOT support something like:

`curl --upload-file archive.zip http://example.com/upload`

**Comment by StevenCyb** [comment]
@mariusgassen Thank you for the response and your workaround suggestion.
