### ISSUE TITLE
use another starting point other than main.go

### ISSUE THREAD

**Issue by Ashtonian** [swaggo/swag#157]
**Is your feature request related to a problem? Please describe.**
I have a multi-application CLI  for a distributed system. Example usage of this kind of app would be something like: 
```
myapp api
myapp scheduler
```
The problem is swag init and the library in general **has** to be pointing at main.go, which for me is a wrapper/entry point to several applications. 

**Describe the solution you'd like**
A way to configure where to look for documentation?  

**Describe alternatives you've considered**
I could go with a different cli structure..

**Comment by easonlin404** [comment]
And I will add all of swag document at our README to get more clarity.
