### ISSUE TITLE
[Question] Is there a way to parse annotations from libraries?

### ISSUE THREAD

**Issue by boindil** [swaggo/swag#1571]
I have a central library, that provides a common route for all my services. Is it possible to parse the annotations in that library, so that it can be tested per service via swagger ui?

**Comment by klaveriuzent** [comment]
Yes, it is possible to parse the annotations in your central library and generate Swagger documentation for each service.

**Comment by klaveriuzent** [comment]
> I have a central library, that provides a common route for all my services. Is it possible to parse the annotations in that library, so that it can be tested per service via swagger ui?

Yes, it is possible to parse the annotations in your central library and generate Swagger documentation for each service.

**Comment by boindil** [comment]
@klaveriuzent would you mind sharing more insight on how to do this? I had no success yet - is this documented somewhere and I've overlooked it?

**Comment by klaveriuzent** [comment]
> @klaveriuzent would you mind sharing more insight on how to do this? I had no success yet - is this documented somewhere and I've overlooked it?

While I may not be able to provide specific implementation details, here's a general outline of the four steps you need to follow:

1. Identify the annotations used in your central library: Review the annotations utilized in your central library, which define the API routes and parameters. Pay attention to annotations specific to your chosen framework or library.

2. Implement an annotation parser: Develop a parser capable of extracting relevant information from the annotations in your central library. Use reflection or framework-specific utilities to analyze the annotations and retrieve the necessary details such as routes, HTTP methods, and additional parameters.

3. Generate Swagger documentation: Once you have parsed the annotations and obtained the required information, leverage it to generate Swagger documentation. There are various libraries and tools available in different programming languages that can assist in programmatically generating Swagger or OpenAPI documentation.

4. Integrate with Swagger UI: Swagger UI is a popular tool for visualizing and testing APIs using Swagger or OpenAPI documentation. Ensure the generated Swagger documentation is integrated with Swagger UI in each service. This integration allows the API endpoints and their documentation to be accessible through the Swagger UI interface.

In general, having prior experience with MVC can make the process of parsing annotations and integrating with Swagger UI more intuitive. By leveraging the existing MVC structure and conventions, you can align the annotation parsing and Swagger documentation generation with the organization of your controllers. This familiarity with MVC principles can facilitate a smoother implementation of the overall process.

Then here what u need https://swagger.io/docs/

**Comment by fishjam** [comment]
I have same issue for this. example:
- 1. I create a common library and define some model struct in it. 
- 2. I create server app and use these model , and try use these model in app's code, 
- 3. go build  <== successful
      swag init <== fail with ParseComment error in file xxxx\http.go :cannot find type definition: model.CreateUserRequest

this is my demo code, If need, I can create a demo project. 

@klaveriuzent 
can swag support this ? thank you very much and waiting for your response. 

```go

import "github.com/xxx/common/model"

// @summary	Create User
// @tags	User
// @Accept	json
// @Produce	json
// @Param	info	body	model.CreateUserRequest	true	"request"               <== swag init fail for this. 
// @Router	/api/v1/user [post]
func (server *HttpServer) createUser(ctx *gin.Context) {
	createRequest := model.CreateUserRequest{}
	err := ctx.Bind(&createRequest)     <== build successful
        ...
}
```

**Comment by fishjam** [comment]
After more check, `--pd`  can `Parse go files inside dependency folder`
