### ISSUE TITLE
Support custom types/fields

### ISSUE THREAD

**Issue by Ashtonian** [swaggo/swag#158]
**Is your feature request related to a problem? Please describe.**
I have a struct: 
```
type Folder struct {
	ID         int           
	Name      string         
	Path      string        
	PathIDs   types.IntSlice
}

// IntSlice - a postgres compatible int slice type
type IntSlice []int
```

it has a custom type `types.InSlice` which is really just an alias (defined `type IntSlice []int` ) for a built-in type so I could add things like `Value()` and `Scan()` to support the db driver.  The problem is swag says `IntSlice is not supported.` I have another type that is also like this but underthe hood is just a `map[string]interface{}`. 

**Describe the solution you'd like**
I'd like to be able to just say override the default string type with x which in my case would be an `[]int`.  

**Describe alternatives you've considered**
I could manually override the generated documentation, or write a script to do it, or create another struct just for documentation purposes.

**Comment by pei0804** [comment]
I'd like to support this.
Are you planning to PR?

**Comment by Ashtonian** [comment]
@pei0804 I am not planning on submitting a PR.

**Comment by pei0804** [comment]
I create now.
https://github.com/swaggo/swag/issues/164
wait plz.

**Comment by pei0804** [comment]
@abdulito fixed this case!
https://github.com/swaggo/swag/pull/198
