### ISSUE TITLE
Support nested imports for Struct definitions

### ISSUE THREAD

**Issue by inoda** [swaggo/swag#159]
**Is your feature request related to a problem? Please describe.**
I have a Struct:
```
type RevenueMetricsPayload struct {
	RevenueMetrics procedures.RevenueMetricsTimeline `json:"revenueMetrics"`
	Counts         []count                           `json:"counts"`
	ProcessedAt    string                            `json:"processedAt"`
}
```

When generating docs, I get this message 

> RevenueMetricsTimeline is not supported. but it will be set with string temporary

**Describe the solution you'd like**
I would like the nested import to be followed, and have `procedures.RevenueMetricsTimeline` in my example built out based on the defined Struct.

**Describe alternatives you've considered**
I could manually override the generated documentation, or write a script to do it, or create another struct just for documentation purposes.

**Comment by easonlin404** [comment]
@inoda PR is welcome 😄

**Comment by pei0804** [comment]
I support this.
