### ISSUE TITLE
can not support Type in denpency and interface Type

### ISSUE THREAD

**Issue by zzq392342084** [swaggo/swag#16]
for example , a struct like below : 
type VO struct{
   code: string 
   msg : string
   data: interface {}
}
I can not reference it in response annotation 

also ,can not reference a type not in current file : 
VoMap defined in other package
_c.JSON(http.StatusOK, VoMap{"code": 200, "org": org})_
![default](https://user-images.githubusercontent.com/12469232/33408675-bf01aec4-d5b2-11e7-99f2-41a09807c1dc.png)

**Comment by easonlin404** [comment]
@zzq392342084  `swag` doesn't support `interface{}` type yet.  I want to support it in further version(pull request welcome 😄 ). For parsing efficiency, `swag` now only search in project root folder which contains `main.go` file.

**Comment by zzq392342084** [comment]
ok,thanks!
