### ISSUE TITLE
A way to specify an empty/nil response body 

### ISSUE THREAD

**Issue by Ashtonian** [swaggo/swag#161]
**Is your feature request related to a problem? Please describe.**
My api for 404 responses just returns a 404 status code, and for deletes just returns a 204 status code. These responses have no body, and I would like to keep that in the documentation.
**Describe the solution you'd like**
A way to indicate the status code with no additional response types. 
Something like `// @Failure 404 nil` ? 

**Describe alternatives you've considered**
not document the failure type 

Thanks for the library! it's pretty dope.

**Comment by pitw** [comment]
Same problem here - tried with {}, [], nil...
Either gives error or shows false content.

**Comment by easonlin404** [comment]
Thanks for report this issue, I will fix asap.

**Comment by pei0804** [comment]
Can you done?
https://github.com/swaggo/swag/pull/163

**Comment by pitw** [comment]
Thanks. This way it works now:

`// @Success 204 ""`

Can you add this to docs?

**Comment by easonlin404** [comment]
@pitw sure, will add to docs later.

**Comment by gl-ot** [comment]
`// @Success 204 ""` doesn't work with open api 3, you have to add description `// @Success 204 "Your Description"`
