### ISSUE TITLE
Implementation of Servers.variables in OpenAPI v3

### ISSUE THREAD

**Issue by nonchan7720** [swaggo/swag#1611]
**Is your feature request related to a problem? Please describe.**
I want to use servers.varables.

**Describe the solution you'd like**
Implement servers.varables.

**Describe alternatives you've considered**
sv-tools/openapi supports Variables, so implement it additionally

**Additional context**

I think I can implement it, so I would like to give it a try.

**Comment by ivan-penchev** [comment]
@nonchan7720  close this issue, since you merged the fix :)

**Comment by nonchan7720** [comment]
@ivan-penchev 

Thank you!
