### ISSUE TITLE
[question] about array swag

### ISSUE THREAD

**Issue by lekeeith** [swaggo/swag#1619]
it's easy for me to do this
```go
//@Param citys query []string true "城市数组" Enums(CityA,CityB,CityC,CityD,CityE,CityF)
```
but i wanna use it in struct
```go
// ParamYayunWRFCMAQTxt WRFCMAQ模型预测结果
type QuerParam struct {
    Citys       []string    `json:"citys" form:"citys" enums:"[CityA,CityB,CityC,CityD,CityE,CityF]" swaggertype:"array,string"`              // city array
}

```
![image](https://github.com/swaggo/swag/assets/51192597/64fdf5aa-29f7-4dfb-a5a9-28c5dbc22d94)

i hope like 
![image](https://github.com/swaggo/swag/assets/51192597/60c013e5-c746-4c00-984a-eefed6935b5e)
the last img is from https://editor.swagger.io/#/
    - description: array cvity
      in: query
      name: citys
      type: array
      items:
        type: string
        enum:
          - "CityA"
          - "CityB"
          - "CityC"
          - "CityD"
          - "CityE"
          - "CityF"

go version 1.18.5
swag version 1.16.1

**Comment by sdghchj** [comment]
不要中括号
```
type QuerParam struct {
    Citys       []string    `json:"citys" form:"citys" enums:"CityA,CityB,CityC,CityD,CityE,CityF" swaggertype:"array,string"`              // city array
}
```

**Comment by lekeeith** [comment]
谢谢你的提醒，带中括号其实只会影响CityA和CityF。但是对我来说是另外一个问题。前端传来参数是使用&符号，但是默认的collectionFormat是csv，当然我可以在函数头添加类似
// @Param  SpecItem query  []models.SpecItem True "查询指定参数" collectionFormat(multi)
实现更改，但是在struct里的
type QuerParam struct {
    Items       []SpecItem    `json:"citys" form:"citys" collectionForma="multi"`              // Item array
}
是无效的。
我还可以在执行 swag init --cf multi 完成 QuerParam中collectionForma参数无效的问题(实际上改变了collectionForma的默认值)
但是无论我做什么努力，在struct里的collectionForma="multi"似乎是无效的。

**Comment by lekeeith** [comment]
@easonlin404  Can you test what i  said above, i test many time and no what result i wanna.

**Comment by sdghchj** [comment]
> 谢谢你的提醒，带中括号其实只会影响CityA和CityF。但是对我来说是另外一个问题。前端传来参数是使用&符号，但是默认的collectionFormat是csv，当然我可以在函数头添加类似 // @param SpecItem query []models.SpecItem True "查询指定参数" collectionFormat(multi) 实现更改，但是在struct里的 type QuerParam struct { Items []SpecItem `json:"citys" form:"citys" collectionForma="multi"` // Item array } 是无效的。 我还可以在执行 swag init --cf multi 完成 QuerParam中collectionForma参数无效的问题(实际上改变了collectionForma的默认值) 但是无论我做什么努力，在struct里的collectionForma="multi"似乎是无效的。

`collectionFormat`  vs `collectionForma`  ????

**Comment by lekeeith** [comment]
> 

是我在github上出入错误，我使用的也确实是collectionFormat。

**Comment by sdghchj** [comment]
结构体成员tag上不支持collectionFormat

**Comment by lekeeith** [comment]
> 结构体成员tag上不支持collectionFormat

谢谢提醒。但是结构成员tag不支持的话，做结构成员对象感觉就不是很必要了。
