### ISSUE TITLE
When the return value defined by the @ Success tag is equal to a null value, a null pointer exception occurs

### ISSUE THREAD

**Issue by addice1019** [swaggo/swag#1653]
**Describe the bug**
When the return value defined by the @ Success tag is equal to a null value, a null pointer exception occurs

**To Reproduce**
1.  Response {data=nil} in the structure
![image](https://github.com/swaggo/swag/assets/107458350/394b3dfd-49dc-4d02-84ee-a4c742baa99c)

2. Run the command swag init in cmd
![image](https://github.com/swaggo/swag/assets/107458350/88ccd9a4-fc90-459e-b1a8-0c89bae12dfa)

3. Invalid memory address or nil pointer dereference discovered through debugging
![image](https://github.com/swaggo/swag/assets/107458350/7f7da9a8-d49c-412a-82fe-b2d536fa956c)

**Expected behavior**
Can swaggo parse comments in the returned structure that are equal to nil, such as utils. Response {data=nil}
Expected swaggo doc definition
```go
// deleteFile 删除文件
//
//	@Summary		删除文件
//	@Description	删除文件
//	@Tags			member
//	@Accept			json
//	@Produce		json
//	@Param			fileIds	query		string	true	"文件ID集合字符串"
//	@Success		200		{object}	utils.Response{data=nil}
//	@Failure		400		{object}	utils.ErrorResponse
//	@Router			/app/deleteFile [POST]
func deleteFile(c *gin.Context) {
}
```
Expected JSON return value
```json
{
   "status": 0,
   "message": "success",
   "data": null
}
```

**Your swag version**
v1.16.1

**Your go version**
go1.20.5

**Desktop (please complete the following information):**
 - OS: [windows 10 19045.3324]

**Comment by sdghchj** [comment]
May I ask why need null?

**Comment by addice1019** [comment]
The project coexists with the Springboot project and requires a unified JSON return value

**Comment by Shimizu1111** [comment]
What do you think of the solution in #1667 ?

**Comment by Shimizu1111** [comment]
@sdghchj 
What do you think of the solution in #1667 ?
