### ISSUE TITLE
能支持一下泛型吗？

### ISSUE THREAD

**Issue by marsberrys** [swaggo/swag#1658]
res.Result{data=xxx}

data 是泛型的情况下，现在只能用这种迂回的方式写，如果数据里多几级都有泛型属性的话，这里得写得好复杂

**Comment by rickylin614** [comment]
已經有支持泛型了

**Comment by bingtianyiyan** [comment]
> 已經有支持泛型了

请问下泛型swager tag返回值有案例么？

**Comment by bingtianyiyan** [comment]
> 已經有支持泛型了
gin-swagger v1.3.0 版本
cannot find type definition: common.ResponsePageList[dto.DevicePageListResponseDto]   is error 
请问下泛型的生成有特别一点么？

**Comment by marsberrys** [comment]
https://github.com/swaggo/swag/blob/master/testdata/generics_nested/api/api.go
看了一系官方的 demo， 确实支持了
