### ISSUE TITLE
Can anyone tell me why the version number was directly upgraded from 1.8.x to 1.16.x

### ISSUE THREAD

**Issue by bilinxing** [swaggo/swag#1665]
I'm curious about this sudden jump in version numbers, but haven't found any explanation or explanation, is 1.16.x a big upgrade or difference from 1.8.x?

**Comment by smallfish06** [comment]
There was a description for a misconfigured tag before (1.16.x), but I have no idea why the new tag was named 1.16.

**Comment by sdghchj** [comment]
Me too.  
It seems commited by @Nerzal at PR #1562. @ubogdan

**Comment by Nerzal** [comment]
We had a package caching problem. Introduced by pushing a wrong Tag
