### ISSUE TITLE
How to document not-function handler?

### ISSUE THREAD

**Issue by mgtest42** [swaggo/swag#169]
I'm using gin and some own helpers on top of it, so my generic handlers look like:
```
var AccountView = api.View{
getOne: getAccount, // returns slice of objects
getAll:getAccounts, // returns object by id from request
preSave: func (c *gin.Context, obj models.IModel){...},
// ...
}

// ...
router.GET("/v1/accounts", AccountView.ListView())
// ...
```

How to use swagger in this case? It seems that godoc comment is parsing only if it placed above the function body - parser sees docs for function handlers.

**Comment by mgtest42** [comment]
Why do you parse only comments above function declaration?
I've made the patch for my use-case - https://pastebin.com/DeqUqkYp
The only change is that I parse all comments.
Should I create pull-request? Or isn't it the feature what you want in the project?

**Comment by pei0804** [comment]
Current syntax was convenient for Go AST package.
but, I would like to merge if there is a good feature.

**Comment by pei0804** [comment]
If possible please tell me the merit of the syntax that you would like to propose.

**Comment by mgtest42** [comment]
I don't insist. In the world of go, there are no established frameworks and everyone uses their basic structure. But this is can be only my approach?

In my use case, handlers with generic logic are defined as a variable declaration.
Perhaps someone would like to make their handlers based on structures, not functions.

After my change, I was able to describe the handlers as follows:

```
// @Summary get all accounts
// @Success 200 {array} models.Account
// @Router /accounts [get]

// @Summary get the account by id
// @Success 200 {object} models.Account
// @Router /accounts/{id} [get]

// AccountView generic view to manipulate accounts
var AccountView = api.View{
	getOne:  getAccount,  // returns slice of objects
	getAll:  getAccounts, // returns object by id from request
	preSave: func(c *gin.Context, obj models.IModel) { ... },
	// ...
}
```

**Comment by pei0804** [comment]
Can I paste a moving sample? or Can you do with your fork destination.

**Comment by pei0804** [comment]
If You have problem reopen issue.

**Comment by solher** [comment]
Hi, I was experimenting with Swag and I would actually have the same request. It would definitely add some flexibility if we could annotate anything.
For example, in our case we would prefer to annotate the router itself and it doesn't get picked up.
I forked Swag, applied the changes from @mgtest42 and it would work with it.

Actually, what is being allowed for annotations right now? Methods only?

**Comment by Hamper** [comment]
I use this workaround for annotate non-handler methods. Is there a better way to do this?
```go
// @Summary check liveness
// @Success 200
// @Router /live [get]
func _() {}

// @Summary check readyness
// @Success 200
// @Router /ready [get]
func _() {}

func New() {
	// some code ...

	app.Use(healthcheck.New(healthcheck.Config{
		LivenessEndpoint:  "/live",
		ReadinessEndpoint: "/ready",
	}))
	
	// some code ...
}
```
