### ISSUE TITLE
Unable to generate Swagger docs due to type definition not found error

### ISSUE THREAD

**Issue by nathannaveen** [swaggo/swag#1696]
Hello,

I'm having trouble generating Swagger documentation for my Go project using Swaggo. I'm encountering an error that seems to be due to Swaggo not being able to find a type definition that is located in a different directory.

Here's the error message I'm getting:

```
Error parsing type definition 'main.Neighbors': hashEquals: cannot find type definition: model.NeighborsNeighborsHashEqual  
Error parsing type definition 'main.JsonResponse': neighborsData: Neighbors: hashEquals: cannot find type definition: model.NeighborsNeighborsHashEqual  
ParseComment error in file /Users/nathannaveen/go/src/github.com/nathannaveen/guac/cmd/rest/known.go :JsonResponse: neighborsData: Neighbors: hashEquals: cannot  
ParseComment error in file /Users/nathannaveen/go/src/github.com/nathannaveen/guac/cmd/rest/known.go :JsonResponse: neighborsData: Neighbors: hashEquals: cannot find type definition: model.NeighborsNeighborsHashEqual
```

The type `model.NeighborsNeighborsHashEqual` is defined in another directory (`/Users/nathannaveen/go/src/github.com/nathannaveen/guac/pkg/assembler/clients/generated/operations.go`), and I'm running `swag init` from `/Users/nathannaveen/go/src/github.com/nathannaveen/guac/cmd/rest`.

I've tried the following steps to resolve this issue:

1. Checked my import statements to ensure the package containing `model.NeighborsNeighborsHashEqual` is correctly imported.
2. Checked my `GOPATH` and `GOROOT` environment variables.
3. Ensured my Go project is correctly organized according to Go's project layout conventions.
4. Ran `swag init` from the root directory of my Go module.
5. Used the `--parseDependency` flag when running `swag init`.
6. Used the `-d` flag when running `swag init` to specify the directory where `swaggo` should search for types.
7. Ensured the package is included in my `go.mod` file and ran `go mod tidy`.

Despite these steps, I'm still encountering the error. Any help would be greatly appreciated.

Thank you!

**Comment by ranefattesingh** [comment]
@nathannaveen could you try runninng this command `swag init -g **/**/*.go` from project root

**Comment by nathannaveen** [comment]
@ranefattesingh That works, thank you!
