### ISSUE TITLE
Deprecate a specific route

### ISSUE THREAD

**Issue by enac21** [swaggo/swag#1733]
I am trying to deprecate some routes in a method with more routes that I don't want to deprecate but swag marks as deprecated all the routes in this method.

<img width="660" alt="image" src="https://github.com/swaggo/swag/assets/96846797/e1f00a75-67b7-496a-a015-e9ad26c33f88">

Solution:
- It would be nice to interpret the @Deprecated annotation above a route or group of routes, this ignoring the routes above this annotations:

<img width="654" alt="image" src="https://github.com/swaggo/swag/assets/96846797/37e5efe6-d436-4343-b091-6e09fc6a5e69">

- A special annotation to deprecated routes:

<img width="646" alt="image" src="https://github.com/swaggo/swag/assets/96846797/809c556a-53fc-402e-b579-29f22f465bb9">

Alternatives:
As I say, creating two methods would be a solution but I don't see a modification in the code for a limitation in the documentation generator as correct

**Comment by sdghchj** [comment]
Have a try.

**Comment by enac21** [comment]
I have run `swag init -g api.go` to generate the documentation and those paths with the new annotation `@DeprecatedRouter` are not being generated. 
The package is updated in my project and I have tried with api.go in `operation_test.go` and it doesn't work with the `swag init `command either. How did you generate the expected documentation?

**Comment by sdghchj** [comment]
Get the newest code and rebuild your swag tool.
