### ISSUE TITLE
extension:"x-order" not working in yaml files but working in json files

### ISSUE THREAD

**Issue by SpaskeISO** [swaggo/swag#1737]
**Describe the bug**
When generating yaml and json files with x-order extension json files are ordered but yaml files are not

**Expected behavior**
The response value should be ordered for both yaml and json files

**Edit**
Looks like even the json files are also being ordered by ABC order instead of x-order it is just that json generation sorts the fields by x-order but it is putting 11 before 2 because it is comparing them like strings if that is changed so that it looks at the x-order like numbers this would probably be resolved at least for json.

**Screenshots**
Swagger editor result with json:
![Screenshot_2024-01-12_09-48-23](https://github.com/swaggo/swag/assets/129440390/74c673a8-3bcc-44df-9ade-8f1d04a11f70)
json file:
![Screenshot_2024-01-12_09-52-21](https://github.com/swaggo/swag/assets/129440390/b7073bb1-3646-4c69-81d0-8f88eff56a1f)

Swagger editor result with yaml:
![Screenshot_2024-01-12_09-51-25](https://github.com/swaggo/swag/assets/129440390/58caaf67-7452-42d5-98b3-2c725a8f176a)
yaml file:
![Screenshot_2024-01-12_09-52-55](https://github.com/swaggo/swag/assets/129440390/4a306d52-7630-4eb6-a3e6-b843a5bfd1ea)

**Your swag version**
1.16.2

**Your go version**
1.21.5

**Desktop (please complete the following information):**
 - OS: [Linux Mint 21.2]
 - Browser: [firefox]
 - Version: [121.0-1]

**Comment by sdghchj** [comment]
This may be more difficult to achieve

**Comment by SpaskeISO** [comment]
No problem just wanted to report it it is not a big impediment.
