### ISSUE TITLE
outputTypes  No default value

### ISSUE THREAD

**Issue by chenbihao** [swaggo/swag#1741]
**Describe the bug**
`outputTypes`  No default value

**To Reproduce**

```go
conf := &gen.Config{
			SearchDir: httpFolder,
			Excludes: "",
			OutputDir: outputDir,
			//  If it is not set, the default value is not found in gen.New().Build() and no error is reported
			//  OutputTypes: []string{"go", "json", "yaml"},
			MainAPIFile: "swagger.go",
			PropNamingStrategy: "",
			ParseVendor: false,
			ParseDependency: 0,
			ParseInternal: false,
			MarkdownFilesDir: httpFolder,
			GeneratedTime: false,
		}
		if err := gen.New().Build(conf); err != nil {
			fmt.Println(err)
		}
```

**Expected behavior**

has default value or error is reported

**Screenshots**

![image](https://github.com/swaggo/swag/assets/21167262/b92b77be-c338-4990-9286-dea09440e386)
![image](https://github.com/swaggo/swag/assets/21167262/b59d82eb-58cd-43fb-a72d-d12b18496384)

**Your swag version**
 1.16.2

**Your go version**
1.20.0

**Desktop (please complete the following information):**
 - OS: win

**Additional context**

**Comment by sdghchj** [comment]
Where is your code from?

outputTypes comes from the default option values of cli.
https://github.com/swaggo/swag/blob/v1.16.2/cmd/swag/main.go#L82
https://github.com/swaggo/swag/blob/v1.16.2/cmd/swag/main.go#L199

**Comment by chenbihao** [comment]
> Where is your code from?
> 
> outputTypes comes from the default option values of cli. [`v1.16.2`/cmd/swag/main.go#L82](https://github.com/swaggo/swag/blob/v1.16.2/cmd/swag/main.go?rgh-link-date=2024-01-17T01%3A26%3A32Z#L82) [`v1.16.2`/cmd/swag/main.go#L199](https://github.com/swaggo/swag/blob/v1.16.2/cmd/swag/main.go?rgh-link-date=2024-01-17T01%3A26%3A32Z#L199)

I didn't call it with CLI. I called this like this `gen.New().Build(conf)`:

```
conf := &gen.Config{
	//  If it is not set, the default value is not found in gen.New().Build() and no error is reported
	//  OutputTypes: []string{"go", "json", "yaml"},
	...
}
if err := gen.New().Build(conf); err != nil {
	fmt.Println(err)
}
```
`gen.New()` and `func (g *Gen) Build` There is no default value set for it in the

**Comment by sdghchj** [comment]
You have to set it yourself.
