### ISSUE TITLE
@DeprecateRouter is not working with swag init command

### ISSUE THREAD

**Issue by enac21** [swaggo/swag#1743]
Routes with @DeprecatedRouter are not being marked as deprecated.

1. Run swag init pointing to the api.go file of operation_test.go. 
2. The generated content is not deprecated endpoints with @DeprecatedRouter annotations.

Swag version: last master changes
Go version: 1.21.5

**Comment by sdghchj** [comment]
swag is a tool which needs to be rebuilded after code updated.
you can check the tests in the PR I committed.

**Comment by sdghchj** [comment]
If so, how did the unit test passed?

**Comment by enac21** [comment]
The only thing that could be happening is that swag init doesn't use the same method as ParseAPI. I am sure because I tried to generate the documentation in the tests themselves with the latest master changes.

**Comment by sdghchj** [comment]
Just debug it.
It's OK, I am sure.

**Comment by enac21** [comment]
I just needed to update the lib. Thanks!!
