### ISSUE TITLE
Path description override Api description

### ISSUE THREAD

**Issue by mderasse** [swaggo/swag#176]
**Describe the bug**
When declaring in the same file (didn't try with multiple file) the API Info and the Path Info the last description of the file is use as the API Description.

**To Reproduce**
Declare your API Info on the top of your func main with a @description field
Declare your Path info on the top of you another func (under the main) with a @description field
Do a swag init

Code Example
```
package main
  
// @title Bug Issue
// @version 1.0
// @description That's the description of my API
func main() {
}

// @Summary A Method
// @Description That's the description of my Method
// @ID get-method
// @Accept html
// @Produce html
// @Success 200 {string} string
// @Router /method [get]
func test() {
}
```

**Expected behavior**
The Description of the API Should not be overrided by the Path Description

What happen:
```
var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "That's the description of my Method",
```

What should have happen:
```
var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "That's the description of my API",
```

**Your swag version**
Swag 1.3.2

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chromium
 - Version 67

**Comment by pei0804** [comment]
I'll check

**Comment by pei0804** [comment]
If You have problem reopen issue.
