### ISSUE TITLE
finding types outside of package root?

### ISSUE THREAD

**Issue by jasonhancock** [swaggo/swag#178]
**Describe the bug**

I have a project with several individual services (each having their own main.go) located under a `services`directory. I have structs defined in an `internal/data` package since they're shared across the services. Example layout:

```
.
|-- internal
|   `-- data  <-- structs defined here
`-- services
    |-- service1 <-- main.go in here
    `-- service2 <-- main.go in here
```

If I run `swag init` in either the `service1` or `service2` directories I end up getting a panic. I traced through the code and I think it's because of something mentioned in this comment: https://github.com/swaggo/swag/issues/16#issuecomment-348101999

specifically, that if the structs aren't defined under the `service1` or `service2` folders they cannot be found. I can confirm this by making a sub-package of `service1` with the struct definitions and running `swag init`. In this case the tree would look like this:
```
.
|-- internal
|   `-- data
`-- services
    |-- service1
    |   `-- data
    `-- service2
        `-- data
```

But then I lose the benefit of sharing the same struct across two services.

Is there a way to relax the restriction (forsaking efficiency) to find the structs in the original location in the `internal/data` package?

**Your swag version**
pulled from master on 2018-08-30 (last commit hash e3d1c4fc7dc4b08b48b5cc5fcb0cae4ccc5348cc)

**Comment by pei0804** [comment]
I know. Currently swag can't solve this.
I am thoughting about countermeasures against this.
https://github.com/swaggo/swag/pull/171#issuecomment-408379593

**Comment by jasonhancock** [comment]
I hacked together a bit of code to work around this limitation. I'll get it cleaned up and attempt a PR.

**Comment by abdulito** [comment]
Actually nvm,

I just tried this and it worked

```
// @Success 200 {object} myproject/pkg/api/v1.Person
```

**Comment by dselans** [comment]
@abdulito The "absolute path" method only appears to work because the logic to find the type definition does not get hit here: https://github.com/swaggo/swag/blob/master/operation.go#L122

"github.com/org/pkg.Type" == the split will result in ["github", "com/org/pkg", "type"] , which goes nowhere right now (but also does not error).

I've described the problem and provided a fix here #188 and #189.

cc: @t-evers ^

**Comment by jasonhancock** [comment]
@agarwal-nitesh it's noted in the PR that it's a known limitation of the current implementation: https://github.com/swaggo/swag/pull/179

**Comment by agarwal-nitesh** [comment]
@jasonhancock Yes. But what about the vendored pkg imports? https://github.com/swaggo/swag/pull/189

**Comment by jasonhancock** [comment]
Same thing
