### ISSUE TITLE
Can't use Custom struct as data type in @Success

### ISSUE THREAD

**Issue by jac1013** [swaggo/swag#181]
**Describe the bug**
I can't use a custom struct as a success response.

**To Reproduce**
1. Create your own struct only using primitive attributes.
2. In your documentation try using it like this `@Success 200 {array} path.to.struct.MyOwnStruct`
3. Generate the documentation (it should successfully be generated)
4. when checking swagger documentation you should see a red alert in the top stating the following:
`Resolver error at paths./api/path.get.responses.200.schema.items.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/path.to.struct.MyOwnStruct does not exist in document`

**Expected behavior**
I should be able to see in the documentation the structure of `MyOwnStruct` as the case of a successful response.

**Screenshots**
Because it couldn't find the struct this is the result in the swagger documentation
![image](https://user-images.githubusercontent.com/5025920/43679957-d0fe8ff2-97f4-11e8-99f1-970e193ee12d.png)

**Your swag version**
v1.3.2

**Desktop (please complete the following information):**
 - OS: LinuxMint
 - Browser Chrome
 - Version 67.0.3396.62

**Additional context**
None

**Comment by pei0804** [comment]
Can you give me error source code example?
I want to know about the location of the struct and the execution place of swag init.

**Comment by jac1013** [comment]
Sure, so the exact locations is `./business/structures/MyOwnStruct` and this is the code folder hierarchy (this is the root)

![image](https://user-images.githubusercontent.com/5025920/43730973-b86c3410-9972-11e8-9e23-8711b6f5ba84.png)

`swag init` runs successfully when I use `business.structures.MyOwnStruct` as data type but then throws the error I provided above when checking the swagger documentation. `MyOwnStruct` doesn't have nested Structs on it, it only uses primitive types.

The code is running from `.../rest/main.go` and the exact error we receive in the swagger alert is:
`Resolver error at paths./example/example-path.get.responses.200.schema.items.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/business.structures.MyOwnStruct does not exist in document`

MyOwnStruct is just a bunch of primitive types with json definitions:

```go
type MyOwnStruct struct {
	Cp float64 `json:"cp"`
	Op float64 `json:"op"`
	H float64 `json:"h"`
	L float64 `json:"l"`
	V float64 `json:"v"`
	Nt float64 `json:"nt"`
	Ot float64 `json:"ot"`
	Ct float64 `json:"ct"`
}
```

I hope this helps.

Thanks for the cool library :).

**Comment by pei0804** [comment]
I was able to reproduce. I'm looking for problems now.
https://github.com/pei0804/swag-sandbox

**Comment by dselans** [comment]
Do not reference the object as `business.structures.MyOwnStruct` but as `structures.MyOwnStruct` -- this means, you should import `structures` in the same file your doc comments live.

Something like:

```
var (
_ = structures.SomeStructure{}
)
```

.. would be enough to satisfy the importer.

**Comment by pei0804** [comment]
If You have problem reopen issue.

**Comment by ZavilenskyIlya** [comment]
> If You have problem reopen issue.

I have the same problem, do you have a solution?

**Comment by mark-jordanovic-lewis** [comment]
I cannot import any data types, stdlib, external, or, home rolled, using swag into my documentation. Is there a solution?

Go v1.9 -> 1.12

**Comment by ahoulgrave** [comment]
Having same issue with a type defined in the same package:

```
// @Success 200 {object} customResponse
```

```
type customResponse struct {
	Total    int              `json:"total" example:"100"`
	Pages    int              `json:"pages" example:"5"`
	Object []core.Object `json:"objects"`
}
```

**Comment by ubogdan** [comment]
This is invalid for swagger. 
`// @Success 200 {object} customResponse
`
the definition needs to be in fromat package.Type , no matter if it's on the same package.

**Comment by songxiaokui** [comment]
> > 如果您有问题，请重新打开。
> 
> 我有同样的问题，您有解决方案吗？



> > If You have problem reopen issue.
> 
> I have the same problem, do you have a solution?

I have the same problem, do you have a solution?
