### ISSUE TITLE
swag init displayed two unexplained warnings

### ISSUE THREAD

**Issue by godcong** [swaggo/swag#1815]
**Describe the bug**
```
2024/05/28 17:38:37 warning: failed to evaluate const magic at \pkg\mod\github.com\xo\terminfo@v0.0.0-20220910002029-abceb7e1c41e\dec.go:11:2, strconv.ParseUint: parsing "o432": invalid syntax
2024/05/28 17:38:37 warning: failed to evaluate const magicExtended at \pkg\mod\github.com\xo\terminfo@v0.0.0-20220910002029-abceb7e1c41e\dec.go:14:2, strconv.ParseUint: parsing "o1036": invalid syntax
```
**To Reproduce**
1. swag init --parseDependency --generalInfo ./main.go --output ./docs

**Expected behavior**

**Screenshots**
![image](https://github.com/swaggo/swag/assets/2727298/c166135e-458b-47a8-9844-4e0237905895)

**Your swag version**
swag.exe version v1.16.3

**Your go version**
go1.22.3

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by sdghchj** [comment]
swag will evaluate all consts in order to evaluate enums.

**Comment by godcong** [comment]
@sdghchj 
What causes this problem?
Do I need to fix it?
I don't know where this is used...

**Comment by sdghchj** [comment]
No need.
Just ignore it.

**Comment by godcong** [comment]
@sdghchj Thanks
