### ISSUE TITLE
swag init

### ISSUE THREAD

**Issue by Jerry-yz** [swaggo/swag#1820]
**Describe the bug**
when i use swag init  generate docs.go, but this file has error, swag.Spec struct has not LeftDelim field and RightDelim field
how can i fix it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}
**To Reproduce**

**Expected behavior**

**Screenshots**

**Your swag version**
e.g. 1.4.1
swag version v1.16.3
**Your go version**
e.g. 1.12.0
go version go1.22.3 linux/amd64
**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by DrowningOtter** [comment]
how to fix this ?

**Comment by buckldav** [comment]
As a workaround, I just removed those lines in my Dockerfile and everything ran fine.

```dockerfile
RUN swag init
RUN sed -i s/LeftDelim.*//g ./docs/docs.go
RUN sed -i s/RightDelim.*//g ./docs/docs.go
```

My versions

- github.com/swaggo/echo-swagger v1.4.1
- github.com/swaggo/swag v1.16.3
- go version go1.22.4 linux/amd64

**Comment by DrowningOtter** [comment]
got it, thanks!

**Comment by Jerry-yz** [comment]
> As a workaround, I just removed those lines in my Dockerfile and everything ran fine.
> 
> ```dockerfile
> RUN swag init
> RUN sed -i s/LeftDelim.*//g ./docs/docs.go
> RUN sed -i s/RightDelim.*//g ./docs/docs.go
> ```
> 
> My versions
> 
> * github.com/swaggo/echo-swagger v1.4.1
> * github.com/swaggo/swag v1.16.3
> * go version go1.22.4 linux/amd64

only manual processing? have other methods?
has bug in source code?

**Comment by Danli741** [comment]
Please have a look at this closed issue:
https://github.com/swaggo/swag/issues/1568

**Comment by ahrorbekOlimjonov** [comment]
in that docs.go file there are `import "github.com/swaggo/swag"` .
For fixing error just run this command `go get github.com/swaggo/swag`, it should fix it.
