### ISSUE TITLE
Install swag v2 (OpenAPI 3.1)

### ISSUE THREAD

**Issue by stuzer05** [swaggo/swag#1822]
Hi!

I'm struggling to install (`go install`) swag v2 to be able to generate OpenAPI 3.1 specs. How to do it? I've tried many combinations but seems like v2 is not installable

**Comment by tfonfara** [comment]
`go install github.com/swaggo/swag/v2/cmd/swag@latest`

**Comment by stuzer05** [comment]
> go install github.com/swaggo/swag/v2/cmd/swag@latest

Thank you!
