### ISSUE TITLE
Add a way to specify a parameter for multiple routes at once

### ISSUE THREAD

**Issue by iTrooz** [swaggo/swag#1842]
**Is your feature request related to a problem? Please describe.**
I have a bunch of endpoints like this:
```
/user/{user_name}/posts/{post_id} [GET]
/user/{user_name}/posts/{post_id} [POST]
/user/{user_name}/posts/{post_id} [DELETE]
/user/{user_name}/posts/  [GET]
```

I'd like to define the {user_name} and {post_id} path params, but without duplicating them their definition (the description being the most problematic) for every endpoint

**Describe the solution you'd like**
A way to define the path params once when they are used in multiple endpoints. Maybe by defining "global params" by their name ?

**Additional context**
Apologies if the feature is already present, I could not find it in the README or already opened issues

**Comment by Us3r-gitHub** [comment]
I found some information in the documentation that might address your concern. You can find details on how to add multiple paths here: [Add Multiple Paths](https://github.com/swaggo/swag#add-multiple-paths).

Does this help resolve your issue?

**Comment by iTrooz** [comment]
Yup, sounds like it ! Thanks
