### ISSUE TITLE
fasthttp support

### ISSUE THREAD

**Issue by svyatoslavratov** [swaggo/swag#1858]
Hello!

Is there any possibility of integration with fasthttp (https://github.com/valyala/fasthttp)?

It would be great to have such integration

**Comment by victorvcruz** [comment]
I also need this integration, and if support is possible, I would like to contribute

**Comment by svyatoslavratov** [comment]
@victorvcruz you can use fasthttp for your controllers and use net/http for listen and serve swaggo/swagg. It is work for me

**Comment by sdghchj** [comment]
newly created: https://github.com/swaggo/fasthttp-swagger
