### ISSUE TITLE
Wrong definition parse

### ISSUE THREAD

**Issue by zdon0** [swaggo/swag#1863]
**Describe the bug**
If struct has embedded struct field with name as other same aliased struct, definition's embedded field will aliased

**To Reproduce**
1. Set --pd using go list
2. Define main struct with embedded struct that has name as alias from other package (embedded struct without alias)
3. Specify response comment with main struct
4. Definition parsing will find embedded struct by alias from other package

**Expected behavior**
Definition parser looks up by struct name, not alias name

**Your swag version**
1.16.3

**Your go version**
1.19.13

**Additional context**
The main problem with parsing dependencies via go list, because it will return packages that parsed from main directory before. TypeSpecDef has NotUnique field = True. Same struct has duplicates by package paths (relative from parse main dir, full path from parse dependency via go list). When parsing embedded structs, the parser tries to look up the field by name and may find an aliased struct from another package.

**Comment by sdghchj** [comment]
Alias is usually used to distinguish definitions with the same name but from different packages, meanwhile, reduce the length of the name of a definition.
If the alias has not made the definition unique, I am confused about its existence. I think this is an artificial bug.

**Comment by sdghchj** [comment]
swag lookup definitions through the imports at the top of the current go source file, but you didn't import bad package in .../good/data.go.
I have checked the test example in the testdata directory you commited, I don't think swag will lookup Emb from the bad package.
And also I try the newest swag, it works well.
Have you provided the right example which leads to this issue?

**Comment by sdghchj** [comment]
swag lookup definitions through the imports at the top of the current go source file, but you didn't import bad package in .../good/data.go.
I have checked the test example in the testdata directory you commited, I don't think swag will lookup Emb from the bad package.
And also I try the newest swag, it works well.
Have you provided the right example which leads to this issue?

**Comment by zdon0** [comment]
this is strange because in my case the latest version does not pass the test. And just parses the structure with the alias from the bad package
<img width="703" alt="image" src="https://github.com/user-attachments/assets/ac3f480d-f940-42d9-aea9-3749de1d2108">
<img width="934" alt="image" src="https://github.com/user-attachments/assets/a7979c3e-a3bd-44a8-b572-1f80aa78b45d">

**Comment by zdon0** [comment]
https://github.com/swaggo/swag/blob/c7f1cd8e8e3702096516b82068b662a29eb79dea/parser.go#L398

At this point swag collects packages also from bad package and parse bad.Emb with alias.
When parse struct, swag finds Emb field from bad package because of alias

**Comment by sdghchj** [comment]
I can't regenerate the issue you described.
swag collects Emb from bad package with name 'Emb', and from good pacage with name 'good.Emb'.
When parsing the struct, swag first lookup good.Emb, then Emb.
So normally good.Emb will be found.

**Comment by zdon0** [comment]
Can you please show me how you're trying to regenerate issue

**Comment by sdghchj** [comment]
I got your point and find the cause.
The file including good.Emb was parsed twice, which led to self conflicts.

A better way to solve it, I think, is to guarantee a file identified by its absolute path be parsed only once.

**Comment by sdghchj** [comment]
![image](https://github.com/user-attachments/assets/2ce86c92-7165-42fe-a8e6-e51d4d45ac4c)

**Comment by sdghchj** [comment]
![image](https://github.com/user-attachments/assets/df6ef4da-56fd-4f9a-a86d-19ed68469d86)

**Comment by zdon0** [comment]
Your version does not pass my test.
`Error parsing type definition 'Gen': emb: cannot find type definition: Emb`
Because when trying to find good.Gen struct, it tries to find via import and load external package
https://github.com/swaggo/swag/blob/c7f1cd8e8e3702096516b82068b662a29eb79dea/packages.go#L532
This line leads the structure to parsing the same files again. After this, good.Emb in unique definitions is nil

**Comment by sdghchj** [comment]
> Your version does not pass my test. `Error parsing type definition 'Gen': emb: cannot find type definition: Emb` Because when trying to find good.Gen struct, it tries to find via import and load external package
> 
> https://github.com/swaggo/swag/blob/c7f1cd8e8e3702096516b82068b662a29eb79dea/packages.go#L532
> 
> 
> This line leads the structure to parsing the same files again. After this, good.Emb in unique definitions is nil

Yes I know this.
As good.Gen has been renamed to Gen,it cannot be found. This is the correct behavior,I think.
Just remove the name prefix 'good.' from the API comments.

**Comment by zdon0** [comment]
If you will delete good.Emb as nil (e. g. like [here](https://github.com/swaggo/swag/blob/c7f1cd8e8e3702096516b82068b662a29eb79dea/packages.go#L407)) it will find Emb by alias from bad package

**Comment by zdon0** [comment]
> Yes I know this. As good.Gen has been renamed to Gen,it cannot be found
No, it cant find exactly Emb struct
