### ISSUE TITLE
Support for go 1.23

### ISSUE THREAD

**Issue by arielsrv** [swaggo/swag#1875]
Unfortunately I can't build my app using golang 1.23 runtime, I would like that swag can support it. There are many issues with new iter feature.

**Comment by sdghchj** [comment]
More detail needed.

**Comment by sdghchj** [comment]
More detail needed.

**Comment by arielsrv** [comment]
2024/08/23 09:23:47 Generate swagger docs....
2024/08/23 09:23:47 Generate general API Info, search dir:src
/Users/arielsrv/go/go1.23.0/src/runtime/time.go:174:17: cannot range over 3 (untyped int constant)
/Users/arielsrv/go/go1.23.0/src/runtime/time.go:174:17: cannot range over 3 (untyped int constant)
/Users/arielsrv/go/go1.23.0/src/runtime/time.go:174:17: cannot range over 3 (untyped int constant)
/Users/arielsrv/go/go1.23.0/src/slices/iter.go:50:17: cannot range over seq (variable of type iter.Seq[E])
/Users/arielsrv/go/go1.23.0/src/runtime/time.go:174:17: cannot range over 3 (untyped int constant)
/Users/arielsrv/go/go1.23.0/src/slices/iter.go:50:17: cannot range over seq (variable of type iter.Seq[E])
/Users/arielsrv/go/go1.23.0/src/runtime/time.go:174:17: cannot range over 3 (untyped int constant)
/Users/arielsrv/go/go1.23.0/src/slices/iter.go:50:17: cannot range over seq (variable of type iter.Seq[E])
/Users/arielsrv/go/go1.23.0/src/runtime/time.go:174:17: cannot range over 3 (untyped int constant)
/Users/arielsrv/go/go1.23.0/src/slices/iter.go:50:17: cannot range over seq (variable of type iter.Seq[E])
/Users/arielsrv/go/go1.23.0/src/runtime/time.go:174:17: cannot range over 3 (untyped int constant)
/Users/arielsrv/go/go1.23.0/src/runtime/time.go:174:17: cannot range over 3 (untyped int constant)
/Users/arielsrv/go/go1.23.0/src/slices/iter.go:50:17: cannot range over seq (variable of type iter.Seq[E])

Works fines with 1.22

Maybe it could work if exlucde internal go folders

**Comment by arielsrv** [comment]
However also If I try it with parseInteral throw this ....

task: [swagger] swag init -d src -g main.go -o src/resources/docs --parseGoList --parseDependency --parseInternal
2024/08/23 09:33:29 Generate swagger docs....
2024/08/23 09:33:29 Generate general API Info, search dir:src
**2024/08/23 09:33:30 warning: failed to evaluate const mProfCycleWrap at /Users/ariel.pineiro/go/go1.23.0/src/runtime/mprof.go:179:7, reflect: call of reflect.Value.Len on zero Value**
2024/08/23 09:33:30 Generating model.MessageDTO
2024/08/23 09:33:30 Generating errorx.Error
2024/08/23 09:33:30 Generating model.CreateMessageDTO
2024/08/23 09:33:30 create docs.go at src/resources/docs/docs.go
2024/08/23 09:33:30 create swagger.json at src/resources/docs/swagger.json
2024/08/23 09:33:30 create swagger.yaml at src/resources/docs/swagger.yaml

**Comment by sdghchj** [comment]
Just use golang v1.23 to rebuild your swag with source code

**Comment by 1saifj** [comment]
/usr/local/go/src/slices/iter.go:50:17: cannot range over seq (variable of type iter.Seq[E])
/usr/local/go/src/maps/iter.go:51:20: cannot range over seq (variable of type iter.Seq2[K, V])
/usr/local/go/src/slices/iter.go:50:17: cannot range over seq (variable of type iter.Seq[E])
/usr/local/go/src/maps/iter.go:51:20: cannot range over seq (variable of type iter.Seq2[K, V])
/usr/local/go/src/slices/iter.go:50:17: cannot range over seq (variable of type iter.Seq[E])
/usr/local/go/src/maps/iter.go:51:20: cannot range over seq (variable of type iter.Seq2[K, V])
/usr/local/go/src/slices/iter.go:50:17: cannot range over seq (variable of type iter.Seq[E])

**Comment by securityguy** [comment]
This is still an issue in both main and v2.0.0-rc4

**Comment by ubogdan** [comment]
@securityguy This is an Open Source project. Feel free to contribute. I'm quite busy at the moment, but I'll gladly assist with a CR.

**Comment by securityguy** [comment]
> [@securityguy](https://github.com/securityguy) This is an Open Source project. Feel free to contribute. I'm quite busy at the moment, but I'll gladly assist with a CR.

Happy to help @ubogdan. Is the V2 branch the best place to start, and any thoughts on where to start looking for this one in the code?
