### ISSUE TITLE
大佬们有没有办法实现记住我刷新前的登录信息呢

### ISSUE THREAD

**Issue by liushuai05** [swaggo/swag#1887]
请问有没有办法实现记住我刷新前的登录信息呢，我这边每次生成swagger后刷新swagger页面都会导致上一次记录的token失效，请问大佬们有没有针对这个信息进行记录然后刷新页面后重新填充进去的解决方案或者功能呢

**Comment by ubogdan** [comment]
Nu cred ca exista aceasta posbilitate
