### ISSUE TITLE
[Bug] Incorrectly generated `docs/docs.go` file

### ISSUE THREAD

**Issue by acraig-pytilia** [swaggo/swag#1895]
**Describe the bug**
`swag init` command generates incorrect docs.go file causing the application to crash upon importing

**To Reproduce**
1. Document main function with godoc `@tag`s
2. Import the `docs` module
3. Run `swag init`
4. Run `go run <main_file>.go`
5. See error (in screenshots section)

**Expected behavior**
The docs.go file should be be generated with all the correct fields

**Actual behavior**
The file is generated with fields that are not present in the struct definition
Perhaps these fields were removed in a previous release with the docs.go template not being updated?

**Screenshots**
<img width="715" alt="image" src="https://github.com/user-attachments/assets/055eb42d-a298-4fa8-b06e-3943c59392f3">
<img width="750" alt="image" src="https://github.com/user-attachments/assets/b509ddaf-ac46-4615-9bb9-8229477b3aee">

**Your swag version**
- 1.16.3 (latest at time of bug submission)
- also present in 1.16.2

**Your go version**
- 1.21.13

**Desktop (please complete the following information):**
 - OS: Debian 12 (Docker)

**Comment by ubogdan** [comment]
Actually, your app doesn't build :D 

I guess you are using the latest swag version and you missed updating [swago/swag](https://github.com/swaggo/swag) version in go.mod.
So `go get github.com/swaggo/swag@latest` in the project root directory should save you from the trouble.

**Comment by ubogdan** [comment]
It's ok not to believe me, The template delimiters were introduced in #1499 and they were released in [v1.16.1](https://github.com/swaggo/swag/blob/v1.16.1/spec.go#L20-L21), 

Please look on go.mod and tell me what version of `github.com/swaggo/swag` you have.
