### ISSUE TITLE
[Q&A] Generating docs for two multiple versions inside one main.go file

### ISSUE THREAD

**Issue by k0rmo0** [swaggo/swag#1897]
I am using chi router in my go project, and inside main go I have routes for my base version and my v1 version. 

     mux.Route("/", func(route chi.Router) {
              ***endpoints***
	})

      mux.Route("/v1", func(route chi.Router) {
              ***endpoints***
       })
	
The handlers for these endpoints are separated in my folder like
project/
*controllers/
** v1/
**base/
*main.go
 
 How can i generate docs for example just for my v1 handlers? Thank you in advance

**Comment by ubogdan** [comment]
There are 2 approaces
1. put main API annotation in v1 preferably in a main.go , cd to that folder and generate the docs.
2. put the main annotation in a file you like and adjust swag cli params to specify where to find it.
You can find all the avail params by running `swag init -h`

**Comment by k0rmo0** [comment]
I've added tags to my functions and when generating docs i added flags like 
`-t v1 -o docs/v1/`
when generating docs so I can generate docs for two different versions.

Thank you.
