### ISSUE TITLE
无法生成文档

### ISSUE THREAD

**Issue by y1713375484** [swaggo/swag#1908]
**Describe the bug**
所有环境依赖都安装了，执行swag init命令无法生成文档，并且也无任何报错

**To Reproduce**
代码如下
`package main

import (
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	_ "test/docs"
)

type Article struct {
	ID            uint32 `gorm:"primary_key" json:"id"`
	CreatedBy     string `json:"created_by"`
	ModifiedBy    string `json:"modified_by"`
	CreatedOn     uint32 `json:"created_on"`
	ModifiedOn    uint32 `json:"modified_on"`
	DeletedOn     uint32 `json:"deleted_on"`
	IsDel         uint8  `json:"is_del"`
	Title         string `json:"title"`
	Desc          string `json:"desc"`
	Content       string `json:"content"`
	CoverImageUrl string `json:"cover_image_url"`
	State         uint8  `json:"state"`
}

func NewArticle() Article {
	return Article{}
}

func main() {
	r := gin.Default()
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	r.Run(":8088")
}

// @Summary 获取单个文章
// @Produce json
// @Param id path int true "文章ID"
// @Success 200 {object} Article "成功"
// @Failure 400 {object} string "请求错误"
// @Failure 500 {object} string "内部错误"
// @Router /api/v1/articles/{id} [get]
func (a Article) Get(c *gin.Context) {

}

// @Summary 获取多个文章
// @Produce json
// @Param name query string false "文章名称"
// @Param tag_id query int false "标签ID"
// @Param state query int false "状态"
// @Param page query int false "页码"
// @Param page_size query int false "每页数量"
// @Success 200 {object} Article "成功"
// @Failure 400 {object} string "请求错误"
// @Failure 500 {object} string "内部错误"
// @Router /api/v1/articles [get]
func (a Article) List(c *gin.Context) {
	return
}

// @Summary 创建文章
// @Produce json
// @Param tag_id body string true "标签ID"
// @Param title body string true "文章标题"
// @Param desc body string false "文章简述"
// @Param cover_image_url body string true "封面图片地址"
// @Param content body string true "文章内容"
// @Param created_by body int true "创建者"
// @Param state body int false "状态"
// @Success 200 {object} Article "成功"
// @Failure 400 {object} string "请求错误"
// @Failure 500 {object} string "内部错误"
// @Router /api/v1/articles [post]
func (a Article) Create(c *gin.Context) {

}

// @Summary 更新文章
// @Produce json
// @Param tag_id body string false "标签ID"
// @Param title body string false "文章标题"
// @Param desc body string false "文章简述"
// @Param cover_image_url body string false "封面图片地址"
// @Param content body string false "文章内容"
// @Param modified_by body string true "修改者"
// @Success 200 {object} Article "成功"
// @Failure 400 {object} string "请求错误"
// @Failure 500 {object} string "内部错误"
// @Router /api/v1/articles/{id} [put]
func (a Article) Update(c *gin.Context) {
	return
}

// @Summary 删除文章
// @Produce  json
// @Param id path int true "文章ID"
// @Success 200 {string} string "成功"
// @Failure 400 {object} string "请求错误"
// @Failure 500 {object} string "内部错误"
// @Router /api/v1/articles/{id} [delete]
func (a Article) Delete(c *gin.Context) {
	return
}
`

**Expected behavior**

**Screenshots**
![QQ_1729407729267](https://github.com/user-attachments/assets/8f4e80bd-7f80-42cc-9ec1-a23f7de42294)
![QQ_1729407742030](https://github.com/user-attachments/assets/c139694f-d6ba-4e73-935c-50a6984da398)
![QQ_1729407775699](https://github.com/user-attachments/assets/e1ea43f5-c714-43cd-9c59-456eb56b89c8)
![QQ_1729407799993](https://github.com/user-attachments/assets/dc1226c6-ccd9-4e48-8915-6b09896989d0)
![QQ_1729407839472](https://github.com/user-attachments/assets/54508320-ac55-4aa3-8aa9-879da4220015)

**Your swag version**
e.g. 1.4.1

**Your go version**
go version go1.22.3 darwin/arm64

**Desktop (please complete the following information):**
macos 14.6.1

**Additional context**

**Comment by ubogdan** [comment]
As far as I can see your main annotations are missing. I recommend you to have main annotations in a `main.go` file and the routes on separate file(s) eg:`routes.go` (they can be on the main package if you want but it's strongly recommended to keep them separate.

**Comment by y1713375484** [comment]
> 据我所知，您的主要注释丢失了。我建议你将主注解放在一个文件中，而路由在单独的文件上，例如：（如果你愿意，它们可以在主包上，但强烈建议将它们分开。`main.go``routes.go`

It shouldn't be an issue with the main method not being commented. Previously, I separated the main method and the router into different packages, but that didn't generate the documentation either. Now, after adding comments to the main method, I can only generate comments for the main method, while comments for other methods still don't work.

**Comment by y1713375484** [comment]
![QQ_1729477521789](https://github.com/user-attachments/assets/4febcd0e-0ef0-45dd-a7e8-77374e3ff426)
![QQ_1729477530540](https://github.com/user-attachments/assets/46c9392d-edbf-48bc-b7b6-0851131bb123)

**Comment by y1713375484** [comment]
I've identified the issue: all my projects are located under the `src` directory within the `GOPATH`, but I'm using `go mod` to manage dependencies. It turns out that moving the code outside of the `GOPATH` allows the documentation to be generated properly. This is quite strange, and I've also checked the file permissions, which are normal.

**Comment by y1713375484** [comment]
I've identified the issue: all my projects are located under the `src` directory within the `GOPATH`, but I'm using `go mod` to manage dependencies. It turns out that moving the code outside of the `GOPATH` allows the documentation to be generated properly. This is quite strange, and I've also checked the file permissions, which are normal.

**Comment by ubogdan** [comment]
You should refactor your project and stop using [GOPATH](https://github.com/golang/go/issues/30329)
