### ISSUE TITLE
Swag v2 with open api --v3.1 breaks model composition overrides

### ISSUE THREAD

**Issue by gabegibbturion** [swaggo/swag#1917]
**Versions**
Swaggo - github.com/swaggo/swag/v2 v2.0.0-rc3
Go - 1.21
Parse command - swag init --parseDependency --parseInternal --v3.1 --tags Imaging-Missions,Opportunities,Images,Tasking-Orders

**Describe the bug**
When using an interface return type
```
type PaginationResult struct {
	Data  interface{} `json:"data"`
	Total int64       `json:"total"`
}
```
and two different handlers that implement its own version of the interface

```
// HANDLER 1 RETURN
//	@Success		200							{object}	models.PaginationResult{data=[]models.TaskingOrder}	"List of Tasking orders retrieved successfully"

// HANDLER 2 RETURN
//	@Success		200							{object}	models.PaginationResult{data=[]models.Opportunity}	"List of Opportunities"
```
I get an issue where the tasking orders overrides the opportunities return, causing every version of PaginationResult to only return TaskingOrders. This was not an issue on the main branch but only seemed to arise when using v2. Is there something I am doing wrong? Is this a bug? I have more handlers, where taking Tasking Orders away just makes the rest default to only opportunity.

**Comment by addshore** [comment]
I did some reading and trying things out

Ultimately this now works

```
// @Success 200 {object} presentation.PaginatedResult[presentation.User]
```

Making use of generics
https://github.com/swaggo/swag?tab=readme-ov-file#how-to-use-generics
https://github.com/swaggo/swag/blob/master/testdata/generics_nested/api/api.go
https://github.com/swaggo/swag/blob/master/testdata/generics_nested/web/handler.go

**Comment by gabegibbturion** [comment]
> I did some reading and trying things out
> 
> Ultimately this now works
> 
> ```
> // @Success 200 {object} presentation.PaginatedResult[presentation.User]
> ```
> 
> Making use of generics https://github.com/swaggo/swag?tab=readme-ov-file#how-to-use-generics https://github.com/swaggo/swag/blob/master/testdata/generics_nested/api/api.go https://github.com/swaggo/swag/blob/master/testdata/generics_nested/web/handler.go

That worked thanks!
