### ISSUE TITLE
Swag init ignores tags by gin binding

### ISSUE THREAD

**Issue by ThomasHoooo** [swaggo/swag#1937]
**Is your feature request related to a problem? Please describe.**
Swag now marks a field as `required` when adding a tag `validation:"required"`. At the same time, the web framework Gin also supports these tags, but they use `bind:"required"`. When running `swag init`, `bind:"required"` doesn't generate the `required` field. And it is quite troublesome to add 2 tags just to make it as `required`. E.g.: `bind:"required" validation:"required"`

**Describe the solution you'd like**
I want to just add `bind:"required"` as Gin already uses validator. 

**Describe alternatives you've considered**

**Additional context**

**Comment by sdghchj** [comment]
Could you please make a PR?
