### ISSUE TITLE
doc.json link redirecting to blank page

### ISSUE THREAD

**Issue by jainsachin99** [swaggo/swag#194]
Hi,
Not sure if this is real bug or I'm missing something.
The link below title doc.json is pointing to blank page. Also the json file which is getting created is with name swgger.json then why this link is to doc.json. 

**Expected behavior**
This link should open the json file in new window.

<img width="1572" alt="screen shot 2018-08-24 at 11 52 53 am" src="https://user-images.githubusercontent.com/32229285/44602437-784b4f80-a794-11e8-81fc-64eb2bbf740f.png">

swag version v1.3.2

**Comment by axiaoxin** [comment]
Click the link will open a `about:blank` page, it doesn't open the url "http://localhost:8080/x/apidocs/doc.json", directly access the url is ok.

**Comment by mguggi** [comment]
I have the same behavior with swag version v1.4.0. Is there a workaround for this issue?

**Comment by leucos** [comment]
In the meantime I use

```
// @description JSON API definition can be retrieved at <a href="/api/v1/swagger/doc.json">/api/v1/swagger/doc.json</a>
```
as a workaround.

**Comment by easonlin404** [comment]
Fixed via https://github.com/swaggo/gin-swagger/pull/46.
 Now you can use `ginSwagger.Config` to point out API doc link:
```go
func main() {
	r := gin.New()
    
	config := &ginSwagger.Config{
		URL: "http://localhost:8080/swagger/doc.json", //The url pointing to API definition
	}
	// use ginSwagger middleware to 
	r.GET("/swagger/*any", ginSwagger.WrapHandler(config, swaggerFiles.Handler))

	r.Run()
}
```

**Comment by Dysar** [comment]
Uhmm, that's good that the issue got fixed for Gin, but what about the users who do not use Gin? 

I also would like to have the working doc.json link with `httpSwagger.WrapHandler`.

**Comment by Loupax** [comment]
Just adding a dot in the beginning of the path seems to fix the issue

```
rs.Handle("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("./swagger/doc.json"),
	)
)
```

**Comment by Congee** [comment]
Would appreciate it if there's a solution for `echoSwagger`

**Comment by Congee** [comment]
there you go `e.GET("/swagger/*", echoSwagger.EchoWrapHandler(func(c *echoSwagger.Config) { c.URL = "./swagger/doc.json" }))`
