### ISSUE TITLE
swag init command not running

### ISSUE THREAD

**Issue by shantanuaggarwal2695** [swaggo/swag#197]
**Describe the bug**
Swag init is not working.

**To Reproduce**
1. Extract swaggo/swag
2. run swag init in the root folder
**Expected behavior**
Command:swag  not found

**Screenshots**

**Your swag version**
e.g. v1.2.0

**Desktop (please complete the following information):**
 - Ubuntu
 - Mozilla
 

**Additional context**

**Comment by easonlin404** [comment]
Please download swag by using:

`$ go get -u github.com/swaggo/swag/cmd/swag`

**Comment by joe9111** [comment]
@easonlin404 I am also facing the same issue. swag: command not found
`$ go get -u github.com/swaggo/swag/cmd/swag

`
did not work

**Comment by mtorkamani** [comment]
Me too!

**Comment by miajorlou** [comment]
me too

**Comment by philip-firstorder** [comment]
#meToo

**Comment by vincentbriglia** [comment]
for those having this problem, make sure your GO Path is on the PATH environment variable ```export PATH=$(go env GOPATH)/bin:$PATH```

**Comment by idawud** [comment]
> for those having this problem, make sure your GO Path is on the PATH environment variable `export PATH=$(go env GOPATH)/bin:$PATH`

This worked for me

**Comment by eeechoo** [comment]
> for those having this problem, make sure your GO Path is on the PATH environment variable `export PATH=$(go env GOPATH)/bin:$PATH`

I think this reply should be append to the readme.md

**Comment by tarim** [comment]
I have the same issue with Mac OS. the path is set up correctly, but it still doesn't work.

**Comment by tarim** [comment]
It works now, after update ~/.zshrc file.

**Comment by sinanbaran** [comment]
if you try swagger in an undefined project it will not work.

https://github.com/swaggo/swag#declarative-comments-format

define a default then swag init is run swag init

**Comment by witcher-vae** [comment]
Try `$GOPATH/bin/swag init` because `go get -u github.com/swaggo/swag/cmd/swag` create swag in `$GOPATH/bin`, `$GOPATH` can be `/home/user/go` which user is "pc user"

**Comment by ubogdan** [comment]
It's not actually a swag issue.

**Comment by mamunsyuhada** [comment]
> ~/.zshrc

it works
```cmd
source ~/.zshrc
```

**Comment by akmalseferagic** [comment]
> for those having this problem, make sure your GO Path is on the PATH environment variable `export PATH=$(go env GOPATH)/bin:$PATH`

Its work for me!

**Comment by spoo24** [comment]
Below steps worked for me
$ cd ~/go/bin
$ ls
you should see "swag" then run 
$ export PATH="/Users/XXX/go/bin:$PATH"
$ source ~/.zshrc
$ swag -v

**Comment by harshSamsung21** [comment]
> export PATH=$(go env GOPATH)/bin:$PATH

Thanks , worked for me

**Comment by nikhe** [comment]
> for those having this problem, make sure your GO Path is on the PATH environment variable `export PATH=$(go env GOPATH)/bin:$PATH`

Thanks, This worked for me

**Comment by isaswa** [comment]
> for those having this problem, make sure your GO Path is on the PATH environment variable `export PATH=$(go env GOPATH)/bin:$PATH`

This worked for me, tyvm.

**Comment by fukaraca** [comment]
This problem was caused by 2 reason for me.
1- GOBIN wasn't set. see` go env GOBIN`  this should return a path like `/home/$(USER)/go/bin`
2- I needed to `go install github.com/swaggo/swag/cmd/swag` . Otherwise no bin file will be in GOBIN folder. So when you call `swag init` it cannot find swag cmd file.

- To set GOBIN; call on terminal  `export GOBIN=$(go env GOPATH)/bin` .This will set GOBIN env create bin folder under gopath. To confirm check `go env`
- Then `go install github.com/swaggo/swag/cmd/swag` .

This worked for me

**Comment by HimanshuSharma-Angel** [comment]
@fukaraca thanks buddy

**Comment by darylblake** [comment]
Just an FYI was making a build a docker container `FROM golang:1.17-alpine AS build`
And was able to run: 
`RUN go get -u github.com/swaggo/swag/cmd/swag`
Then access swag.
However in golang:1.18-alpine it doesnt work. 

Installing using go install works with 1.18:
`RUN go install github.com/swaggo/swag/cmd/swag@latest`

There are other threads here on generics in 1.18 and apparently this lib is not 100% ready..

**Comment by eguadorodrigo** [comment]
> This problem was caused by 2 reason for me. 1- GOBIN wasn't set. see` go env GOBIN` this should return a path like `/home/$(USER)/go/bin` . if its empty, then it means you GOBIN path is missing and you need to set. 2- I needed to `go install github.com/swaggo/swag/cmd/swag` . Otherwise no bin file will be in GOBIN folder. So when you call `swag init` it cannot find swag cmd file.
> 
> * To set GOBIN; call on terminal  `export GOBIN=$(go env GOPATH)/bin` .This will set GOBIN env create bin folder under gopath. To confirm check `go env`
> * Then `go install github.com/swaggo/swag/cmd/swag` .
> 
> This worked for me

Works for me too, thanks for sharing, help me a lot!! :)

**Comment by madhavdutta** [comment]
Try using the following.

export GOROOT=$HOME/go
export PATH=$PATH:$GOROOT/bin

Worked fine for me.Thanks

**Comment by MohammadMobasher** [comment]
for who that still have swag error, please use this command for install :
`go install github.com/swaggo/swag/cmd/swag@latest`

**Comment by a-u-z** [comment]
> Below steps worked for me
> $ cd ~/go/bin
> $ ls
> you should see "swag" then run
> $ export PATH="/Users/XXX/go/bin:$PATH"
> $ source ~/.zshrc
> $ swag -v

this help 
thanks a lot

**Comment by Psarmmiey** [comment]
> Try using the following.
> 
> export GOROOT=$HOME/go export PATH=$PATH:$GOROOT/bin
> 
> Worked fine for me.Thanks

This worked for me

**Comment by shashwat-kumar-rmi** [comment]
**MAC with M1 chipset**
Default location of swag binary is `/go/bin/linux_amd64` . On adding this to my path swag is working fine.

**Comment by Guo-xuejian** [comment]
""go get -u" switch to "go install" worked for me

**Comment by mucansever** [comment]
> ""go get -u" switch to "go install" worked for me

I did this also and wonder if this could cause versioning problems later on

**Comment by greazleay** [comment]
My own issue was because my models were used in the controller files that was annotated, I structured my app to have service files where database interactions are handled. Adding an import for my models at the top of controller files fixed my issue

**Comment by semyonkrutolevich** [comment]
Also if someone got this error on mac os, try to find it in this path: ~/go/bin/export/swag

**Comment by KiranHRubix** [comment]
The above error resolution in M1 MAC,

First of all set the GOPATH as per the countless helping comments before this has pointed out.

For MacBooks with M1 Pro Chipset, Swag is installed in the path 

`/Users/<username>/go/bin/darwin_amd64`

use the below command to export the path 
`export PATH=$PATH:/Users/<username>/go/bin/darwin_amd64`

then you can call swag init

**Comment by navid-shokri** [comment]
So, My laptop is running Ubuntu 22.04. I ran: 
> sudo go get -u github.com/swaggo/swag/cmd/swag

and after al blah blah printing without any error:

I check my GOPATH/bin and there is no swag file at all. I also tried : 
> /home/myuser/go/bin/swag init

**Comment by navid-shokri** [comment]
Oh I solve it by this answer in [SO](https://stackoverflow.com/a/75834433/1093228)

> go install github.com/swaggo/swag/cmd/swag@latest

**Comment by SHresTho12** [comment]
Try reloading the terminal after running this command
`go install github.com/swaggo/swag/cmd/swag@latest`

**Comment by ArienYi** [comment]
> export PATH=$PATH:$GOROOT/bin

Worked for me! Thanks!!

**Comment by gurodrigues-dev** [comment]
> for those having this problem, make sure your GO Path is on the PATH environment variable `export PATH=$(go env GOPATH)/bin:$PATH`

This worked for me, thanks \o/

**Comment by Zollelibraw** [comment]
> ""go get -u" switch to "go install" worked for me

(
    - go get github.com/swaggo/swag/cmd/swag
    - go install github.com/swaggo/swag/cmd/swag
)
this help me
thanks a lot

**Comment by iqquee** [comment]
To do this temporarily for the current session: 
```sh
export PATH=$PATH:$HOME/go/bin
```

To permanently add it to your PATH, you can edit your shell profile (.bashrc or .zshrc, depending on your shell):
For Bash:
```sh
echo 'export PATH=$PATH:$HOME/go/bin' >> ~/.bashrc
```
```sh
source ~/.bashrc
```

For Zsh:
```sh
echo 'export PATH=$PATH:$HOME/go/bin' >> ~/.zshrc
```
```sh
source ~/.zshrc
```
After updating your PATH, verify that the swag command works:
```sh
swag --version
```
If you want to install swag globally and avoid the PATH issue altogether, you can move the swag binary to a directory like /usr/local/bin which is usually in your PATH by default:
```sh 
sudo mv $HOME/go/bin/swag /usr/local/bin/
```
