### ISSUE TITLE
It would be gret respecting authoring

### ISSUE THREAD

**Issue by landru29** [swaggo/swag#203]
When you copy/paste a project (https://github.com/landru29/swaggo) or its concept, it would be fair to respect authoring, change the name of the project, or change a little bit the syntax.

Wouldn't it be better to fork or to contribute ?

https://github.com/swaggo/swag/commit/c7ded85c2c92711f4f60901bea1a341c1ceece20 (Jun 10, 2017)
vs
https://github.com/landru29/swaggo/commits/master (Sep 24, 2016)

**Comment by easonlin404** [comment]
Actually there are a lot of similar tool to do the same thing and syntax not the same. IMO, I think all of was inspired by https://github.com/yvasiyarov/swagger, but like you said it's get a confusing with naming,
