### ISSUE TITLE
docker image with swag pre-installed

### ISSUE THREAD

**Issue by Ashtonian** [swaggo/swag#208]
**Is your feature request related to a problem? Please describe.**
I'd like to use swag init as kind of a utility and a bit cleaner in my build pipeline. This would be useful for people with drone and circle ci and potentially others. 

**Describe the solution you'd like**
a public docker image on docker-hub with swag installed
 
**Describe alternatives you've considered**
currently maintaining my own image for this 

Somebody with repo admin will need to update Travis with docker account credentials. This *should* be close I think to what you need. I can try and work on this a bit more on a fork when I have some more time and submit a PR if it's not. 

starter .dockerfile although there is probably a better way to use the local source code
```docker 
from golang:1.11

RUN go get -u github.com/swaggo/swag/cmd/swag
````

starter .travis.yml modifications
```
sudo: required

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO= swaggo/swag
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
```

**Comment by pei0804** [comment]
It looks like a good idea.
PR is accepted at any time.

**Comment by easonlin404** [comment]
Now you can download pre-installed binary form release page [v1.4.1](https://github.com/swaggo/swag/releases/tag/v1.4.1).

**Comment by RamLodhi111** [comment]
Hello guys, I am facing challenge in integrating swag with my build pipeline. Can you please help me how to run swag init in docker ? Using docker alpine image.
