### ISSUE TITLE
package name error

### ISSUE THREAD

**Issue by elvizlai** [swaggo/swag#211]
**Describe the bug**
i have a dir call `pb`. for some reason, the packname should be `xyz`.

here is some code sample:
```
import "xyz/pb"

var _ = xyz.UserInfo{}
```

the swaggo need using pb.UserInfo, but it actually xyz.UserInfo

```
package ctrl

import (
	"net/http"

	"xyz/pb"
)

// ShowAccount godoc
// @Summary Show a account
// @Description get string by ID
// @Accept  json
// @Produce  json
// @Param id path int true "Account ID"
// @Success 200 {object} pb.UserInfo
// @Router /accounts/{id} [get]
func Test(rw http.ResponseWriter, r *http.Request) {
	_ = xyz.UserInfo{}
	log.Infof("req: %v", r)
}
```

**Comment by pei0804** [comment]
This problem the namespace.
To be a little difficult to solve.

**Comment by easonlin404** [comment]
please use the [v1.6.5](https://github.com/swaggo/swag/releases/tag/v1.6.5) try again. Reopen it if there are problems.
