### ISSUE TITLE
Buffalo Support

### ISSUE THREAD

**Issue by cippaciong** [swaggo/swag#214]
Hello, I was wondering if there is any plan/will to add support for the Buffalo framework.
What kind of changes are required to add support for Buffalo starting from the gin-swagger codebase for example?
Thanks

**Comment by pei0804** [comment]
Is this what you are talking about?
https://github.com/gobuffalo/buffalo

There is no plan to do, but additions are possible if there are collaborators.

**Comment by cippaciong** [comment]
Yes, that's what I'm talking about. Is there any documentation about adding support for a new framework or can you give me some insights?
Thanks

**Comment by easonlin404** [comment]
@cippaciong you can reference https://github.com/swaggo/echo-swagger/blob/master/swagger.go#L18-L55 to wrap a new `buffalo.Handler` function.

**Comment by cippaciong** [comment]
Hello, I was finally able to write a Buffalo middleware for swaggo. If you want to take a look at it, I put the code in this repository: https://github.com/cippaciong/mw-swaggo

**Comment by easonlin404** [comment]
@cippaciong LGTM. Can you help transfer to https://github.com/swaggo/buffalo-swagger? I have invited you as admin collaborator.

**Comment by easonlin404** [comment]
we have added support for the Buffalo framework. https://github.com/swaggo/buffalo-swagger 💯
