### ISSUE TITLE
Programmatic way to set some swagger options

### ISSUE THREAD

**Issue by bojand** [swaggo/swag#215]
**Is your feature request related to a problem? Please describe.**

Experimenting with this package, and overall really like the idea and approach. Specifically I am using echo, but i think my issue is generally applicable. It would be great if some of the Swagger options could be set programmatically. Specifically I am thinking of `host` and `basePath`, and potentially `version`. It is very plausible that `host` and `basePath` may not be known at swag-init-time (when the swag tool is run to generate docs) and may come from configs or other settings. Similarly  version may come from an external source at build time for example, and not necessarily at swag-init-time. 

**Describe the solution you'd like**

One possible solution could be to expose [template variables](https://golang.org/pkg/text/template/) that could be set at some point. So things like `Host`, `BasePath` and `Version`. Then the generated `doc` variable could be a templated string where `host` and `basePath` could be:

```go
"host":  "{{ .Host }}",
"basePath": "{{ .BasePath }}",
```
The swag tool could set these variables into the exposed template data from parsing the comment annotations. But the exposed data would be available for us to mutate... So:

```go
import "github.com/me/swag-test/docs" // docs is generated by Swag CLI, you have to import it.
```
and then elsewhere:
```go
docs.Version = "1.0"
docs.BasePath = "/api"
docs.Host = "localhost:1234"
```

`ReadDoc()` could execute the template string with the data, and result in proper spec.

This is just one idea that quickly came to me, but I am not sure if it's the best solution as I am not familiar with implementation details of swag completely.

If this approach or similar works, or whatever, I would be happy with PR effort if I think I can do it.

Thanks.

**Comment by pei0804** [comment]
Your idea is good.
Can you try it?

**Comment by bojand** [comment]
Sure, Might be a bit busy this week but will try and get to it soon.

**Comment by pei0804** [comment]
Yeah. I want to your good work.

**Comment by Nerzal** [comment]
This can be closed, as it is solved.
