### ISSUE TITLE
@Param do not load custom struct

### ISSUE THREAD

**Issue by gabrielDevlog** [swaggo/swag#216]
**Describe the bug**
Swag panic when trying to load a custom struct with @Param: `panic: assignment to entry in nil map`.

**To Reproduce**
This code run into a panic with `swag init`
```
import "github.com/myproject/model"

// @Router /websites [post]
// @Summary Create a new website
// @Description Create a new website using user's data
// @Accept json
// @Produce json
// @Tags Website
// @Param website body model.WebsiteDTO true "dto"
// @Success 201 {object} model.Website
func myFunc() {
}
```
`swag init` fails with this error:
```
2018/09/25 21:12:49 Generate swagger docs....
2018/09/25 21:12:49 Generate general API Info
panic: assignment to entry in nil map
...
```

Ìf I remove this line `swag init` run without failure :
 `// @Param website body model.WebsiteDTO true "dto"`

Also, I noticed that custom model are correctly loaded in `@Success`. I mean this line `// @Success 201 {object} model.WebsiteDTO` do not produce any failure, and my model is correctly loaded and described by swag.

Which leads me to this hack:
```
// @Router /websites [post]
// @Summary Create a new website
// @Description Create a new website using user's data
// @Accept json
// @Produce json
// @Tags Website
// @Success 201 {object} model.WebsiteDTO // <- Declaring Success here is a hack so @Param can load model
// @Param website body model.WebsiteDTO true "dto"
// @Success 201 {object} model.Website // <- Overriding previous "@Success" to display correct struct
// @Failure 400 "Bad_Request"
```
Putting `@Success` before `@Param` resolve the bug, load the expected model definition :3

**Expected behavior**
@Param should load model without a hack

**Your swag version**
v1.4.0

**Desktop (please complete the following information):**
 - OS: windows X

**Comment by GitBalou** [comment]
I try with : ` go get -u github.com/swaggo/swag` and `swag init` but no luck. Still the same error, still the same fix.

**Comment by moskal91** [comment]
Same issue for me, but when using models from external vendored package (no matter if @Param is after @Success or not).

OS: Ubuntu 18.04
Swag version: v1.4.0

**Comment by tankgirlnz** [comment]
Same issue for me - workaround hack works.

OS: Ubuntu 18.04
Swag version: V1.4.0

**Comment by sdghchj** [comment]
Try latest master branch

**Comment by easonlin404** [comment]
please reopen it if there are any problems.
