### ISSUE TITLE
bug: recursive model support

### ISSUE THREAD

**Issue by elvizlai** [swaggo/swag#218]
For model like this:
```
type Node struct {
	Id        string
	Next      *Node
	NextSlice []*Node
}
```

```
go get github.com/elvizlai/swag-example
cd $GOPATH/github.com/elvizlai/swag-example
make doc1
make doc2
```

And I also notice that when package is outside `gateway` (it this case, the code is in pb), it can not find ref automatic.

When we using micro services, we often put micro and gateway in a big dir with model. but the model is outside gateway.

**Comment by pei0804** [comment]
Do you have problem now?

**Comment by easonlin404** [comment]
lose response for long, please use the last version of swag and try again.
