### ISSUE TITLE
Gorilla mux support

### ISSUE THREAD

**Issue by rugwirobaker** [swaggo/swag#223]
Is there a plan to add [ gorilla mux](https://github.com/gorilla/mux) support any time soon?
It is one of the most popular HTTP request multiplexer around and I am quite surprised, it is not already supported yet.

**Comment by easonlin404** [comment]
you can use  [swaggo/http-swagger](https://github.com/swaggo/http-swagger) to support for  gorilla/mux because it  It implements the `http.Handler`  Examples code as following: 

https://github.com/swaggo/http-swagger/blob/d2bf002bf65b31fc7f152b174c07a6bce5e0a50f/example/gorilla/main.go#L1-L29
