### ISSUE TITLE
Can not find the "github.com/swaggo/gin-swagger" 

### ISSUE THREAD

**Issue by jayhuang75** [swaggo/swag#23]
Hello,

First of all, great package. But I follow the use guide, and seems i can not find the 

`"github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"`

Please advices.

**Comment by easonlin404** [comment]
@jayhuang75  you have to download  by using if you want to generate swagger UI via gin-swagger:
```
$ go get -u github.com/swaggo/gin-swagger
$ go get -u github.com/swaggo/gin-swagger/swaggerFiles
```
I will update the readme doc asap. 😄

**Comment by jayhuang75** [comment]
Hello @easonlin404,

I figure it out, just download those missing libs. 

Thank you for your help. And please check my other question. Much appreciated your help. 

Have a great day.
