### ISSUE TITLE
missing libs: golang.org\x\net

### ISSUE THREAD

**Issue by af913337456** [swaggo/swag#231]
run : go build -v -a cmd/swag/main.go

..\..\..\golang.org\x\net\idna\idna.go:23:2: cannot find package "golang.org/x/text/secure/bidirule" in any of:
        C:\go_1.9\src\golang.org\x\text\secure\bidirule (from $GOROOT)
        C:\go_1.9\lgh\src\golang.org\x\text\secure\bidirule (from $GOPATH)
..\..\..\golang.org\x\net\idna\idna.go:24:2: cannot find package "golang.org/x/text/unicode/bidi" in any of:
        C:\go_1.9\src\golang.org\x\text\unicode\bidi (from $GOROOT)
        C:\go_1.9\lgh\src\golang.org\x\text\secure\bidirule (from $GOPATH

**Comment by af913337456** [comment]
golang.org/x/text/secure/bidirule can't be found anymore!

**Comment by af913337456** [comment]
@elvizlai

**Comment by af913337456** [comment]
@easonlin404  i have use this command,but get the same error message

**Comment by easonlin404** [comment]
Did you have run `swag`  command instead of `go build -v -a cmd/swag/main.go` ?

**Comment by af913337456** [comment]
@easonlin404  how can i run swag？i can't event build it , there is no swag executable file.

**Comment by easonlin404** [comment]
swag executable will exist in this `$GOPATH/bin` folder.

**Comment by af913337456** [comment]
@easonlin404 has check，not exits！

**Comment by af913337456** [comment]
@easonlin404

**Comment by easonlin404** [comment]
please follow https://golang.org/doc/code.html#GOPATH to setup your `$GOPATH`.

**Comment by af913337456** [comment]
@easonlin404  my gopath is good，already set before

**Comment by easonlin404** [comment]
please download swag by using:
```
$ go get -u github.com/swaggo/swag/cmd/swag
```
