### ISSUE TITLE
How to add Request Cookies	?

### ISSUE THREAD

**Issue by leonlau** [swaggo/swag#237]
Cookie Authentication :
https://swagger.io/docs/specification/authentication/cookie-authentication/

**Comment by JiaLiangoooo** [comment]
Me too!

**Comment by pei0804** [comment]
We haven't yet. Do you want to it?
If you want to use soon you make PR please or I want you to wait for a while.
@leonlcw @JiaLiangoooo

**Comment by ubogdan** [comment]
This is from "OAS 3" specifications not from "OAS 2" (our swagger implementation)
