### ISSUE TITLE
set a []int type field example has a bug? 

### ISSUE THREAD

**Issue by axiaoxin** [swaggo/swag#238]
**Describe the bug**
```
type X struct {
  Numbers []int 
}
```
how to set an example for X.Numbers correctly? I try `example:"1"` `example:"[1]"` both are wrong example.

If delete the example tag, example show int is unkown type...

**Comment by xiaoguiSniper** [comment]
hey,do you solve this problem now? I think I got the same problem as you.
```
type X struct {
  IDs []int64 
}
```
then `swag init`, but I got `Unknown  Type:int64`

**Comment by sdghchj** [comment]
Try latest master
```
type X struct {
  Numbers []int `example:"1,2,3"`
}
```

**Comment by easonlin404** [comment]
please reopen it if there are any problems.
