### ISSUE TITLE
Unknown Type: int

### ISSUE THREAD

**Issue by jayhuang75** [swaggo/swag#24]
Hello All,

I try to implement the example as follow.
My type is:
`type SwaggerProjectList struct {
	ProjectId   string
	ProjectName string
	NumTasks    int
}`

My Swaggo comments
`// @Success 200 {object} models.SwaggerProjectList "project list"`

The problem is in swaggo UI:
`
{
  "NumTasks": "Unknown Type: int",
  "ProjectId": "string",
  "ProjectName": "string"
}
`

**Comment by jayhuang75** [comment]
@easonlin404 Could you give me some advice on this? Thank you.

**Comment by jayhuang75** [comment]
@easonlin404 sorry for bugging you, I follow the trace, so the quick fix just add a new type of integer
`type integer struct {}`
This will fix the issues. 

So moving forward, which I find out the reason, it generates the swagger doc on top of this [go-swagger](https://github.com/go-swagger/go-swagger). And go-swagger do not have the int type.

**Comment by easonlin404** [comment]
Fix via #26. Thank you for your contribution. 💯
