### ISSUE TITLE
Use struct define in vendor

### ISSUE THREAD

**Issue by Nexucis** [swaggo/swag#242]
**Describe the bug**
Hello,
I have the following folder hierarchy : 
```
.
| -- endpoints
|     `-- user.go
| -- model
|     `-- error.go
| -- vendor
      `-- my.repository
           `-- common-lib
                `-- model
                     `--user.go
```                     

I would like to reference the struct contains in vendor/my.repository/.../user.go for the response of my endpoint user for example.

And I have no clue about how I can do it. I have tried several different possible configuration but nothing good so far.

Here is my go client of the endpoint : 

```golang
import (
	"io"
	"net/http"

	"github.com/labstack/echo"
	commonModel "my.repository/common-lib/model"
	"my.repository/model"
)

// @Tags users
// @Router /users [post]
// @Accept  json
// @Produce  json
// @Success 200  {object} commonModel.UserEntity
// @Failure   400  {object} model.ErrorEntity
// @Failure   500  {object} model.ErrorEntity
func (e *UserEndpoint) CreateUser(ctx echo.Context) error {
	// code
}
```

This code produce the following error : 

```log
2018/11/06 19:33:28 ParseComment panic:can not parse response comment "200 {object} commonModel.UserEntity "
panic: ParseComment panic:can not parse response comment "200 {object} commonModel.UserEntity "
```

I also try to put the complete package name instead of the alias : 
```golang
// @Success 200  {object} my.repository/common-lib/model.UserEntity
```
which is generate the swagger without the definition of the struct `UserEntity`

**Expected behavior**
The goal is at the end to generate the definition for all struct (in the swagger.json), event if the struct are in the vendor of the application

**Your swag version**
v1.4.0
I also tried with the last commit on master [6993bc5667b70aa...](https://github.com/swaggo/swag/tree/6993bc5667b70aa5067a78abaa67c094dc96e864)

**Desktop (please complete the following information):**
 - OS: windows 10

**Additional context**
I suppose this is related to the issue #188. But I don't get it how to reference the types that come from the vendor folder

**Comment by 8tomat8** [comment]
Have the same problem on
v1.4.0
OS: Linux

**Comment by mthhk** [comment]
@easonlin404 @pei0804

**Comment by icobani** [comment]
I have same issue.

**Comment by pei0804** [comment]
OK.
I understand this issue.

**Comment by pei0804** [comment]
@a180285 fixed it Thx!
https://github.com/swaggo/swag/pull/331
