### ISSUE TITLE
Restful API used gin-swagger and oauth2，can not get the client_id,client_secret from the post request.

### ISSUE THREAD

**Issue by lulouis** [swaggo/swag#245]
**Describe the bug**

Like the next picture,marked some question

![image](https://marisfrolg.nos-eastchina1.126.net/TEMP/xxx20181112131630.png)

**To Reproduce**

1. I defined the authorization type "OAuth2Application".

```
// @securitydefinitions.oauth2.application OAuth2Application
// @tokenUrl http://localhost:8080/oauth2/token
// @scope.write Grants write access
// @scope.admin Grants read and write access to administrative information
```

2. I defined the action with some paramater ,especially this '@Security'
```
// ListAccounts godoc
// @Summary Get all account as a list [auth token]
// @Description get accounts
// @Tags accounts
// @Accept  json
// @Produce  json
// @Param q query string false "name search by q" Format(email)
// @Success 200 {array} model.Account
// @Failure 400 {object} httputil.HTTPError
// @Failure 404 {object} httputil.HTTPError
// @Failure 500 {object} httputil.HTTPError
// @Security OAuth2Application [admin]
// @Router /accounts [get]
func (c *Controller) ListAccounts(ctx *gin.Context) {

	q := ctx.Request.URL.Query().Get("q")
	accounts, err := model.AccountsAll(q)
	if err != nil {
		httputil.NewError(ctx, http.StatusNotFound, err)
		return
	}
	ctx.JSON(http.StatusOK, accounts)
}
```

3. cmd input 'swag init ',after that I get a Restful API server.
4. Browder my site http://localhost:8080/swagger/index.html,
   when I click the 'Authorize' button,I get this bug.

**Comment by lulouis** [comment]
there are my sourcecode repository.

**Comment by easonlin404** [comment]
I will look this issue asap.

**Comment by lulouis** [comment]
> I will look this issue asap.

Thank you very much.I am standing by for your reply.

**Comment by lulouis** [comment]
Dear Eason,
I am waiting for your solution yet . Do you need some screenshot or code any more ?
I would like to answer you at all times.Thank you so much.

**Comment by lulouis** [comment]
Eason,
Thank you , I corrected this issue, it is worked now.
Reference : https://github.com/swagger-api/swagger-ui/issues/4533.

`export const authorizeApplication = ( auth ) => ( { authActions } ) => {
  let { schema, scopes, name, clientId, clientSecret } = auth
  let headers = {
    Authorization: "Basic " + btoa(clientId + ":" + clientSecret)
  }
  let form = {
    grant_type: "client_credentials",
    scope: scopes.join(scopeSeparator),
    client_id: clientId, //need line
    client_secret: clientSecret //need line
  }`
