### ISSUE TITLE
What are the differences between swaggo and go-swagger?

### ISSUE THREAD

**Issue by KantarBruceAdams** [swaggo/swag#247]
As a newcomer to both go and swagger it is not obvious how to choose between the [swaggo](https://github.com/swaggo) and [goswagger](https://github.com/go-swagger/go-swagger) projects.
Both use different syntax for marking up REST APIs and both are capable of generating documentation.
It would be helpful if there was a page explaining the history or difference in goal of each project.

It is also unclear which syntax makes more sense.

swagger:route looks more go like
but the @ notation sems more in line with descriptions on the swagger web-site.

I think one major difference is that goswagger can also generate code from swagger definitions.
However, if you only want the documentation generation side (as I do) it is less obvious which to choose.

**Comment by KantarBruceAdams** [comment]
cross posted to go-swagger as https://github.com/go-swagger/go-swagger/issues/1794

**Comment by easonlin404** [comment]
PR is welcome to improve documents better. 👍
