### ISSUE TITLE
Swag parses comments rule.

### ISSUE THREAD

**Issue by rookiejin** [swaggo/swag#25]
it`s will be very slowly that the vendor directory are included in the Parser.files map 

```
//   in windows  "/vendor"  would be "\vendor" so i think it just make vendor will be ok ! 
if ext := filepath.Ext(path) ; ext == ".go" && !strings.Contains(path , "/vendor"){
			astFile , err := parser.ParseFile(token.NewFileSet() ,path ,nil, parser.ParseComments)
			if err != nil {
				panic(err)
			}
			log.Println(path)
			p.files [path] = astFile
		}
		return nil
```

**Comment by rookiejin** [comment]
I think it would be well that defined the Definitions use the follewn: 
`
// @def MyModel 
type MyModel struct {
     Name string 
}
// @Success 200 object @MyModel "the response" 
func Get(ctx *gin.Context) {
  //to do
}

`
because the pkg could be not found  and we can`t panic the exception 

I have an issue .

**Comment by easonlin404** [comment]
@rookiejin Sorry for the late reply. 😢   `Swag` only parses all Go source files in the  project root folder which contains main.go file and it will exclude vendor folder.
