### ISSUE TITLE
Change Request: change default output dir

### ISSUE THREAD

**Issue by Nerzal** [swaggo/swag#251]
**Is your feature request related to a problem? Please describe.**
If following the [standard project layout](https://github.com/golang-standards/project-layout) the default output path should be /api and not /docs

> OpenAPI/Swagger specs, JSON schema files, protocol definition files.

The current default directory is for something else, according to the standard project-layout.

> Design and user documents (in addition to your godoc generated documentation). See  the /docs directory for examples.

**Describe the solution you'd like**
It would be great, if the default output dir would be /api

**Comment by easonlin404** [comment]
same as https://github.com/swaggo/swag/issues/257

**Comment by pei0804** [comment]
@Nerzal 
You can use. https://github.com/swaggo/swag/pull/325
