### ISSUE TITLE
Can add docExpansion param make it default folding label？

### ISSUE THREAD

**Issue by IsSwm** [swaggo/swag#253]
**Is your feature request related to a problem? Please describe.**
`Yes, When I open doc, all tags have to be expanded. Bloated display。`

**Describe the solution you'd like**

`The folding state of labels can be controlled.`

**Additional context**

Like swagger-ui => https://github.com/swagger-api/swagger-ui/issues/3088

**Comment by Nerzal** [comment]
It looks like this behavior could be handled in the javaScript, which is part of the html in the [echo-swagger](https://github.com/swaggo/gin-swagger), [net/http-swagger](https://github.com/swaggo/http-swagger), [gin-swagger](https://github.com/swaggo/gin-swagger) projects.

![grafik](https://user-images.githubusercontent.com/9110370/48676107-3ac34c00-eb62-11e8-88cb-668f8de6b04e.png)

But i also think, that it would be nice to add a possibility to control this behavior.
To add this feature the way these "WrapHandlers" are working needs to be changed, as we need to inject that information anyhow.

**Comment by IsSwm** [comment]
Ok,thanks.I am using [gin-swagger](https://github.com/swaggo/gin-swagger) now.
But did not find such a function.

Although he is not a required function, he will bring visual convenience.
