### ISSUE TITLE
How can I add description to every field of request body JSON?

### ISSUE THREAD

**Issue by xiaocode** [swaggo/swag#254]
**Is your feature request related to a problem? Please describe.**
Now,I know how to add 'example' to the request body JSON, but I also want to add description to every field that makes others can easy to know what is the field really meaning.

**Describe the solution you'd like**
type user struct {
    username string `json:"username" example:"john smith" description:"login username"`
}

**Comment by ubogdan** [comment]
It is actually possible but you need to use comments. 

type Example struct {
	// Comment for Message field
	Message      string   `json:"message" example:"Test message goes here ..."`
}

**Comment by Dysar** [comment]
This does not work. Any luck for others?

**Comment by gy0624ww** [comment]
use  // comment

**Comment by Marif226** [comment]
Is there a working solution as commenting the struct field doesn't work?
