### ISSUE TITLE
Populating JSON bodies is not properly explained

### ISSUE THREAD

**Issue by jdmeyer3** [swaggo/swag#256]
To clear the record, I found it difficult to understand how to add a JSON body to the swagger definitions. Especially since my struct is in the same file as the http handler call (this is probably not best practice at the moment). I would like to have the JSON model explained a little better. For example, I have the following code in a package called `http`
```go
package http

type LoginInput struct {
	Username string `json:"Username" example:"Ryan" description:"login user"`
	Password string `json:"Password" example:"Renolds" description:"user password"`
}

//
//@Summary Login existing user
//@Tags	aaa
//@Description set JWT token
//@Accept json
//@Produce json
//@Param	loginInput		body	http.LoginInput	true	"login Input"
//@Success 200 {string} string	"ok"
//@Router /aaa/login [post]
func (a *UserHttpHandler) Login(ctx *gin.Context) {
...
}
```

explaining that the model definition is created by having \<package\>.\<struct\> as the DataType would help save other people time. For a while I thought it was absolute path until I accidentally stumbled across this. Please let me know if you need more clarification, this is already implemented and I'm an idiot, or this is a duplicate. Thank you for your time.

**Comment by xiaoguiSniper** [comment]
yeah, I got confused with this same question.
is there any helpful solution?

**Comment by k1ng440** [comment]
have you solved the issue?

**Comment by jdmeyer3** [comment]
The issue is solved, I'll close out this issue

**Comment by fmyxyz** [comment]
I got confused with this same question . What is the solution？ @jdmeyer3
