### ISSUE TITLE
Add an option for placing the docs/docs.go file

### ISSUE THREAD

**Issue by j0hnwhyte** [swaggo/swag#257]
When generating the documentation with swag init, there is no option to place the generated docs folder differently. I'm trying to separate the documentation generation code from the application code.

At the moment the folder is always placed in the directory specified with the d flag, which is the analysed one. I'm aiming to have a src/ folder with the program code and a docs/ folder with the documentation and swagger code.

I use this script at the moment to move the generated file outside the source dir
```bash
#!/usr/bin/env bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

APIPATH="../../src/admin-api"
INITFILE="admin-api.go"

cd "$SCRIPTPATH"

cd admin-api
swag init -g "$APIPATH/$INITFILE"  -d "$APIPATH" -s swagger/ || exit 1
mv "$APIPATH/docs/docs.go" docs/docs.go
rmdir "$APIPATH/docs/"

go build -o bin/admin-api-docs || exit 1
```

Please tell me if more explanations are needed, thanks

**Comment by pei0804** [comment]
@j0hnwhyte 
You can use. https://github.com/swaggo/swag/pull/325
