### ISSUE TITLE
 Panic when parse nested struct fields

### ISSUE THREAD

**Issue by yryz** [swaggo/swag#258]
**Describe the bug**
```go
type ListData struct {
	List  interface{}
	Total int
}

type AuditLogs struct {
	Data struct {
		ListData
	}
}
```

swag init panic:
> 2018/11/27 18:51:39 Generating model.AuditLogs
> panic: runtime error: index out of range
> 
> goroutine 1 [running]:
> github.com/swaggo/swag.(*Parser).parseField(0xc0000c3a90, 0xc00042eec0, 0xc0000e4f20)
>         /Users/jerry/go/src/github.com/swaggo/swag/parser.go:767 +0xfdc
> github.com/swaggo/swag.(*Parser).parseStruct(0xc0000c3a90, 0xc000501ba9, 0x5, 0xc00042eec0, 0x0)
>         /Users/jerry/go/src/github.com/swaggo/swag/parser.go:577 +0x77

**Screenshots**

![image](https://user-images.githubusercontent.com/1646732/49077397-22e07c00-f276-11e8-9275-51952456bb4a.png)

**Your swag version**
v1.4.0

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by ubogdan** [comment]
It's not a nested struct issue . 
You are asking swag to describe the field List that you defined as interface , change it to any of a golang primitive type (eg: string / int/ uint) or other struct that does not have interface type fields and it will work. 
Not a bug !

**Comment by yryz** [comment]
```
type ListData struct {
	Total int
}

type AuditLogs struct {
	Data struct {
		ListData
	}
}
```
The same error.
> panic: runtime error: index out of range


About defined as an interface, it works fine. No nested. example:
```
type ResultData struct {
	Code   int
	Data   interface{}
	Errors []string
}

type Users struct {
	ResultData
	Data *UserListData
}
```

**Comment by pei0804** [comment]
want code sample.

```go
type ListData struct {
	Total int
}

type AuditLogs struct {
    Data Data
}

type Data {
   ListData ListData
}

```

example
https://github.com/swaggo/swag/blob/4f45ba52207fc2f6af0f73e950384abef3c977d8/example/celler/model/bottle.go#L3-L7
