### ISSUE TITLE
How do I add description in model then show in sawgger?

### ISSUE THREAD

**Issue by JimChung0403** [swaggo/swag#260]
I hope to look at the description in sawgger (like picture).
How can I do write struct?

type ExamplePost struct {
Name string binding:"required" example:"jim"
Old int binding:"required" example:"30" format:"int"
}

![image](https://user-images.githubusercontent.com/13103974/49273355-a0430100-f4af-11e8-898a-c01375eb95b0.png)

**Comment by ubogdan** [comment]
It is actually possible but is not easy to figure out because is not documented.  :)

type Example struct {
	// Comment for Message field
	Message      string   `json:"message" example:"Test message goes here ..."`
}

**Comment by easonlin404** [comment]
Welcome PR to improve the swag’s documentation.

**Comment by wanghe4096** [comment]
good idea

**Comment by xiaoguiSniper** [comment]
@JimChung0403 I wonder that if you have any solution for this question?

**Comment by kuangchanglang** [comment]
Is it possible to support trailing comment as description.
```go
type Example struct{
    Message string `json:"msg"` // I get use to comment here
}
```

**Comment by xiaoguiSniper** [comment]
I think you should do comment like this:
```
type Example struct{
    // I get use to comment here
    Message string `json:"msg"` 
}
```

**Comment by kuangchanglang** [comment]
Hi @xiaoguiSniper, I see how your codes work. But I prefer tailing comments especially on large struct, which looks good for me.
```go
type LargeStruct struct {
    // comment i
    I string
    // comment prefer
    Prefer int
    // comment Tailing
    Trailing string
    // comment comments
    Comments string
    // comment though
    Though string
}

type LargeStruct struct {
    I        string // comment i
    Prefer   int    // comment prefer
    Trailing string // comment Tailing
    Comments string // comment comments
    Though   string // comment though
}
```
