### ISSUE TITLE
How exсlude nested model of swagger UI

### ISSUE THREAD

**Issue by magvan** [swaggo/swag#261]
http://joxi.ru/a2XbbPei1e040r.jpg

type Campaign struct {
	ID        uint `gorm:"primary_key" json:"id" example:"19398"`
	CreatedAt time.Time `json:"created_at" example:"0001-01-01T00:00:00Z"`
	UpdatedAt time.Time	`json:"updated_at" example:"0001-01-01T00:00:00Z"`
	DeletedAt *time.Time `sql:"index" json:"deleted_at" example:"0001-01-01T00:00:00Z"`
	User User `gorm:"foreignkey:User" swagger:"ignore"`
	Name string `json:"name" example:"Shop campaigns"`
}

**Comment by ubogdan** [comment]
you can use json ignore if you want to hide it. 
type Campaign struct {
.....
User User gorm:"foreignkey:User" json:"-"
....
}

**Comment by magvan** [comment]
Thank you!

**Comment by ilya-korotya** [comment]
@ubogdan Is there another option to exclude the field from the swagger UI? I want this field to come in the HTTP response but not show up in the swagger UI.

**Comment by ubogdan** [comment]
@ilya-korotya sound like security by obscurity. 
The real reason for having open API documentation is to expose these fields.

**Comment by ilya-korotya** [comment]
@ubogdan About my case. I have a response structure with next fields:
```go
type BatchResponse struct {
  Success []interface{} `json:"success,omitempty"`
  Failed []interface{} `json:"failed,omitempty"`
  NotFound []interface{} `json:"notFound,omitempty"`
  ...etc
}
```
Some endpoints use not all fields from `BatchResponse`. They use only `Success` and `Failed` fields for example. I create swagger comments for these endpoints like:
```go
// @Success 200 {object} libPayload.BatchResponse{success=[]payload.AddIPRequest,failed=[]payload.InsertIPInvalidBatchItem}
```
I want to hide fields that won't use in swagger comment above.

Expect swagger doc:
```
{
  Success: [
    {
       "ip": "1.2.3.4",
       "reason":"some reason"
    }
    ....
  ],
  Failed: [
    {
       "ip": "1.2.3.4",
       "err":"some error"
    }
    ....
  ]
}
```
Actual swagger doc:
```
{
  Success: [
    {
       "ip": "1.2.3.4",
       "reason":"some reason"
    }
    ....
  ],
  Failed: [
    {
       "ip": "1.2.3.4",
       "err":"some error"
    }
    ....
  ],
  NotFound: [{}],
  ... and another fields from BatchResponse
}
```

**Comment by ubogdan** [comment]
@ilya-korotya The chosed path is quite ambiguous...
```golang
type AddIPRequest struct {
}
...
type NotFound struct {
    IP string
    Err string
}
...
type InternalError struct {
    IP string
    Err string
}

// @Success 200 {object} libPayload.AddIPRequest
// @Failure 400 {object} libPayload.NotFound
// @Failure 500 {object} libPayload.InternalError
```

**Comment by ilya-korotya** [comment]
@ubogdan got it. Thanks for your help!

**Comment by ubogdan** [comment]
You're wellcome.
