### ISSUE TITLE
Go Modules support

### ISSUE THREAD

**Issue by tzilist** [swaggo/swag#267]
**Is your feature request related to a problem? Please describe.**
Currently, I don't think this CLI supports go modules at all. It would be nice to support this as that is where go-lang seems to be heading

**Describe the solution you'd like**
I should be able to run the `swag` cli from outside of the `GOPATH`
**Describe alternatives you've considered**

**Additional context**

**Comment by kolaente** [comment]
I have the same problem when referencing structs as response defined in vendored packages using go mod. Swaggo creates a reference in the type of `external.repo.io/repo.StructName` but doesnt create a response definition for it. The swagger client then throws errors like 
```
Resolver error at paths./stuff.get.responses.403.schema.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/external.repo.io/repo.StructName does not exist in document
```
When I manually add the missing response to the generated file, it works.

**Comment by christianhujer** [comment]
I have the same issue. I am developing a go module that implements a `/health` endpoint according to the upcoming IETC RFC. When I created the sample code that supports swag, I could not see the `/health` endpoint. Without having looked at the code, I would currently assume that `swag` does not scan module sources, but only recursively from the current directory.

It would be very useful for people if `swag` would support go modules, I just don't know how easy or difficult this is to implement. I will try something, maybe I can even come up with a PR.

**Comment by tzilist** [comment]
@easonlin404 it looks like an issue with gotools loader not knowing where to look. It is entirely possible you would need to use a different tool or figure out how to configure it. I've heard of people using [gogrep](https://github.com/mvdan/gogrep), but I am not entirely sure.

In the mean time, the work-around I have found is to run this before running swag:
```
go mod vendor
cp -R /vendor/* $GOPATH/src/
```

**Comment by easonlin404** [comment]
It's not easy to support go modules.  I will  using different tool like [gogrep](https://github.com/mvdan/gogrep),[godef](https://github.com/rogpeppe/godef) or any other tool instead of current searching mechanisms asap.

**Comment by josephzidell** [comment]
This ticket has been open for 6 months and is only becoming more relevant and more difficult to ignore. Would it be possible to get some traction on this?

**Comment by easonlin404** [comment]
I agree with you that having supported for Go modules feature is highest priority now.  Will keep  on support for it and release on v1.6.

**Comment by easonlin404** [comment]
Please use the latest swag that supports founding declarative annotations from go-module packages via #415. 🎉

**Comment by aguaje** [comment]
Why was this closed?  I am still having this issue and could only resolve it using the workaround that @tzilist posted.   I'm using v1.6.5
