### ISSUE TITLE
go get -u github.com/swaggo/swag/cmd/swag

### ISSUE THREAD

**Issue by VICTORYGS** [swaggo/swag#269]
Can anyone help me?
![image](https://user-images.githubusercontent.com/33747619/50334578-ba6a7f00-0543-11e9-89cb-7ed20025dbbf.png)

**Comment by easonlin404** [comment]
@VICTORYGS You can download executable binary from https://github.com/swaggo/swag/releases/tag/v1.4.1 for windows.

**Comment by easonlin404** [comment]
please reopen it if u have any questions.
