### ISSUE TITLE
Can't define 2 different example responses

### ISSUE THREAD

**Issue by gempir** [swaggo/swag#271]
**Describe the bug**
The API I am building can respond with plain text or json depending on a query parameter and or the content-type in the request headers. So I want swagger to show the 2 different type of responses and the look of them. 
When defining 2 @Success responses only the last one will be shown in swagger when you switch between the 2 Response content types in swagger UI nothing changes and the "string" example will always show. 

![image](https://user-images.githubusercontent.com/9765622/50371956-1aedd080-05c5-11e9-8ede-b0f2f72eb34c.png)

**To Reproduce**
Create an example with this as an API Controller
```
// @Produce  json
// @Produce  plain
// @Success 200 {object} someStruct json
// @Success 200 {string} plain string
```

**Expected behavior**
2 different example responses are visible in Swagger and will show depending on the content-type.

**Comment by yangkghjh** [comment]
Maybe use a struct.

**Comment by gempir** [comment]
Yes that would probably solve it, but makes no sense if you think about the HTTP Spec. Both responses are 200 and just differ in the content.

**Comment by pei0804** [comment]
It's difficult.
I think  can't it due to spec format.

```yml
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Account'
            type: object

```

**Comment by jeffwalter-rum** [comment]
@pei0804 can we get this reopened? It's not that difficult and is clearly supported by the openAPI spec: https://swagger.io/docs/specification/describing-responses/
