### ISSUE TITLE
Could swag support  registration twice?

### ISSUE THREAD

**Issue by william-tu** [swaggo/swag#285]
How to register twice in a project?

**Screenshots**
![image](https://user-images.githubusercontent.com/20549680/51240697-3cb95800-19b7-11e9-8ffb-6e04c446e66f.png)

![image](https://user-images.githubusercontent.com/20549680/51240945-c406cb80-19b7-11e9-83e3-459d2c6d237f.png)

**Your swag version**
e.g. v1.4.0

**Desktop (please complete the following information):**
 - OS: [macOS ]

**Comment by mziia** [comment]
Any thoughts? Solved this problem?
