### ISSUE TITLE
Nested array struct not shown correctly

### ISSUE THREAD

**Issue by baba2k** [swaggo/swag#289]
**Describe the bug**
A nested array struct will not displayed correctly

**To Reproduce**
type Bank struct {
	City                         string `json:"city,omitempty"`
        // ...
	Credentials []struct {
		Masked bool   `json:"masked"`
		Label  string `json:"label,omitempty"`
	} `json:"credentials,omitempty"`
}
**Expected behavior**
Model should be displayed correctly in Swagger

**Screenshots**
Displayed as:
[&{%!s(token.Pos=1542) %!s(*ast.FieldList=&{1549 [0xc000337d40 0xc000337d80] 1625}) %!s(bool=false)}]

**Your swag version**
v1.4.0

**Desktop (please complete the following information):**
 - OS: macOSX Mojave
 - Browser: Chrome

**Comment by pei0804** [comment]
If I write I think define another struct.

https://github.com/swaggo/swag/blob/4f45ba52207fc2f6af0f73e950384abef3c977d8/example/celler/model/bottle.go#L6
