### ISSUE TITLE
installed swag version is v1.3.2 instead of v1.4.0

### ISSUE THREAD

**Issue by gitouyoung** [swaggo/swag#291]
I use `go get -u github.com/swaggo/swag/cmd/swag`. 
```
go: finding github.com/swaggo/swag/cmd/swag latest
go: finding github.com/swaggo/swag/cmd latest
go: extracting github.com/swaggo/swag v1.4.0
```
Then the `swag --version` is still `swag version v1.3.2`. 
I'm using `go version go1.11.1 windows/amd64`

**Comment by easonlin404** [comment]
I don't have windows can reproduce. Needs someone help.

**Comment by stefano-salmaso** [comment]
Hi,
I have downloaded this https://github.com/swaggo/swag/archive/v1.4.0.zip and
the `version.go` file says `const Version = "v1.3.2"`
Is the tag correct?

Thanks

**Comment by easonlin404** [comment]
@stefano-salmaso It's not correct. I will bump v.1.4.1 to fix this issue.

**Comment by easonlin404** [comment]
please using latest https://github.com/swaggo/swag/releases/tag/v1.4.1 version.

**Comment by stefano-salmaso** [comment]
Hi again,
there is something strange/wrong... this what I made:
I have run
`go clean -i github.com/swaggo/swag/cmd/swag`
and then
`go get -u github.com/swaggo/swag/cmd/swag`
`swag` binary has been re-created in `~/go/bin` but, if I run it, I have:
```
mac:~/go/bin$ ./swag --version
swag version v1.4.0
```
Any clue?

**Comment by easonlin404** [comment]
@stefano-salmaso you can run `$ go env` to check if `$GOPARH` is correct.
