### ISSUE TITLE
Could not resolve reference because of: Could not resolve pointer: /definitions/

### ISSUE THREAD

**Issue by Gelembjuk** [swaggo/swag#293]
**Describe the bug**

I try to use this tool with my gin-gonic code. In general it works. But i have errors like

"Could not resolve reference because of: Could not resolve pointer: /definitions/taskAddResponse does not exist in document" 

My declaration looks like 
```
// @Success 202 {object} taskAddResponse "ID of created task"
```

And the taskAddResponse structure is
```
type taskAddResponse struct {
	ID string `json:"id" example:"xxxxxx-xxxxx-xxxxx"`
}
```

The structure taskAddResponse is in another file but in same package in same folder with main.go . Declaration for Success is in main.go file.

This problems happens for all Success and Failure declarations. I have 4 structs and 1 error struct. All of them fail. There is nothing in  /definitions/ in swagger json

Version of swag is fresh . I installed today 

What can be wrong?

**Comment by pei0804** [comment]
sry. I don't have idea.
I want to more code.

**Comment by pei0804** [comment]
If you have problem reopen issue.

**Comment by benprofessionaledition** [comment]
@Gelembjuk I had the same issue. It probably has something to do with swaggo generating definitions  relative to docs.go. I resolved this by moving e.g. `taskAddResponse` to `responses.go` and then changing the comment to `// @Success 202 {object} responses.taskAddResponse "ID of created task"`

**Comment by ahoulgrave** [comment]
Seems same issue as https://github.com/swaggo/swag/issues/181
