### ISSUE TITLE
import alias error

### ISSUE THREAD

**Issue by CaiJinKen** [swaggo/swag#294]
**Describe the bug**
response not support import alias

**Screenshots**
code like this:
```
import (
	.....
	apiv2 "...../services/api/v2"
	servicev2 "...../services/v2"
        ....
)
......
// @Success 200 {object} apiv2.Response
// @Failure 400 {object} apiv2.Response
// @Router /api/v2/something [post]
```
error messages when run swag init
```
can not find ref type:"apiv2.Request
```
if i replace all apiv2 to v2, and delete apiv2 in import then everything ok.

**Your swag version**
v1.4.0

**Desktop (please complete the following information):**
 - OS: GNU/Linux

**Comment by pei0804** [comment]
Thx for PR.
I want to more example or testcase can you help me?
@CaiJinKen
