### ISSUE TITLE
Definitions section is missed in generated JSON. Same package

### ISSUE THREAD

**Issue by Gelembjuk** [swaggo/swag#296]
**Describe the bug**
I use swag to generate API docs for my Go code. I have @Success and @Failure comments

Like:

```
// @Success 200 {object} TaskAddResponse "ID of created task"
// @Failure 400 {object} HTTPError "Unknown error"
```

Structures are in other files in same package

```
type TaskAddResponse struct {
	ID string `json:"ID" example:"xxxxxx-xxxxx-xxxxx"`
}
type HTTPError struct {
	Code    int    `json:"code" example:"400"`
	Message string `json:"message" example:"status bad request"`
}
```

When i execute "swag init". There is no /definitions/TaskAddResponse and /definitions/HTTPError in JSON .

What can be wrong?

**Comment by Gelembjuk** [comment]
I have got this example
https://github.com/swaggo/gin-swagger/tree/master/example

It works fine

But when i moved the structure APIErrorto the package api and removed from web. It doesn't work then
There is no reference in JSON file.

Does it work only for extrenal packages?

**Comment by Gelembjuk** [comment]
I have found a trick to solve this.
When i add main. before structure name it works.
// @Success 200 {object} main.TaskAddResponse "ID of created task"
// @Failure 400 {object} main.HTTPError "Unknown error"

It it must be a self name of a package if it is not main. 
So, swag requires structure name have a prefix even it if it in same package with the docs

**Comment by pei0804** [comment]
I see.
swag need `main.hoge` for parse logic.

**Comment by pei0804** [comment]
If you have problem reopen issue.

**Comment by FabioRodrigues** [comment]
> I have found a trick to solve this.
> When i add main. before structure name it works.
> // @success 200 {object} main.TaskAddResponse "ID of created task"
> // @failure 400 {object} main.HTTPError "Unknown error"
> 
> It it must be a self name of a package if it is not main.
> So, swag requires structure name have a prefix even it if it in same package with the docs

You solved my day, thx!
