### ISSUE TITLE
Support objects for formData

### ISSUE THREAD

**Issue by lsattem** [swaggo/swag#300]
**Is your feature request related to a problem? Please describe.**
Not that i know of.

**Describe the solution you'd like**
I have not seen a solution to this in the documentation, but the documentation on @Param is a bit lacking (i.e. does not mention formData being an option).
When setting @Param, it would be nice if you could specify object and object type. This way it's clear what sort of input my endpoint expects. For example, **the following go code...**
```golang
package main

type MyStruct struct{
	AnInt int
}

// @Summary test form data
// @Accept multipart/form-data
// @Param payload formData main.MyStruct true "form data"
// @Router /test [post]
func test(){}
```

**...provides the following swagger:**
```json
{
    "info": {
        "contact": {},
        "license": {}
    },
    "paths": {
        "/test": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "test form data",
                "parameters": [
                    {
                        "type": "main.MyStruct",
                        "description": "form data",
                        "name": "payload",
                        "in": "formData",
                        "required": true
                    }
                ]
            }
        }
    }
}
```
What **I would like** is for the swagger to include the type def, and look like **this**:
```json 
{
    "info": {
        "contact": {},
        "license": {}
    },
    "paths": {
        "/test": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "test form data",
                "parameters": [
                    {
                        "type": "main.MyStruct",
                        "description": "form data",
                        "name": "payload",
                        "in": "formData",
                        "required": true
                    }
                ]
            }
        }
    },
    "definitions": {
        "main.MyStruct": {
            "type": "object",
            "properties": {
                "anInt": {
                    "type": "integer"
                }
            }
        }
    }
}
```
**Describe alternatives you've considered**
An alternative, but ugly, solution is to add a dummy function that contains the struct as an object, such as this one.
```golang
// @Failure 200 {object} main.MyStruct "wish this wasn't necessary"
func dummy(){}
```

I could also use param type 'body', but that is also somewhat ugly (and misleading).

**Additional context**
N/A

**Comment by pei0804** [comment]
I see.
I'm thoughting for solution.

**Comment by JayenLee** [comment]
I have the same problem


type equipmentQuery struct {
	ProductName string `json:"product_name" form:"product_name"` // 产品名称
	Sn          string `json:"sn" form:"sn"`                     // sn号
	ClientCode  string `json:"client_code" form:"client_code"`   // 代理商编号可多选用","隔开
	Page        int    `json:"page" form:"page"`                 //页数
	PageSize    int    `json:"pagesize" form:"pagesize"`         // 每页展示条数
	File        string `json:"file"form:"file" format:"binary" form:"file"`
}
// @Param file  formData equipmentQuery true "parameter"


I set a structure to use the parameter type of formdata, but when generating a swagger document, it will report equipmentquery is not supported type for formdata

Does formdata not support user defined struct yet?

**Comment by danielpoe** [comment]
Any updates? 

paramType body seems to work - paramType formData not..
(In our case the posted form application/x-www-form-urlencoded data is marshaled into a struct)

**Comment by wiliansilvazup** [comment]
Any updates?

**Comment by birdycn** [comment]
你好，请问解决了吗
