### ISSUE TITLE
swag rejects valid MIME Types for @Produce, panic

### ISSUE THREAD

**Issue by christianhujer** [swaggo/swag#303]
**Describe the bug**
Swag limits the MIME types allowed for APIs without good reason to do so.
Here are four MIME types which I want to use which swag disallows, panicing when I use them:

* `application/xhtml+xml`
* `application/xml`
* `application/health+json`
* `image/svg+xml`

**To Reproduce**
1. Create an endpoint that produces a valid MIME type not in the documentation of `swag`.
2. Run `swag init`

**Expected behavior**
All valid MIME types are accepted. There are no restrictions to what APIs can use. APIs are free to choose.

** Actual Behavior**
`swag` panics.

```
+ /home/christian.hujer/go/bin//swag init
2019/02/20 16:16:44 Generate swagger docs....
2019/02/20 16:16:44 Generate general API Info
2019/02/20 16:16:44 ParseComment panic in file health/health.go :application/health+json produce type can't accepted
panic: ParseComment panic in file health/health.go :application/health+json produce type can't accepted

goroutine 1 [running]:
log.Panicf(0x8f0078, 0x22, 0xc4201b3510, 0x2, 0x2)
        /usr/lib/go-1.10/src/log/log.go:333 +0xda
github.com/swaggo/swag.(*Parser).ParseRouterAPIInfo(0xc4204b7630, 0xc4203f7240, 0x10, 0xc420502b00)
        /home/christian.hujer/go/src/github.com/swaggo/swag/parser.go:347 +0x256
github.com/swaggo/swag.(*Parser).ParseAPI(0xc4204b7630, 0x8e2247, 0x2, 0x8e3479, 0x7, 0x8e7ed3, 0x13)
        /home/christian.hujer/go/src/github.com/swaggo/swag/parser.go:96 +0x242
github.com/swaggo/swag/gen.(*Gen).Build(0xc42048f988, 0x8e2247, 0x2, 0x8e3479, 0x7, 0x8e5a3e, 0xe, 0x8e3e9a, 0x9, 0x0, ...)
        /home/christian.hujer/go/src/github.com/swaggo/swag/gen/gen.go:30 +0x2c6
main.main.func1(0xc4200fe2c0, 0xc4202efb00, 0xc4200fe2c0)
        /home/christian.hujer/go/src/github.com/swaggo/swag/cmd/swag/main.go:34 +0x194
github.com/urfave/cli.HandleAction(0x843500, 0x8ffde0, 0xc4200fe2c0, 0x0, 0xc420143020)
        /home/christian.hujer/go/src/github.com/urfave/cli/app.go:502 +0xbe
github.com/urfave/cli.Command.Run(0x8e285f, 0x4, 0x0, 0x0, 0xc42040f210, 0x1, 0x1, 0x8e5ae6, 0xe, 0x0, ...)
        /home/christian.hujer/go/src/github.com/urfave/cli/command.go:165 +0x47d
github.com/urfave/cli.(*App).Run(0xc420074000, 0xc4200ba000, 0x2, 0x2, 0x0, 0x0)
        /home/christian.hujer/go/src/github.com/urfave/cli/app.go:259 +0x6e8
main.main()
        /home/christian.hujer/go/src/github.com/swaggo/swag/cmd/swag/main.go:61 +0x4e2
```

**Your swag version**
```
~/go/bin/swag --version
swag version v1.4.1
```

**Desktop (please complete the following information):**
- OS: Kubuntu 18.04.2 LTS
- Go version: go1.10.4 linux/amd64

**Additional context**
I've seen that `swag` has already been patched several times to accomodate more MIME Types.
It should not be necessary to patch `swag` for new MIME Types.
`swag` should not panic on MIME Types it does not know, it should simply pass them through.
If `swag` shall help with avoiding accidents with MIME Types, such as wrong MIME Types, it should issue a warning for unknown MIME types instead of panicing. Also, in that case, `swag` should not maintain authority over the list of known MIME types but accept IANA as authority, refering to the official list of registered MIME types at https://www.iana.org/assignments/media-types

**Comment by easonlin404** [comment]
fixed by #304
