### ISSUE TITLE
Multiline description in annotation is not working

### ISSUE THREAD

**Issue by desylva** [swaggo/swag#305]
**Describe the bug**
Adding multiple @description in the buffalo actions/app.go but only the last description line is used.

**To Reproduce**
Adding these descriptions to actions/app.go in a buffalo app:
// @title Lines
// @version 1.0
// @description Line 1
// @description Line 2
// @description Line 3

Only getting the last line in swagger.yaml for the description:
description: Line 3

**Expected behavior**
I'd expect the description in swagger.yaml after running "swag init -g actions/app.go" to be:
description: Line 1 Line 2 Line 3

**Your swag version**
v1.4.1

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.3

**Comment by easonlin404** [comment]
can you post your `./docs/swaager/swagger.json` file?   Will generate as following:
```
{
    "swagger": "2.0",
    "info": {
        "description": "Line 1\nLine 2\nLine 3",
        "title": "Lines",
        "contact": {},
        "license": {},
        "version": "1.0"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}
```

**Comment by desylva** [comment]
I can confirm that when my actions/app.go contain this annotations:
```
// @title Lines API
// @version 1.0
// @description Line 1
// @description Line 2
// @description Line 3.
```

The json file looks this way:
```
{
    "swagger": "2.0",
    "info": {
        "description": "Line 3.",
        "title": "Lines API",
```

And the yaml file looks like this:
```
info:
  contact:
    email: ...
    name: ...
    url: ...
  description: Line 3.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Lines API
  version: "1.0"
```

**Comment by easonlin404** [comment]
It's work for me when using  v1.4.1 version, can you check `$swag -version`?

**Comment by desylva** [comment]
ok, this resolves it for me.
Despite having swag@1.4.1 installed in my packages, the swag binary was still version 1.3.2.
On compiling the swag command to have version 1.4.1, I can confirm the docs are generated correctly now. Thanks for your time and making me look at the right place.
