### ISSUE TITLE
Ability to select the protocol http or https

### ISSUE THREAD

**Issue by desylva** [swaggo/swag#306]
**Is your feature request related to a problem? Please describe.**
When the api is running over https, it doesn't seem possible to set the host with a https protocol.
When doing so, the requests in swagger-ui are directed to http://https://{host}:{port}

![screenshot 2019-02-20 at 18 37 50](https://user-images.githubusercontent.com/3845144/53115757-e653b200-353e-11e9-812e-d7693044d5ac.png)

**Comment by easonlin404** [comment]
You can use `schemes` annotation to supports the https like:
```go
// @Schemes https
```
