### ISSUE TITLE
Auto set Authorization header with ApiKeyAuth

### ISSUE THREAD

**Issue by fannheyward** [swaggo/swag#314]
**Expected behavior**

I already set `@securityDefinitions.apikey ApiKeyAuth` in General API info, and `@Security ApiKeyAuth` in Each API operation:

```
@securityDefinitions.apikey ApiKeyAuth
func main() {
}

// @Security ApiKeyAuth
// @router /account/info [get]
func GetAccountInfo(c *gin.Context) {
}
```

This works great, except that Swagger UI says there is no params needed:

<img width="377" alt="image" src="https://user-images.githubusercontent.com/345274/53967306-f4552580-412f-11e9-94b8-a099488d43c0.png">

This is not correct since Authorization header is needed for the API. After I add `@param` definition to API:

```
// @Security ApiKeyAuth
// @param Authorization header string true "Authorization"
// @router /account/info [get]
func GetAccountInfo(c *gin.Context) {
}
```

Now, Swagger UI is correct:

<img width="761" alt="image" src="https://user-images.githubusercontent.com/345274/53967736-b7d5f980-4130-11e9-9c3c-f7dee6fc8a26.png">

<img width="679" alt="image" src="https://user-images.githubusercontent.com/345274/53968296-b9ec8800-4131-11e9-9072-4304d0903484.png">

But Authorization header is empty when trying out the API.

Is there any way to auto set Authorization header that already set by ApiKeyAuth?

**Your swag version**
1.4.1

**Comment by pei0804** [comment]
Difine
https://github.com/swaggo/swag/blob/934068ff10f3d59cc4c91e9726eb4f5530093107/example/celler/main.go#L33-L35

Use
https://github.com/swaggo/swag/blob/e5d83e9840f5f169ccfa779899f03478e6d6973a/example/celler/controller/admin.go#L24

push auth button in swagger ui
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/9821370/54685738-e6a19600-4b5a-11e9-9597-5def311302cf.png">

Done.
<img width="640" alt="image" src="https://user-images.githubusercontent.com/9821370/54685760-f4efb200-4b5a-11e9-8d09-e43de3bf6725.png">

example is here.
https://github.com/swaggo/swag/tree/master/example/celler

@fannheyward

**Comment by pei0804** [comment]
If you have problem reopen issue.

**Comment by rametta** [comment]
@pei0804 Does this work for Oauth2Implicit ? It doesn't seem to be sending my Authorization Header after I Authenticate
