### ISSUE TITLE
Operation description gets appended to general info if they share the same file

### ISSUE THREAD

**Issue by umanovskis** [swaggo/swag#340]
**Summary**

Swag version 1.4.1.

If general API info is in the same file as operations, then the @description tag of operations will also get appended to the general info. I think this was introduced after adding support for multiline @description in the general API.

**Example**

Code in the same file:

```
// @title       Test API
// @version     0.1
// @description General API description

// @Summary Returns true
// @Description Always returns true, really
// @Success 200
// @Router /test [get]
func op() bool {
        return true
}
```
After `swag init`, it will generate this description for the general API:

```
"description": "General API description\nAlways returns true, really",
```

And the operation's description itself will be correct:

```
 "description": "Always returns true, really",
```

**Comment by pei0804** [comment]
Thank you!
I will review your code.

**Comment by umanovskis** [comment]
PR has been merged - thanks to the maintainers.
