### ISSUE TITLE
Is allow define common header for all api

### ISSUE THREAD

**Issue by foolin** [swaggo/swag#351]
I want define a common header for all api like security ApiKeyAuth, but ApiKeyAuth seems that only one field is allowed to be defined?

For example, define the following fields in the header: 
```
App-ID: xxxx
Access-Token: xxxx
```

```
curl -X POST \
  http://127.0.0.1:8080/v1/data/list \
  -H 'Access-Token: MC4xNTUzMjc2NjExLmgzbjZ2NVNxRXVaWDdzSlZXaWD' \
  -H 'App-ID: 1001' \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache' \
  -d '{
	"offset": 0,
	"size": 20
}'
```

**Comment by pei0804** [comment]
I think use include path than use `App-ID` better.
eg : http://127.0.0.1:8080/v1/{app-id}/data/list

If you want to multi header. 
You create PR or I'll create PR for this solution.

**Comment by foolin** [comment]
OK, my solution now is to add the following code for each api:

```
// @Param App-ID header string true "App ID"
// @Param Access-Token header string true "Access Token"
```

**Comment by pei0804** [comment]
If you have problem reopen issue.
