### ISSUE TITLE
string raw in body

### ISSUE THREAD

**Issue by dimuls** [swaggo/swag#357]
**Describe the bug**
If you try to make body string param you will get wrong generated docs:
```
<...>
      - description: This is body string param
        in: body
        name: body-string-param
        required: true
        schema:
          $ref: '#/definitions/string'
          type: object
<...>
```

**To Reproduce**
Use this kind of definition:
```
// @param body-string-param body string true "This is body string param"
```

**Expected behavior**
I'm not sure in right definition in docs. But certainly this is wrong definition:
```
schema:
          $ref: '#/definitions/string'
          type: object
```
It causes error in gin-swagger ui.

**Your swag version**
1.4.1

**Your go version**
1.11.2

**Comment by pei0804** [comment]
I think you have to use struct.
`// @param body-string-param body string true "This is body string param"`

https://github.com/swaggo/swag/blob/master/testdata/simple/api/api.go#L13

**Comment by dimuls** [comment]
No need string exactly. I have `@accept text/csv` API method. I need to fill textarea with CSV rows in UI.

**Comment by pei0804** [comment]
Is this POST method?

**Comment by dimuls** [comment]
Yes, this is POST method.

**Comment by pei0804** [comment]
Does this api no need key of key-value?
Is this similar api? https://stackoverflow.com/questions/50998620/post-csv-text-file-using-curl

BTW, swag have file upload annotation.
eg: https://github.com/swaggo/swag/blob/master/testdata/simple/api/api.go#L50

**Comment by dimuls** [comment]
My API does not require any key. CSV data will be read from whole body.

**Comment by pei0804** [comment]
swag don't support this case yet.
Does @easonlin404  know?

Maybe this.
https://swagger.io/docs/specification/2-0/describing-request-body/


```yaml
    paths:
      /status:
        post:
          summary: Updates the status message.
          consumes:
            - text/plain      # <----------
        parameters:
          - in: body
            name: status
            required: true
            schema:
              type: string  # <----------
        responses:
          200:
            description: Success!
```

**Comment by pei0804** [comment]
> About file upload: can i do something like this?

Yes.

`// @Param  filekey formData file true  "this is a test file"`

**Comment by dimuls** [comment]
> 
> 
> swag doesn't support this case yet.
> Does @easonlin404 know?
> 
> Maybe this.
> https://swagger.io/docs/specification/2-0/describing-request-body/
> 
> ```yaml
>     paths:
>       /status:
>         post:
>           summary: Updates the status message.
>           consumes:
>             - text/plain      # <----------
>         parameters:
>           - in: body
>             name: status
>             required: true
>             schema:
>               type: string  # <----------
>         responses:
>           200:
>             description: Success!
> ```

I'm sure, this is that i'm need. Swag should support this type of definitions.

**Comment by pei0804** [comment]
> I'm sure, this is that i'm need. Swag should support this type of definitions.

I can't create soon.
but swag is OSS. you can create PR.

**Comment by ubogdan** [comment]
@pei0804 i guess he [know](https://github.com/swaggo/swag/blob/bd1235d8e7291c9914afe94717e0c3d2972f45bc/operation.go#L161) :

**Comment by ubogdan** [comment]
Please test with latest version and open an issue if necessary.
