### ISSUE TITLE
how can I make the swag comment flexible in different environments?   

### ISSUE THREAD

**Issue by huahuayu** [swaggo/swag#360]
how can I make the swag comment flexible in different environments?   

for the local test I may use
```
// @Host 127.0.0.1
```

for the server, I should use  
```
// @Host <server public ip>
```

I don't want to manually change every time when deploying the project.

**Comment by easonlin404** [comment]
Some general API info can be set dynamically. you can follow like:
```go
// programatically set swagger info
	docs.SwaggerInfo.Title = "Swagger Example API"
	docs.SwaggerInfo.Description = "This is a sample server Petstore server."
	docs.SwaggerInfo.Version = "1.0"
	docs.SwaggerInfo.Host = "petstore.swagger.io"
	docs.SwaggerInfo.BasePath = "/v2"
```

**Comment by davidnewhall** [comment]
No, we want the generated json spec to be accurate. This leaves it inaccurate and unsharable.
