### ISSUE TITLE
Unable to request with Basic Auth

### ISSUE THREAD

**Issue by 0zAND1z** [swaggo/swag#365]
**Describe the bug**
Request Header generated by the Swagger UI is missing the Basic Auth Authorization.. Hence the request is being rejected by the API.

Expected Header (from Postman):
```
curl -X GET \
 'http://localhost:3000/<ROUTE>' \
 -H 'Authorization: Basic YWljdW06MTIzNDU2' \
 -H 'cache-control: no-cache'
```

Header obtained from the Swagger UI:
```
curl -X GET "http://localhost:3000/<ROUTE>" -H  "accept: application/json"
```

As you may observe, the above Curl Request does not have the Authorization, although the Swagger UI definition has been made, as follows:
``` 
// @securityDefinitions.basic BasicAuth
// @in header
// @name Authorization
```

**To Reproduce**
1. Add the above swagger definition to the API source file  
2. login via AUTHORIZE button in the revised Swagger UI
3. Make a GET/POST request 

**Expected behavior**
Route must be executed by the API with a response code reverted to the UI.

**Screenshots**
Authorize button & Login dialogue:
![image](https://user-images.githubusercontent.com/11145839/55133807-e3a33880-514c-11e9-864c-b209a72a8978.png)

Response after executing a route via the Swagger UI:
![image](https://user-images.githubusercontent.com/11145839/55133811-e736bf80-514c-11e9-8210-7a3c29e24afb.png)

**Your swag version**
Latest

**Your go version**
Latest

**Desktop (please complete the following information):**
 - Browser: Chrome, Mac

**Comment by easonlin404** [comment]
@pei0804 would you help to check?

**Comment by pei0804** [comment]
:eyes:

**Comment by pei0804** [comment]
Are you adding `@Security` ?

https://github.com/swaggo/swag/blob/03e66e658b41d11a7a40f920f8ab151ab1b925e1/example/celler/controller/admin.go#L24

**Comment by akshitababel** [comment]
@pei0804 
// @Security ApiKeyAuth is added when we want apikey auth. right? Actually we are looking for basic auth.

**Comment by akshitababel** [comment]
@pei0804  we are using basic auth not api key auth. Anyways replacing  `@Security ApiKeyAuth ` with `@Security BasicAuth` solved our issue. We can close this issue now.

**Comment by 0zAND1z** [comment]
Thanks @akshitababel .
I am now closing this issue.

Will open a PR with update to the documentation :)

Cheers
