### ISSUE TITLE
Don't create docs directory with swag-cmd into custom directory path

### ISSUE THREAD

**Issue by mrfoe7** [swaggo/swag#368]
**Describe the bug**
Don't create docs directory with swag-cmd into custom directory path.

**To Reproduce**
Next test case:
swag init --dir ../test/

Output:
2019/03/31 23:10:58 Generate swagger docs....
2019/03/31 23:10:58 Generate general API Info
2019/03/31 23:10:58 create docs.go at  docs/docs.go
2019/03/31 23:10:58 create swagger.json at  docs/swagger.json
2019/03/31 23:10:58 create swagger.yaml at  docs/swagger.yaml

I checked dir and don't found files from this.
From this cases docs folder is not created and not exists. 

Next test case:
- swag init --dir ./utils/
Output:
2019/04/01 10:12:37 Generate swagger docs....
2019/04/01 10:12:37 Generate general API Info
2019/04/01 10:12:37 create docs.go at  docs/docs.go
2019/04/01 10:12:37 create swagger.json at  docs/swagger.json
2019/04/01 10:12:37 create swagger.yaml at  docs/swagger.yaml

From this cases docs folder is created but not from custom directory. 
I am tried to do test with flag -d

I think it is problem not from swag cmd. Because from source code used https://github.com/urfave/cli.

p.s. I wanna fix with bug, but i don't have enough time for this problem :(

**Expected behavior**
I expected to cli create docs directory into my custom path.

**Screenshots**
Start experiment:
https://cdn1.imggmi.com/uploads/2019/4/1/3df6189d6dee645e036b79f1dc0a7aa6-full.png
Test one: 
https://cdn1.imggmi.com/uploads/2019/4/1/20f83c17def2302fab731410d8138f5b-full.png
Test two:
https://cdn1.imggmi.com/uploads/2019/4/1/ea730838ea06c1469487c7ae753d61d2-full.png

**Your swag version**
swag version v1.5.0

**Your go version**
go version go1.11.5 darwin/amd64

**Desktop (please complete the following information):**
 - OS: mac OS
 - Version:
    System Software Overview:
      System Version: macOS 10.14.3 (18D109)
      Kernel Version: Darwin 18.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal

**Comment by pei0804** [comment]
please use `tree` command because difficult to understand the tree structure from the next is.
Where is general-api-info?
If main.go has general-api-info you have to `swag init` on ldap/src.

**Comment by mrfoe7** [comment]
@pei0804 hm... 

> Directory you want to parse (default: "./")

Sorry, I misunderstood what the flag does&
