### ISSUE TITLE
How to declare `additionalProperties` for the query parameter?

### ISSUE THREAD

**Issue by dvasilen** [swaggo/swag#374]
Did anyone manage to declare `additionalProperties` for the query parameter? 
The code suggests that `additionalProperties` are supported https://github.com/swaggo/swag/search?utf8=%E2%9C%93&q=additionalProperties&type=

But I am having hard time trying to figure out how it can be done looking thru
https://github.com/swaggo/swag#declarative-comments-format

**Comment by pei0804** [comment]
For example.
https://github.com/swaggo/swag/blob/2a57949e334f0974aedeae62875eb32a2c03bebd/testdata/composition/api/api.go#L26

**Comment by dvasilen** [comment]
It seems to work in the `// @Success 200 ...` but fails to parse for the query....

I am getting 

```
2019/04/11 09:41:21 Generate swagger docs....
2019/04/11 09:41:21 Generate general API Info
2019/04/11 09:41:21 ParseComment error in file handlers.go :missing required param comment parameters "q query {object} model.PropMap false "The optional query parameters""
```
_______________________

```
package model 

type PropMap map[string]Prop

type Prop struct {
	Key string
}
```
--------------
```
package main
...
// @Param   q query {object} model.PropMap false "The optional query parameters"
....
```

**Comment by pei0804** [comment]
I want to know more code.

**Comment by dvasilen** [comment]
Sure, thanks, I will provide the complete example later today.

**Comment by dvasilen** [comment]
I have created a repository https://github.com/dvasilen/additionalProperties which shows the issue. 
The `additionalProperties` work fine when we define then for the `@Success` 
https://github.com/dvasilen/additionalProperties/blob/master/src/test/main.go#L26

See generated swagger https://github.com/dvasilen/additionalProperties/blob/master/src/docs/swagger.yaml#L7

But parsing fails when we try to use them in the query 

https://github.com/dvasilen/additionalProperties/blob/master/src/test/main.go#L17

When I add 

```
// @Param   q query {object} model.PropMap false "The optional query parameters"
```

the parsing fails 

```
2019/04/12 13:56:31 ParseComment error in file test/main.go :missing required param comment parameters "q query {object} model.PropMap false "The optional query parameters""
```

**Comment by sdghchj** [comment]
Try latest master branch again

**Comment by easonlin404** [comment]
Please reopen it or raise a new one if there are still problems on the latest master branch.
