### ISSUE TITLE
Panic on parsing

### ISSUE THREAD

**Issue by lily-lee** [swaggo/swag#375]
**Describe the bug**

It panics when I use swag i

```
type Param struct {
	SendTime Time `json:"send_time" form:"send_time" gorm:"DEFAULT:NULL"`
}

// Time ...
type Time time.Time

// TimeLayout ...
var TimeLayout = "2006-01-02 15:04:05"

// MarshalJSON ...
func (t Time) MarshalJSON() ([]byte, error) {
	return json.Marshal(time.Time(t).Format(TimeLayout))
}

// UnmarshalJSON ...
func (t *Time) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}

	if s == "" {
		return nil
	}

	tt, err := time.Parse(TimeLayout, s)
	if err != nil {
		return err
	}
	*t = Time(tt)
	return nil
}
```

**To Reproduce**

**Expected behavior**

**Screenshots**
![WechatIMG294](https://user-images.githubusercontent.com/16358848/55853221-adc17380-5b92-11e9-8c3a-9f126c44104a.jpeg)

**Your swag version**
swag version v1.5.0

**Your go version**
go version 1.11.5

**Desktop (please complete the following information):**
 Macos 10.14.4

**Additional context**

**Comment by easonlin404** [comment]
please see https://github.com/swaggo/swag#use-swaggertype-tag-to-supported-custom-type, thanks.

**Comment by lily-lee** [comment]
> please see https://github.com/swaggo/swag#use-swaggertype-tag-to-supported-custom-type, thanks.

Thanks.
