### ISSUE TITLE
Nested Struct (Promoted fields) aren't showing properly in the documentation.

### ISSUE THREAD

**Issue by jac1013** [swaggo/swag#376]
**Describe the bug**
Nested Struct (Promoted fields) don't generate correct documentation.

**To Reproduce**
1. Create a nested struct with Promoted fields:
```go
package rest_login
type Response struct {
	rest.ResponseWrapper
        Result Result `json:"result"`
}

type Result struct {
	login.Response
}

// rest.ResponseWrapper
type ResponseWrapper struct {
	Status   string      `json:"status"`
	Code     int         `json:"code"`
	Messages []string    `json:"messages"`
	Result   interface{} `json:"result"`
}
```

**Expected behavior**
It should generate the whole JSON when using `@Success 200 {object} rest_login.Response`

**Screenshots**
This is what it's generating
![image](https://user-images.githubusercontent.com/5025920/55996063-f30da000-5c7b-11e9-8596-a45c933b8af4.png)

**Your swag version**
e.g. 1.5.0

**Your go version**
e.g. 1.11.5

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: Chrome
 - Version: 73.0.3683.103

**Comment by LuGuoHuas** [comment]
I have the same problem. Have any solution?


Your swag version
e.g. 1.5.0

Your go version
e.g. 1.12.3

Desktop (please complete the following information):

OS: Windows10
Browser: Chrome
Version:  71.0.3578.98

**Comment by jac1013** [comment]
Hey @LuGuoHuas my solution was to use a second struct for the documentation. For example

```go
type A struct {
    B
    C
}
```

Then for Swagger documentation I'd create a new struct that matches `A` but without nesting

```go
type AForSwagger struct {
    AttributeInB string
    AnotherAttributeInB string
    ...
}
```

I wanted to use nesting because for my use case it was leading to better code in general, I preferred to have structs "duplicated" for the sake of swagger documentation.

**Comment by LuGuoHuas** [comment]
Thank you, this is also a way.

**Comment by easonlin404** [comment]
@jac1013 fixed by #463 ,please try the latest version against master. Reopen it if still have any questions.

**Comment by jac1013** [comment]
@easonlin404 I'll wait for next release, much appreciate!

**Comment by jac1013** [comment]
Hi @easonlin404 first of all, thanks for delivering a solution for this.

Now, I'm not seeing the expected behavior tho, here's what I'm experiencing:

Struct:

```Go
type Response struct {
	rest.ResponseWrapper
}
```

Swag comment:
```Go
// @Success 201 {object} signup.Response
```

Result:

![image](https://user-images.githubusercontent.com/5025920/67724208-4d6a1600-f9ac-11e9-9a92-25e608cca0b3.png)

I'm doing exactly what #463 it's emulating in the test :man_shrugging: maybe we could wait for someone else to test it, for now, I'll keep the TODOs in my code to fix this whenever it's working for me.

**Comment by ubogdan** [comment]
@jac1013 please use the latest version (if you really want to see it working) or just wait until next release. 
If you do that and encounter any issues, please feel free to open a new issue.(this one is closed)

**Comment by jac1013** [comment]
I'll try again later, I'm sure I was using the latest version in which the fix is present. I'll create a new ticket in case is not working for me. Thanks!
