### ISSUE TITLE
Generated docs.go should load data from swagger.json

### ISSUE THREAD

**Issue by taynguyen** [swaggo/swag#378]
**Is your feature request related to a problem? Please describe.**
I want to use swaggo to host my custom API docs, (from protocol.swagger.json generated by `protoc`), but it was not possible due to docs.go using hard-code value with the content is exactly the same with swagger.json. So I cannot replace swagger.json by my protocol.swagger.json.

Should we support a more flexible way to make possible of using a custom swagger.json file. 

**Describe the solution you'd like**
I think in docs.go, we should load data from swagger.json instead of hard-code the content. That would be more flexible to custom.

**Comment by ubogdan** [comment]
The docs.go is used to embed the documentation in the final binary. This is very useful when ever you are going to deploy a micro service because it  don't force you to carry allot of files with you.

On the other hand i don't see any benefit of using swagger if the documentation is generated from outside.

PS can accomplish this by creating a package like:
```
package mydoc

import (
	"io/ioutil"
	"github.com/swaggo/swag"
)

type s struct{}

func (s *s) ReadDoc() string {
    doc,err := ioutil.ReadAll("protocol.swagger.json")
	if err != nil {
		panic("Cannot load protocol.swagger.json")
	}
	return string(doc)
}
func init() {
	swag.Register(swag.Name, &s{})
}
```

**Comment by easonlin404** [comment]
@ubogdan ping. I have sent email to you via github, did u have receive it? If not, please told me email I would like discuss with you.

**Comment by ubogdan** [comment]
@easonlin404  is the same as yours  githubuser@gmail.com . Please check your inbox because you have another email from me.

**Comment by taynguyen** [comment]
@ubogdan  Thanks for your reply. I already accomplished with the familiar approach.
