### ISSUE TITLE
remove backticks from struct field's comment

### ISSUE THREAD

**Issue by sepehrmm** [swaggo/swag#381]
**Describe the bug**
If the comment of a struct's field has backticks ("`") it will end up in final doc which will cause compile error for the main program.

**To Reproduce**
Have a simple struct with backtick in a field's comment:

``type Sample struct {``
``// this is `name` ``
``	Name int `json:"name"` ``
`}`

and reference it: 
`// @Success 200 {object} model. Sample comment`
> $ swag init -g main.go
$ go run main.go
docs/docs.go:89:48: syntax error: unexpected is after top level declaration
docs/docs.go:89:56: newline in string
docs/docs.go:99:2: string not terminated

**Expected behavior**
No backtick in the generated doc since it's assigned as raw strings to `doc` variable.

**Your swag version**
v1.5.0

**Your go version**
go1.12.3

**Desktop (please complete the following information):**
 - OS: Mac OSX

**Comment by ubogdan** [comment]
Added a PR for this issue.

**Comment by easonlin404** [comment]
fixed by #442
