### ISSUE TITLE
type embeded support

### ISSUE THREAD

**Issue by kshamiev** [swaggo/swag#387]
**Is your feature request related to a problem? Please describe.**
swag init
...
2019/05/01 19:40:40 Generating model.User
2019/05/01 19:40:40 Field type of '*ast.SelectorExpr' is unsupported. Skipping
...

**Describe the solution you'd like**
feature support embeded field structure

**Additional context**

type User struct {
	gorm.Model
	UserName       string        `json:"username" valid:"required"`
	FullName       string        `json:"fullname" valid:"required"`
        ....
}

**Comment by ubogdan** [comment]
Duplicated. See #376
