### ISSUE TITLE
Duration is not supported

### ISSUE THREAD

**Issue by kshamiev** [swaggo/swag#388]
**Describe the bug**
swag init
....
Duration is not supported. but it will be set with string temporary. Please report any problems.
...

**Expected behavior**
type integer

**Screenshots**

type User struct {
        ....
	SessionTimeout time.Duration `json:"sess_timeout"`
        .....
}

**Your swag version**
last

**Your go version**
1.12.1

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Browser: FF

**Comment by ubogdan** [comment]
You're right . time.Duration is not declared as Go primitive in the code.

As a workaround you can use 
> type User struct {
> ....
> SessionTimeout int64 json:"sess_timeout"
> .....
> }

in your definition and just cast it to time.Duration when ever you need it.

**Comment by kshamiev** [comment]
плохое решение.
подгонять код программы под документацию

**Comment by kshamiev** [comment]
bad decision.
customize program code for documentation

**Comment by ubogdan** [comment]
Next time you can read the documentation and learn how to use it.
```
type  User struct {
	SessionTimeout time.Duration `json:"sess_timeout" swaggertype:"primitive,integer"`
}
```
Produce 
```
"definitions": {
        "main.User": {
            "type": "object",
            "properties": {
                "sess_timeout": {
                    "type": "integer"
                }
            }
        }
    }
```
