### ISSUE TITLE
External objects don't work for @Success {object}?

### ISSUE THREAD

**Issue by lsattem** [swaggo/swag#391]
**Describe the bug**
Added `//Success 200 {object} calendar.Event` to an endpoint.
The calendar.Event object exists in the "google.golang.org/api/calendar/v3" package.
I get the error `can not parse response comment "200 {object} calendar.Event "event was updated""`

**To Reproduce**
1: Create an endpoint with swagger doc. 
2: Set return type for success to "calendar.Event" from "google.golang.org/api/calendar/v3".  
2: Run swagger generation

**Expected behavior**
I expect no error to be thrown, and the calendar.Event object to be described in the swagger.json file.

**Your swag version**
v1.5.0

**Your go version**
v1.12.2

**Desktop (please complete the following information):**
 - OS: ubuntu 18.10
 - Browser: N/A
 - Version: N/A

**Comment by Nerzal** [comment]
I also need this feature.
Any hint's on how to tell the ast to parse external packages?

**Comment by ubogdan** [comment]
have you tried 

```
import (
   calendar "google.golang.org/api/calendar/v3"
)

//Success 200 {object} calendar.Event
func handler() {

}
```

**Comment by zimpy** [comment]
Don't forget to do use `--parseDependency` when you do swag init. And also `--parseVendor` if you use a vendor folder
