### ISSUE TITLE
Cant locate my gin route handlers

### ISSUE THREAD

**Issue by Herocod3r** [swaggo/swag#392]
**Describe the bug**
The library cant locate my handler functions....my handler functions are not called directly from the main function go file

**To Reproduce**
1. Create functions in another directory and observe
**Expected behavior**
The search for functions/comments, should be somewhat recursive and span all directories and sub directories in the project 

**Desktop (please complete the following information):**
 - OS: macos mohave
 - Browser: chrome

**Comment by easonlin404** [comment]
Please use the latest swag that will found go module dependencies.

**Comment by easonlin404** [comment]
Please reopen it if still have any problems.
