### ISSUE TITLE
Support for global response model

### ISSUE THREAD

**Issue by easyforgood** [swaggo/swag#395]
**Is your feature request related to a problem? Please describe.**
Here's a global common response model in our API:

``` json
{
	"code": 1000,
	"message": "success",
	"data":{
               
	}
}
```
`data` is defined by different value object model.

If I want to use annotations to gen the swagger docs, I think here's the only way now:

```go
// @Success 200 {object} model.AccountApiResponse
// @Router /accounts/{id} [get]

...

// @Success 200 {object} model.UserApiResponse
// @Router /users/{id} [get]

...

type AccountApiResponse struct {
	Code int
	Message string
	Data Account
} 

type UserApiResponse struct {
	Code int
	Message string
	Data User
} 
```

It's not an elegant way, is it ?  

many duplicate codes here and changing the common response model is a hard thing.

**Describe the solution you'd like**

First, I'd like to write the **struct** like this way:

```go
type ApiResponse struct {
	Code int
	Message string
	Data interface{}
} 

type User struct {
  ....
}

type Account struct {
  ....
}
```

Maybe the annotations will be:

```go
...
// @Success 200 {object:model.ApiResponse} {.Data} model.User
// @Router /users/{id} [get]
...
// @Success 200 {object:model.ApiResponse} {.Data} model.Account
// @Router /accounts/{id} [get]
```

**Describe alternatives you've considered**

Empty

**Additional context**
Empty

**Comment by lyfunny** [comment]
this is also my question

**Comment by moneyzmey** [comment]
+ my question

**Comment by ubogdan** [comment]
You may need to model your data accordingly 

```
type Error struct {
	Code int
	Message string
} 


type User struct {
  ....
}

type Account struct {
  ....
}

type UserResponse struct {
   Data User 
   Error
}

type AccountResponse struct {
   Data Account 
   Error
}
```
