### ISSUE TITLE
Unnecessary type field on response objects

### ISSUE THREAD

**Issue by glcohen** [swaggo/swag#397]
**Describe the bug**
The Swagger editor yells at me that `"type": "object"` exists in error for the schema object of a response with a `"$ref"`. When a ref exists, the type should be excluded.

**To Reproduce**
See below.

**Expected behavior**
A valid swagger 2.0 output.

**Screenshots**
This is with the generation comment
```
// @Failure 422 {object} rest.HttpError
```
https://imgur.com/RfMMVGQ

**Your swag version**
1.5.0

**Your go version**
1.12.4

**Desktop (please complete the following information)**
- Using [editor.swagger.io](editor.swagger.io)

**Comment by glcohen** [comment]
Note, the example 
https://github.com/swaggo/swag/blob/fbdf74d059b731dc3dd201b57aae23bb61f600b1/example/celler/docs/swagger/swagger.json

fails the same validation in the swagger editor

**Comment by ubogdan** [comment]
Looks like a bug to me . @easonlin404  see [ref.doc](https://swagger.io/docs/specification/using-ref/). 
I think i can do a PR for this .

**Comment by easonlin404** [comment]
fixed by #459
