### ISSUE TITLE
Decrecated methods

### ISSUE THREAD

**Issue by monstarnn** [swaggo/swag#404]
**Is your feature request related to a problem? Please describe.**
Is it available to mark method as deprecated, like this:

<img width="901" alt="Swagger_UI" src="https://user-images.githubusercontent.com/17584655/58758629-864dae00-8526-11e9-8426-c6d16532296f.png">

It can be described with tag `Deprecated`:

```
// @Summary Finds Pets by tags
// @Router ​/pet​/findByTags [get]
// @Deprecated
```

**Comment by easonlin404** [comment]
fix via #410
