### ISSUE TITLE
AuthInfo: to be able to change TokenUrl and OAuth2 type at runtime

### ISSUE THREAD

**Issue by jurabek** [swaggo/swag#420]
Currently defining authentication only possible from comment 
```
// @securitydefinitions.oauth2.application OAuth
// @tokenUrl http://localhost:5000/connect/token
```
when you deploy to prod you should change the code, 

due to this, we should add `AuthInfo` type same as `swaggerInfo` and must be able to override information at the runtime

**Comment by kyroy** [comment]
We have the same problem, during compile time we cannot know the url

**Comment by Jurabek** [comment]
Hi, @easonlin404 I want to fix this issue, I don't know where to start, could you please give me some advice?

**Comment by kyroy** [comment]
A workaround I use:

```go
// @tokenUrl [[.TokenUrl]]

func main() {
	docs.Init(viper.GetString("token.url"))
	...
}
```

`docs/fix.go`:
```go
package docs

import "strings"

func Init(tokenURL string) {
	doc = strings.ReplaceAll(doc, "[[.TokenUrl]]", tokenURL)
}

```

**Comment by Jurabek** [comment]
Hi, @kyroy did you change [[.TokenUrl]] template in swagger.yml and swagger.json too?

**Comment by kyroy** [comment]
Hi @Jurabek, I do not use these files so I am okay. I am not sure where to start if you also want to change the http handler that serves these files.

**Comment by ubogdan** [comment]
Closing: not related to swag. Should be fixed in HTTP hander (echo-swagger, http-swagger ...)
