### ISSUE TITLE
Incorrectly parsing go module dependencies

### ISSUE THREAD

**Issue by bruceadowns** [swaggo/swag#421]
**Describe the bug**
The latest code is parsing all go module dependencies. (aka vendor deps)

**To Reproduce**
1. Run swag init on project using go 1.11 modules.

**Expected behavior**
The swagger document should include only annotations from the immediate project. Or a command line option should be available to do so.

**Screenshots**
NA

**Your swag version**
The latest on master as of this writing.

**Your go version**
e.g. 1.12.6

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
The amount of time to generate the swagger doc has also increased dramatically. It appears to be related to recursively walking and parsing the dependency tree via https://github.com/KyleBanks/depth.

**Comment by easonlin404** [comment]
yes, swag is parsing go module dependencies via [depth](https://github.com/KyleBanks/depth)(Thanks for this project), and only found the annotations for swagger usage. So what's you `the immediate project` mean? would you describe in more details?

**Comment by bruceadowns** [comment]
I would like the option to explicitly include or exclude third party dependencies from my swagger document. Behavior similar to the --parseVendor argument.

**Comment by easonlin404** [comment]
fixes via #426. add new flag `parseDependency` to determine whether should be parse outside dependencies, disable by default.
