### ISSUE TITLE
form is not supported paramType

### ISSUE THREAD

**Issue by Cloudzp** [swaggo/swag#422]
**Describe the bug**
use command ` swag.exe init --parseVendor=true` when pkg "github.com/swaggo/swag" in my vendor, i get an error :" ParseComment error in file vendor\github.com\swaggo\swag\operation.go :form is not supported paramType "

**Expected behavior**
get a success result, with `--parseVendor=true`

**Screenshots**
![image](https://user-images.githubusercontent.com/25190767/60312275-5494ff00-998d-11e9-8cff-37aba3a96e9a.png)

**Your swag version**
$ swag.exe -v
swag.exe version v1.5.1

**Your go version**
$ go version
go version go1.11 windows/amd64

**Comment by easonlin404** [comment]
fixes via #423

**Comment by ismdeep** [comment]
@easonlin404 this bug remained at v1.8.3
