### ISSUE TITLE
Swag init including example files

### ISSUE THREAD

**Issue by das-solo** [swaggo/swag#429]
**Describe the bug**
Example files from gin-swagger are also generated into my Swagger docs after running `swag init`.

**To Reproduce**
1. Run `swag init` with source code annotated and before including the following dependencies:
`import "github.com/swaggo/gin-swagger" // gin-swagger middleware
import "github.com/swaggo/gin-swagger/swaggerFiles" // swagger embed files`
2. Swagger UI shows correct annotated routes
3. Include above mentioned dependencies
4. Run `swag init` again
5.  All of the test data from `github.com\swaggo\swag\example\celler` is included in the Swagger UI

**Expected behavior**
Only my annotated routes should be displayed in the Swagger UI.

**Your swag version**
1.4.1

**Your go version**
1.12.6

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
I am running the `swag init` command from my project root directory. The file that contains my General  API notations is `internal/core/ginServer.go

`swag init` output: 
swag init  -g ginServer.go -d ./internal/core/
2019/07/01 20:57:47 Generate swagger docs....
2019/07/01 20:57:47 Generate general API Info
2019/07/01 20:57:52 Generating api.Bar
2019/07/01 20:57:52 Generating api.BarMap
2019/07/01 20:57:52 Generating api.Foo
2019/07/01 20:57:52 Generating api.FooBar
2019/07/01 20:57:52 Generating api.FooBarPointer
2019/07/01 20:57:52 Generating api.SwagReturn
2019/07/01 20:57:52 Generating controller.Message
2019/07/01 20:57:52 Generating data.Foo
2019/07/01 20:57:52 Generating data.TimeContainer
2019/07/01 20:57:52 Generating httputil.HTTPError
2019/07/01 20:57:52 Generating model.Account
2019/07/01 20:57:52 Generating model.AddAccount
2019/07/01 20:57:52 Generating model.Admin
2019/07/01 20:57:52 Generating model.Bottle
2019/07/01 20:57:52 Skipping 'model.Account', already parsed.
2019/07/01 20:57:52 Generating model.UpdateAccount
2019/07/01 20:57:52 Generating web.APIError
2019/07/01 20:57:52 Generating web.AnonymousStructArray
2019/07/01 20:57:52 Generating web.CrossAlias
2019/07/01 20:57:52 Generating cross.Cross
2019/07/01 20:57:52 Generating web.IndirectRecursiveTest
2019/07/01 20:57:52 Generating web.Tag
2019/07/01 20:57:52 Generating web.Pet
2019/07/01 20:57:52 Skipping 'web.Tag', recursion detected.
2019/07/01 20:57:52 Generating web.Pet2
2019/07/01 20:57:52 Skipping 'web.Pet2', already parsed.
2019/07/01 20:57:52 Skipping 'web.Pet', already parsed.
2019/07/01 20:57:52 Skipping 'web.Pet2', already parsed.
2019/07/01 20:57:52 Generating web.Pet5a
2019/07/01 20:57:52 Generating web.Pet5b
2019/07/01 20:57:52 Generating web.Pet5c
2019/07/01 20:57:52 Generating web.Post
2019/07/01 20:57:52 Generating web.RevValue
2019/07/01 20:57:52 Generating web.Tags
2019/07/01 20:57:52 create docs.go at  docs/docs.go
2019/07/01 20:57:52 create swagger.json at  docs/swagger.json
2019/07/01 20:57:52 create swagger.yaml at  docs/swagger.yaml

C:.
├───.vscode
├───api
├───cmd
│   └───prodApi
│       └───configs
├───docs
├───init
├───internal
│   ├───controllers
│   ├───core
│   ├───models
│   └───utils
└───services

**Comment by easonlin404** [comment]
The issue have fixes after merged https://github.com/swaggo/swag/pull/425. And now you can execute the following to specify paring outside dependencies, disabled by default.
`swag init `--parseDependency=true`

**Comment by das-solo** [comment]
@easonlin404 Thanks for the quick reply! I updated my version to v1.6.0 and it is working now.

**Comment by vkakde-discovery** [comment]
> The issue have fixes after merged #425. And now you can execute the following to specify paring outside dependencies, disabled by default. `swag init `--parseDependency=true`

Took a few hours to figure this out, thanks so much. The error message "recursion detected" was not too helpful IMO. It could be helpful for `parseDependency` to be enabled by default? Seems to me limiting depth could be a less common use case, for which a user could look up docs.
