### ISSUE TITLE
Swag ignoring XMLName field in struct

### ISSUE THREAD

**Issue by jetuuuu** [swaggo/swag#431]
**Describe the bug**
Golang has [this rule](https://golang.org/pkg/encoding/xml/#Unmarshal). But swag ignores it.

**To Reproduce**
Define a struct like this: 
```
type Test struct {
    XMLName xml.Name `xml:"data"`
    Field1 string `xml:"field_1"
}
```
**Expected behavior**
swagger.json should contains in the block 'definitions' this code around necessary model: 
```
"xml": {
    "name": "data"
},
```

**Your swag version**
e.g. 1.5.1

**Your go version**
e.g. 1.12.5

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.5

**Additional context**
Swagger docs: [https://swagger.io/docs/specification/data-models/representing-xml/](https://swagger.io/docs/specification/data-models/representing-xml/) 'Change Element Names'

**Comment by ubogdan** [comment]
As i responded in #427 Documentation is generated using Struct field name when json tags are missing.
As a workaround you should add `json:"-"` to xml.Name tag if you want to hide it in documentation.
