### ISSUE TITLE
Ability to set "schemes" programatically

### ISSUE THREAD

**Issue by dskoda1** [swaggo/swag#433]
**Is your feature request related to a problem? Please describe.**

A service i'm working on requires scheme to be http for local development, and preferably only https once its deployed. If the `schemes` could be controlled programatically, this would be possible!

Currently I can only set schemes to `https http` to make this work; and its a lose lose, because locally, I need to switch it to http to get requests working, and when deployed, http is still an option even though I don't want it to be one.

**Describe the solution you'd like**

Add an option to the `SwaggerInfo` struct created in #220 to set the scheme.

**Describe alternatives you've considered**

Open to other options people might think of.

**Comment by dskoda1** [comment]
I'm happy to take a stab at this by the way!

**Comment by easonlin404** [comment]
PR is welcome 👍

**Comment by dskoda1** [comment]
So it looks like all the other configurations which can be set programmatically are being set in a template, within a template - [gen.go](https://github.com/swaggo/swag/blob/master/gen/gen.go#L139-L145). The intermediate template variables are being set in [the parser](https://github.com/swaggo/swag/blob/master/parser.go#L189-L194). These are being set on the [SwaggerProps](https://github.com/go-openapi/spec/blob/9d9763c0ce87242cb4611b52b8601987f01eb4ed/swagger.go#L109-L126) struct of upstream go-openapi/spec repository.

Unfortunately I can't figure out a way to set up a template representation of the array of schemes in the second link (parser) such that it can be stored in the [`SwaggerProps.Schemes`](https://github.com/go-openapi/spec/blob/9d9763c0ce87242cb4611b52b8601987f01eb4ed/swagger.go#L113) property, since its a slice of strings, not just a string like the other variables. 

Definitely a bit of a roadblock, any ideas on how this could be worked around? Possibly an option is to make use of the `VendorExtensible` aspect of the `spec.Swagger` type, however i'm not very familiar with how that works.

**Comment by ubogdan** [comment]
I've just created a PR for this. Good luck!

**Comment by easonlin404** [comment]
fix via #438
