### ISSUE TITLE
support anonymous nested structure slice parsing

### ISSUE THREAD

**Issue by blxzfb307** [swaggo/swag#437]
**Describe the bug**
There is a problem in nested structure slice parsing when generating the document. If I have a nested structure slice in the object, it will fail to parse that field.

**To Reproduce**
Define the structure and use it for response
```go
// @Success 200 {object} Response
type Response struct {
	Code int `json:"code"`
	Data []struct{
		Field1 uint `json:"field1"`
		Field2 string `json:"field2"`
	} `json:"data"`
}
```

**Expected behavior**
It is supposed to parse to an object array with item which is anonymous structure.

**Screenshots**
![image](https://user-images.githubusercontent.com/15121801/60758648-1c0bba00-a04c-11e9-8842-50f2549dc69c.png)

**Your swag version**
e.g. 1.4.0

**Your go version**
e.g. 1.12.6

**Desktop (please complete the following information):**
 - OS: windows 10 1903 
 - Browser: chrome
 - Version: 75

**Additional context**
By the way, what is the best practice for a HTTP response while using swag?
I usually define an anonymous structures for response like which showed below, but it seem I must name the structure for generating document.

```go
response := struct {
	Code int `json:"code"`
	Data []struct{
		Field1 uint `json:"field1"`
		Field2 string `json:"field2"`
	}
}{}
return c.JSON(200, response)
```

**Comment by easonlin404** [comment]
@blxzfb307 fix by #462 please use the latest swag against master and open it if you still have any problems.
