### ISSUE TITLE
go get fails with error

### ISSUE THREAD

**Issue by ArthurClemens** [swaggo/swag#444]
**Describe the bug**

Installing swag recursively results in an install error.

**To Reproduce**

```
go get -u github.com/swaggo/swag/...
```

Results in:

```
# github.com/swaggo/swag/example/basic/api
example/basic/api/api.go:21:4: no new variables on left side of :=
```

**Your swag version**
e.g. 1.6.1

**Your go version**
e.g. 1.11.5

**Comment by benjaminkomen** [comment]
Thanks for fixing this so quickly @easonlin404 ! :)
