### ISSUE TITLE
How to declare example for string param?

### ISSUE THREAD

**Issue by henrahmagix** [swaggo/swag#445]
**Is your feature request related to a problem? Please describe.**
I have a required string parameter, but I don't know how to add an example value for it in declarative comments:
```
// @Router /hello/{name} [get]
// @Param name path string true "The name to say hello to"
```
produces
```yaml
/hello/{name}:
  get:
    parameters:
    - description: The name to say hello to
      in: path
      name: name
      required: true
      type: string
```

**Describe the solution you'd like**
Perhaps an attribute at the end?
```
// @Param name path string true "The name to say hello to" example(Henry)
```

**Describe alternatives you've considered**
An example declaration tied to a param name:
```
// @Param name path string true "The name to say hello to"
// @Example name "Henry"
```

**Additional context**
I'm generating the definitions with `github.com/swaggo/swag/cmd/swag v1.6.1` using `swag init`, and https://github.com/apiaryio/dredd to test the definitions against the real thing. Dredd requires an example value (though I may be using Dredd wrong and instead should use its hooks – but I really like the idea of everything coming from swag declarative comments).

If I use `default(Henry)` then Dredd works but it prints a warning. Ideally I'd like to be able to set example definitions via comments.
>warn: API description URI template expansion warning in /api/swagger.yaml (Hello Test > /hello/{name} > Says hello to name with title > 200): Required URI parameter 'name' has a default value.
>Default value for a required parameter doesn't make sense from API description perspective. Use example value instead.

**Comment by henrahmagix** [comment]
Turns out Dredd uses `x-example:` instead of `example:` in the `parameters` definition.

Is it possible to pass custom key/values to the parameter definition in declarative comments? I'd like to generate from the comments but that would override any custom additions to the yaml file like `x-example: Henry`

**Comment by ubogdan** [comment]
@easonlin404  i think the best way is to add another  atribute named "extensions" and we whould be able to define what ever we need.
Example
```
// @Param string query string false "string valid" minlength(5) maxlength(10) extensions:(x-nullable,x-abc=def)
```
Note this will work only for primitives.

**Comment by easonlin404** [comment]
I agree. Only thing I concerns is swag already have `example` tag for structs, but for parameters with query, path,  we have to to use a different declared way to use that would get little bit confused.

**Comment by ubogdan** [comment]
any suggestions ?

**Comment by arturovm** [comment]
Hello! At [Credijusto](https://github.com/credijusto) we're using swag to generate our API specs, and we need this feature precisely. Would it be alright for me to adopt this issue? How can we reach consensus about the best way to go about implementing this?

Cheers!

**Comment by mullerch** [comment]
It would also be great to have a way to define the example for the response body through @Success.

**Comment by arvenil** [comment]
What annoys me is that generated swagger documentation can't be tried out because there is no way to provide example for param. What worked for me is `default(1234)` but then this generates "Default value: 1234" text which is misleading. From UI perspective it looks pretty straightforward to have `example(1234)` but that doesn't work.

**Comment by mcauto** [comment]
It's works.

```go
// @Param _ query Query false "comment"
```

```
type Query struct {
  	Page     *int    `query:"page"        example:"1"`
	PageSize *int    `query:"page-size"   example:"5"`
}
```

**Comment by ubogdan** [comment]
Default values for param are supported now. see example [unit test](https://github.com/swaggo/swag/blob/0bbefcf634be220bc0736de451c8b04d9e23063a/operation_test.go#L1088).

// @Param string query string false "string valid" default(test)

Also this is documented in [README.md](https://github.com/swaggo/swag#attribute).

**Comment by jtavernier** [comment]
Would be great to add the same feature but to set the example
//@param string query string false "string valid" example(test)

**Comment by ubogdan** [comment]
@jtavernier can you please open an issue about this.

**Comment by sjdhanasekaran** [comment]
> It's works.
> 
> ```go
> // @Param _ query Query false "comment"
> ```
> 
> ```go
> type Query struct {
>   	Page     *int    `query:"page"        example:"1"`
> 	PageSize *int    `query:"page-size"   example:"5"`
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/15080806/130572597-955d36b0-67a6-40e8-8704-843e676d62cd.png)
> 
> If you want to change params key then add json tags.
> 
> ```go
> type Query struct {
>   	Page     *int    `query:"page"        example:"1"`
> 	PageSize *int    `query:"page-size"   example:"5"  json:"page-size"`
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/15080806/130573001-cda52c2d-dddf-4635-9d11-70c76907b4b2.png)
> 
> If you want to set default values then add default tags.
> 
> ```go
> type Query struct {
>   	Page     *int    `query:"page"        example:"1"  default:"1"`
> 	PageSize *int    `query:"page-size"   example:"5"  json:"page-size" default:"5"`
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/15080806/130573708-525faed5-58d3-4b73-8fbd-dc2d917cdaf6.png)

@mcauto How can we provide description for the same. 
Like i need 
some thing like :
> type Query struct {
>   	Page     *int    `query:"page"        example:"1"  default:"1" description:"Enter page"`
> 	PageSize *int    `query:"page-size"   example:"5"  json:"page-size" default:"5" description:"Enter Size"`
> }
