### ISSUE TITLE
can't set schemes in annotation anymore

### ISSUE THREAD

**Issue by joshk0** [swaggo/swag#449]
**Describe the bug**

After 1.6.2 release, I can no longer use a `// @schemes https` annotation to set the `schemes` element in the resulting swagger.

I think this is because of [this line of code](https://github.com/swaggo/swag/pull/438/files#diff-f6323525ef3e0adf0d65af09a9aede9aR72) which erases `swagger.Schemes` no matter what it was set to previously.

**To Reproduce**
1. Use a `// @schemes https` annotation
2. `swag init`
3. `docs/swagger.json` will have no `schemes` field

**Expected behavior**
the `schemes` field should be settable at runtime, however, it should not impact what shows up in the yaml and json files.

**Your swag version**
1.6.2

**Your go version**
1.12.5

**Desktop (please complete the following information):**
 - OS: Mac

**Comment by ubogdan** [comment]
I will fix this by a PR in a few days.

**Comment by easonlin404** [comment]
@joshk0 please use `go get -u github.com/swaggo/swag/cmd/swag@master` and try again.
