### ISSUE TITLE
Implementation for standard Library.

### ISSUE THREAD

**Issue by LordRahl90** [swaggo/swag#45]
Nice job thus far, but you did not include any how to for the standard library users.

**Comment by pei0804** [comment]
https://github.com/swaggo/http-swagger
We can use!

**Comment by easonlin404** [comment]
🎉 🎉 🎉 🎉 🎉 🎉

**Comment by easonlin404** [comment]
@LordRahl90 please reopen it if you have any questions for the standard library usage.
