### ISSUE TITLE
How to add array param?

### ISSUE THREAD

**Issue by ZR233** [swaggo/swag#455]
How to write like this, thanks!
>       
      tags:
      - "pet"
      summary: "Finds Pets by status"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "findPetsByStatus"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "status"
        in: "query"
        description: "Status values that need to be considered for filter"
        required: true
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"

**Comment by ubogdan** [comment]
This is supported now. Please test and open an issue if is the case.
Example:
```
// @Param status query string true "Payload"
```
