### ISSUE TITLE
multiple methods

### ISSUE THREAD

**Issue by pjebs** [swaggo/swag#460]
There seems to be no way to specify multiple HTTP methods for a given route. ie. a given route supports GET & POST.

**Comment by ubogdan** [comment]
Yes, it's true, but Can you do that in swagger editor ?

**Comment by pjebs** [comment]
yes its possible

**Comment by ubogdan** [comment]
ok then, why don't you do a PR for this.

**Comment by pjebs** [comment]
can you show approx area of code where to make the change?

**Comment by ubogdan** [comment]
You can start from here:
https://github.com/swaggo/swag/blob/bd1235d8e7291c9914afe94717e0c3d2972f45bc/operation.go#L106-L109

Please note you will need to write code testing if you want your PR to merged into master.

**Comment by ubogdan** [comment]
If you decide to go with a pr , please mention this issue id.
Thanks.

**Comment by idefixcert** [comment]
> yes its possible

How is that possible?
