### ISSUE TITLE
docs.go not support markdown

### ISSUE THREAD

**Issue by lyfunny** [swaggo/swag#465]
when markdown has follow text,the  \`\`\` confilct with docs string \`\`\`
{
    "code":0,
    "data":interface{},
    "msg":"success"
}
```

**Comment by lyfunny** [comment]
follow 
```

**Comment by ubogdan** [comment]
We have bug report and feature request templates. None of them where used.
Good luck.

**Comment by ubogdan** [comment]
Comment ticks have been fixed #466 so the docs.go get generated well . Meanwhile i've started making some tests with markdown and looks very unfinished to me.
