### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by pjebs** [swaggo/swag#473]
The example in the readme doesn't explain well how to apply markdown.
It appears as if to use this feature, for a API operation description, you need to have an external *md file.

Is there a way to use markdown directly from Go code annotations?

**Comment by ubogdan** [comment]
duplicate #412

**Comment by ubogdan** [comment]
Let's take fhe following annotation.
 
```
// @title Swagger Example API
// @version 1.0
// @description.markdown

// @tag.name admin
// @tag.description.markdown
```
It means it is imperative to create `api.md` and `admin.md` in the same folder where you are going to generate the swagger documenatation.

Then you need to run
> swag init --md .

**Comment by ubogdan** [comment]
Examples [added](https://github.com/swaggo/swag/tree/master/example/markdown) !

**Comment by Osiris1975** [comment]
Tried to follow the examples above, was not able to get it to work. Perhaps a more detailed walkthrough is in order.

**Comment by SOYJUN** [comment]
> 

How about two tag.name ?
