### ISSUE TITLE
github.com/myesui/uuid support

### ISSUE THREAD

**Issue by pjebs** [swaggo/swag#477]
It would be good if the package github.com/myesui/uuid is added.

**Comment by easonlin404** [comment]
would you tell us why need to add this lib you think?

**Comment by pjebs** [comment]
It's a common uuid library. You've added `https://github.com/google/uuid` and `https://github.com/satori/go.uuid`

**Comment by easonlin404** [comment]
Actually `satori/go.uuid` package be used in examples not in swag core packages,  I think we could add `go.mod` in our examples so that would include all of dependencies.

**Comment by pjebs** [comment]
i'm referring to detecting `uuid` data type.

**Comment by ubogdan** [comment]
What exactly do you expect swagger to do with uuid ?

As you can see uuid is a slice of 16 byte.

[github.com/google/uuid](https://github.com/google/uuid/blob/c2e93f3ae59f2904160ceaab466009f965df46d6/uuid.go#L19)
`type UUID [16]byte
`

[github.com/satori/go.uuid/](https://github.com/satori/go.uuid/blob/b2ce2384e17bbe0c6d34077efa39dbab3e09123b/uuid.go#L32-L37)
```
// Size of a UUID in bytes.
const Size = 16

// UUID representation compliant with specification
// described in RFC 4122.
type UUID [Size]byte
```

**Comment by pjebs** [comment]
I don't understand how this package works. I was just hoping that the package will treat `myesui/uuid` in exactly the same way as the other 2 packages for ALL intents and purposes.

So if I have a struct field of type `myesui/uuid`, for example, then the package will recognise it as type "uuid" instead of string for example.

**Comment by ubogdan** [comment]
As you can see it's another 16 byte slice too.
[github.com/myesui/uuid](https://github.com/myesui/uuid/blob/835a10bbd6bce40820349a68b1368a62c3c5617c/types.go#L36)
```
const (
	length       = 16
)
type UUID [length]byte

```
You just need to declare it as this one ....
https://github.com/swaggo/swag/blob/77b90205c6f8e3daada98d3a4612f16f7facf865/example/celler/model/account.go#L10-L15
