### ISSUE TITLE
Use template variables like `Schemes` and `Host` in the API Description

### ISSUE THREAD

**Issue by lonnblad** [swaggo/swag#478]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use template variables like `Schemes` and `Host` in my API Description like this: `// @Description More information can be found here: [Service Documentation]({{index .Schemes 0}}://{{.Host}}/docs/service).` This is because we host other information like flow diagrams, code examples, etc. on the same server as the Open API spec.

**Describe the solution you'd like**
Parse and Execute the SwaggerInfo.Description as a template like the generated doc.

**Comment by ubogdan** [comment]
According to your example please explain what will happen if host and schemes will not be set in comments/annotation (because they are optional). 
Is there any reason this doesn't work for you ?
```
// @Description More information can be found here: [Service Documentation](/docs/service).
```

**Comment by lonnblad** [comment]
true, that should cover my case

**Comment by lonnblad** [comment]
close the issue and revisit if another use-case comes up?

**Comment by ubogdan** [comment]
I think is better to not implement it for the moment. If we will have more requests for this we will take in consideration this feature.
Thanks.
