### ISSUE TITLE
Programmatically defined Multiline API Description breaks the generated JSON

### ISSUE THREAD

**Issue by lonnblad** [swaggo/swag#480]
**Describe the bug**
Programmatically defined Multiline API Description breaks the generated JSON

**To Reproduce**
1. Add 
```
  docs.SwaggerInfo.Description = `
  # Foo
  ## Bar
  `
```
2. Generade API
3. Open the hosted API
4. Click to open the JSON file
5. See the Error: `Error: Parse error on line 5: ...     "description": "`

**Expected behavior**
Valid JSON to be generated when using a Multiline API Description

**Screenshots**
Error:
![image](https://user-images.githubusercontent.com/5733970/62034631-a7f9a780-b1ee-11e9-8b67-0b04102d9884.png)

Expected:
![image](https://user-images.githubusercontent.com/5733970/62034639-ac25c500-b1ee-11e9-9f88-819ee52d33b6.png)

**Your swag version**
master (c19280e76fac72a09e9730a4b3c9ae3e144d9b3a)

**Your go version**
1.12.4

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: chrome
 - Version: 74

**Comment by ubogdan** [comment]
JSON new lines must be replaced with escaped "\n".
```
docs.SwaggerInfo.Description = strings.Replace(`
  # Foo
  ## Bar
  `,"\n","\\n",-1))
```
I have discovered a similar issue with markdown description , but i have no time to fix it right now.
