### ISSUE TITLE
一个结构体  struct 使用了别的 struct，无法识别

### ISSUE THREAD

**Issue by joeluodongjiu** [swaggo/swag#484]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by joeluodongjiu** [comment]
type CommonModel struct {
	ID       string    `gorm:"Column:id;primary_key"  json:"id"`
	CreateAt JsonTime  `gorm:"Column:createAt"  json:"createAt"`
	UpdateAt JsonTime  `gorm:"Column:updateAt"  json:"updateAt"`
	DeleteAt *JsonTime `gorm:"Column:deleteAt" sql:"index" json:"deleteAt"`
}

type RoleMenu struct {
	orm.CommonModel
	RoleID string `gorm:"column:role_id;not null;"` 
	MenuID string `gorm:"column:menu_id;not null;"`
}

swag  result:

{   "role_id": "string",   "menu_id": "string"}
--

**Comment by ubogdan** [comment]
Please be more specific about the issue.

**Comment by wuteng606** [comment]
with an error  

> Field type of '*ast.SelectorExpr' is unsupported. Skipping

**Comment by sdghchj** [comment]
fixed, try "swag init --parseDependency" with the latest master branch
