### ISSUE TITLE
cannot parse source files swag@v1.6.2, expects main.go

### ISSUE THREAD

**Issue by tkivisik** [swaggo/swag#485]
**Describe the bug**
Cannot parse source files when running `swag init` when main.go is not in the base directory. Swag version 1.6.2 fails (1.6.0 and 1.6.1 gave other errors) while 1.5.1 seems to work nicely.

**To Reproduce**
```bash
mkdir -p rebug/server && cd rebug
touch server/main.go
cat > "server/main.go" << EOF
package main

import (
    "fmt"
    "net/http"
    "time"
)

// Greet greets you with the latest timestamp
// @Summary GET greeted
// @Description Endpoint to get greeted
// @Tags greet
// @Failure 400 "wrong data submitted"
// @Router / [Get]
func Greet(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "Hello World! %s", time.Now())
}

func main() {
    http.HandleFunc("/", Greet)
    http.ListenAndServe(":8080", nil)
}
EOF
go mod init
swag init
```

Output
```
2019/08/02 17:22:43 Generate swagger docs....
2019/08/02 17:22:43 Generate general API Info, search dir:./
2019/08/02 17:22:43 cannot parse source files: open /home/user/go/src/github.com/someuser/rebug/main.go: no such file or directory
```

**Expected behavior**
Expected it to produce docs/docs.go, docs/swagger.json, docs/swagger.yaml . It does not.

**Your swag version**
1.6.2

**Your go version**
1.12.6

**Desktop (please complete the following information):**
 - OS: Linux Mint

**Comment by ubogdan** [comment]
There is no go source files in pwd. Try
`swag init -dir server/`

**Comment by tkivisik** [comment]
Thank you @ubogdan for pointing that out. My raised Issue was too simplistic. In reality I do not have my handlers in the main package, but in another one. Therefore, the proposed trick does not work.

Replicate a more realistic scenario with handlers in a separate package:
```
mkdir -p rebug/server rebug/api && cd rebug
cat > "server/main.go" << EOF
package main

import (
	"net/http"

	"github.com/someuser/rebug/api"
)

func main() {
	http.HandleFunc("/", api.Greet)
	http.ListenAndServe(":8080", nil)
}
EOF

cat > api/greet.go << EOF
package api

import (
	"fmt"
	"net/http"
	"time"
)

// Greet greets you with the latest timestamp
// @Summary GET greeted
// @Description Endpoint to get greeted
// @Tags greet
// @Failure 400 "wrong data submitted"
// @Router / [Get]
func Greet(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World! %s", time.Now())
}
EOF

go mod init
swag init // output: cannot parse source files: open /home/user/go/src/github.com/someuser/rebug/main.go: no such file or directory
swag init -dir server/ // output: docs are created but empty
swag init -dir api/ // output: cannot parse source files: open /home/user/go/src/github.com/someuser/rebug/api/main.go: no such file or directory
```

**Comment by ubogdan** [comment]
Looks like nobody is reading the manual .

```
swag  help init
NAME:
   swag init - Create docs.go

USAGE:
   swag init [command options] [arguments...]

OPTIONS:
   --generalInfo value, -g value       Go file path in which 'swagger general API Info' is written (default: "main.go")
   --dir value, -d value               Directory you want to parse (default: "./")
   --propertyStrategy value, -p value  Property Naming Strategy like snakecase,camelcase,pascalcase (default: "camelcase")
   --output value, -o value            Output directory for al the generated files(swagger.json, swagger.yaml and doc.go) (default: "./docs")
   --parseVendor                       Parse go files in 'vendor' folder, disabled by default
   --parseDependency                   Parse go files in outside dependency folder, disabled by default
   --markdownFiles value, --md value   Parse folder containing markdown files to use as description, disabled by default
```
Actualy you need to 

**$ go get -u github.com/swaggo/swag/cmd/swag**

**$ ~/go/bin/swag init -g server/main.go**
```
2019/08/05 11:49:34 Generate swagger docs....
2019/08/05 11:49:34 Generate general API Info, search dir:./
2019/08/05 11:49:34 create docs.go at  docs/docs.go
2019/08/05 11:49:34 create swagger.json at  docs/swagger.json
2019/08/05 11:49:34 create swagger.yaml at  docs/swagger.yaml
```

**$ cat docs/swagger.json** 
```
{
    "swagger": "2.0",
    "info": {
        "contact": {},
        "license": {}
    },
    "paths": {
        "/": {
            "get": {
                "description": "Endpoint to get greeted",
                "tags": [
                    "greet"
                ],
                "summary": "GET greeted",
                "responses": {
                    "400": {
                        "description": "wrong data submitted"
                    }
                }
            }
        }
    }
}
```

**Comment by tkivisik** [comment]
@ubogdan thank you for the solution.
Comments on my experience, which might help to either be more confident about the UX as it is currently, or help to improve it:

- I did read the help of the command, unfortunately they did not resemble to me like something connected to my error message (besides the dir flag).
- As I had been using swag before the 1.6.2, and it worked without any further flags, I was biased towards thinking no flags are necessary to just do what the command was doing before.
- From my previous experience with CL tools, I have often seen that a directory can/needs to be specified, which I did use this time as well with no success.

Thank you for your contribution to the package.

**Comment by ubogdan** [comment]
I have no clue when exactly that flags have been added. For sure they where not in 1.4 (the version i used the most), but i always read the code when i see somersetting is not working properly.
If you have any suggestion about params description that may lead to better understading of the flags, please open a new issue and i will do PR.

**Comment by dwikurniantom** [comment]
At first i think Iam the one who lost here, but after lookup to this old issues, i can speculate that this repositories just lack of documentation. Trying run `swag ini` with options, but non of them parsing my sub directories. That's really suck since i have similar swagger with Laravel lumen and its working perfectly and easy to use

**Comment by ubogdan** [comment]
@dwikurniantom this is ab Open Source project. any contribution is welcome.
