### ISSUE TITLE
Three-dimensional array in body is not spport

### ISSUE THREAD

**Issue by FengchenX** [swaggo/swag#490]
**Describe the bug**
{
   a: [][][]string
}
this struct in body, can not parse.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Your swag version**
e.g. 1.4.1

**Your go version**
e.g. 1.12.0

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by ubogdan** [comment]
Please provide an usages case and we may think about it.
