### ISSUE TITLE
formdata array param did not work

### ISSUE THREAD

**Issue by ZR233** [swaggo/swag#495]
// @Param sendTypes formData int true "Payload"

![QQ截图20190815151205](https://user-images.githubusercontent.com/34859362/63078763-2ab08f80-bf6f-11e9-93cf-30d426cf7796.png)

**Comment by ubogdan** [comment]
Please be more specific if this is a bug or feature.

**Comment by easonlin404** [comment]
please provide a reproduced step for it.
