### ISSUE TITLE
Model incorrectly generated when type is []int

### ISSUE THREAD

**Issue by ShadowStrikerJ** [swaggo/swag#496]
**Describe the bug**
When the model includes a type that is []int, swag does not appear to generate the proper documentation for it.
Ex:
type Account struct {
	ID     int    `json:"id" example:"1"`
	Name   string `json:"name" example:"account name"`
	Groups []int  `json:"groups" example:"[132, 123, 546]"` // The groups in this account
}
This will make swagger generate documentation for model.Account, where it shows ID and Name, but not Groups.

**To Reproduce**
1. Create a model with a field type of []int
2. Create a function to use it
3. Generate with Swag
4. Verify the field with that type does not exist

**Expected behavior**
The generated documentation should allow for types of []int

**Screenshots**
![Screen Shot 2019-08-15 at 8 36 55 AM](https://user-images.githubusercontent.com/17069485/63102292-156c3e80-bf38-11e9-9ab9-c8dd941b7488.png)

**Your swag version**
v1.6.2

**Your go version**
1.12.7 darwin/amd64

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 76.0.3809.100 (Official Build) (64-bit)

**Additional context**
Of note may be that it appears to generate properly if you change the []int to a []string

**Comment by ubogdan** [comment]
i don't think example tag was changed to accept slice . 
I'm wondering how are you going to define a slice of strings since " is allready used as tag value separator.

**Comment by sdghchj** [comment]
your issue has been fixed in the latest master branch, have a try.
`example` should be as follow without spaces
```
type Account struct {
ID int json:"id" example:"1"
Name string json:"name" example:"account name"
Groups []int json:"groups" example:"132,123,546"
}
```

**Comment by easonlin404** [comment]
please reopen it if there are any problems.
