### ISSUE TITLE
HTTP GET with request body

### ISSUE THREAD

**Issue by hu011655** [swaggo/swag#502]
When i send http get with request body in swagger page, it return:

TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.

But my api was no problem with it in fact. I also see in stackoverflow about this problem: 
[https://stackoverflow.com/questions/978061/http-get-with-request-body?noredirect=1&lq=1](url)

Should it be repair? or is there a solution when http get with request body?

**Comment by ubogdan** [comment]
First of all , please read again because it seems  you misunderstood the response from stackoverflow. 
Swagger is only a OpenApi documentation generator (meaning by you are writing the http handler definition and code). This means there is nothing to fix here.

**Comment by hu011655** [comment]
> 
> 
> First of all , please read again because it seems you misunderstood the response from stackoverflow.
> Swagger is only a OpenApi documentation generator (meaning by you are writing the http handler definition and code). This means there is nothing to fix here.

thanks, it seem to be swagger's issues...
