### ISSUE TITLE
Example tag for maps

### ISSUE THREAD

**Issue by hsanchezl** [swaggo/swag#503]
**Describe the bug**
I have this code sample:

```golang
type User struct {
	ID   int    `json:"id" example:"1"`
	Name string `json:"name" example:"UserA"`
}

// Response :
type Response struct {
	Users        map[string]User   `json:"users"`
	Relationship map[string]string `json:"relationship"`
}
```

I need to add an example tag `(example:"")` for two fields `Users` and `Relationship` in the `Response` struct, like I did with the fields `ID` and `Name` in the `User` struct but I have the next problems:

 - In first place swag doesn't recognizes the `map[string]User` even I have the `example:""` tags in the model where the map is pointing.
 - Finally, how can I add the `example:""` tag to a ` map[string]string`

**Expected behavior**
To expect to add the `example:""` tag in my struct definition and get this json by using the `swag init` command:

```json
{
  "users": {
    "userA": {
      "id": 1,
      "name": "UserA",
    },
    "userB": {
      "id": 2,
      "name": "UserB",
    },
  },
  "elationship": {
    "userA": "userB"
  }
}
```

**Swag version**
1.6.1

**Go version**
1.11.0

**Desktop:**
 - OS: Ubuntu 18.04.3 LTS 
 - Browser: Firefox
 - Version: 68.0.2

**Comment by kychandar** [comment]
Hi,
Can anyone share here a example tag for this part of struct
`	Users        map[string]User   `json:"users"`
`
