### ISSUE TITLE
Integrate with generated protobuf struct in param body

### ISSUE THREAD

**Issue by navono** [swaggo/swag#505]
When I use  struct data type within param for request or data for response, everything is fine. But when I change the handl made struct to proto struct(generated by proto compiler) and then `swag init`, it just produce a plain object like this:
```
    "definitions": {
        "handler.SwaggerCreateProjectRequest": {
            "type": "object"
        }
    }
```

all of the proto struct details lost.

I don't know it's posilble to integrate proto struct with swaggo or I do something wrong with it.

**Comment by ubogdan** [comment]
If you look at the code `swag init` scan and parse definitions from all go files except from "vendor" and "internal" folder staring (from current folder, the folder you are invoking swag command) and use them to generate the OpenApi "definitions".
Depending where your handler is , you may need to use "--parseDependency" flag if you need to load them from external package like "github.com/youruser/yourproject" or to invoke swag command from upper directory .
See `swag init --help` for more details.

**Comment by navono** [comment]
I try `swag init` with `--parseDependency`, but it seems not the case that I described in this issue.
I just want to use protobuf generated go file with swag, not external package.

**Comment by ubogdan** [comment]
@navono since you have no clue what is happening can you be nice to share with us the struct definition of `handler.SwaggerCreateProjectRequest` and hopefully we will figure out for you.
As more details you provide will increase the chance to get/find the right answer.

**Comment by navono** [comment]
@ubogdan Thanks for response.
I create a demo from scratch, it works. Maybe I missed something when I first use `swaggo`. here is example [go-pb-swagger](https://github.com/navono/go-pb-swagger.git).
