### ISSUE TITLE
External file markdown format supports for @Descriptions attribute at Controller level

### ISSUE THREAD

**Issue by aladine** [swaggo/swag#506]
**Is your feature request related to a problem? Please describe.**
For each endpoint, we have a long description and it cannot fit to one line. Though we can split to multiple lines, we wish to have markdown description in a separate file for each endpoint in controller

**Describe the solution you'd like**
Have something like @Description.markdown [endpoint name] to indicate which md file to read from

**Describe alternatives you've considered**
N.A

**Additional context**

**Comment by Nerzal** [comment]
Hi, you could also use a markdown file for the description.
