### ISSUE TITLE
Type definition with internal underlying type leads to panic

### ISSUE THREAD

**Issue by greenpart** [swaggo/swag#508]
**Describe the bug**
`swag` panics trying to generate documentation for type defined with internal underlying type (e.g. `sql.NullInt64`). 

```
panic: runtime error: invalid memory address or nil pointer dereference
…
exit status 2
```

**To Reproduce**
1. create file in an empty directory and fill it with:
```
package main

import (
	"database/sql"
)

// @Success 200 {object}  main.Object "Response data"
func main() {
	_ = Object{}
}

type Object struct {
	ID NullableID
}

type NullableID sql.NullInt64
```
2. run `swag init --parseDependency` in this directory
3. See error `panic: runtime error: invalid memory address or nil pointer dereference`

**Expected behavior**
Swagger documentation successfully generated.

**Your swag version**
1.6.2

**Your go version**
1.12.3

**Desktop (please complete the following information):**
 - OS X 10.12.6

**Comment by easonlin404** [comment]
it's should be use [swagger type tag](https://github.com/swaggo/swag#use-swaggertype-tag-to-supported-custom-type) for non supporting type.

**Comment by greenpart** [comment]
Tags are not applicable with type definitions like `type NullableID sql.NullInt64`.
We have some types like that and want to continue with them rather than convert to
```
type NullableID struct {
    sql.NullInt64 `swaggertype:"…"`
}
```
