### ISSUE TITLE
Add net/http WrapHandler

### ISSUE THREAD

**Issue by pei0804** [swaggo/swag#51]
Thank you for a nice OSS.
I want to use net/http.
There are probably many people who think so.

I created WrapHandler for net/http 
https://github.com/pei0804/go-http-swagger

Is it possible to include this in the repository?
For examle custome error. more test cases...
If there is a problem I am motivated to improve.

**Comment by easonlin404** [comment]
Sure! Thanks all for your contribution. 💯 

Please add  it in https://github.com/swaggo/http-swagger repo.

**Comment by pei0804** [comment]
Sorry i miss commit....!
please wait.

**Comment by pei0804** [comment]
I create PR
https://github.com/swaggo/http-swagger/pull/1
