### ISSUE TITLE
There is a problem with array element support in the structure

### ISSUE THREAD

**Issue by singhwang** [swaggo/swag#510]
**Describe the bug**
// ListAccounts godoc
// @Summary List accounts
// @Description get accounts
// @Tags cluster
// @Accept  json
// @Produce  json
// @Param Authorization header string true " "
// @Param url query string true " "
// @Param start query string true " "
// @Param end query string true " "
// @Param step query string false " "
// @Success 200 {object} common. ResponseData

Add this comment to the function, and then there will be an unsupported situation.

**To Reproduce**
First case 

type Response struct {
	Status  int    `json:"status"`
	Message string `json:"message"`
}

type ResponseData struct {
	Data [][]Response `json: "data"`
}
The error is [&{%!s(token.Pos=143) <nil> Response}].

Second case

type ResponseData struct {
	Data []interface{} `json: "data"`
}
The error is [&{%!s(token.Pos=143) %!s(*ast.FieldList=&{152 [] 153}) %!s(bool=false)}].

Third case

type ResponseData struct {
	Data [][]interface{} `json: "data"`
}
The error is [&{%!s(token.Pos=143) <nil> %!s(*ast.InterfaceType=&{145 0xc0003a2270 false})}]

**Your swag version**
e.g. v1.6.2

**Your go version**
e.g. go1.12.1

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all
 - Version: all

**Comment by singhwang** [comment]
If you can solve the above problems, swag will be more perfect in universal support.

**Comment by ubogdan** [comment]
Swagger is OpenApi compliant , not "universal" api. 

In order to be able to generate request and response objects swagger need to have concrete implementations.

**Comment by singhwang** [comment]
> Swagger is OpenApi compliant , not "universal" api.
> 
> In order to be able to generate request and response objects swagger need to have concrete implementations.
> 
> If you think you can implement the universal support please do a PR.

Thanks for your help.

**Comment by sdghchj** [comment]
try new master branch again
