### ISSUE TITLE
Wrong dependencies

### ISSUE THREAD

**Issue by dink10** [swaggo/swag#512]
While go get -u github.com/swaggo/swag/cmd/swag

`github.com/cpuguy83/go-md2man/md2man
../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/md2man.go:11:16: undefined: blackfriday.EXTENSION_NO_INTRA_EMPHASIS
../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/md2man.go:12:16: undefined: blackfriday.EXTENSION_TABLES
../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/md2man.go:13:16: undefined: blackfriday.EXTENSION_FENCED_CODE
../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/md2man.go:14:16: undefined: blackfriday.EXTENSION_AUTOLINK
../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/md2man.go:15:16: undefined: blackfriday.EXTENSION_SPACE_HEADERS
../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/md2man.go:16:16: undefined: blackfriday.EXTENSION_FOOTNOTES
../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/md2man.go:17:16: undefined: blackfriday.EXTENSION_TITLEBLOCK
../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/md2man.go:19:29: too many arguments to conversion to blackfriday.Markdown: blackfriday.Markdown(doc, renderer, extensions)
../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/roff.go:19:9: cannot use &roffRenderer literal (type *roffRenderer) as type blackfriday.Renderer in return argument:
        *roffRenderer does not implement blackfriday.Renderer (missing RenderFooter method)
../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/roff.go:102:11: undefined: blackfriday.LIST_TYPE_ORDERED
../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/roff.go:102:11: too many errors`

But it works without -u
It doesn't mean which go version I have 
`go version go1.13 darwin/amd64`
`go version go1.12.7 darwin/amd64`

**Comment by marcusthorstrom** [comment]
I cannot even use `go get ...` without the `-u` option.

This seems to be because of an update to the depending package [cli](https://github.com/urfave/cli) that have [recently updated their dependency](https://github.com/urfave/cli/commit/249cb3339254361b1a884733a98d4202e2838b9b#diff-2a0cb88ddd9482c046c169b7b242d36cL11) to [md2man](https://github.com/cpuguy83/go-md2man).

**Comment by ubogdan** [comment]
It woks like a charm . 
```
$ go version
go version go1.12.7 linux/amd64
$ go get -u github.com/swaggo/swag/cmd/swag

```
If you look closer to swagger [go.sum](https://github.com/swaggo/swag/blob/master/go.sum) file you will notice there is no direct or indirect dependency to "github.com/cpuguy83". 
I'm guessing is related somehow to your GO enviroment variables ( especialy GOPATH) , but it's a guess...

**Comment by Terminator637** [comment]
Yes, got the same issue.

**Comment by Terminator637** [comment]
Helped this adding to end of go.mod file:
```mod
replace github.com/urfave/cli v1.22.0 => github.com/urfave/cli v1.21.0 
```
Taken from there: https://github.com/aws/aws-lambda-go/issues/231

**Comment by ubogdan** [comment]
This is realy interesting because swag go.mod  require cli 1.20.0
https://github.com/swaggo/swag/blob/d74ed70e44450ffd5ca0016f0e78e2c569abbc45/go.mod#L12

**Comment by easonlin404** [comment]
please use the latest version [v1.6.5](https://github.com/swaggo/swag/releases/tag/v1.6.5) and try again.
