### ISSUE TITLE
Query Params based on user defined struct

### ISSUE THREAD

**Issue by louis77** [swaggo/swag#518]
**Is your feature request related to a problem? Please describe.**
We have many endpoints sharing the same huge set of query parameters. I tried to declare it like this:
// @Param params query model.FilterParams false "..."

However this doesn't work. So we have to copy/paste about 30 lines of params over 15 different endpoints. Is it possible to implement @Param to use a user defined struct?

**Describe the solution you'd like**
// @Param params query model.FilterParams false "..."

**Describe alternatives you've considered**
I see no alternative :-)

**Comment by letsfire** [comment]
I think this is a useful feature

**Comment by sdghchj** [comment]
Feature added, try latest master branch. 
Reopen it if you have any more questions.

**Comment by movpushmov** [comment]
@sdghchj can you provide example? This don't work:

```go
type Params struct {
	test string
	anotherTest int32
}

// ListAccounts godoc
// @Summary      List accounts
// @Description  get accounts
// @Tags         accounts
// @Accept       json
// @Produce      json
// @Param        params  query  Params false "..."
// @Success      200  {array}   Account
// @Router       /accounts [get]
func test() {}
```

**Comment by muya** [comment]
@movpushmov 

Something similar to this is working for me:

```go
// QueryListOptions represents the query parameters for a list of resources.
type QueryListOptions struct {  
   // The page number to return.  
   Page int `json:"page" minimum:"1" validate:"optional" example:"1"`  
   // The number of items to return per page.  
   PageSize int `json:"page_size" minimum:"1" maximum:"20" validate:"optional" example:"10"`   
}

// @Summary     Some Endpoint
// @Produce     json
// @Param       request             query    QueryListOptions false "Query Params"
func someHandler() {

}
```

It has generated this
![screenshot-20220925-142216](https://user-images.githubusercontent.com/1861055/192148595-919218b2-1739-43d5-aac1-d2d6542b207b.png)

**Comment by kahunacohen** [comment]
I don't see this in the docs, unless I'm mistaken. Would you like a PR?
