### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by carsonip** [swaggo/swag#522]
Hello maintainers, thanks for maintaining this great project.

Is it possible to cut a new release soon? It has been a while since the last release (July 2019). And in the past there were new releases every few weeks.

Given this project provides a CLI binary, it is much easier to install by just downloading a binary instead of `go get`, not to mention the fact that `go get` does not support version pinning.

Thanks in advance.

**Comment by easonlin404** [comment]
Thanks your input. Will release soon.

**Comment by easonlin404** [comment]
We release the v2.6.3 new version.

**Comment by carsonip** [comment]
Many thanks! By the way, it is 1.6.3, not 2.6.3.

**Comment by easonlin404** [comment]
@carsonip thanks you point out. It's typo. 👍
