### ISSUE TITLE
Support for deep object serialization in query string

### ISSUE THREAD

**Issue by betabandido** [swaggo/swag#526]
I am using [Gin](https://github.com/gin-gonic/gin) to create an API that has one endpoint accepting a map as a querystring. This is described here:

https://github.com/gin-gonic/gin#map-as-querystring-or-postform-parameters

A map encoded in a query string (named `map`) looks like:

`/endpoint?map[key1]=value1&map[key2]=value2`

This concept seems to match what swagger specification refers to as "deep objects" (see https://swagger.io/docs/specification/describing-parameters/ and https://swagger.io/docs/specification/serialization/).

I believe swaggo does not support this yet. Is that correct? If so, are there any plans to add support for it?

**Comment by ubogdan** [comment]
All the links are for OpenAPI 3.0, swagger is OpenAPI 2.0 compliant.

**Comment by betabandido** [comment]
Indeed. Closing this ticket in favor of https://github.com/swaggo/swag/issues/386
