### ISSUE TITLE
swag init with -g CLI failed with error

### ISSUE THREAD

**Issue by yigere** [swaggo/swag#534]
**Describe the bug**
when i try with:      swag init -g app/galerie.go 

I get:

/Users/guoyf/go/pkg/mod/github.com/gabriel-vasile/mimetype@v0.3.16/mime.go:9:2: could not import github.com/gabriel-vasile/mimetype/internal/matchers (go/build: importGo github.com/gabriel-vasile/mimetype/internal/matchers: exit status 1
error writing go.mod: open /Users/guoyf/go/pkg/mod/github.com/gabriel-vasile/mimetype@v0.3.16/go.mod749512523.tmp: permission denied

)
ParseComment error in file pkg/controller/user.go :can not find type def: "controller.json" error: couldn't load packages due to errors: github.com/gabriel-vasile/mimetype

**Your swag version**
1.6.3

**Your go version**
1.12.0

**Comment by ubogdan** [comment]
@yigere This is not a swagger issue.
Please fix your file permissions in "/Users/guoyf/go" and everything should work as expected.

**Comment by hyacinthus** [comment]
@yigere  I met this issue too. How did you fix it?

https://github.com/golang/go/issues/27455

seems because this issue

**Comment by hyacinthus** [comment]
@ubogdan 
why swag want to change a file in mod cache?

The folder's mask is 400 now, so change the file failed.

**Comment by hyacinthus** [comment]
After use  --parseDependency option, it worked...
What is means to this option?

**Comment by yigere** [comment]
@hyacinthus 
I change the write and read permisson of this folder to fix one problem. /xxxxxxx/gabriel-vasile/mimetype@v0.3.16/go.mod749512523.tmp

**Comment by kolaente** [comment]
I'm also hitting this in 1.6.5

**Comment by kolaente** [comment]
Swaggo should not try to change `go.mod` files in random places.
