### ISSUE TITLE
Hide swagger model at the bottom

### ISSUE THREAD

**Issue by Solutionist** [swaggo/swag#536]
**Is your feature request related to a problem? Please describe.**
Is it possible to hide the model at the bottom of the swagger-ui? In swagger you can hide the model by setting defaultModelsExpandDepth: -1

**Describe the solution you'd like**
An API that allows the user to set whether to hide the model ui at the bottom

**Describe alternatives you've considered**

**Additional context**
<img width="1376" alt="Screen Shot 2562-10-08 at 10 53 06" src="https://user-images.githubusercontent.com/17399678/66366207-de575e00-e9b9-11e9-957f-c1a4b1a4f0a0.png">

**Comment by ubogdan** [comment]
This request is not directly related to swagger. It is more appropriate to [echo-swagger](https://github.com/swaggo/echo-swagger) or [gin-swagger](https://github.com/swaggo/gin-swagger) or what-ever wrapper you are using to render the HTML page.
