### ISSUE TITLE
Format docs.go output with gofmt

### ISSUE THREAD

**Issue by mlimos** [swaggo/swag#537]
When running `swag init` against a codebase and generating the swagger docs and `docs.go` file, `docs.go` does not meet `gofmt` standards. This can be a hindrance if `gofmt` checks are done when building/deploying using pipeline automation.

**Proposed Solution**
Generated `docs.go` is run through `gofmt`

**Comment by ubogdan** [comment]
Are u sure ?https://github.com/swaggo/swag/blob/c9f403a30434dc43903a02f80bcf736f11169a86/gen/gen.go#L211 
Maybe generated source is invalid for some reason
https://github.com/swaggo/swag/blob/c9f403a30434dc43903a02f80bcf736f11169a86/gen/gen.go#L128-L134

**Comment by mlimos** [comment]
true, I saw this code snippet as well. My guess is perhaps discrepancies between `gofmt` and programmatically using `go/format`. I'm going to look into this further.
