### ISSUE TITLE
How to use an external package

### ISSUE THREAD

**Issue by ikerlin** [swaggo/swag#538]
**Describe the bug**
How to use an external package as a response, we used go mod in the project.

**To Reproduce**
```
// @Summary auth
// @Description auth
// @Tags auth
// @Accept x-www-form-urlencoded
// @Produce json
// @Param code formData string true "code"
// @Success 200 {object} bean.Response "success"
// @Failure 400 {object} xxx.com/proto/packageName.StructName "error"
// @Router /authByCode [post]
```

**Expected behavior**
Semantic error at paths./authByCode.post.responses.400.schema.$ref
$refs must reference a valid location in the document

**Your swag version**
1.6.3

**Your go version**
1.13

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
we find this [link](https://github.com/swaggo/swag/tree/master/example/go-module-support), but not what we want.

**Comment by ubogdan** [comment]
Have you tried 
```go

import (
   "xxx.com/proto/packageName"
)


// @Summary auth
// @Description auth
// @Tags auth
// @Accept x-www-form-urlencoded
// @Produce json
// @Param code formData string true "code"
// @Success 200 {object} bean.Response "success"
// @Failure 400 {object} packageName.StructName "error"
// @Router /authByCode [post]
```

**Comment by ikerlin** [comment]
> Have you tried?
> 
> ```go
> import (
>    "xxx.com/proto/packageName"
> )
> 
> 
> // @Summary auth
> // @Description auth
> // @Tags auth
> // @Accept x-www-form-urlencoded
> // @Produce json
> // @Param code formData string true "code"
> // @Success 200 {object} bean.Response "success"
> // @Failure 400 {object} packageName.StructName "error"
> // @Router /authByCode [post]
> ```

oh, it is work. thank you.

**Comment by ikerlin** [comment]
still have a question, how to distinguish the same packageName

```golang
import (
   "xxx.com/proto/packageName"
   "xxx.com/proto_2/packageName"
)
```

**Comment by ubogdan** [comment]
the parser index data types in the form "packageName.structName" so if the struct name is different it should work. otherwise you may get in trouble.

**Comment by ikerlin** [comment]
ok, I know, thank u again

**Comment by ikerlin** [comment]
sorry, we have the last question, how to use it. we get the values are a string
```golang
import (
	packageNameAlias "xxx.com/proto/packageName"
        "xxx.com/proto_2/packageName"
)

type Response struct {
    Value []*packageNameAlias.DateLineCount `json:"value"`
}
```

`xxx.com/proto/packageName` code 
```golang
type DateLineCount struct {
	Date      string   `json:"date"`
	Count    int64    `json:"count"`
}
```

**Comment by c5433137** [comment]
if it is private storage  how we should do?

**Comment by paddie** [comment]
I had to add the flag `--parseDependency` to the  `swag init` command for it to parse an external dependency.
