### ISSUE TITLE
Swag init v1.6.3 not generating docs

### ISSUE THREAD

**Issue by madmagi** [swaggo/swag#544]
**Describe the bug**
Simple project, all in main.go at root of folder.  swag init, or swag init -g ./main.go both generate 
2019/10/20 15:40:12 Generate swagger docs....
2019/10/20 15:40:12 Generate general API Info, search dir:./
2019/10/20 15:40:12 open : no such file or directory

**To Reproduce**
create simplistic api, with 1 Get function and API tital section (@title, @verison, etc)
enough that has worked in past as a starting point to teach others how swag works to do swagger.

perform swag init in project folder 
(
swag already installed using  
 go get -u github.com/swaggo/swag/cmd/swag
)
retrieved error message above.  Debug steps used
go list -  project shows up
go mod graph - dependency graph shows up
go build - project builds w/out swagger support (swagger hosting not added until we can generate docs)
built against 1.13, 1.12.12, no difference in results

**Expected behavior**
The docs folder is generated, along with the docs.go,  swagger.json and swagger.yaml files

**Screenshots**

**Your swag version**
1.6.3

**Your go version**
1.12.12, 13.3, Running in modules mode not Historical Path mode

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.x, Current Patches as of 10/19
 - Browser: Chrome
 - IDE, JetBrains GoLand

**Additional context**
Have built several api systems using swag, this is the first issue I have had with swag init.
Tried on 2 seperate linux boxes with same issues.  Took an older project which was working just fine and re-rand swag init and it failed with 1.6.3.  Guessing either 1.63 or Ubuntu is the issue.

Thank You.

**Comment by Merlinvt** [comment]
Same Problem:
Go version 1.13
IDE: vscode
Ubuntu: 18.04

**Comment by dennypenta** [comment]
Probably you should install it globally, out of current module. 
And try again.

**Comment by Merlinvt** [comment]
I fixed it for myself. It turned out I was referring to some markup files, that did not exist jet.

**Comment by madmagi** [comment]
> I fixed it for myself. It turned out I was referring to some markup files, that did not exist jet. I can check tomorrow what line exactly caused the problem. My be it helps someone else.

any eta on this?  thanks

**Comment by Merlinvt** [comment]
Sorry i totaly forgot about this. I am not sure if i can totaly replicate what the problem was and how i fixed it. But here is what i think happend.

I set the following tags in my main.go method
// @tag.name update
// @tag.description.markdown

My Api has a method update where i set the tags 
// @Tags update
// @ID update

In the docs/api folder i did not have a corresponding update.md file.

I hope that helps.

**Comment by easonlin404** [comment]
@madmagi sorry for the late reply. can you create a reproduced repo?  Let me can figure out what's root cause.
