### ISSUE TITLE
如何一个项目生成两个json文件？

### ISSUE THREAD

**Issue by chenyu1990** [swaggo/swag#545]
管理API和其它API分别在两个json里显示

**Comment by sdghchj** [comment]
github不是中国网站，全世界的coder都在此，很多大项目也都是老外在维护，你确定老外能看得懂你说的？

**Comment by chenyu1990** [comment]
> github不是中国网站，全世界的coder都在此，很多大项目也都是老外在维护，你确定老外能看得懂你说的？

你说的我都知道，i dont care.
