### ISSUE TITLE
Allow saggertype work for some method only

### ISSUE THREAD

**Issue by Jerome1337** [swaggo/swag#549]
**Is your feature request related to a problem? Please describe.**
I use ` swaggertype:"-"` to remove a struct field of the swagger doc for a given method.
For example this struct is used in a login POST method and for a GET user method (as return value)

```go
type User struct {
	ID       uint   `json:"id,omitempty" sql:",pk" swaggertype:"-"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Role     string `json:"role,omitempty" swaggertype:"-"`
}
```
If I add ` swaggertype:"-"` the field will be hidden in the swagger doc.

But I only want to hide it on the POST method, but not in the GET one.

**Describe the solution you'd like**
Maybe have a `swaggertype:"post"` that will only show it for POST methods. If nothing is specified, keep the actual state.

**Additional context**
Here is it ok.
![image](https://user-images.githubusercontent.com/7968649/67948047-306c5780-fbe5-11e9-9d67-515d5ac09b4b.png)

Here not
![image](https://user-images.githubusercontent.com/7968649/67948086-42e69100-fbe5-11e9-8ffc-a2fa225820c3.png)

**Comment by Jerome1337** [comment]
@ubogdan What `invalid` label mean?

**Comment by ubogdan** [comment]
Please read de [docs](https://github.com/swaggo/swag#use-swaggertype-tag-to-supported-custom-type) and if it's not clear enough read the code.

**Comment by ubogdan** [comment]
@Jerome1337 invalid means your `issue` is not an issue. This because swaggertype is meant to do something else.
If you don't want to use `omitempty` in json tag you should simply create another struct.
