### ISSUE TITLE
Windows 10 do not recognize swag as a command

### ISSUE THREAD

**Issue by adrianquiala** [swaggo/swag#553]
After apparent successful run of "go build -o swag cmd/swag/main.go" swag command my Windows 10 is not recognizing swag as internal command and there for swag init is impossible. Have someone here installed this tool with success in a Windows 10 system?

**My swag version**
e.g. 1.6.3

**My go version**
e.g. 1.13.0

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by ubogdan** [comment]
Have you tried `go build -o swag.exe cmd/swag/main.go` ?

**Comment by adrianquiala** [comment]
@ubogdan Yes, I did it already and I continue with the same issue.

**Comment by adrianquiala** [comment]
@ubogdan Actually, I just noted I was doing it without the .exe part. It seems that now it will work. THANKSSSSSSSS!!!!

**Comment by mrvudoan** [comment]
> Have you tried `go build -o swag.exe cmd/swag/main.go` ?

Thanks @ubogdan, it works for my case: Windows 11, tried many times of installing swag as in the Getting started page but got no luck and even no error message to Google for. 

I followed this guide and copied the output swag.exe to the $GOPATH/bin folder.
