### ISSUE TITLE
ParseComment error

### ISSUE THREAD

**Issue by adrianquiala** [swaggo/swag#554]
**Describe the bug**
After a successful resolution of my last issue I have been trying to do swag init -g cmd/api.go
But I am getting ParseComment error in file cmd\api.go :can not find schema type: "main.MyType"
Why does this happen if I am doing a successful build of my project?

**Expected behavior**
Generation of the doc folder with the docs.go and more
My swag version
e.g. 1.6.3

My go version
e.g. 1.13.0

Desktop (please complete the following information):
OS: Windows 10

**Comment by ubogdan** [comment]
@adrianquiala The build won't fail no matter what you wrote in comments. Is there any `type MyType strcut {}` in main package ?

**Comment by easonlin404** [comment]
can you provide a reproduced repo for it? Let me can figure out what's the problem.
