### ISSUE TITLE
ignore same fieds in swagger. 

### ISSUE THREAD

**Issue by 381162797** [swaggo/swag#560]
**Is your feature request related to a problem? Please describe.**
I use a struct like this:
type User struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
	CTime    int64  `json:"cTime"`
}
so the UI display like this:
 {
	id:0,  // at there , id is primary key that auto create by mysql.
         username :"string",
          cTime:"string"
}
 We only need username field in request, the id field which auto create by mysql is
 usually  appears in the response.
if we use :  ID int `json:"-"` , at our UI about response , id field was igore too.But we only want to ignore it in request.
 Is there a way to salve this problem？
How about add a tag for swag  like `swag:"ignore"`

**Comment by sdghchj** [comment]
Obviously，your can have your request object embeded in response.
```
type UserRequest struct {
    Username string json:"username"
}

type UserResponse struct {
   ID int json:"id"
   CTime int64 json:"cTime"
   UserRequest 
}
```
