### ISSUE TITLE
ParseComment error: can not parse router comment "/ [get]"

### ISSUE THREAD

**Issue by mexx** [swaggo/swag#561]
**Describe the bug**
After updating to v.1.6.3 the generation fails with:
`ParseComment error: can not parse router comment "/ [get]"`
It works with v.1.6.2 perfectly.

**Your swag version**
1.6.3

**Your go version**
1.13.4

**Comment by sdghchj** [comment]
[operation.go#L441](https://github.com/swaggo/swag/blob/master/operation.go#L441)
regexp is `^(/[\w\.\/\-{}\+:]+)[[:blank:]]+\[(\w+)]`, I also don't know why.

why not   `^(/[\w\.\/\-{}\+:]*)[[:blank:]]+\[(\w+)]`

**Comment by ubogdan** [comment]
@mexx please explain your use case. I don't see any reason to have a route without a resource name.

**Comment by lc-jordanfelix** [comment]
We didn't have this issue with v1.6.3, but now have it with v1.6.4

See: [#599](https://github.com/swaggo/swag/issues/599) which also tries to explain the use case.

In summary, we have a base path and our health check on the base path.  We use a query parameter to engage the health check.  E.g. https://my-service.com/my-service?health=true so /my-service is our base path and we needed a way to annotate a function used on our base path for a get request.

**Comment by sdghchj** [comment]
This issue seems to be a result of a PR #552 on 10 Nov,2019

**Comment by ubogdan** [comment]
@sdghchj I don't see any difference between the 2 regular expressions you posted. 
We tried to be a little restrive with router paths in PR #522 in order to not allow invalid paths.
@lc-jordanfelixIi perfectly understand your frustration regarding the issue. 
A normal CRUD path should have the entity name in the path like `@router /users [get]`. 
Thanks for reporting the issue, meanwhile you can 1.6.3 or if you have some free time feel free to push a PR to fix this.

**Comment by sdghchj** [comment]
> @sdghchj I don't see any difference between the 2 regular expressions you posted.
> We tried to be a little restrive with router paths in PR #522 in order to not allow invalid paths.

One + replaced by * .

**Comment by sdghchj** [comment]
Try v1.6.5.

**Comment by kyroy** [comment]
Works, thank you very much =)

**Comment by faisalbd21** [comment]
this is my swagger docs.
`// GetByCompanyCode godoc`
`// @ID getByCompanyCode`
`// @Tags verificationlog`
`// @Accept  json`
`// @Produce  json`
`// @Param companyCode path string true "company code"`
`// @Param currentPage path int true "current page"`
`// @Param offset path int true "offset"`
`// @Param limit path int true "limit"`
`// @Success 200 {array} dtos.VerificationLogDto`
`// @Router /verificationlog/{companyCode}&{currentPage}&{offset}&{limit} [get]`


And I get the parse error message. How to solve it?
