### ISSUE TITLE
Seems no dependency on gin-swagger (cyclic dependency ?)

### ISSUE THREAD

**Issue by gasuketsu** [swaggo/swag#563]
**Describe the bug**

It looks that current swag does not have dependency on gin-swagger though go.mod has dependency on gin-swagger@v1.2.0.
Due to this dependency, performing `go mod tidy` in project using echo-swagger fails with following error.

```
        github.com/swaggo/echo-swagger tested by
        github.com/swaggo/echo-swagger.test imports
        github.com/swaggo/gin-swagger/example/docs: module github.com/swaggo/gin-swagger@latest found (v1.2.0), but does not contain package github.com/swaggo/gin-swagger/example/docs
```

**To Reproduce**
1. Create a 'go moduled' project depends on  `github.com/labstack/echo/v4` and `github.com/swaggo/echo-swagger`.
2. Perform `go mod tidy` in the project

**Expected behavior**
`go mod tidy` completes w/o error.

**Screenshots**
n/a

**Your swag version**

1.6.3

**Your go version**

1.13.4

**Comment by ubogdan** [comment]
@gasuketsu  GO is right, there is no docs package in [swaggo/gin-swagger/example](https://github.com/swaggo/gin-swagger/tree/v1.2.0/example) for version 1.2.0 as swagg/go.mod is describing.

**Comment by akojo** [comment]
#800 along with swaggo/echo-swagger#33 should fix this issue

**Comment by ubogdan** [comment]
Closing: fixed.
