### ISSUE TITLE
Is there a way to set multiple @Router for one controller?

### ISSUE THREAD

**Issue by axiaoxin** [swaggo/swag#569]
I have a controller use by two gin Group, such as:

```
g1 := ginapp.Group("/g1")
{
    g1.GET("/ping", Ping)
}
g2 := ginapp.Group("/g2")
{
    g2.GET("/ping", Ping)
}
```

Is there a way can write comments for the Ping to support two different router?

**Comment by ubogdan** [comment]
Answer: No. And this is because you are mapping the call yo a single function. 
As a work around you can create `func Ping2() { return Ping1()}` with the same comments as Ping one except @router

**Comment by matheusmosca** [comment]
Could I add support for multiple routers in a single controller? @ubogdan @easonlin404
