### ISSUE TITLE
How to use the same model in many @param different?

### ISSUE THREAD

**Issue by gmarcial** [swaggo/swag#574]
Has as use the same model in many @param different, just that with different values of example.

Example:

`type User struct {
	ID        uint64 
	Email     string
	Password  string
	Person    *Person
}`

In endpoint A:

// @Param full body model.User true "..."
`{
	"email": "sample@sample.com",
	"password": "password",
	"person": 
	{
		"name": "Sample name",
                 "..."
	}
}`

In endpoint B:
// @Param short body model.User true "..."
`{
	"email": "sample@sample.com"
}`

I saw that you can use the example tag to specify, but it seems to me that it becomes an example for all parameters that model is used.

**Comment by sdghchj** [comment]
Examples are bind to models, referenced by APIs。

**Comment by ubogdan** [comment]
Closing: outdated.
