### ISSUE TITLE
Prebuilt binary behaves differently from go get version

### ISSUE THREAD

**Issue by indyFan63** [swaggo/swag#575]
A few weeks back I grabbed the prebuilt OSX binary of v1.6.3.  Today I'm adding a swagger generation task to our CI. I started getting errors.  To make sure the CI machine and my Mac are running the same version I:

`go get -u github.com/swaggo/swag/cmd/swag`

On both platforms.  Both platforms and the prebuilt binary all report v1.6.3.  The OSX version I just "go got" produces the error, while the prebuilt binary I grabbed a few weeks ago does not.

Sorry, No easy answer here as I don't have a small source code example

**Expected behavior**

**Screenshots**
 The error I'm getting...

`2019/12/05 13:44:09 Type definition of type '*ast.InterfaceType' is not supported yet. Using 'object' instead.
2019/12/05 13:44:09 unknown field type &ast.InterfaceType{Interface:4414, Methods:(*ast.FieldList)(0xc00082ecf0), Incomplete:false}`

**Your swag version**
v1.6.3

**Your go version**
go version go1.13.3 darwin/amd64

**Desktop (please complete the following information):**
 - OS: OSX 10.15.1
 - Browser: Chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by indyFan63** [comment]
FWIW: I updated I'm hitting this (and similar) errors on both an Ubuntu CI container and OSX.  Don't ever see the errors with the pre-built binary.

And I think I've narrow it down to what structure is causing it.  Commenting out fields looking for the offender I can get it in a state where swag crashes 75% of the time and successfully parses the code 25% of the time.  No changes to the input source files between runs.

**Comment by indyFan63** [comment]
And FWIW: Today I installed both the pre-built and the "go get" version side-by-side on our CI machine.  This is an Ubuntu box vs OSX, and also an older version of Go.  Anyway, exactly the same results.  Prebuilt works every time and the "go get" version errors parsing structure types.  Here are the version numbers and output log from the CI machine:

$ cat /etc/issue
Ubuntu 18.04.3 LTS \n \l

$ go version
go version go1.12 linux/amd64
$ make swagger
Generating swagger API specification for fleetd
swag init -g web/app.go
2019/12/06 16:00:08 Generate swagger docs....
2019/12/06 16:00:08 Generate general API Info, search dir:./
2019/12/06 16:00:08 Generating generalprovider.badLoginResponse
2019/12/06 16:00:08 Skipping 'time.Time', pkg 'time' not found, try add flag --parseDependency or --parseVendor.
2019/12/06 16:00:08 Generating generalprovider.loginRequest
2019/12/06 16:00:08 Generating generalprovider.loginResponse
2019/12/06 16:00:08 Skipping 'time.Time', pkg 'time' not found, try add flag --parseDependency or --parseVendor.
2019/12/06 16:00:08 Generating userdb.Permission
2019/12/06 16:00:08 Generating twofactor.RecoveryCode
2019/12/06 16:00:08 Type definition of type '*ast.InterfaceType' is not supported yet. Using 'object' instead.
2019/12/06 16:00:08 unknown field type &ast.InterfaceType{Interface:1315, Methods:(*ast.FieldList)(0xc000653620), Incomplete:false}
make: *** [swagger] Error 1
Makefile:49: recipe for target 'swagger' failed
ERROR: Job failed: exit code 1

**Comment by xpunch** [comment]
Same error under go1.13.4-alpine, but running fine in go1.13.1-alpine.
Swag version is 1.16.3, which is very strange.

**Comment by MarceloVano** [comment]
I'm facing a simular issue when trying to declare an interface type object:
`type ApiError interface`

After run `swag init`:
2020/01/15 14:53:43 Generating apierrors.ApiError
2020/01/15 14:53:43 Type definition of type '*ast.InterfaceType' is not supported yet. Using 'object' instead.

~ » go version
go version go1.12.14 darwin/amd64

MacOS Catalina 10.15.2 (19C57)

**Comment by ubogdan** [comment]
This kind of error happen in go1.12 where module implementation was not so stable.
