### ISSUE TITLE
OAuth2Implicit Not Sending Authorization Header

### ISSUE THREAD

**Issue by rametta** [swaggo/swag#578]
**Describe the bug**
After authenticating properly with OAuth2Implicit, I get redirected back to the swagger docs with the token in the url fragment, but it does not send those as a Bearer token for my requests.
Even with this security definition:
```
// @securitydefinitions.oauth2.implicit OAuth2Implicit
// @in header
// @name Authorization
// @authorizationurl myauthurl.com
```
and my endpoint has: `// @Security OAuth2Implicit` on each

**To Reproduce**
1. Setup swagger with OAuth2Implicit
2. Authenticate in swagger
3. Make a request inside swagger
4. Realize the Authorization header is not sent

**Expected behavior**
The Bearer token should be sent as a header called Authorization when making requests

**Your swag version**
e.g. 1.6.3

**Your go version**
e.g. 1.13.4

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser: [e.g. chrome, safari] Firefox
 - Version: [e.g. 22

**Comment by ubogdan** [comment]
@rametta can you produce the desired behavior using [swagger editor](https://editor.swagger.io/) and share it with us. 
It's not clear for me if is a generator bug (swag) or a frontend (swagger.js) issue.

**Comment by henri9813** [comment]
@rametta , did you find a solution ?
