### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by agxmaster** [swaggo/swag#589]
master分支的代码 
go version go1.13.5 linux/amd64

go build 执行报错

router/dev.go:16:13: cannot use echoSwagger.WrapHandler (type "github.com/labstack/echo/v4".HandlerFunc) as type "github.com/labstack/echo".HandlerFunc in argument to engine.GET

**Comment by sdghchj** [comment]
你的问题跟本项目没有关系。提示也说得很清楚，echoSwagger.WrapHandler要的参数类型是 "github.com/labstack/echo".HandlerFunc，而不是type "github.com/labstack/echo/v4".HandlerFunc，也就是说你import的路径有误。

**Comment by agxmaster** [comment]
哈哈哈哈不好意思 我发错地方了

**Comment by easonlin404** [comment]
no worries, man. 😄
