### ISSUE TITLE
Is there a way to use custom css for the swagger UI?

### ISSUE THREAD

**Issue by AhmedMKamal** [swaggo/swag#600]
Is there a way to apply changes to the swagger UI or use a custom css file instead of the default one?

**Comment by ubogdan** [comment]
There is no way to use custom CSS.

**Comment by sdghchj** [comment]
Tring exploring it [here](https://github.com/swaggo/gin-swagger/blob/master/swagger.go#L141)

**Comment by AhmedMKamal** [comment]
Okay fine, what I've ended up with is creating a custom route that is serving my custom CSS file at route `/swagger/swagger-ui.css` and it did work.

**Comment by sdghchj** [comment]
> Okay fine, what I've ended up with is creating a custom route that is serving my custom CSS file at route `/swagger/swagger-ui.css` and it did work.

Ok, if that , close this issue
