### ISSUE TITLE
Description, Reference of struct not working for package outside the folder.

### ISSUE THREAD

**Issue by poonam-netsmartz** [swaggo/swag#602]
**Describe the bug**
Description, Reference of struct not working for package outside the folder.

**To Reproduce**
1. In main.go file i have imported model from external folder like :
"bitbucket.org/abc/common/models"
And example of my model is as below :
type WebsocketBroadcast struct {
	Users map[string]bool `json:"omit_users"` // broadcast is omitted for users listed here
	UserId    string          `json:"user_id"`    // broadcast only occurs for this user
	ChannelId string          `json:"channel_id"` // broadcast only occurs for users in this channel
	TeamId    string          `json:"team_id"`    // broadcast only occurs for users in this team
}

And importing model struct in main.go as below:

// apiPostUsers godoc
// @Summary apiPostUsers
// @Description user login to app
// @Tags Authentication
// @ID apiPostUsers
// @Accept  json
// @Produce  json
// @Success 200 {object} models.WebsocketBroadcast 
// @Failure 400 {object} app.ApiInterfaceError
// @Failure 404 {object} app.ApiInterfaceError
// @Failure 500 {object} app.ApiInterfaceError

func (c *appContext) apiPostUsers(w http.ResponseWriter, r *http.Request) {
}

**Expected behavior**
In swagger.yaml description should be add from // Comment part of struct

**Comment by sdghchj** [comment]
Have you tried 'swag init --parseDependency' ?

**Comment by poonam-netsmartz** [comment]
> Have you tried 'swag init --parseDependency' ?
