### ISSUE TITLE
go get -u github.com/swaggo/swag/cmd/swag failing

### ISSUE THREAD

**Issue by cristianmartinello-wf** [swaggo/swag#606]
**Describe the bug**

go get -u github.com/swaggo/swag/cmd/swag currently fails on version 1.6.4

**To Reproduce**
1. go get -u github.com/swaggo/swag/cmd/swag
2. See error:
go: finding github.com/swaggo/swag/cmd/swag latest
go: finding github.com/swaggo/swag/cmd latest
go: finding github.com/swaggo/swag v1.6.4
go: downloading github.com/swaggo/swag v1.6.4
go: extracting github.com/swaggo/swag v1.6.4
go: finding github.com/swaggo/cli v1.20.0
go: finding github.com/alecthomas/template latest
go: finding github.com/swaggo/files latest
go: finding github.com/go-openapi/spec v0.19.5
go: finding golang.org/x/tools latest
go: finding golang.org/x/net latest
go: finding github.com/mattn/go-isatty v0.0.11
go: finding github.com/PuerkitoBio/urlesc latest
go: finding golang.org/x/sys latest
go: finding github.com/modern-go/concurrent latest
go: finding golang.org/x/crypto latest
go: finding github.com/go-openapi/swag v0.19.6
go: finding github.com/kr/pretty v0.2.0
go: finding golang.org/x/sync latest
go: finding github.com/json-iterator/go v1.1.9
go: finding github.com/swaggo/cli v1.22.0
go: finding golang.org/x/mod v0.1.1-0.20191105210325-c90efee705ee
go: finding golang.org/x/crypto v0.0.0-20191011191535-87dc89f01550
go: finding gopkg.in/yaml.v2 v2.2.4
go: finding gopkg.in/check.v1 latest
go: finding golang.org/x/mod v0.1.0
go: finding golang.org/x/sys v0.0.0-20191026070338-33540a1f6037
go: finding gopkg.in/go-playground/validator.v9 v9.31.0
go: finding golang.org/x/xerrors latest
go: finding github.com/cpuguy83/go-md2man v1.0.10
go: finding github.com/russross/blackfriday v1.5.2
go: finding github.com/russross/blackfriday v2.0.0+incompatible
go: downloading github.com/swaggo/cli v1.22.0
go: downloading github.com/go-openapi/spec v0.19.5
go: downloading golang.org/x/tools v0.0.0-20200110042803-e2f26524b78c
go: extracting github.com/swaggo/cli v1.22.0
go: downloading github.com/cpuguy83/go-md2man v1.0.10
go: downloading github.com/go-openapi/swag v0.19.6
go: downloading golang.org/x/net v0.0.0-20191209160850-c0dbc17a3553
go: extracting github.com/cpuguy83/go-md2man v1.0.10
go: downloading github.com/russross/blackfriday v2.0.0+incompatible
go: extracting github.com/go-openapi/swag v0.19.6
go: extracting golang.org/x/tools v0.0.0-20200110042803-e2f26524b78c
go: extracting github.com/go-openapi/spec v0.19.5
go: extracting golang.org/x/net v0.0.0-20191209160850-c0dbc17a3553
go: extracting github.com/russross/blackfriday v2.0.0+incompatible
# github.com/cpuguy83/go-md2man/md2man
../../../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/md2man.go:11:16: undefined: blackfriday.EXTENSION_NO_INTRA_EMPHASIS
../../../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/md2man.go:12:16: undefined: blackfriday.EXTENSION_TABLES
../../../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/md2man.go:13:16: undefined: blackfriday.EXTENSION_FENCED_CODE
../../../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/md2man.go:14:16: undefined: blackfriday.EXTENSION_AUTOLINK
../../../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/md2man.go:15:16: undefined: blackfriday.EXTENSION_SPACE_HEADERS
../../../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/md2man.go:16:16: undefined: blackfriday.EXTENSION_FOOTNOTES
../../../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/md2man.go:17:16: undefined: blackfriday.EXTENSION_TITLEBLOCK
../../../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/md2man.go:19:29: too many arguments to conversion to blackfriday.Markdown: blackfriday.Markdown(doc, renderer, extensions)
../../../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/roff.go:19:9: cannot use &roffRenderer literal (type *roffRenderer) as type blackfriday.Renderer in return argument:
        *roffRenderer does not implement blackfriday.Renderer (missing RenderFooter method)
../../../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/roff.go:102:11: undefined: blackfriday.LIST_TYPE_ORDERED
../../../../pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/roff.go:102:11: too many errors

**Expected behavior**
go get fetches the package correctly.

**Screenshots**
NA

**Your swag version**
e.g. 1.6.4

**Your go version**
e.g. o1.12.6

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: NA
 - Version: NA

**Comment by sdghchj** [comment]
Repeated issue, have a look at #598 .
Wait for v1.6.5 , please.
