### ISSUE TITLE
Cannot install swag because blackfriday dependency errors

### ISSUE THREAD

**Issue by daletake** [swaggo/swag#608]
Hi, when I try to install swag: 
`$ go get -u github.com/swaggo/swag/cmd/swag`
I get:
```
# github.com/cpuguy83/go-md2man/md2man
/Users/<usr>/go/pkg/mod/github.com/cpuguy83/go-md2man@v1.0.10/md2man/md2man.go:11:16: undefined: blackfriday.EXTENSION_NO_INTRA_EMPHASIS
...
```
I'm using modules and I have, in my go.mod file:
	github.com/russross/blackfriday v2.0.0+incompatible // indirect

My Go version:
go1.13.6 darwin/amd64
on Mac

**Comment by sdghchj** [comment]
v1.6.5 fixed

**Comment by easonlin404** [comment]
@daletake please use the latest [V1.6.5](https://github.com/swaggo/swag/releases/tag/v1.6.5) to try again. Please reopen it if there is any problems.
