### ISSUE TITLE
Not detecting inline controller definitions

### ISSUE THREAD

**Issue by mporracindie** [swaggo/swag#611]
I'm having a problem where documentation for inline definition of handlers is not being detected.

For example:

```
// PingExample godoc
// @Summary ping example
// @Description do ping
// @Tags example
// @Accept json
// @Produce json
// @Success 200 {string} string "pong"
// @Router /ping [get]
func PingHandler(c *gin.Context) {
	c.String(http.StatusOK, "pong")
}

func mapRoutes() {
	router.GET("/ping", PingHandler)
	router.GET("/gaia/step/:id",
	// GetStep godoc
	// @Summary Get step object
	// @Description do ping
	// @Tags step
	// @Accept json
	// @Produce json
	// @Success 200 {object} domain.Step
	// @Router /gaia/step/{id} [get]
	func (c *gin.Context) {
		controller.GenericController(c, domain.Step{}, service.Get, controller.ParseId)
	})
}
```

This results on the Ping information being display properly but **not** Step one. Is there any way to fix this? We are using generic controllers to avoid maintaining more code.

Regards.

**Comment by sdghchj** [comment]
I am still confused why it must be inline.
Comments above function are parsed as function's doc while in function scope as general comments.
It can be fixed, but as a result , it will try to parse all the comments in file.

**Comment by ubogdan** [comment]
@sdghchj if you do that the parsing time will increase too much. think about the situation when --parseDependency flag is in use. 

@mporracindie going back to your question. Yes, there is a way to fix by moving the swagger annotation outside the function body.

**Comment by mporracindie** [comment]
@sdghchj I'm using a generic controller to save me from having the same code N times (in this particular case I have like 30 endpoints that go through the same controller and that controller just calls the corresponding service).

How hard is it to change it so it looks for every comment instead? I could change it for this project in particular at my own risk. Or it could be default off feature for everyone maybe?

@ubogdan This doesn't really solve the problem. It just forces me to create a ton of controllers. Here is another snipper to show you what I mean.

```
```

I'm doing something like this for +30 objects.

**Comment by sdghchj** [comment]
In my opinion, controller is just a concept. 
I guess controller.GenericController is what you call "the same controller", however in every router it is still wrapped in anonymous function "func (c *gin.Context)" as a handler. You still have to add comments for every anonymous function. 
What you only need to do is to give it a name, let it be a global named function.
On the other hand, if service.Get, service.Put etc. are functions, they also can be called controllers, I think.

**Comment by mporracindie** [comment]
Yes, but I need to insist on the point that I have multiples routes definitions that down the road all call the same functions (controllers, services, etc..) the only big difference is the domain I pass to each one. 

In any case, I'm playing around with the "ParseRouterAPIInfo" function to see if I can make it either all comments or scan all statements inside each function body. 
If you have already done this and can give me a hand it would be great.

**Comment by sdghchj** [comment]
[here](https://github.com/swaggo/swag/blob/master/parser.go#L464), you can traverse astFile.Comments to parse instead of  astFile.Decls.Doc.List.

**Comment by mporracindie** [comment]
I ve tried changing it for:

```
// ParseRouterAPIInfo parses router api info for given astFile
func (parser *Parser) ParseRouterAPIInfo(fileName string, astFile *ast.File) error {
	for _, astDescription := range astFile.Comments {
		fmt.Printf("Parsing: %v",astDescription)
		operation := NewOperation() //for per 'function' comment, create a new 'Operation' object
		operation.parser = parser
		for _, comment := range astDescription.List { // astDeclaration.Doc.List {
			if err := operation.ParseComment(comment.Text, astFile); err != nil {
				return fmt.Errorf("ParseComment error in file %s :%+v", fileName, err)
			}
		}
		var pathItem spec.PathItem
		var ok bool

		if pathItem, ok = parser.swagger.Paths.Paths[operation.Path]; !ok {
			pathItem = spec.PathItem{}
		}
		switch strings.ToUpper(operation.HTTPMethod) {
		case http.MethodGet:
			pathItem.Get = &operation.Operation
		case http.MethodPost:
			pathItem.Post = &operation.Operation
		case http.MethodDelete:
			pathItem.Delete = &operation.Operation
		case http.MethodPut:
			pathItem.Put = &operation.Operation
		case http.MethodPatch:
			pathItem.Patch = &operation.Operation
		case http.MethodHead:
			pathItem.Head = &operation.Operation
		case http.MethodOptions:
			pathItem.Options = &operation.Operation
		}
		parser.swagger.Paths.Paths[operation.Path] = pathItem
	}

	return nil
}
```

But it still not working. I was unable to find how this ends up being executed down from the `swag.Register(swag.Name, &s{})` line.

Is there anything else I need to consider/change?

**Comment by sdghchj** [comment]
@mporracindie I tested your code. It works all right.

**Comment by mporracindie** [comment]
My bad, I was changing the library on the vendor and not rebuilding the bin. Thank you so much for your help.
