### ISSUE TITLE
cannot find package "github.com/alecthomas/template

### ISSUE THREAD

**Issue by bkocadere** [swaggo/swag#612]
--> swag init
--> go install

docs\docs.go:12:2: cannot find package "github.com/alecthomas/template" in any of:
	c:\go\src\github.com\alecthomas\template (from $GOROOT)
	C:\Users\bkocadere\go\src\github.com\alecthomas\template (from $GOPATH)
exit status 1
Process exiting with code: 1

swag : v1.6.5

go version go1.13.6 windows/amd64

**Comment by sdghchj** [comment]
go get github.com/alecthomas/template

**Comment by pigubaoza** [comment]
should probably put this on the README.md
