### ISSUE TITLE
Exclude the Model from model list

### ISSUE THREAD

**Issue by RajatBanerjee** [swaggo/swag#619]
Is there something similar to
https://github.com/swagger-api/swagger-ui/issues/4803

either by a setting or a custom handler where i can remove the model from the UI

OR If that is not possible, we can rename it 
https://github.com/swaggo/swag/issues/316

**Comment by sdghchj** [comment]
So far as I can see, only struct used as query param may be useless in model list, which can be excluded.
Do you mean that?

**Comment by rayterrill** [comment]
This is exactly what I was looking for - is it possible to exclude query param structs?
