### ISSUE TITLE
Add argument to search model definition

### ISSUE THREAD

**Issue by comphilip** [swaggo/swag#622]
## Problem
I have a project with following folder structure:
```
.
├── cmd
│   ├── api
│   │   ├── controllers
│   │   └── main.go
│   └── runner
│       ├── controllers
│       └── main.go
├── go.mod
├── infra
│   ├── jsonutil
│   ├── logging
│   ├── mockutil
│   └── timeutil
└── internal
    ├── config
    ├── dal
    ├── model
    └── services
```
There are more than one executable tools (main.go) under `cmd` folder. May of them acted as http server to different provide REST APIs. Each tool has its own REST API go annotation under its `controllers` folder. All executable tools share same data struct definitions (model) under `internal` folder.

To generate `api` tool swagger document, I ran `./swag init -g cmd/api/main.go -o cmd/api/docs`. It works but the result contains REST APIs belongs to other tools since swag search from `./`.

Swag failed with narrow down search dir: `./swag init -d cmd/api -g main.go -o cmd/api/docs`
```
2020/02/08 21:55:59 Generate swagger docs....
2020/02/08 21:55:59 Generate general API Info, search dir:cmd/api
go/build: importGo gitlab-spiral.spiral.exchange/next/system/backend/internal/model: exit status 2
go: cannot find GOROOT directory: /usr/local/Cellar/go@1.12/1.12.12/libexec


2020/02/08 21:55:59 ParseComment error in file cmd/api/controllers/next-share-jobs.go :can not find type def: "model.NextModelTraingJob" error: no initial packages were loaded
```

Swag also failed with **--parseDependency** : `./swag init -d cmd/api -g main.go -o cmd/api/docs --parseDependency`
```
2020/02/08 21:58:38 Generate swagger docs....
2020/02/08 21:58:38 Generate general API Info, search dir:cmd/api
2020/02/08 21:58:38 pkg gitlab-spiral.spiral.exchange/next/system/backend/cmd/api cannot find all dependencies, unable to resolve root package
```
## Solution
It is better to add `--model-dir` to let swag search models.

```bash
./swag init \
    --model-dir internal \
    -d cmd/api \
    -g main.go \
    -o cmd/api/docs
# support more model dir
./swag init \
    --model-dir internal1 \
    --model-dir internal2 \
    -d cmd/api \
    -g main.go \
    -o cmd/api/docs
```

**Comment by comphilip** [comment]
Refer to #640

**Comment by sdghchj** [comment]
Were you run on window system?

**Comment by comphilip** [comment]
@sdghchj ubuntu 18.04

**Comment by sdghchj** [comment]
what is gitlab-spiral.spiral.exchange/next/system/backend/cmd/api ?
I really still don't known your packages' dependent relations. 
Can you give your repository out on github?

**Comment by comphilip** [comment]
gitlab-spiral.spiral.exchange/next/system/backend is internal gitlab repository path. I can't share source code

**Comment by sdghchj** [comment]
OK, I tried your package structure with go 1.13.5, it does work well.

**Comment by comphilip** [comment]
@sdghchj It works well on scan all swagger api comment, just like what I mentioned:

> To generate api tool swagger document, I ran ./swag init -g cmd/api/main.go -o cmd/api/docs. It works but the result contains REST APIs belongs to other tools since swag search from ./.

I want to generate swagger api under `cmd/api` but not include `cmd/runner`. Swag v1.6.5 has no way to support it.

**Comment by sdghchj** [comment]
> @sdghchj It works well on scan all swagger api comment, just like what I mentioned:
> 
> > To generate api tool swagger document, I ran ./swag init -g cmd/api/main.go -o cmd/api/docs. It works but the result contains REST APIs belongs to other tools since swag search from ./.
> 
> I want to generate swagger api under `cmd/api` but not include `cmd/runner`. Swag v1.6.5 has no way to support it.

Yes, I was trying like that with swag v1.6.5.

I ran 'swag init --dir ./cmd/api -o ./cmd/api/docs', all right, only cmd/api  generated.

```
backend/backend2
.
├── cmd
│   ├── api
│   │   ├── controller
│   │   │   └── api.go
│   │   ├── docs
│   │   │   ├── docs.go
│   │   │   ├── swagger.json
│   │   │   └── swagger.yaml
│   │   └── main.go
│   └── api2
│       ├── controller
│       │   └── api.go
│       └── main.go
├── go.mod
└── internal
    └── model
        └── model.go
```

In my go.mod
```
module backend/backend2

go 1.12.9
```

**Comment by sdghchj** [comment]
You'd check your env whether GO111MODULE=on

**Comment by comphilip** [comment]
I have submit example code to: https://github.com/comphilip/swag-issue-622-code

**Comment by sdghchj** [comment]
> I have submit example code to: https://github.com/comphilip/swag-issue-622-code

I've got your issue.

model.InboxMessage was only used in comments in your cmd/api/controllers/inbox.go, so you needn't to, of course, didn't import example/internal/model. However, **swag search for model.InboxMessage according to inbox.go's imports**. 

Yes, you have to import example/internal/model:
```
import  _  "example/internal/model"
```

**Comment by comphilip** [comment]
@sdghchj thanks for your help!
