### ISSUE TITLE
swag generator shouldn't include `type` tag for refs if one exists already

### ISSUE THREAD

**Issue by wangdrew** [swaggo/swag#625]
The swagger spec generated from `swag init` command shouldn't generate a `type` field in a `schema` object under `parameters` if a `$ref` field exists that refers to an object whose definition already contains a `type` field. 

Currently, swag generates this:
```
parameters:
        schema:
          $ref: '#/definitions/web.Pet'
          type: object
``` 
https://github.com/swaggo/swag/blob/master/example/basic/docs/swagger/swagger.yaml#L112

where `type: object` already exists in the `web.Pet` definition:
```
definitions:
  web.Pet:
    type: object
```
 https://github.com/swaggo/swag/blob/master/example/basic/docs/swagger/swagger.yaml#L35

This causes validation errors when trying to generate clients from the swag's generated definition using the [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator) library 
```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 1
Errors:
        -attribute paths.'/testapi/get-string-by-int/{some_id}'(get).[some_id].type is unexpected
```
Additionally reincluding the `type` field conflicts with the example outlined in [swagger 2.0 docs](https://swagger.io/docs/specification/2-0/describing-request-body/) 

**To Reproduce**
1. `swag init` on an api that specifies an endpoint whose parameter is a body referring to a golang struct. Example: https://github.com/swaggo/swag/blob/master/example/basic/api/api.go#L15 

**Expected behavior**
`type` field should not be added to a `schema` object under `parameters` if it contains a `$ref` which already specifies a `type` field.

**Your swag version**
1.6.5

**Your go version**
1.13.4

**Comment by liuggio** [comment]
I have this issue, but maybe we should add this `openapi-generator-cli` check to in the ci?

cc @easonlin404 @pei0804 @ubogdan

**Comment by liuggio** [comment]
Sorry if I insists, the swaggo create an invalid swag I think this is quite important :)

**Comment by sdghchj** [comment]
https://github.com/swaggo/swag/blob/master/example/basic/docs/swagger/swagger.yaml haven't been updated for over half a year.
v1.6.5 does not generate a type field for a $ref.

**Comment by wangdrew** [comment]
Thanks @sdghchj I confirmed I no longer have this issue with v1.6.5.
