### ISSUE TITLE
Allow renaming of models

### ISSUE THREAD

**Issue by Nightapes** [swaggo/swag#628]
**Is your feature request related to a problem? Please describe.**
At the moment swag uses the package name and struct name as model name. like `types.Account`. For users and also for generating clients it would be better to have `Account` as the model name. The package name is something from golang internal.

**Describe the solution you'd like**

```
package types
// @name Account
type Account struct {
    Bar string `minLength:"4" maxLength:"16"`
}
```

**Describe alternatives you've considered**

Or drop the package name in the generated swagger, and show user if there is a conflict

**Additional context**

There was already a issue #316, but it was closed without a solution

**Comment by easonlin404** [comment]
@Nightapes fixed by #631 , please use the latest master.

**Comment by Nightapes** [comment]
@easonlin404 Thank you, it's working perfectly  :+1:

**Comment by itinance** [comment]
Although I upgraded to latest master, it won't work for me.

```
go get github.com/swaggo/swag@master
```

Will give me:

`github.com/swaggo/swag v1.6.6-0.20200404095705-3b82b47aece6`

I double checked that the master is really on my hard drive with necessary commits.

However,

whether I use 

```
// @name AccountX
type Account struct {
```

nor 
```
// AccountCreation
type AccountCreation struct {
	BaseAccount
	OwnerAddress BaseAddress `json:"owner_address"`
}//@name AccountCreation
```

won't work and still render "model.Account" instead of "AccountX" respectively "model.AccountCreation" instead of "AccountCreation".

**Comment by tuxnavell** [comment]
Is there a way to ignore the package name?

**Comment by alex-roman** [comment]
works for me with (note @name goes after the struct def) 
```
type SendEmailParameters struct {
	From    string
	To      []string
	Message string
} // @name SendEmailParameters
```

**Comment by kongh** [comment]
> 

I think a client cmd option should be used, just like `--ignore-package model ` ,`--ignore-package errors`. This is friendly for the developers.
