### ISSUE TITLE
an error when use swag with go mod

### ISSUE THREAD

**Issue by c5433137** [swaggo/swag#634]
**Describe the bug**
Is “swag init ”  supporting  gomod when i need the object of other git storage？

**To Reproduce**
1. edit comment like thsi ”// @Failure 400 {object} group_api_pb.CheckWhetherGroupResponse“
2. group_api_pb.CheckWhetherGroupResponse is other git storage。
3.when i swag init ， See error
zhuxiufenghust@ubuntu:/mnt/hgfs/newgo/yxzq.com/group_buy/group_apiserver$ swag init
2020/02/28 15:27:38 Generate swagger docs....
2020/02/28 15:27:38 Generate general API Info, search dir:./
/mnt/hgfs/go/pkg/mod/yxzq.com/group_buy/group_pb@v0.0.0-20200220040718-712b5145c30c/group_api_pb/group.pb.go:10:4: could not import yxzq.com/group_buy/group_pb/group_server_pb (cannot find package "yxzq.com/group_buy/group_pb/group_server_pb" in any of:
	/usr/local/go/src/yxzq.com/group_buy/group_pb/group_server_pb (from $GOROOT)
	/mnt/hgfs/go/src/yxzq.com/group_buy/group_pb/group_server_pb (from $GOPATH))
/mnt/hgfs/go/pkg/mod/yxzq.com/group_buy/group_pb@v0.0.0-20200220040718-712b5145c30c/group_api_pb/group_api.pb.go:10:7: could not import yxzq.com/group_buy/group_pb/base (cannot find package "yxzq.com/group_buy/group_pb/base" in any of:
	/usr/local/go/src/yxzq.com/group_buy/group_pb/base (from $GOROOT)
	/mnt/hgfs/go/src/yxzq.com/group_buy/group_pb/base (from $GOPATH))
2020/02/28 15:27:41 ParseComment error in file route/v1/group_router.go :can not find type def: "group_api_pb.CheckWhetherGroupResponse" error: couldn't load packages due to errors: yxzq.com/group_buy/group_pb/group_api_pb

----
it maybe not support go mod.

**Your swag version**
 1.6.5

**Your go version**
1.13.0

**Comment by sdghchj** [comment]
go mod ? But as shown in the console output, it searches packages in $GOPATH

**Comment by Nerzal** [comment]
try 

> go mod init

and redo it again

**Comment by KenjiTakahashi** [comment]
I've noticed that it has to be run in the directory where `go.mod` is, otherwise it doesn't find it. If your actual package is somewhere deeper, use the `-g` option.

**Comment by HappyUncle** [comment]
> group_api_pb.CheckWhetherGroupResponse

Is this a struct or a function?

**Comment by ubogdan** [comment]
Closing: outdated.
