### ISSUE TITLE
collectionFormat

### ISSUE THREAD

**Issue by affanshahid** [swaggo/swag#636]
Is there a way I can provide the collection format for query params which are suppose to be arrays? The default is `csv` but gin by default works with `multi`

**Comment by sdghchj** [comment]
By description?

**Comment by affanshahid** [comment]
I'm sorry but you could you give me an example? I tried a few things but wasn't able to get it to work

**Comment by sdghchj** [comment]
I mean you can use description to show your API users the format.
```
@param name query []int true "format: name=1&name=2"
```
Swag just generates docs to be showed by gin-Swagger, and now hasn't support collectionFormat for array in query.
Yes, I remember gin-Swagger's default behavior is csv.
If your debugs directly in swagger UI with gin server, it will fail.
Next PR will consider it.
Of course, welcome your PR.

**Comment by sdghchj** [comment]
Try master branch

**Comment by affanshahid** [comment]
Works perfectly in comment form but not working when used in struct tags:
```go
type GetDefinitionMappersQuery struct {
	Name       *string  `json:"name" form:"name"`
	Category   []string `json:"category" form:"category" collectionFormat:"multi"`
	TenantWide *bool    `json:"tenant_wide" form:"tenant_wide"`
}
```

**Comment by sdghchj** [comment]
@affanshahid Said clear in README.md, collectionFormat is only supported for params in query and formdata

**Comment by pasquale95** [comment]
@sdghchj in my case it doesn't work even for formData:

```
type Params struct {
	Status []uint `form:"status" collectionFormat:"multi"` // The Status ids
}
```

Do you know if I'm missing something?

**Comment by malmeidam** [comment]
Still not working

**Comment by KianYang-Lee** [comment]
I think it should be explicitly stated that it is not supported for struct tag, the way it states this now  is a bit misleading

**Comment by sdghchj** [comment]
> [@sdghchj](https://github.com/sdghchj) in my case it doesn't work even for formData:
> 
> type Params struct {
> 	Status []uint `form:"status" collectionFormat:"multi"` // The Status ids
> }
> Do you know if I'm missing something?

Try the global settings in the main file:
```
@query.collection.format multi
```
This will set the default way.

**Comment by sdghchj** [comment]
> I think it should be explicitly stated that it is not supported for struct tag, the way it states this now is a bit misleading

@KianYang-Lee Try latest commit
