### ISSUE TITLE
Specify order of params in response struct scheme

### ISSUE THREAD

**Issue by Sandburg** [swaggo/swag#637]
Is there currently a way to order the fields in the generated response scheme?
Right now it doesnt apply the order of my struct, but orders it alphabetically.

Also can the order of all requests be specified?

**Comment by sdghchj** [comment]
Yes, struct fields are ordered  alphabetically.
So how do you want to order them? 
Ony its natural order, I think , besides  alphabetical order.

**Comment by Sandburg** [comment]
Yes, it would be nice to configure it some way, that the natural order in the struct would be kept.

**Comment by sdghchj** [comment]
After reviewing, I found it impossible to keep the natural order for swaggo/swag , because the Properties used in Schema , which is shared by several projects ,is map type which might lose keys' order。

**Comment by hyacinthus** [comment]
Strong need for this feature.

**Comment by sdghchj** [comment]
further, json will order them when marshaling and there is no way to change its behavior

**Comment by hyacinthus** [comment]
The encoding/json package marshals maps in sorted key order and structs in the order that the fields are declared.
If I have a large struct, I would like to preserve the order of it.

**Comment by sdghchj** [comment]
> The encoding/json package marshals maps in sorted key order and structs in the order that the fields are declared.
> If I have a large struct, I would like to preserve the order of it.

However, we have to use map to collect  fields of different struct models.

**Comment by sdghchj** [comment]
> The encoding/json package marshals maps in sorted key order and structs in the order that the fields are declared.
> If I have a large struct, I would like to preserve the order of it.

As I see, it relates several projects. 
First, [go-openapi](https://github.com/go-openapi/spec/issues/24)

**Comment by soranoba** [comment]
Using orderedmap (needs to correspond to json marshal) instead of map may solve this problem.
ref: https://github.com/maurice2k/orderedmap

**Comment by sdghchj** [comment]
Checkout the latest commit in github/go-openapi/spec and have a try by flag like `extensions:x-order=1` .
