### ISSUE TITLE
global GOROOT and swag init GOROOT mismatches

### ISSUE THREAD

**Issue by orkunkl** [swaggo/swag#639]
**Describe the bug**
After upgrading go to `v1.14` I got `go: cannot find GOROOT directory: /usr/local/Cellar/go/1.13.7/libexec` error on `swag init -parseVendor` yet `go env` returns `GOROOT="/usr/local/Cellar/go@1.13/1.13.8/libexec"`

**Your swag version**
v1.6.5

**Your go version**
1.13.0

**Desktop (please complete the following information):**
 - OS: mac

**Comment by ubogdan** [comment]
@orkunkl

**Comment by orkunkl** [comment]
Yes you are right. I managed to fix it. I've dockerized swag check it out here https://github.com/iov-one/swag-docker. It is much more convenient to use than installing swag locally.
