### ISSUE TITLE
Documenting nested models

### ISSUE THREAD

**Issue by Lallassu** [swaggo/swag#641]
This might not be a bug but the lack of knowledge. But this is my last resort to find out how to do this.

Let's say I have 2 models:
```
type Item struct {
    ID int `readonly:"true"`
    Name string
    Tags []Tag
}

type Tag struct {
   ID int
   Name string
}
``` 
Problem:
- POST /tags will expose "id" when we only want to expose "name". But we can't set "id" to `readonly` because we need to specify tag.ID in Items.Tags.
- POST /items should be enough to specify the ID for tags (since they are created above), but since we want to be able to create a tag we need to have the tag.Name as NOT `readonly`.

So POST to /items looks like this for the generated swagger doc (via UI).
```
{
  "name": "string"
  "tags": [
    {
      "id": 0,
      "name": "string" // <-- Would like this to be hidden, since it was already set by POST /tags
    }
  ]
}
```
And for posting to /tags:
```
{
  "id": 0, // <-- Would like this to be hidden, since it's generated server side.
  "name": "string"
}
```

Is there a way to handle this scenario?

**Comment by sdghchj** [comment]
```
type Item struct {
    ID int `readonly:"true"`
    Name string
    TagIDs []int
}

type Tag struct {
   ID int `swaggerignore:"true"`
   Name string
}
```

**Comment by Lallassu** [comment]
> ```
> type Item struct {
>     ID int `readonly:"true"`
>     Name string
>     TagIDs []int
> }
> 
> type Tag struct {
>    ID int `swaggerignore:"true"`
>    Name string
> }
> ```
That seems to work with one change and that would be to set Tag.ID to `readonly` instead of swaggerignore. However, I'm using `gorm` as an ORM for my project, hence I'm using relational mapping which makes me want to use []Tag instead of an integer array. I guess I'm out of luck in such case.

**Comment by sdghchj** [comment]
Models are shared, behave the same with different APIs.
You have to define different models for your case.

**Comment by Lallassu** [comment]
> Models are shared, behave the same with different APIs.
> You have to define different models for your case.

You mean define models just for documentation?

**Comment by sdghchj** [comment]
> > Models are shared, behave the same with different APIs.
> > You have to define different models for your case.
> 
> You mean define models just for documentation?

Yes, I usually do that myself.

**Comment by Lallassu** [comment]
Ok, I guess that's the only way forward. Thanks.
