### ISSUE TITLE
How to generate docs from non top-level comment

### ISSUE THREAD

**Issue by soonoo** [swaggo/swag#644]
It seems that `swag` only parses top-level comments for route declarations. How to generate `swagger.json` from inner-level comments?

```go
func main() {
    // ShowAccount godoc
    // @Summary Show a account
    // @Description get string by ID
    // @ID get-string-by-int
    // @Accept  json
    // ...
    r.GET("/", func() {
        // this is example
    })
}
```

**Comment by sdghchj** [comment]
Not support yet, since it will try to parse all comments which may cost more time, inefficient.
