### ISSUE TITLE
Support required in struct tag

### ISSUE THREAD

**Issue by Colstuwjx** [swaggo/swag#645]
**Is your feature request related to a problem? Please describe.**
I know how to specify a param as required, but didn't find how to mark a custom struct field as required.

**Describe the solution you'd like**
Maybe like this: https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.4.3 ? We need to add sth like `required: true` such struct tag to mark the struct field is required.

**Describe alternatives you've considered**

**Additional context**

**Comment by sdghchj** [comment]
```
type Example struct {
      Name string `validate: "required"`
}
```

**Comment by Colstuwjx** [comment]
Thanks! I don't see any document about this, so there is confusion.
