### ISSUE TITLE
custom type to be enum

### ISSUE THREAD

**Issue by chyroc** [swaggo/swag#647]
```go
type SomeEnumType int

const (
	SomeEnumTypeA = 1  // hhh
	SomeEnumTypeB = 2 //  bbb
)

type Req struct {
	Type SomeEnumType `json:"type"`
}
```

i want the `Req.Type` is enum, which has 1 and 2 value

and 1 has comment `hhh`, 2 has comment `bbb`

**Comment by sdghchj** [comment]
请先看一遍文档README.md

```
type Req struct {
	Type SomeEnumType `enums:"1,2"`   //1 hhh，2 bbb
}
```

model definitions里还不支持枚举类型，自然谈不上枚举的Comment

**Comment by chyroc** [comment]
我知道这么做是可以实现的，我在想能不能自动化一点

**Comment by sdghchj** [comment]
> 我知道这么做是可以实现的，我在想能不能自动化一点

那你看一下源码怎么更自动化一些，欢迎提交PR。

**Comment by johan-lejdung** [comment]
Any solution to this yet? It's not very practical to write out `enum:"1, 2"` on multiple models. It's easily missed and when there is an update to the ENUM in question you'd have to change on multiple places

**Comment by zishiguo** [comment]
Does this package support these tags in Model , such as "description", "enum"?
`type Pet struct {
	Id                uint          `json:"id"`
	Name              string        `json:"name"`
	Status            string        `json:"status" description:"pet status in the store" enum:"available,pending,sold"`
}`
