### ISSUE TITLE
object swaggertype supports reference another model

### ISSUE THREAD

**Issue by comphilip** [swaggo/swag#649]
**Is your feature request related to a problem? Please describe.**

There is struct used both in mysql orm and swagger document
```go
type NextTradeServerExtra struct {
    StartTimes []string `json:"start_times"`
    StopTimes  []string `json:"stop_times"`
    TraderIds  []int64  `json:"trader_ids"`
}

type NextTradeServer struct {
    IP    string                `gorm:"column:ip;primary_key"`
    // mysql JSON column type, to save misc(non-index) information without creating new columns.
    Extra json.RawMessage       `gorm:"column:extra" swaggertype:"object,NextTradeServerExtra"` // <-- NextTradeServerExtra is not used
    cache *NextTradeServerExtra `json:"-"`
}

func (*NextTradeServer) TableName() string {
    return "next_ts"
}

func (n *NextTradeServer) ExtraInfo() (*NextTradeServerExtra, error) {
    // unmarshall Extra field json to NextTradeServerExtra
    return nil, nil
}

func (n *NextTradeServer) SetExtraInfo(v *NextTradeServerExtra) error {
    // marshall NextTradeServerExtra to Extra field
    return nil
}
```

**Describe the solution you'd like**

`swaggertype:"object,NextTradeServerExtra"` supports reference to other data model

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by sdghchj** [comment]
PR is welcome, or wait for others's, please

**Comment by comphilip** [comment]
Hard to implement. In parse.go it is hard to reuse parse logic in operation.go. 

The feature I need is more like "Overriding deep-level fields in response object", not only response object, but also request body.

I will try to add feature "Overriding deep-level fields in request body object"

**Comment by sdghchj** [comment]
> Hard to implement. In parse.go it is hard to reuse parse logic in operation.go.
> 
> The feature I need is more like "Overriding deep-level fields in response object", not only response object, but also request body.
> 
> I will try to add feature "Overriding deep-level fields in request body object"

Try `refactored` branch,  object in request body  is supported
