### ISSUE TITLE
Support inheritance/Model Composition in Response with allOf and ref

### ISSUE THREAD

**Issue by whunmr** [swaggo/swag#650]
**Is your feature request related to a problem? Please describe.**

- Background
 we have common response fields such as `code` and `message` in following struct, 
and fill response payload in `Data` field
```
type JSONResult struct {
	Code    JSONResultCode `json:"code" swaggertype:"integer"`
	Message string  `json:"message"`
	Data    interface{}  `json:"data"`
}
```

- Problem:  use following swagger code comment, can not generate detailed struct for `Data` fields
```
 // @Success 200 {object} jsonresult.JSONResult
```
which generates:
```
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/jsonresult.JSONResult'
```

- Expected result for `object` and `array-of-object` Data payload may be:
```
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/jsonresult.JSONResult'
            - properties:
                data:
                  $ref: '#/definitions/proto.Order'
              type: object
```
and 
```
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/jsonresult.JSONPaging'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/proto.Order'
                  type: array
              type: object
```

---

**Describe the solution you'd like**

- One solution maybe: Add nested schema spec in comments like following:
for `object` :
```
@Success 200 {object} jsonresult.JSONResult "{{data=proto.Order}}"
```

for `array-of-object`:
```
@Success 200 {object} jsonresult.JSONResult "{{data=[]proto.Order}}"
```

for `primitive types`:
```
@Success 200 {object} jsonresult.JSONResult "{{data=string}}"
```

- Original `description` fields can follow the `{{.*=([])?.*}}` sequence like:
```
@Success 200 {object} jsonresult.JSONResult "{{data=[]proto.Order}} The real comments"
```

- the field name is also customizable like, use `payload` as nested field name
```
@Success 200 {object} jsonresult.JSONResult "{{payload=[]proto.Order}} "
```

---

**Describe alternatives you've considered**

- Defined each struct with code, message, Data with specific type, produces lots duplicate code.    (also needs some write Constructor code)
```
type OrderJSONResult struct {
	Code    JSONResultCode `json:"code" swaggertype:"integer"`
	Message string                 `json:"message"`
	Data    []*proto.Order       `json:"data"`
}
```

--- 
Already implemented the before mentioned usage, 
 see [commits](https://github.com/whunmr/swag/commit/601287152b5aa6f0e50090e226b4063bb79d3fab)

I'd like to prepare a pull request(sure with unit test), if this is what we all want.

**Additional context**
- Add `"{{data=[]proto.Order}}"` in  description field is for backward compatibility, 
this is just suggestion, we can also discuss which way (where to place the nested schema spec) is best for all. 

- References: [Swagger Inheritance](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/)

**Comment by sdghchj** [comment]
It's useful for response.
Now an alternative way I usually take is:
```
type JSONCommonResult struct {
	Code    JSONResultCode   `json:"code" swaggertype:"integer"`
	Message string                 `json:"message"`
}

type OrderJSONResult struct {
        JSONCommonResult 
	Data    []*proto.Order       `json:"data"`
}
```
Whatever, PR is welcome.

**Comment by sdghchj** [comment]
I think following is better, fields close to response type without spaces.
```
@Success 200 {object} jsonresult.JSONResult{data1=[]proto.Order;data2=string}  "description"
```

**Comment by sdghchj** [comment]
Besides, whether deep nested fields to be considered or not?

For example jsonresult.JSONResult.data.data2

**Comment by whunmr** [comment]
> @Success 200 {object} jsonresult.JSONResult{data1=[]proto.Order;data2=string}  "description"

That's a good idea to put the spec together.

IMHO, single field like `data` is sufficient for most use cases.
If someone needs data1 and data2 etc,  defined a separate struct would be more suitable.

so I suggest:
1.  only support single nested field for simplicity
> @Success 200 {object} jsonresult.JSONResult{data1=[]proto.Order}  "description"

2. also not support  `jsonresult.JSONResult.data.data2` for simplicity

**Comment by whunmr** [comment]
PR already merged.  will close the issue now.

Thanks for the support @sdghchj
