### ISSUE TITLE
Model composition in response not working

### ISSUE THREAD

**Issue by pineappleFTW** [swaggo/swag#656]
**Describe the bug**
I tried Model composition in response and its not working 

**To Reproduce**
I have a response struct and category struct 
```
//in models package
type Response struct {
	Status  string      `json:"status"`
	Data    interface{} `json:"data,omitempty"`
	Message string      `json:"message,omitempty"`
	Code    int         `json:"code"`
}

//in models package
type Category struct {
     //some fields
}

//Create Category godoc
//@Summary Create Category
//@Accept json
//@Product json
//@Security Authorization
//@Param Category body models.Category true "Category"
//@Success 200 {object} models.Response{data=models.Category} "Success"
//@Router /category [post]
func (app *application) createCategory(w http.ResponseWriter, r *http.Request) {
}

```
Result
![image](https://user-images.githubusercontent.com/10570836/77842582-9413a480-71c6-11ea-9a86-4eb8f2e2e287.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/10570836/77842583-9675fe80-71c6-11ea-860c-0b64ca370b92.png)

**Your swag version**
v1.6.5

**Your go version**
1.13.5

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.3

**Comment by solokirrik** [comment]
My case might be similar 👀
```
package response

type Response struct {
	Meta
	Data *Data `json:"result"`
}

type Meta struct {
	Success    bool        `json:"success"`
	Error      []MetaError `json:"errors,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}

type Data struct {
	//some fields
}

type MetaError struct {
	Code      string `json:"code,omitempty"`
	Message   string `json:"message"`
	FieldName string `json:"fieldName,omitempty"`
}

type Pagination struct {
	Total  int64 `json:"total"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}
```
```
package api

// Get User godoc
// @Summary Get user 
// @Description Get user by id
// @Produce json
// @Param id path int true "User ID"
// @Success 200 {object} Response
// @Failure 404 {object} Meta
// @Failure 500 {object} Meta
// @Router /users/{id} [get]
func (gw *Gateway) Get(w http.ResponseWriter, r *http.Request) {
	// do some work
}
```
Result
<img width="487" alt="image" src="https://user-images.githubusercontent.com/20256925/77851093-9a624a80-71df-11ea-8e5a-c7435fa97b4e.png">
Expected result 
<img width="528" alt="image" src="https://user-images.githubusercontent.com/20256925/77851127-f3ca7980-71df-11ea-8a23-9b34d941afb2.png">

**Your swag version**
v1.6.5

**Your go version**
1.14

**Desktop (please complete the following information):**
    OS: MacOS 10.15.3

**Comment by sdghchj** [comment]
@pineappleFTW  v1.6.5 not support yet. 
Use latest master branch, but there is a bug with integer.

**Comment by sdghchj** [comment]
@solokirrik 
I guess your response package is not in your current searching dir.
Then you should import your response package in your main.go file, next set the --parseDependency flag when running swag binary.

**Comment by solokirrik** [comment]
> @solokirrik
> I guess your response package is not in your current searching dir.
> Then you should import your response package in your main.go file, next set the --parseDependency flag when running swag binary.

But with --parseDependency it causes panic from https://github.com/swaggo/swag/issues/567 :/

**Comment by birdycn** [comment]
mee too..

**Comment by idweball** [comment]
git clone https://github.com/swaggo/swag.git
cd swag/cmd/swag
go build .
mv swag /usr/bin/
