### ISSUE TITLE
Swag init can't parse struct but no error message

### ISSUE THREAD

**Issue by businiaowyf** [swaggo/swag#657]
**Describe the bug**
```
type Example struct {
   Status         uint32 `json:"status" example:"true"`
}
```
swag init can't parse this struct, but it prints success. 

**To Reproduce**
1. install swag 1.6.5
```
export GO111MODULE=off
go get -d -u github.com/swaggo/swag/cmd/swag
cd "$(go env GOPATH)"/src/github.com/swaggo/swag
make
cp swag "$(go env GOPATH)"/bin/
```
2. swag init
3. Check docs/docs.go

**Expected behavior**
I expect to see some error message when I run ```swag init```

**Screenshots**

**Your swag version**
1.6.5

**Your go version**
1.13.4

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: 10.14.3

**Additional context**
The reason is in my struct, the type of the field ```status``` is uint32, but I use a wrong example ```true``` which caused that issue.

**Comment by sdghchj** [comment]
will report error next PR
