### ISSUE TITLE
go get -u master,but Version is still 1.6.5.

### ISSUE THREAD

**Issue by birdycn** [swaggo/swag#658]
I want to achieve this effect：
https://github.com/swaggo/swag/issues/656#issue-589727434

my go.mod:

``
require (
	github.com/swaggo/files v0.0.0-20190704085106-630677cd5c14
	github.com/swaggo/gin-swagger v1.2.0
	github.com/swaggo/swag v1.6.6-0.20200323071853-8e21f4cefeea
)

```

I execute through CMD：
```go get -u github.com/swaggo/swag/cmd/swag@master```

but "swag --version" tips:v.1.6.5，how should i do？

**Comment by sdghchj** [comment]
As v1.6.6 haven't been released, "1.6.5" is coded in version.go, so  it still shows v1.6.5 if you build swag with master branch
