### ISSUE TITLE
Adding Description to Authentication

### ISSUE THREAD

**Issue by shibasisp** [swaggo/swag#663]
I want to document the complete authentication flow for my API. However, for `@securityDefinitions.apikey` field, I can't find any *description*.

 I tried putting the description in `@description`, but the content was put inside the main introduction.

I can see a *description* field [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#security-scheme-object) in the OpenAPI 2.0 spec, however, seems like swag doesn't support it.
Can anyone please help me with any alternative way to do it?

**Comment by ubogdan** [comment]
Looks like `@securityDefinitions.description` is not supported at this time. If you like to use time by contributing to swag an get back to us with PR regarding this matter, the things may move more fast and you will be able to use this feature.

**Comment by shibasisp** [comment]
Sure, I will try to come up with a PR.

**Comment by shibasisp** [comment]
Also, if I am not wrong, [here](https://github.com/swaggo/swag#api-operation), the correct usage of adding annotation would be to capitalize it right?
I mean `// @Description` instead of `// @description`. Is there any specific rule where to use the capitalize annotation and where to use annotations with all small case?

**Comment by ubogdan** [comment]
It actialy doesn't matter too much because in [parser.go](https://github.com/swaggo/swag/blob/3b82b47aece6792a09fab48edb05a0d9d868569f/parser.go#L216-L217) they are converted to lowercase. 

Please don't forget to write a test case for your implementation/feature. Thanks.

**Comment by shibasisp** [comment]
Thanks for the clarification. I am closing the issue.
