### ISSUE TITLE
@description.markdown is not working inside controller

### ISSUE THREAD

**Issue by shibasisp** [swaggo/swag#664]
**Describe the bug**
I was following the documentation and I found that:
- To add a markdown description to a tag, we can use `// @tag.description.markdown` and it will take the content of the `<tag_name>.md` file. (I also tried using `// @Tags.description.markdown`)
- To add a markdown description to an endpoint, we can use `// description.markdown` and it will take the markdown content from `<end_point_name>.md` file. (I also tried using `// Description.markdown`)

However none of them are working for me. This is the annotation for my API for reference.
```
// @Summary Get Services
// @Tags services
// @version 1.0
// @description.markdown
// @Accept  json
// @Produce json
// @Param organization_id path string true "organization_id"
// @Success 200 {array} Service
// @Router /organizations/{organization_id}/services [get]
```
**To Reproduce**
1. Place the above annotation above the handler function.
2. create a markdown file inside docs/ called *services.md*
3. Run `swag init --markdownFiles docs` in the parent folder.

**Expected behavior**
I should get the tag description which is present in the services.md file as the tag description in the swagger.yaml file.

**Your swag version**
`swag version v1.6.5`

**Your go version**
`go version go1.13.7 darwin/amd64`

**Comment by sdghchj** [comment]
@description.markdown reads **api.md** from the dir specified by --markdownFiles.
Further more, @description.markdown and @tag.description.markdown must be above func main in main.go, not above handler functions.

**Comment by sdghchj** [comment]
Read README.md carefully and you can reference **swag/example/markdown**

**Comment by shibasisp** [comment]
Thanks for the clarification. I am closing the issue.

**Comment by davisford** [comment]
> @description.markdown reads **api.md** from the dir specified by --markdownFiles.
> Further more, @description.markdown and @tag.description.markdown must be above func main in main.go, not above handler functions.

The docs indicate this is supposed to work at the handler level here: https://github.com/swaggo/swag#api-operation and it is supposed to look for `endpointname.md` file.  This is not working for me.

**Comment by sdghchj** [comment]
@davisford @shibasisp  Have a try like below.
```
// @Summary Get Services
// @Tags services
// @version 1.0
// @description.markdown  endpointname
// @Accept  json
// @Produce json
// @Param organization_id path string true "organization_id"
// @Success 200 {array} Service
// @Router /organizations/{organization_id}/services [get]
```

**Comment by soupdiver** [comment]
> @davisford @shibasisp Have a try like below.
> 
> ```
> // @Summary Get Services
> // @Tags services
> // @version 1.0
> // @description.markdown  endpointname
> // @Accept  json
> // @Produce json
> // @Param organization_id path string true "organization_id"
> // @Success 200 {array} Service
> // @Router /organizations/{organization_id}/services [get]
> ```

I ran into the same issue. This works but I think the docs are a little misleading

**Comment by ubogdan** [comment]
@soupdiver This is an open-source project, feel free and contribute with a PR regarding the misleading documentation and I will be more than happy to assist you with a CR.
