### ISSUE TITLE
Example value for struct does not respect tag `json:",string"`

### ISSUE THREAD

**Issue by tcarreira** [swaggo/swag#665]
**Describe the bug**
If you add the `json:",string"` tag to a struct field, the Response example value does not respect it.
 

**To Reproduce**

Create a struct that tags an int as `json:",string"` 
```
type MyUser struct {
    Name string `json:"name" example:"John Doe"`
    Age  int    `json:"age,string" example:"25"`
}
``` 

and document some API endpoint with
```
// @Success 200 {object} MyUser "My User"`
``` 

Then open the Swagger UI and check the return example

The example given is:
```
{
  "age": 25,
  "name": "John Doe"
}
```
25 is not quoted but the actual Response is.

**Expected behaviour**

The Response example value should be 
```
{
  "age": "25",
  "name": "John Doe"
}
```

**Screenshots**
![Screenshot_20200409_211757](https://user-images.githubusercontent.com/5046551/78951286-fe222880-7aa7-11ea-867d-fe3f208091a6.png)

**Your swag version**
$ swag --version
swag version v1.6.5

**Your go version**
$ go version
go version go1.14.1 linux/amd64

**Comment by sdghchj** [comment]
I see.
json package uses `json:",string"` to change field of golang built-in type to string.
PR, welcome.
