### ISSUE TITLE
Swag parses vendored libraries incorrectly

### ISSUE THREAD

**Issue by kolaente** [swaggo/swag#673]
**Describe the bug**
I have a project with go modules where all my dependencies are located in the `vendor/` directory (created with `go mod vendor`).

When running `swag init` (full command see below) I would expect it to find all needed dependencies and look for them in the `vendor/` directory.
Instead, it tries to find the dependency of a library I'm using in my project (say `library.url/project`) in `vendor/library.url/project/vendor/dependency.url/project` insted of `vendor/dependency.url/project`.

**To Reproduce**
Run `swag init --parseVendor -g pkg/routes/routes.go -o ./pkg/swagger` in https://kolaente.dev/vikunja/api/src/branch/fix/swagger.

Output:
```
swag init --parseVendor -g pkg/routes/routes.go -o ./pkg/swagger;
2020/04/12 21:40:21 Generate swagger docs....
2020/04/12 21:40:21 Generate general API Info, search dir:./
/go/src/code.vikunja.io/api/vendor/code.vikunja.io/web/web.go:18:13: could not import github.com/labstack/echo/v4 (go/build: importGo github.com/labstack/echo/v4: exit status 1
can't load package: package github.com/labstack/echo/v4: cannot find package "." in:
        /go/src/code.vikunja.io/api/vendor/code.vikunja.io/web/vendor/github.com/labstack/echo/v4
```

**Expected behavior**
Generation should work without issues.

**Your swag version**
1.6.5

**Your go version**
1.13.5

**Desktop (please complete the following information):**
 - OS: NixOS 19.09

**Comment by ubogdan** [comment]
@kolaente did you figured it out? can you share with us the rolution?

**Comment by kolaente** [comment]
@ubogdan I did not figure it out yet.

I assume the 1.7.2 version was tagged twice but the first one got picked up by sum.golang.org. A solution would be to publish a 1.7.3 with no changes.

**Comment by ubogdan** [comment]
Yes, the 1.7.2 was tagged twice because I forgot to change the "version.go" before releasing it. I made a new release with version  1.7.3.
