### ISSUE TITLE
gen multiple SearchDir

### ISSUE THREAD

**Issue by dudochkin-victor** [swaggo/swag#682]
is there way to scan few dir's for swagger api?
or what hapening if i call ParseAPI few times?

**Comment by sdghchj** [comment]
you can -exclude multiple dirs or files from top searching dir.

**Comment by dudochkin-victor** [comment]
I have different task. I have a modular structure of project.
So few routes handled one project, other routes handled other project located absolutelly in different repo. Both located on top of $GOPATH.
So i want to parse both repos.

**Comment by sdghchj** [comment]
Use branch `refactored`

**Comment by dudochkin-victor** [comment]
thanks

**Comment by genofire** [comment]
please open this issue again - it is not solved yet
