### ISSUE TITLE
Adding configuration options such as deeplinking/docExpansion

### ISSUE THREAD

**Issue by Stigz** [swaggo/swag#684]
**Is your feature request related to a problem? Please describe.**
I'd like to implement deepLinking for each endpoint (permalink) as well as a `docExpansion: none` which will minimize all the sections, but I haven't been able to figure out how to do this. Normally I would implement it like this: https://github.com/swagger-api/swagger-ui/blob/8dab91f184103be794ae2fcfeb67b02126730e88/docs/deep-linking.md and normally you would put it in the swagger-config.yaml file I think: https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/

**Describe the solution you'd like**
A way to set configuration options like the ones above.

**Describe alternatives you've considered**
Not sure if this already exists or works somehow? I tried adding that swagger-config.yaml file but nothing happened.

New to Swagger/swaggo so I'm not sure if there's already a way!

**Comment by ubogdan** [comment]
Closing: This issue is related to http handlers.

Note: Please check specific implementation. Some of them allready have this feature.
