### ISSUE TITLE
Customize UI

### ISSUE THREAD

**Issue by umeat** [swaggo/swag#685]
Is it possible to customize the Swagger UI with this library? If so, is there any documentation describing how to do it?

**Comment by Stigz** [comment]
Pretty sure this is the same question I have! https://github.com/swaggo/swag/issues/684

**Comment by umeat** [comment]
I _think_ I'm talking about custom layouts: https://swagger.io/docs/open-source-tools/swagger-ui/customization/custom-layout/

**Comment by ubogdan** [comment]
Closing: This issue is related to HTTP handlers.

Note: Please check specific implementation. Some of them already have this feature.
