### ISSUE TITLE
In the controller layer of my pro, i have v2/v3 which i only want to generate v3 api, so i exec "swag init -g ../../main.go -d api/v3" then i cannot parse the object which is in models folder 

### ISSUE THREAD

**Issue by SeaJames** [swaggo/swag#687]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Your swag version**
1.6.5

**Your go version**
1.13.4

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by SeaJames** [comment]
I try add "--parseDependency go list <absolute-pro-dir>/mypro/main.go, but i Got all the v2, v3 api which are not expected

**Comment by sdghchj** [comment]
import the dir where exist models in main.go, and add --parseDependency

**Comment by SeaJames** [comment]
@sdghchj thx
