### ISSUE TITLE
import problem

### ISSUE THREAD

**Issue by Kotodian** [swaggo/swag#689]
If I import a package like nodev1 "lb.io/api/node/v1", I used model nodev1.NodeList as response's model.When I used the command 'swag init',it will return the error 'ParseComment error: schema type: nodev1.NodeList'

**Comment by sdghchj** [comment]
try branch `refactored`

**Comment by Kotodian** [comment]
> try branch `refactored`

it can't be worked

**Comment by Kotodian** [comment]
> try branch `refactored`

execute go list command, exit status 1

**Comment by Kotodian** [comment]
when I use parseDependcy== true 
![image](https://user-images.githubusercontent.com/22030659/80668088-7ee6aa00-8ad3-11ea-842a-24522ca4e4d3.png)

**Comment by sdghchj** [comment]
finally,  it works or not ?

**Comment by Kotodian** [comment]
> finally, it works or not ?

thanks
