### ISSUE TITLE
Model composition in `@param`

### ISSUE THREAD

**Issue by Dot-H** [swaggo/swag#690]
**Is your feature request related to a problem? Please describe.**
I am trying to use the model composition for a `@param` tag.

**Describe the solution you'd like**
It would be great to be able to do model composition for the `@param` as it is done in the `@success`. 

**Describe alternatives you've considered**
Using swaggertype tag in the model structure. Sadly this is a generated structure and I cannot update the attributes.

**Additional context**
Here is what I would be able to do in my comments:
```go
// @Param request body Ctx{extended_data_interface=object} true "Document template to create"
// @Success 201 {object} Ctx{extended_data_interface=object} "Document template created"
```

But I get the error:
```
ParseComment error in file api/routes/document/template/create.go :can not find schema type: "doctemplate.Ctx{extended_data_interface=object}"
```

**Comment by sdghchj** [comment]
try branch `refactored`

**Comment by Dot-H** [comment]
When being on this branch, `swag` dies while creating the models. It says:
```
2020/04/30 16:00:23 Generating doctemplate.Ctx
2020/04/30 16:00:23 Generating models.DocumentsTemplate
2020/04/30 16:00:23 ParseComment error in file api/routes/document/template/create.go :cannot find package path of type: Uint64
```

The `doctemplate.Ctx` struct is like this:
```go
type Ctx struct {
	models.DocumentsTemplate
	DocumentData []string `json:"document_data"`
}
```

And `models.DocumentsTemplate`:
```go
type DocumentsTemplate struct {
	ID                    uint64      `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatorUUID           null.Uint64 `boil:"creator_uuid" json:"creator_uuid,omitempty" toml:"creator_uuid" yaml:"creator_uuid,omitempty"`
	Name                  string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	ExtendedDataInterface types.JSON  `boil:"extended_data_interface" json:"extended_data_interface" toml:"extended_data_interface" yaml:"extended_data_interface"`
	Description           null.String `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`

	R *documentsTemplateR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L documentsTemplateL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}
```

This structure was parsed well when being in the `@success` tag on branch `master`.

**Comment by sdghchj** [comment]
@Dot-H 
package `null` have not been parsed.

when running `swag init`, -d can be set multiple dirs.

another way, import package `null` in your main.go, and set --parseDependency when running `swag init`.

**Comment by Dot-H** [comment]
I have tried both of your recommendations and it still does not work.

**Comment by sdghchj** [comment]
pull and try again

**Comment by Dot-H** [comment]
Thanks for the update. I have tried to pull and run it again. It dies a bit further.

The error is:
```
2020/05/01 07:51:01 Generating models.DocumentsTemplate
2020/05/01 07:51:01 Generating null.Uint64
2020/05/01 07:51:01 Generating types.JSON
2020/05/01 07:51:01 ParseComment error in file api/routes/document/template/create.go :cannot find package path of type: RawMessage
```

Which is defined as
```go
import (
	"encoding/json"
)

type JSON json.RawMessage
```
and is the actual type of `types.JSON` from `DocumentsTemplate`.

I used the `--parseDependency` with
```go

	_ "encoding/json"

	_ "github.com/volatiletech/null"
	_ "github.com/volatiletech/sqlboiler"
```

package `types` being at `github.com/volatiletech/sqlboiler/types`, adding or removing it from the import did not change anything.

**Comment by sdghchj** [comment]
—parseDependency ignored internal package by others’ PR long time ago

**Comment by Dot-H** [comment]
That's a bummer. So I have tried passing the package containing the `RawMessage` definition to the command but it seems that, even though the parsing is done, `RawMessage` is not found.

The command I used is:
```bash
swag init --parseDependency --dir './,/usr/local/go/src/encoding/json/'
```

And the logs:
```
2020/05/01 08:19:17 Generate swagger docs....
2020/05/01 08:19:17 Generate general API Info, search dir: ./
2020/05/01 08:19:18 Generate general API Info, search dir: /usr/local/go/src/encoding/json/
2020/05/01 08:19:41 Generating doctemplate.Ctx
2020/05/01 08:19:41 Generating models.DocumentsTemplate
2020/05/01 08:19:41 Generating null.Uint64
2020/05/01 08:19:41 Generating types.JSON
2020/05/01 08:19:41 ParseComment error in file api/routes/document/template/get.go :cannot find package path of type: RawMessage
```

**Comment by sdghchj** [comment]
I see json.RawMessage is marshaled as raw byte array.
Maybe you can use tag `swaggertype` as bellow:
```
type Sample struct{
       RawMsg json.RawMessage `swaggertype:"array,integer"`
}
```

**Comment by sdghchj** [comment]
A new update,``` swag init --parseDependency --dir './,/usr/local/go/src/encoding/json/' ```  works

**Comment by Dot-H** [comment]
Working like a charm :+1: 
I am now able to do `// @Param request body Ctx{extended_data_interface=object} true "Document template to create"`

Thanks a lot for your time and reactivity :slightly_smiling_face: 

Do you think it is safe to use this branch to build a documentation ? Or should I stick to a specific commit ?

**Comment by sdghchj** [comment]
As you like.
You can use it to regenerate your swagger docs and compare with old ones.
I think master branch is in such a mass and need to be refactored,  so I have made a lot of changes in branch `refactored`.  But I am not the owner of this repository, and code review may cost lots of time, so there may be a certain long time waiting for members in swaggo team's permission to review and merge .

**Comment by Dot-H** [comment]
Mokay. I think I will stick to the current commit on `refactored`. Thanks again !
