### ISSUE TITLE
Add default response annotation

### ISSUE THREAD

**Issue by jancona** [swaggo/swag#691]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to define a default response for an operation, as described here: https://swagger.io/docs/specification/2-0/describing-responses/#default

**Describe the solution you'd like**
In addition to `@produce` and `@error` add a similar new tag `@default` that generates the default response definition.

**Describe alternatives you've considered**
I don't see an alternative other than generating all possible responses for every operation.

**Additional context**
If you think this would be valuable, I can put a PR together.

**Comment by sdghchj** [comment]
It's valuable, PR is welcome

**Comment by easonlin404** [comment]
@jancona Hi, https://github.com/swaggo/swag/pull/837 support default response by using _default_ keyword.
