### ISSUE TITLE
Map Type problem

### ISSUE THREAD

**Issue by Kotodian** [swaggo/swag#694]
**Describe the bug**
![image](https://user-images.githubusercontent.com/22030659/81138124-7f7bb680-8f93-11ea-95bf-634c2a12e5c6.png)
If I want to use swaggertype.How to define it.
ps.MediaType is string  

**Screenshots**
It report this problem
![image](https://user-images.githubusercontent.com/22030659/81138078-50fddb80-8f93-11ea-80ae-26df1091d344.png)

**Your swag version**
e.g. 1.6.5

**Your go version**
e.g. 1.13.0

**Comment by sdghchj** [comment]
Try latest `master` or `refacored` branch, please.

**Comment by Kotodian** [comment]
> Try latest `master` or `refacored` branch, please.

swag version 1.6.5 isn't the latest?

**Comment by sdghchj** [comment]
> > Try latest `master` or `refacored` branch, please.
> 
> swag version 1.6.5 isn't the latest?

yes. master is forward.
