### ISSUE TITLE
Additional Properties, Declarative Comments and Returning Map

### ISSUE THREAD

**Issue by sculler** [swaggo/swag#696]
I've searched all over but I've had no luck. How do I use the [declarative comments](https://github.com/swaggo/swag#declarative-comments-format) format to specify a @success response returns a map[string]bool? I know I need to do something with additionalProperties but can't figure out how that's added in the declarative comments. Thanks!

**Comment by sdghchj** [comment]
Checkout latest version.
```
// @sucess  200 {object} map[string]bool "description"
```

**Comment by sculler** [comment]
I'm using version 1.65. When I run swag init it returns: 

`can not find schema type: "handler.map"`

using this:

`// @Success 200 {object} map[string]bool "feature"`

**Comment by sdghchj** [comment]
> I'm using version 1.65. When I run swag init it returns:
> 
> `can not find schema type: "handler.map"`
> 
> using this:
> 
> `// @Success 200 {object} map[string]bool "feature"`

Latest master branch or refactoed branch
