### ISSUE TITLE
Ignore protobuf generate useless field

### ISSUE THREAD

**Issue by binwan-dev** [swaggo/swag#698]
Hi, I directly use the class generated by the pb.go file in the project as the web request return body. One problem is that the private fields  generated by protobuf in pb.go cannot be automatically ignore and the lowercase of the first letter of the field cannot be set . this is not swagger problem,  set swaggerignore and json tag can be solved this problem,  but must manual set it every time when pb.go is regenerated.
Is it possible to add a setting to automatically ignore these useless fields of protobuf.

There is pb.go files
![image](https://user-images.githubusercontent.com/45676208/81788032-79a64800-9534-11ea-9b32-88f510888b09.png)
state,sizeCache,unknowFields is not ignore.
![image](https://user-images.githubusercontent.com/45676208/81788669-78294f80-9535-11ea-8ab2-337c8dbd347b.png)

and i'm fork swag project , modify parser.go 
![image](https://user-images.githubusercontent.com/45676208/81788388-07823300-9535-11ea-9cf8-b6395e832e83.png)
state,sizeCache,unknowFields is ignore.

![image](https://user-images.githubusercontent.com/45676208/81788531-3b5d5880-9535-11ea-8700-774524b88cdc.png)

Is it possible to add a parameter setting can ignore protobuf useless fields

**Comment by sdghchj** [comment]
Try latest `master` or `refactored` branch
