### ISSUE TITLE
tag swaggerignore not working

### ISSUE THREAD

**Issue by magvan** [swaggo/swag#699]
https://github.com/swaggo/swag#use-swaggerignore-tag-to-exclude-a-field not working

$ swag -v
swag version v1.6.5

$ go version
go version go1.13.8 linux/amd64

type User struct {
    UpdatedAt time.Time `json:"updated_at" example:"2019-08-12T09:50:15.166906Z" swaggerignore:"true"`
    Features Features `json:"features" gorm:"-" swaggerignore:"true"`
}

**Comment by comphilip** [comment]
@magvan v1.6.5 is not sync with latest master commits. I have no idea the release policy of this projects. You can fix by `go get -u github.com/swaggo/swag/cmd/swag`

**Comment by sdghchj** [comment]
@easonlin404  Could you please release v1.6.6?
