### ISSUE TITLE
Alias typecould not resolve

### ISSUE THREAD

**Issue by epolar** [swaggo/swag#700]
**Describe the bug**
Resolver error at paths./ad/all.get.responses.200.schema.items.properties.status.$ref
Could not resolve reference because of: Could not resolve pointer: /definitions/web.T does not exist in document

**To Reproduce**
```golang
// APIError example
type APIError struct {
	ErrorCode    int
	ErrorMessage string
	CreatedAt    time.Time
	Type         APIType
}
type T uint8

type APIType 
```

**Expected behavior**
generate 
```
"web.T": {
            "type": "integer"
        },
```

**Your swag version**
1.6.5

**Your go version**
go1.13.5 darwin/amd64

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4

**Comment by sdghchj** [comment]
Does web.T has anything to do with  /definitions/repo.Type?
A little more detailed to make your question clear, please.

**Comment by epolar** [comment]
> Does web.T has anything to do with /definitions/repo.Type?
> A little more detailed to make your question clear, please.

I'm sorry. My problem is swag does not parse alias type to swagger definition,  cause $ref could not resolve reference. Maybe is because swag is not recursive parse source code.

**Comment by sdghchj** [comment]
pull latest commit and try again

**Comment by epolar** [comment]
> pull latest commit and try again

Not work, 

> pull latest commit and try again

I push my code to https://github.com/epolar/swag.git, 
generate swag docs by `swag init --dir example/basic --output example/basic/docs`
run sample by `go run example/basic/main.go`
will reproduce my problem, pls, help me.

**Comment by sdghchj** [comment]
Got it.
Try branch `refactored`. It works.

**Comment by epolar** [comment]
> Got it.
> Try branch `refactored`. It works.

I'm sorry, it doesn't work for me.

**Comment by sdghchj** [comment]
> I'm sorry, it doesn't work for me.

I tried just now, refactored branch  works well

**Comment by epolar** [comment]
> > I'm sorry, it doesn't work for me.
> 
> I tried just now, refactored branch works well

Do you append this code on example/basic/handler.go?
```
// RevValue example
type RevValue struct {
	RevValueBase

	Data int     `json:"Data"`
	Type APIType `json:"type"`
}

type T uint8

type APIType T
```

Models/APIType is empty struct, but should be integer type.

**Comment by sdghchj** [comment]
```
git checkout refactored
```
rebuild swag binary

**Comment by sdghchj** [comment]
> Do you append this code on example/basic/handler.go?
> 
> ```
> // RevValue example
> type RevValue struct {
> 	RevValueBase
> 
> 	Data int     `json:"Data"`
> 	Type APIType `json:"type"`
> }
> 
> type T uint8
> 
> type APIType T
> ```
> 
> Models/APIType is empty struct, but should be integer type.

Sure.
Have you tried as I said?

**Comment by epolar** [comment]
> > Do you append this code on example/basic/handler.go?
> > ```
> > // RevValue example
> > type RevValue struct {
> > 	RevValueBase
> > 
> > 	Data int     `json:"Data"`
> > 	Type APIType `json:"type"`
> > }
> > 
> > type T uint8
> > 
> > type APIType T
> > ```
> > 
> > 
> > Models/APIType is empty struct, but should be integer type.
> 
> Sure.
> Have you tried as I said?

Think you, it works!

**Comment by epolar** [comment]
throw error on more complex project: ParseComment error in file $go_file_path :cannot find package path of type: $type

**Comment by sdghchj** [comment]
> throw error on more complex project: ParseComment error in file $go_file_path :cannot find package path of type: $type

What is $type?  Identifier starts with $ ?

**Comment by epolar** [comment]
> > throw error on more complex project: ParseComment error in file $go_file_path :cannot find package path of type: $type
> 
> What is $type? Identifier starts with $ ?

just a hold character
2020/05/21 14:01:18 ParseComment error in file service/consumer/controller/acceptor.go :cannot find package path of type: RegisterCode`

**Comment by epolar** [comment]
@sdghchj I have comment on controller.go:
```
// @Tags order
// @Security ApiKeyAuth
// @Summary place order
// @Param body body req.PlaceOrder true "param"
// @Success 201 {object} response.Order
// @Router /deal/order [post]
```
but I had not import `response` package. `import (_ "response")` resolve this case.

**Comment by sdghchj** [comment]
> @sdghchj I have comment on controller.go:
> 
> ```
> // @Tags order
> // @Security ApiKeyAuth
> // @Summary place order
> // @Param body body req.PlaceOrder true "param"
> // @Success 201 {object} response.Order
> // @Router /deal/order [post]
> ```
> 
> but I had not import `response` package. `import (_ "response")` resolve this case.

Import of package path is necessary in branch `refactored`.
Imagine a case that two or more models with the same name from different packages.
So, `import _  response` is required.

**Comment by sdghchj** [comment]
a.go
```
import xxx/yyy/response

response.Order
```

b.go
```
import aaa/bbb/response

response.Order
```

c.go
```
import response aaa/bbb/ccc

response.Order
```

**Comment by epolar** [comment]
> a.go
> 
> ```
> import xxx/yyy/response
> 
> response.Order
> ```
> 
> b.go
> 
> ```
> import aaa/bbb/response
> 
> response.Order
> ```
> 
> c.go
> 
> ```
> import response aaa/bbb/ccc
> 
> response.Order
> ```

You are right. Implicit package name maybe ambigous.
