### ISSUE TITLE
How to return struct in struct?

### ISSUE THREAD

**Issue by juwell** [swaggo/swag#702]
i don't know how to describe my problem, just thought the title:joy:
please look below:
//----------------------------------------------------------------------------------
i want return like this: `CommReply{Data:OneInfo{}}`

there is some structs define:

```go
// package define
type UserEntity struct {
	Nickname string `json:"nickname,omitempty"`
	Avatar   string `json:"avatar,omitempty"`
	Gender   int    `json:"gender,omitempty"`
}

// package form
type CommReply struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

// package form
type OneInfo struct {
	Content string `json:"content"`
	From define.UserEntity `json:"from" swaggertype:"object"` // UserEntity define in define package
	To []define.UserEntity `json:"to" swaggertype:"array,object"`
}
```

so i write the return annotations like this:

`// @success 0 {object} form.CommReply{data=[]form.OneInfo}`

the result is, docs make success, but when i click the interface in swagger ui, it show en error:

```
Resolver error at paths./v1/work/do.post.parameters.0.schema.properties.to.items.$ref

Could not resolve reference: Could not resolve pointer: /definitions/define.UserEntity does not exist in document
```
//---------------------------------------------------------------------------------

so, what is the problem? 

sorry for my poor english....

**Comment by sdghchj** [comment]
Model `define.UserEntity` has not been generated yet.
define.UserEntity 没有被解析生成definition。

You had better check whether the definition of define.UserEntity is in your seaching dir.
你确定一下搜索目录里是否有define.UserEntity的类型定义

If not, you have to import the package path of  define.UserEntity in your main.go, and add flag`--parseDependency` when you run `swag init`.
如果没有，找到它定义所在包路径，在main.go里import，执行`swag init --parseDependency`

**Comment by juwell** [comment]
the definition is not in my seaching dir, but the `import` is added

i tried to use `parseDependency`, the compile become very very slow, is it normal?

**Comment by sdghchj** [comment]
> i tried to use `parseDependency`, the compile become very very slow, is it normal?

That depends
