### ISSUE TITLE
Possible to combine two swagger json files?

### ISSUE THREAD

**Issue by WLun001** [swaggo/swag#707]
**Is your feature request related to a problem? Please describe.**
I have 2 swagger definitions. One is generated from `Swag`, another is `proto-gen-swagger`.
Possible to combine two definitions during `swag init?

maybe something like this
```shell
swag init --file apidocs.json
```

So the output docs will have the definitions parsed from source code with `swag` and `apidocs.json`

**Comment by ubogdan** [comment]
@WLun001 Event if this is doable from a programming perspective it may not be feasible because you may end up having conflicts or mismatches due to the way the 2 generators you are handling definitions generation.
