### ISSUE TITLE
Add Swagger Bearer Authentication Scheme

### ISSUE THREAD

**Issue by mplachter** [swaggo/swag#709]
**Is your feature request related to a problem? Please describe.**
Not having this feature creates a poor user experience if the services uses Bearer Token authentication. 

**Describe the solution you'd like**
https://swagger.io/docs/specification/authentication/bearer-authentication/

Would like to have another @security annotation maybe `@securitydefinitions.bearer`

**Describe alternatives you've considered**
Adding Description into the header for auth which means the user still has to enter it before they enter their Token into the authorization header field in swagger docs.

**Additional context**
This is supported in Swagger 2.0 and Up.

**Comment by mplachter** [comment]
Opened this as I see you leverage the go-openapi to validate schemes https://swagger.io/docs/specification/authentication/bearer-authentication/

**Comment by mplachter** [comment]
Ah so bearer authentication is only for 3.0... I guess the better question would be when would swaggo move to 3.0 API spec

**Comment by naftulikay** [comment]
Running into this now, so is the current state that we can't do more than just:

```text
// @securityDefinitions.apiKey JWT
// @in header
// @name Authorization
```

Or is there a way within the latest release to specify bearer-type authorization?

**Comment by ubogdan** [comment]
We may switch to OAS3 in v2. Meanwhile, you need to use the securityDefinition.ApiKey as an alternative.

**Comment by raulfortes** [comment]
Any news about this ?

**Comment by ialekseychuk** [comment]
I used custom solution - post processing

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	// Читаем сгенерированный swagger.json
	swaggerData, err := os.ReadFile("docs/swagger.json")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to read swagger.json: %v\n", err)
		os.Exit(1)
	}

	// Читаем шаблон securitySchemes
	templateData, err := os.ReadFile("docs/bearer.json")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to read security_template.json: %v\n", err)
		os.Exit(1)
	}

	var swagger, template map[string]interface{}
	if err := json.Unmarshal(swaggerData, &swagger); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to unmarshal swagger.json: %v\n", err)
		os.Exit(1)
	}
	if err := json.Unmarshal(templateData, &template); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to unmarshal security_template.json: %v\n", err)
		os.Exit(1)
	}

	// Преобразуем в OpenAPI 3.0
	swagger["openapi"] = "3.0.0"
	delete(swagger, "swagger") // Удаляем метку OpenAPI 2.0

	// Объединяем components.securitySchemes
	if components, ok := template["components"].(map[string]interface{}); ok {
		swagger["components"] = components
	}

	// Сохраняем преобразованный swagger.json
	output, err := json.MarshalIndent(swagger, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to marshal swagger JSON: %v\n", err)
		os.Exit(1)
	}

	err = os.WriteFile(filepath.Join("docs", "swagger.json"), output, 0644)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write swagger.json: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Swagger documentation post-processed successfully")
}

and json template for bearer

{
  "components": {
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": "Bearer token (JWT) for authentication. Format: Bearer <token>"
      }
    }
  }
}
