### ISSUE TITLE
how to use x-order=n ?

### ISSUE THREAD

**Issue by YankeeTube** [swaggo/swag#715]
i have user struct and then declare `extensions:"x-order=1"`  

![image](https://user-images.githubusercontent.com/34546950/82874180-897c4e00-9f70-11ea-8797-4d6ef2be3961.png)

but `swag init` generate to   
![image](https://user-images.githubusercontent.com/34546950/82874314-b7619280-9f70-11ea-878e-0a72999995d5.png)

Is there a way to ensure the order?

**Comment by sdghchj** [comment]
I am afraid not now, refer to [go-openapi/spec](https://github.com/go-openapi/spec/issues/24)

**Comment by sdghchj** [comment]
try github/sdghchj/spec which is forked from  github/go-openapi/spec by using cmd `replace` in your go.mod file

**Comment by sdghchj** [comment]
My PR to github/go-openapi/spec has been merged. You can checkout the latest commit to confirm.

**Comment by YankeeTube** [comment]
tk @sdghchj 
but 
I don't understand why you didn't do PR on "github.com/swaggo/swag" and did it on "github/go-openapi/spec."

**Comment by sdghchj** [comment]
github/go-openapi/spec provides the basic data structure of swagger，in which fields of a struct are stored as a map.
As we know，json orders keys alphabetically in default when marshaling a map object.

**Comment by YankeeTube** [comment]
@sdghchj 
i updated last swag but doesn't work x-order

**Comment by sdghchj** [comment]
> @sdghchj
> i updated last swag but doesn't work x-order
Change  the version of  github/go-openapi/spec to the latest commit  in  swag's go.mod

**Comment by foxluqi** [comment]
> > @sdghchj
> > i updated last swag but doesn't work x-order
> 
> Change the version of github/go-openapi/spec to the latest commit in swag's go.mod

waiting swaggo update go.mod

**Comment by rosehsu47** [comment]
> 

same here, x-order key appears in the swagger.yaml file, but the result on the site is still ordered by alphabet

**Comment by venomuz** [comment]
> >

Same problem with me

**Comment by HansAlbertLianto** [comment]
Can confirm the above two comments. Given a struct like this:
```
type SomeType struct {
	bField string `extensions:"x-order:1"`
	dField string `extensions:"x-order:2"`
	aField string `extensions:"x-order:3"`
	cField string `extensions:"x-order:4"`
}
```

The `swagger.yaml` doesn't return fields in the intended order.
```
types.SomeType:
    properties:
      aField:
        type: string
        x-order:3: true
      bField:
        type: string
        x-order:1: true
      cField:
        type: string
        x-order:4: true
      dField:
        type: string
        x-order:2: true
```

Using `github.com/swaggo/swag v1.8.10` and `github.com/go-openapi/spec v0.20.8 // indirect` in `go.mod`, where v0.20.8 should be the version where you modified go-openapi/spec. Can check again if there's anything we can do to fix this @sdghchj?

**Comment by sdghchj** [comment]
> > 
> 
> same here, x-order key appears in the swagger.yaml file, but the result on the site is still ordered by alphabet

I guess you have to upgrade version of `github.com/swaggo/files`

**Comment by sdghchj** [comment]
@HansAlbertLianto 
@all
First,  We have use a higher version of swag tool built with higher versions of `github.com/swaggo/files` and `github.com/go-openapi/spec`, to generate struct fields in order.
Then in our projects, we also shoud import a higher version of `github.com/swaggo/files` to render the page

**Comment by halon176** [comment]
> @HansAlbertLianto @ALL First, We have use a higher version of swag tool built with higher versions of `github.com/swaggo/files` and `github.com/go-openapi/spec`, to generate struct fields in order. Then in our projects, we also shoud import a higher version of `github.com/swaggo/files` to render the page

Still the same issue
```
	github.com/swaggo/files v1.0.1
	github.com/go-openapi/spec v0.21.0

```

struct is like 

```
type SendEmailRequest struct {
	To       []string     `json:"to" extensions:"x-order:0" `
	Subject  string       `json:"subject" extensions:"x-order:1"`
	Body     string       `json:"body" extensions:"x-order:2"`
```

doesn't preserve order in generated documentation

```
        "emails.SendEmailRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string",
                    "x-order:2": true
                },
                "cc": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "x-order:3": true,
                    "example": [
                        ""
                    ]
                },
             ....
                "subject": {
                    "type": "string",
                    "x-order:1": true
                },
                "to": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "x-order:0": true
                }
```
the order appears to be alphabetical

**Comment by your-diary** [comment]
Is this issue really closed *as completed*?.
If not, I think it should be re-opened.

**Comment by Dieg0Code** [comment]
hahaha I was struggling with this for quite some time. Nice ♥♥♥

**Comment by olivatooo** [comment]
Do I need to use `x-order=0` on EVERY FIELD? This looks incorrect
