### ISSUE TITLE
接口如何排序？

### ISSUE THREAD

**Issue by kgdxpr** [swaggo/swag#716]

**Comment by sdghchj** [comment]
你想怎么排序

**Comment by zhengpeiqiang** [comment]
能不能根据方法在go文件内的位置生成swagger.json也按照那个顺序，而不是按照字母顺序

**Comment by sdghchj** [comment]
swag只是一个文档生成工具，使用的数据结构是[go-openapi/spc](https://github.com/go-openapi/spc)项目定义的，大量用到了go的map，没法保证原始顺序；然后前端界面又是gin-swagger等项目根据接口的tags进行分类处理展示的。另外go文件又不可能只有一个。如果有想法可以深入了解源码，contribution is welcome.
@zhengpeiqiang

**Comment by xiaofeichuan** [comment]
同问这个问题，有没有方法根据go文件方法排序。

**Comment by 20gu00** [comment]
有解决排序的方法么

**Comment by sdghchj** [comment]
上面已经说了，swag是按照[go-openapi/spc](https://github.com/go-openapi/spc)规范生成swagger内容结构数据，至于如何渲染成前端页面不在swag工具功能范围之内，最多是配合做一些排序上的配置，前提我猜应该是https://github.com/swaggo/files这个项目的支持，对前端我不太了解，所以帮不上忙。
