### ISSUE TITLE
can't generate definitions when use  struct alias

### ISSUE THREAD

**Issue by hutu1st** [swaggo/swag#718]
**Describe the bug**
can't generate definitions when user struct alias

**To Reproduce**

1、comment contains this
// @Success  200 {object} Res  "ok"

2、struct

type JsonTime time.Time  // give a alias

// Res is used to response
type Res struct {
     Name       string
     CreateAt JsonTime
}

3、After execute command `swag init`, you can see  definitions like this in docs.go and swagger.json

"JsonTime": {
            "$ref": "#/definitions/time.Time"
}

4、open swagger web page, you'll see  Resolver error : /definitions/time.Time does not exist in document

**Expected behavior**
 I think JsonTime can be given a type like "object" or time.Time must be added in definitions
 
**Screenshots**

![image](https://user-images.githubusercontent.com/48120621/83258587-18939b00-a1e9-11ea-9a7e-c0f6f8ff344a.png)

**Your swag version**
swag version v1.6.5

**Your go version**
go version go1.13.5 darwin/amd64

**Desktop (please complete the following information):**
 - OS: [masos]
 - Browser: [chrome]

**Comment by sdghchj** [comment]
Use `refactored` branch

**Comment by hutu1st** [comment]
> Use `refactored` branch

Can you make it clear? I don't quite understand -，-

**Comment by hutu1st** [comment]
> Use `refactored` branch

sorry，I'll try refactored branch

**Comment by hutu1st** [comment]
Yes, I solved it by use refactored branch, thanks sdghchj's answer  very much!!!
