### ISSUE TITLE
does it support without main.go

### ISSUE THREAD

**Issue by xiaogu-space** [swaggo/swag#722]
if i rename main.go to web.go ,does it support ?

**Comment by sdghchj** [comment]
No, however , you can give  an empty go source file

**Comment by xiaogu-space** [comment]
OK

**Comment by sdghchj** [comment]
Sorry, I mean a main file is a must, and it can be named anything. If not named main.go, you have to set it in command line
```
swag init -g web.go
```

**Comment by xiaogu-space** [comment]
> Sorry, I mean a main file is a must, and it can be named anything. If not named main.go, you have to set it in command line
> 
> ```
> swag init -g web.go
> ```
but I get the error
Incorrect Usage: flag provided but not defined: -g

**Comment by sdghchj** [comment]
> > Sorry, I mean a main file is a must, and it can be named anything. If not named main.go, you have to set it in command line
> > ```
> > swag init -g web.go
> > ```
> 
> but I get the error
> Incorrect Usage: flag provided but not defined: -g

That's a bug.

Should be: 

```
swag init -generalInfo web.go
```

**Comment by xiaogu-space** [comment]
Thanks
