### ISSUE TITLE
How to add annotate to display download file？

### ISSUE THREAD

**Issue by kcgp007** [swaggo/swag#726]
I want to display **download file** in **swagger/index.html**.

But I don’t know what **{param type}, data type** should be written behind **@success 200**.

**Comment by jozuenoon** [comment]
I would bet for something like above for pdf download:
```
// @Produce  application/pdf
// @Success 200 {file} binary
```

However, on swagger doc page I'm still getting:
```
Response body
Unknown response type
```

Maybe someone can give an advice?

**Comment by kitonaoto** [comment]
```
type PdfFile io.Writer

// @Success 200 {file} PdfFile
```
it will be fine

**Comment by kcgp007** [comment]
@kitonaoto @jozuenoon Thank you very much, this is a feasible solution:

`// @Success 200 {file} file`
