### ISSUE TITLE
Swag does not find package types

### ISSUE THREAD

**Issue by kolaente** [swaggo/swag#737]
**Describe the bug**
I have a project whose swag annotations reference an external type contained in the `vendor/` folder. To make swag recognize this, I call swag with the `--parseVendor` option. When I add that option the errors about swag not being able to find the type go away, but then swag seems to be incapable to find types from other packages _within my project_:

```
$ swag init --parseVendor --parseInternal -g pkg/routes/routes.go -o ./pkg/swagger;
2020/06/13 21:21:41 Generate swagger docs....
2020/06/13 21:21:41 Generate general API Info, search dir:./
2020/06/13 21:21:49 ParseComment error in file pkg/routes/api/v1/login.go :can not find type def: "user.UserLogin" error: type spec not found
```

The `user.UserLogin` is a struct which is located in the `pkg/users` package of my project.

**Expected behavior**
Generation succeeds without issues.

**Your swag version**
1.6.7

**Your go version**
1.14

**Additional context**
The project can be found [here](https://kolaente.dev/vikunja/api).

**Comment by sdghchj** [comment]
Is it an alias type?

**Comment by kolaente** [comment]
No, not an alias. A simple struct:

```golang
type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
```

It does not always fail with that type though. For some runs it fails with a different struct but always the same pattern. (I assume this has to do with parallelization of the parser)

**Comment by sdghchj** [comment]
That's strange, maybe you have to debug it yourself.
I checked out your project and tried with swag v1.6.7, many errors about web.HTTPError.

I see many comment lines like
 `// @Failure 400 {object} code.vikunja.io/web.HTTPError "Something's invalid."`
 in your project, but `code.vikunja.io/web.HTTPError` is not supported, as I see.

**Comment by kolaente** [comment]
>  but `code.vikunja.io/web.HTTPError` is not supported, as I see.

`web.HTTPError` isn't either. But as I described in the initial comment of this issue, swag is able to find the struct from the `code.vikunja.io/web` package with the `--parseVendor` flag, but no other structs from different packages inside of my projects.

**Comment by joelazar** [comment]
I came across something similar today with the latest version. This was the output for me:
```
▶ swag init --generalInfo ./cmd/am-api/main.go
2020/06/29 16:39:49 Generate swagger docs....
2020/06/29 16:39:49 Generate general API Info, search dir:./
2020/06/29 16:39:49 warning: failed to get package name in dir: ./, error: execute go list command, exit status 1, stdout:, stderr:can't load package: package .: no Go files in /home/joelazar/git/work/backend/am-
api
2020/06/29 16:39:49 Generating models.User
2020/06/29 16:39:49 Generating models.Model
2020/06/29 16:39:49 ParseComment error in file pkg/handlers/invitation_handler.go :cannot find type definition: pq.StringArray
```
And I didn't have the time to look into this deeper, but reverting to 1.6.5 version apparently fixed it for me.

**Comment by sdghchj** [comment]
@joelazar Yes, old version will parse definitions from outside current directory if they are in API comments, but won't pass those ones which are members of structs. It's an incomplete feature, I think, so I removed it in latest refactored version and it can be achieved in another way '--parseDependency'.

**Comment by joelazar** [comment]
oh, I see, thank you, parseDependecy did make the trick there.
