### ISSUE TITLE
can not support prt type in struct ??  (在struct里面 有指针类型或者匿名继承的字段，无法自动解析到 swagger)

### ISSUE THREAD

**Issue by majintao** [swaggo/swag#741]
can not support prt type in struct ??  (在struct里面 有指针类型或者匿名继承的字段，无法自动解析到 swagger)

**Comment by sdghchj** [comment]
Show your example and swag version

**Comment by majintao** [comment]
just like this

**Comment by majintao** [comment]
version： the last release ，just like this， HostPost  and UserInfo  show as string ，i must  write the tag to fomart it to object ？？

type ActivityRankInfo struct {
	Id       int
	Rank     int
	Point    float64
	Name     string
	TopTitle string
	GiftId   int
	GroupId  int
	HostPost *fPartUser
	UserInfo *fPartUser
}

**Comment by sdghchj** [comment]
fPartUser 是个什么东西？

**Comment by majintao** [comment]
哦 fPartUser 一个 struct  用户信息，就这样 放个指针  被解析成 HostPost 是个string 不是obj

**Comment by sdghchj** [comment]
fPartUser是别名类型吗？

**Comment by sdghchj** [comment]
正常情况下没有复现

**Comment by majintao** [comment]
可以的话 再example里面添加 这样的复杂实例   组合和匿名嵌套 和 指针类型的组合用例

**Comment by sdghchj** [comment]
给出你的详细example再说

**Comment by hutu1st** [comment]
> 正常情况下没有复现

你好，可以帮忙看看 #747 问题吗
