### ISSUE TITLE
Support Markdown Files at API Method Level

### ISSUE THREAD

**Issue by Osiris1975** [swaggo/swag#742]
**Is your feature request related to a problem? Please describe.**
I had a request to insert some rather long documentation for the description of a particular handler. The `@tag.markdown` feature only supports using markdown files at the API level for a particular endpoint. 

**Describe the solution you'd like**
I'd like to be able to use the markdown tag to use a markdown tile for the description for a specific API method (ex: POST) for a particular API. 

**Describe alternatives you've considered**
I ended up using about 15 @Description tags for the swaggo annotations for the particular endpoint. 

**Additional context**
This is what I get using the current features, which involves using the @tag.markdown and @tag.name combination above main.go:
![Screen Shot 2020-07-02 at 5 32 29 PM](https://user-images.githubusercontent.com/12798364/86411544-1494e600-bc8b-11ea-85bd-7d0d62da1398.png)

This is what I ended up doing by using multiple @Description tags on the handler:
![Screen Shot 2020-07-02 at 2 17 10 PM](https://user-images.githubusercontent.com/12798364/86411613-355d3b80-bc8b-11ea-9ea2-3dfb1b5fd5f9.png)

I would've preferred to be able to use a markdown file.

**Comment by sdghchj** [comment]
Swag already supports tag @description.markdown at method level.

**Comment by Osiris1975** [comment]
Okay, it's been kind of hard following the documentation so it might help to make it a bit clearer or have more examples.
