### ISSUE TITLE
Flaky results in uniqueness of model names from different packages

### ISSUE THREAD

**Issue by krishna-birla** [swaggo/swag#745]
**Describe the bug**
Flaky results in maintaining unique model names after https://github.com/swaggo/swag/pull/736

**To Reproduce**
- Have two models (structs) with same name in different packages (same package name but different parent folders).
###### For example in a project called `Awesome`, a struct called `Message` is in two packages, namely `foo` (Awesome/foo) and `foo` (Awesome/pkg/foo).
- Built swagger files again and again, and it shows flaky results.

**Expected behavior**
The struct names should be: `github.com_Awesome_foo.Message` and `github.com_Awesome_pkg_foo.Message`

**Actual behavior**
Sometimes the struct names are `github.com_Awesome_foo.Message` and `foo.Message`.
###### Only one conflicted struct is handled
Other times it is `github.com_Awesome_pkg_foo.Message` and `foo.Message`.

**Your swag version**
e.g. 1.6.7

**Your go version**
e.g. 1.14.4

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Browser: Safari
 - Version:

**Additional context**
I would expect that in case of conflict, ideally all conflicted structs should take up full names.

**Comment by sdghchj** [comment]
I think a stable result is enough

**Comment by sdghchj** [comment]
Sorry, I have not found a better way to make it stable.

**Comment by krishna-birla** [comment]
I am not able to test this, as `$ go get -u github.com/swaggo/swag/cmd/swag` is pulling v1.6.7 tag, not master. How can I pull master code of this repo?

**Comment by krishna-birla** [comment]
@sdghchj Thanks for the super quick action!

Please let me test this.

**Comment by sdghchj** [comment]
@sdghchj I known where the problem is, but have not got a proper idea to fix it.

**Comment by krishna-birla** [comment]
Okay, please keep the issue open in that case. Sooner or later this will need fixing for sure.
