### ISSUE TITLE
当struct中有指向自己的指针时，执行swag init 会出现panic

### ISSUE THREAD

**Issue by hutu1st** [swaggo/swag#747]
**Describe the bug**
当struct中有指向自己的指针时，执行swag init 会出现panic

**To Reproduce**
1、我想创建一个Account的struct，里面有一个属性，母账户，指向自己，如下：
// Account 账户表
type Account struct {
	Id              uint              `db:"id" json:"Id"`                          // 账户id
	ParentAccount   *Account          `db:"-" json:"ParentAccount"`                // 母账户
}
2、在注释中有这么一行 
//@Success  200 {object} Account "ok"

3、执行swag init 会出现panic

对了，我使用的是 refactored 分支

**Comment by sdghchj** [comment]
是最新的refactored 分支吗？
我试了这种情况不会panic呀。

**Comment by hutu1st** [comment]
拉了新分支试了一下，可以，多谢！
