### ISSUE TITLE
是不是不支持Go mod方式的工程，未能找到pkg解析  （I got one error，when the project which mode is go mod，it cannot find the pkg，and then fail）

### ISSUE THREAD

**Issue by majintao** [swaggo/swag#748]
是不是不支持Go mod方式的工程，未能找到pkg解析  （I got one error，when the project which mode is go mod，it cannot find the pkg，and then fail）

所有需要被解析的文件一定要放在gopath里面？？

**Comment by sdghchj** [comment]
不是。主要还是支持go mod, 检查一下你的环境变量GO111MODDULE

**Comment by majintao** [comment]
环境变量 gomod是开启的，不过我没有用Vendor来 放依赖；直接用gopath默认，好像依赖也只是下载了pkg放到gopath而已；下面是我的环境变量 

顺便问下解析外部依赖的原理是什么？go mod确定能自动解析到？？


`set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xxx\AppData\Local\go-build
set GOENV=C:\Users\xxx\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=github.com/majintao
set GONOSUMDB=github.com/majintao
set GOOS=windows
set GOPATH=D:\Go-Project
set GOPRIVATE=github.com/majintao
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Nonolive\AppData\Local\Temp\go-build046433390=/tmp/go-build -gno-record-gcc-switches`

**Comment by sdghchj** [comment]
swag init命令行上指定的当前目录必须有go.mod文件或者是有go.mod文件的子目录。
晒出你的目录结构吧，我还是不清楚到底是怎么个情况。
用的什么版本？提示的到底是个什么错误？

**Comment by majintao** [comment]
比方说解析这个工程，可以下载解压 https://github.com/majintao/problems/blob/master/composition.rar      用的版本是 master   提示 pkg composition cannot find all dependencies, unable to resolve root package

**Comment by sdghchj** [comment]
swag init解析没问题。请你自己调试吧。
