### ISSUE TITLE
cannot find type definition: docs.HTTPError, working in go-code, working when not in different package

### ISSUE THREAD

**Issue by boindil** [swaggo/swag#749]
**Describe the bug**
```
2020/07/10 16:04:21 Generate swagger docs....
2020/07/10 16:04:21 Generate general API Info, search dir:./
2020/07/10 16:04:21 ParseComment error in file apiservice.go :cannot find type definition: docs.HTTPError
```

**To Reproduce**
I used the following:
```
// @Failure 401 {object} docs.HTTPError
// @Failure 500 {object} docs.HTTPError
```

I placed the struct in a new go file in the docs folder:
```
// HTTPError
type HTTPError struct {
	Code    int    `json:"code" example:"400"`
	Message string `json:"message" example:"status bad request"`
}
```

I tested, whether I use the struct in go-coding and it compiled without any problem
```
d := docs.HTTPError{}
_ = d
```

**Expected behavior**
no errors

**Your swag version**
e.g. 1.6.7

**Your go version**
e.g. 1.13.4

**Desktop (please complete the following information):**
 - OS: Debian 10

**Additional context**
Go-Modules are used for this project. swag init works when the struct is in the same file or package

**Comment by sdghchj** [comment]
Folder named "docs" will be ignored.
