### ISSUE TITLE
Use std package to work with templates

### ISSUE THREAD

**Issue by ShoshinNikita** [swaggo/swag#754]
Hello. I noticed `swag` uses `github.com/alecthomas/template` instead of `text/template`. Is there any reason to use this third-party dependency? I couldn't find any usage of its main [feature](https://github.com/alecthomas/template#gos-texttemplate-package-with-newline-elision):

> a backslash immediately after a closing delimiter will delete all subsequent newlines until a non-newline

I think it would be better to use the std package. Especially because code of `github.com/alecthomas/template` hasn't been updated since 2015

**Comment by olliefr** [comment]
I'd like to +1 this issue. An extra dependency on a _fork_ of an out-of-date version of standard library module, last updated in 2015. Is there _really_ an engineering need for this, please? 🙃
