### ISSUE TITLE
undefined: strings.ReplaceAll

### ISSUE THREAD

**Issue by sriharikapu** [swaggo/swag#755]
**Describe the bug**

This is a dependency in my project, when tried installing its failing 

**To Reproduce**
`sudo go get -u github.com/swaggo/swag/cmd/swag`

**Expected behavior**

Not to give an error 

**Screenshots**

![image](https://user-images.githubusercontent.com/6247133/87858242-1bd61800-c94a-11ea-8eb9-2e4aa58b322b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser: Not Aplicable
 - Version: 18
- Processor AMD 64

**Comment by sdghchj** [comment]
Upgrade your golang sdk, higher than 1.13 is recommended
