### ISSUE TITLE
Error when use --parseVendor and package contains ".go"

### ISSUE THREAD

**Issue by jpfaria** [swaggo/swag#758]
when I run the command:

swag init -g ./cmd/server/rest/subscription/main.go --parseInternal --parseDependency --parseVendor

The error below happens:

2020/07/21 17:25:51 Generate swagger docs....
2020/07/21 17:25:51 Generate general API Info, search dir:./
2020/07/21 17:25:51 ParseFile error:read vendor/github.com/lightstep/tracecontext.go: is a directory

ps.: several libraries contain ".go" in packages.

swag version: v1.6.7
go version: go1.13.8

**Comment by sdghchj** [comment]
Try lastest master branch
