### ISSUE TITLE
slice of maps not parsed properly

### ISSUE THREAD

**Issue by vijayrajah** [swaggo/swag#759]
**Describe the bug**
I have a struct with 

```
type SomeStruct struct {
  SomeMember               []map[string]interface{} `json:"some_member,omitempty"
}
```

This gets parsed as (swagger,json)
```
"some_member": {
       "type": "array",
               "items": {
                        "type": "\u0026{%!s(token.Pos=1359) string %!s(*ast.InterfaceType=\u0026{1370 0xc0066b3170 false})}"
               }
     },
```

**Your swag version**
1.6.3

**Your go version**
1.13

Does the slice of maps needs to be handled differently?

**Comment by sdghchj** [comment]
1.6.3 is too old. 
needs upgrading

**Comment by vijayrajah** [comment]
@sdghchj .. Thanks.. I upgraded, that fixed the issue...  this can be closed....
