### ISSUE TITLE
Maximum and Minimum attributes do not function

### ISSUE THREAD

**Issue by parnic** [swaggo/swag#761]
**Describe the bug**
Using the attributes `maximum` or `minimum` in swagger documentation does not emit the max/min output.

**To Reproduce**
1. Create api documentation enforcing the `maximum` value of a field.
2. Run `swag init`
3. Observe maximum is not present.

**Expected behavior**
Maximum is exported.

**Your swag version**
1.6.7

**Your go version**
1.14.6

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave (Chromium)
 - Version: 1.11.101 Chromium: 84.0.4147.89 (Official Build) (64-bit)

**Additional context**
This applies to both the Maximum and Minimum attributes. Some documentation says these need to be `maxinum` and `mininum` instead.

**Comment by sdghchj** [comment]
So this is an error of spelling ? 
Ha , I thought it is combined with **maxi**mum and **num**ber

**Comment by parnic** [comment]
Well it's not my project, but I've never seen "maxinum" anywhere before, so I assumed it was an error. Swagger itself uses maximum/minimum: https://swagger.io/docs/specification/data-models/data-types/
