### ISSUE TITLE
 ParseComment error: cannot find type definition for object in aliased package

### ISSUE THREAD

**Issue by FluorescentTouch** [swaggo/swag#764]
**Describe the bug**
I have a comment, that describes handler's response:
// @Success 200 {object} HTTP.Success{payload=domain.DealsHistory} "ok"

Package HTTP is aliased, because of interference with default net/http package. Import looks like:
`import HTTP "github.com/something/http"`

This package contains object named Success:
```
type Success struct {
	Status     string      `json:"status"`
	TrackingID string      `json:"trackingId"`
	Meta       interface{} `json:"meta,omitempty"`
	Payload    interface{} `json:"payload,omitempty"`
	statusCode int
}
```

After completing swag init in command line i got:
ParseComment error in file handlers/instruments.go :cannot find type definition: HTTP.Success

Making alias in lowercase doesn't change anything

**To Reproduce**
Try to build swag doc with object from aliased package (maybe try to interfere with default go packages)

**Expected behavior**
Swagger docs built successfully.

**Your swag version**
swag version v1.6.7 (even built from master branch)

**Your go version**
go version go1.14.4 linux/amd64

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS

**Comment by sdghchj** [comment]
Make sure pacakge "github.com/something/http" is in the directory specified by flag  "-d".

**Comment by FluorescentTouch** [comment]
This package is in "internal" dir, but flag --parseInternal is provided

**Comment by FluorescentTouch** [comment]
Actually running swag from root dir, not dir where main was located with all dependencies flags solved the problem:

swag init --dir cmd/api --parseVendor --output=cmd/api/docs --parseDependency --parseInternal

@sdghchj TU for help
