### ISSUE TITLE
No way to select multiple accepts at UI

### ISSUE THREAD

**Issue by sudersen** [swaggo/swag#765]
**No way to select multiple accepts at UI*
While the documentation comment over the implementation does have a way to supply multiple accepts, it doesn't have a to select all the accepts at once. 

**To Reproduce**
Supply the under for multiple accepts in the code
```
// @Accept json, text/csv
// @Produce json, text/csv
```

**Expected behavior**
At the UI end, I'd be expecting to select multiple accepts as allowed by W3C convention. The UI should be a multi select of accept rather than basing it on the *Content-Type* of the response 

**Screenshots**
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/12055231/89197241-b6ba2d80-d5ab-11ea-9af7-3fc44be5f7b6.png">

As it could be seen, we don't have a way to select multiple accepts which is otherwise allowed by the standards.

**Comment by ubogdan** [comment]
I'm trying to understand the issue but as far as I see there is only 1 accept and 1 produce in your definition.
```
// @Accept json, text/csv
// @Produce json, text/csv
```
Can you be more specific?

**Comment by ubogdan** [comment]
Are u sure ? 
![multiple_consume](https://user-images.githubusercontent.com/4992696/136951131-601f5311-169f-4015-88eb-8487089af501.png)

**Comment by ubogdan** [comment]
The fact the annotations need to be written in a comment line makes this very error-prone.
