### ISSUE TITLE
when a int64 value 1000000000000000008 return in respond but display in swagger ui will show 1000000000000000000 

### ISSUE THREAD

**Issue by LiuFei1981** [swaggo/swag#774]
**Describe the bug**
when a int64 value 1000000000000000008 return in respond but display in swagger ui will show 1000000000000000000 

**To Reproduce**
1. a respond type testobj struct { 
ID   int64
}
2. set //@Success 200 {object} testobj success

3. var test test obj{1000000000000000008}

**Expected behavior**
{
  "ID": 1000000000000000008
}

**Screenshots**
{
  "ID": 1000000000000000000
}

**Your swag version**
e.g. 1.4.1

**Your go version**
e.g. 1.12.0

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by ubogdan** [comment]
I believe this it's a Javascript issue and there is nothing we can fix here.

**Comment by PathakMihir** [comment]
Any work around for this issue?

**Comment by LiuFei1981** [comment]
no, stop using it.

2022年11月24日 17:25，PathakMihir ***@***.*** ***@***.***> > 写道：


Any work around for this issue?
