### ISSUE TITLE
Overwriting Path Key values ​​when have same route but different query parameters

### ISSUE THREAD

**Issue by vlsouza** [swaggo/swag#776]
I have two endpoints with the same @Router which looks like this:

@Router /v1/costumers [get]

But they have different Query Parameters, in the first one i have {ids} as parameters and the second one i have {name} and {national_identifier}.
They also return different things. The first one returns an object of costumer and the second returns and array of costumer objects.

When i run swag command to generate the docs just the second one appears on swagger.json. I believe that is because swagger use the route as the Key on the json file and the second on is overwriting the first one. 

Any suggestions how to proceed in this case that is not write manually on the swagger files?

**Comment by sdghchj** [comment]
So how do you distinguish two endpoints from each other? 
It's a problem of your business logic, I think.

**Comment by vlsouza** [comment]
@sdghchj Is the same route but they have different query parameters and different handle methods

**Comment by vlsouza** [comment]
Understand that I must review my Routes
