### ISSUE TITLE
Invalid redirect path while working with gateway

### ISSUE THREAD

**Issue by FluorescentTouch** [swaggo/swag#778]
**Describe the bug**
My service is using swag-generated docs with swagger-ui with httpSwagger.Handler on chi router.
`docsHandler := httpSwagger.Handler(
		httpSwagger.URL(cfg.Docs.Path + "/v2/docs/doc.json"),
	)`
Service is running after a gateway, that has its own prefix, lets call it  /gateway/.
So, i try to access the docs with address like that: http://some-host.com/gateway/v2/docs/index.html
For this to work (correct .json receiving and swagger-ui correct work) i have to set swagger Host to http://some-host.com and BasePath to /gateway/v2 on runtime and this is OK.
Not ok tho, that if i try to access docs by http://some-host.com/gateway/v2/docs/ (without index.html suffix), httpSwagger handler redirects me to http://some-host/v2/docs/index.html completely ignoring gateway component. And there is no way to me to provide this gateway prefix to handler, it works only with request URI like this: /v2/docs/

Is there a way to let swaggerHttp handler accept this prefix (if it exists), or maybe receive correct path with prefix from swaggerInfo.BasePath?

**Your swag version**
swag version v1.6.7

**Your go version**
go version go1.14.4 linux/amd64

**Desktop (please complete the following information):**
 - OS: linux
 - Browser: chrome
 - Version: latest

**Comment by ubogdan** [comment]
Please post this issue in [http-swagger](https://github.com/swaggo/http-swagger) because is not related to swag it self.
