### ISSUE TITLE
swag never exists when referencing a value type that can't be resolved, but in a package that can be resolved

### ISSUE THREAD

**Issue by joshk0** [swaggo/swag#782]
**Describe the bug**

Under certain types of annotations, swag fails to exit and consumes unbounded cpu and memory.

**To Reproduce**

1. Create a separate package containing types.
2. Create an API annotation which references this package and a type in that package.
3. Run swag to generate swagger. It should work.
4. Change the annotation to refer to the wrong package name. swag fails immediately. `2020/08/26 11:47:29 ParseComment error in file pkg/api/tasks/v1/inventory.go :can not find schema type: "nonexistentpackage.AnyType"`
5. Change the annotation to refer to the right package name but non existent type. swag hangs / consumes unbounded memory after printing: `2020/08/26 11:47:20 Generate general API Info, search dir:./`

Here is the example annotation (mildly redacted) which I used for my case.

```go
// @Summary Finish Inventory Scan
// @Tags tasks
// @Description Finish Inventory Scan
// @Accept json
// @Produce json
// @Param widget_id query string true "Widget ID"
// @Param tenant_id query string true "Tenant ID"
// @Param next body existingpackage.NonExistentType true "continuation data created by inventory endpoint"
// @Success 200 "OK"
// @Failure 400 {object} api.httpError
// @Failure 401 {object} api.httpError
// @Failure 403 {object} api.httpError
// @Failure 404 {object} api.httpError
// @Router /tasks/v1/finish_inventory [post]
```

You can change the `@Param next` line for the various steps of this bug.

**Expected behavior**
If the type did not exist in that package, swag should have exited with an error right away.

**Your swag version**
1.6.7

**Your go version**
1.14.3

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux in WSL

**Comment by sdghchj** [comment]
I failed to reproduce. It works well.
