### ISSUE TITLE
index.js:19 Could not find component JsonSchema_integer

### ISSUE THREAD

**Issue by beaquant** [swaggo/swag#783]
**Describe the bug**
**Could not render this component, see the console.**
**_Console show:index.js:19 Could not find component JsonSchema_integer_**

**To Reproduce**
```
// api response
type Response struct {
	Code    int         `json:"code"`
	Message string      `json:"message,omitempty"`
	Data    interface{} `json:"data"`
}

// models account 
type Account struct {
	NickName      string      `gorm:"unique" json:"nick_name" example:"我是大佬"`
	Symbols       string      `json:"symbols" example:"BTC_USDT,ETH_USDT"`
}

// @Summary get account
// @Tags setting
// @Accept json
// @Produce  json
// @Security ApiKeyAuth
// @Param   from query int true "from"
// @Success 200 {object} api.Response{data=arrary{models.Account}}	"data=[]models.Account"
// @Router /account [get]
```
response is a object, the data is a interface, when success, data will be a array of models.Account.
it create swagger normally. but can't load it.

**Expected behavior**
load successfully

**Screenshots**

**Your swag version**
swag version v1.6.7

**Your go version**
e.g. 1.14

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: chrome

**Comment by sdghchj** [comment]
api.Response{data=[]models.Account}

**Comment by beaquant** [comment]
good, it work, thanks
