### ISSUE TITLE
Set same response header for multiple return codes

### ISSUE THREAD

**Issue by vijayrajah** [swaggo/swag#785]
I have an API, that *always* responds with a request id header ( X-Request-ID ), regardless of the response status (error, or otherwise)

Currently I'm specifying the response headers in multiple lines
```
// @header 200 {string} X-Request-ID "Unique request ID for every request"
// @header 400 {string} X-Request-ID "Unique request ID for every request"
// @header 404 {string} X-Request-ID "Unique request ID for every request"
// @header 500 {string} X-Request-ID "Unique request ID for every request"
```

Is there a way to use wild-cards or something like that to specify the response for all return status code

**Your swag version**
e.g. 1.6.7

**Your go version**
e.g. 1.14.4

**Comment by easonlin404** [comment]
fixed by #837
