### ISSUE TITLE
How to write the path of the @Param?

### ISSUE THREAD

**Issue by weihaipy** [swaggo/swag#786]
If my code like following:

file structure:

```
project_name
├─api
│  └─admin
│       └─admin.go
│
├─model
|    └─request
|        └─common.go
└─main.go

```

the content of main.go:

```go
package main

func main() {

}
```

the content of admin.go:

```go
package admin

import (
	reqC "project_name/model/request/common"
	"fmt"

	"github.com/gin-gonic/gin"
)

// @Param data body project_name/model/request/common.GetByID true "delete admin"
func AdminDelete(c *gin.Context) {
	var reqID reqC.GetByID
	fmt.Printf("ID: %#v\n", reqID.ID)
}
```

the content of common.go:

```go
package request

type GetByID struct {
	ID uint `json:"id"`
}
```

When I excute `swag init`,always return `ParseComment error in file api\admin\admin.go :can not find schema type: "project_name/model/common.GetByID"`.

In this  case,how should I write the path of `@Param` in `api/admin/admin.go`?

I have run `go mod init project_name`,and tried `project_name/model/request/common.GetByID` or `model/request/common.GetByID` or `common.GetByID` or `reqC.GetByID`,but it doesn't work.

**version**:

* swag : v1.6.7

* go : 1.15

**Comment by weihaipy** [comment]
If I want to run `swag init` in `project_name` directory

**Comment by sdghchj** [comment]
// @Param data body common.GetByID true "delete admin"

**Comment by weihaipy** [comment]
> 
> 
> // @param data body common.GetByID true "delete admin"

sorry, it will return `ParseComment error in file api\admin\admin.go :can not find type def: "common.GetByID" error: no initial packages were loaded`

**Comment by sdghchj** [comment]
// @param data body request.GetByID true "delete admin"

**Comment by weihaipy** [comment]
> 
> 
> // @param data body request.GetByID true "delete admin"

It works,think you 👍
