### ISSUE TITLE
Add support for x-tokenName extension in the oauth2 security schema

### ISSUE THREAD

**Issue by lahsivjar** [swaggo/swag#790]
**Is your feature request related to a problem? Please describe.**
Yes, Swagger-UI supports reading a "x-tokenName" property from a "oauth2" entry in "securityDefinitions". This is used in order to select another JSON field (default is "access_token") in the token response from a OAuth2.0 server.

**Describe the solution you'd like**
Allow swag to parse "x-tokenname" variable from the GeneralAPI annotations and apply it to oauth2 specs

**Describe alternatives you've considered**
N/A

**Additional context**
More context can be found [here](https://github.com/swagger-api/swagger-ui/issues/4084) and [here](https://github.com/swagger-api/swagger-js/pull/1278)

**Comment by krystian-kulgawczuk-pr** [comment]
Does this feature actually work? I'm using version 1.6.9 which is suppose to have changes and getting an error:
`2020/11/18 15:53:32 ParseComment error in file main.go :annotation @x-tokenname need a valid json value`

**Comment by krystian-kulgawczuk-pr** [comment]
I built binary directly from master branch and tested if `x-tokenname` works and it doesn't. I get an error:
`2020/11/18 16:16:40 ParseComment error in file main.go :annotation @x-tokenname need a valid json value`
I copied section directly from tests to my project:
```
// @securitydefinitions.oauth2.accessCode OAuth2AccessCode
// @tokenUrl https://example.com/oauth/token
// @authorizationurl https://example.com/oauth/authorize
// @scope.admin Grants read and write access to administrative information
// @x-tokenname id_token
```

**Comment by lahsivjar** [comment]
Hmm, this shouldn't be the case since the `@x-tokenname` is ignored completely. Can you double-check the binary you have built?

**Comment by krystian-kulgawczuk-pr** [comment]
> Also, please check how you are adding the dependency of the built binary into your project and make sure that it is actually using your self built binary.

I even started a new project with clean go.mod/vendor and It's still not working. I am quite sure that I use correct binary because the file provided in tests works just fine `swag/testdata/main.go`. This file goes through all unit tests and mine errors out on `ParseAPI` from `Parser`.

Maybe I'll just post full example that doesn't work:
```
// @title test
// @version 1.0.0
// @description test
// @schemes https
// @x-google-backend {"address": "<service_placeholder>", "protocol": "h2", "deadline": 60.0}
// @license.name Proprietary license
// @host <gateway_placeholder>
// @BasePath /api

// @securitydefinitions.oauth2.accessCode OAuth2AccessCode
// @tokenUrl https://example.com/oauth/token
// @authorizationurl https://example.com/oauth/authorize
// @scope.admin Grants read and write access to administrative information
// @x-tokenname id_token
```

Also one more thing, `Security Scheme Object` should support any field that that follows a pattern `x-*` (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#security-scheme-object), but I guess that's completely another feature request I guess.

**Comment by krystian-kulgawczuk-pr** [comment]
`// @x-tokenname "id_token"` works

**Comment by krystian-kulgawczuk-pr** [comment]
Found out what was the issue, no newline after `// @x-tokenname id_token`...
I was assuming that as long as this is the last statement, newline won't be required to "close" securitydefinition section.

**Comment by willforeverin** [comment]
hi @krystian-kulgawczuk-pr , I'm seeing exactly the same error as you described when using 
```
//@x-tokenName id_token
```
However, you commented 
```
// @x-tokenname "id_token" works
```
I tried, swag init does not complain now, but the token I received is still access token. 
May I know what's your `securityDefinitions` in docs.go? mine is like this:
```
    "securityDefinitions": {
        "OAuth2-cognito": {
            "description": "Description for what is this security definition being used",
            "type": "oauth2",
            "flow": "accessCode",
            "authorizationUrl": "{auth-url}",
            "tokenUrl": "{token-url}",
            "x-tokenname": "\"id_token\""
        }
    }
```
Any suggestion is appreciated! Thanks!

**Comment by willforeverin** [comment]
never mind. finally understood that a new line is needed. after added the new line, the correct `securityDefinitions` is generated:
```
    "securityDefinitions": {
        "OAuth2-cognito": {
            "type": "oauth2",
            "flow": "accessCode",
            "authorizationUrl": "{auth-url}",
            "tokenUrl": "{token-url}",
            "x-tokenname": "id_token"
        }
```
however, I still got access token instead of id_token. Any suggestion?

**Comment by willforeverin** [comment]
found the problem.
with
```
//@x-tokenName id_token
```
the generated swagger.json will have 
```
            "x-tokenname": "id_token"
```
please notice that the first char n for name is not capitalized. 
however, in swagger-ui-boundle.js, it is looking for `x-tokenName`:
```
                                        } else if ("oauth2" === o || "openIdConnect" === o) {
                                            var f, d = t.token || {}, m = d[n["x-tokenName"] || "access_token"], v = d.token_type;
                                            v && "bearer" !== v.toLowerCase() || (v = "Bearer"),
                                            u.headers.Authorization = s()(f = "".concat(v, " ")).call(f, m)
                                        }
```
Proposed fix:
change the js code to use lower-cased key: `x-tokenname` instead of `x-tokenName`
