### ISSUE TITLE
Field Settings in the request structure are required

### ISSUE THREAD

**Issue by lgy1027** [swaggo/swag#792]
When I set the request parameters 
// @Param   params body PodInfoRequest true "namespace"
How do I set the required fields for each property in the structure
type PodInfoRequest struct {
	// @description namespace
	NameSpace string `json:"namespace",`
	// @description podName
	PodName string `json:"podName"`
}

**Comment by sdghchj** [comment]
type PodInfoRequest struct {
// @description namespace
NameSpace string `json:"namespace" binding:"required" `
}

**Comment by ubogdan** [comment]
Closing: outdated.
