### ISSUE TITLE
Error in data model fails to parse

### ISSUE THREAD

**Issue by lahsivjar** [swaggo/swag#793]
**Describe the bug**
If error type is a field in a data model for request or response then it fails to parse with an error "cannot find type definition: error"

**To Reproduce**
1. Create a struct with error field
2. Use the above struct to define a a swagger annotation 
3. Run swag init

**Expected behavior**
No error for field with error type

**Your swag version**
1.6.7 or master

**Your go version**
e.g. 1.13.14

**Comment by sdghchj** [comment]
error is an interface.
If you take it as string, `swaggertype:"string"` may help, I think.

**Comment by lahsivjar** [comment]
This should work, but my problem is that error is a part of a struct from a third-party package. Any idea how I can add the swaggertype to such struct?

**Comment by ubogdan** [comment]
The only way is to import the package in a vendor folder and apply a patch to it ...
