### ISSUE TITLE
Remove gin dependency

### ISSUE THREAD

**Issue by akojo** [swaggo/swag#796]
**Is your feature request related to a problem? Please describe.**
Running tests requires [gin](https://github.com/gin-gonic/gin), even though `swag` itself doesn't depend on gin in any way. When using swag in a project that uses some other framework (like http/gorilla/echo), gin and its dependencies are unnecessarily pulled along.

**Describe the solution you'd like**
- Remove gin dependency from test code and use stdlib http module instead
- Add `go.mod` to each example so that they can be run stand-alone without needing their dependencies in main go.mod.

If this is deemed a good idea, I can do the necessary changes and submit a PR

**Comment by sdghchj** [comment]
Welcome
