### ISSUE TITLE
replace unsupported and vulnerable satori/go.uuid with gofrs/uuid

### ISSUE THREAD

**Issue by rootatdarkstar** [swaggo/swag#799]
**Is your feature request related to a problem? Please describe.**
Replace non-maintained and vulnerable satori/go.uuid with its successor - gofrs/uuid
https://github.com/satori/go.uuid
https://github.com/gofrs/uuid

satori/go.uuid security issue:
https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMSATORIGOUUID-72488

**Describe the solution you'd like**
PR: https://github.com/swaggo/swag/pull/798

**Describe alternatives you've considered**
Since gofrs/uuid is mature successor of satori/go.uuid - it's most compatible replacement of it

**Additional context**
https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMSATORIGOUUID-72488

**Comment by ubogdan** [comment]
Merged. 
Thanks for your contributions.
