### ISSUE TITLE
"custom struct" is not supported type for formData

### ISSUE THREAD

**Issue by lzw5399** [swaggo/swag#801]
**Describe the bug**
There is a API receive the `formData` param, I tried the following screenshots behavior but got the error msg. 
Thanks in advance^-^

**To Reproduce**
1. define the swag annotations as below
2. `swag init`
3. saw the error

**Expected behavior**
I have seen this issue #300 , it seems this feature should be supported in the latest swag release. Did I miss something?

**Screenshots**

![](http://pic.codepie.fun/img/20201005210845.png)

**Your swag version**
1.6.7

**Your go version**
1.15.2

**Desktop (please complete the following information):**
 - OS: WIN 10

**Comment by lzw5399** [comment]
Oh, swag 1.6.7 was released in June. Looking forward the new release. I will close it...

**Comment by J-Ibarra** [comment]
`swag version v1.7.0`


how implement file request whit `swaggertype:"file"`?

example

![image](https://user-images.githubusercontent.com/4218738/120912604-a147e100-c65e-11eb-8aea-357f6e08c333.png)

when i generate the spec the output its `:file is not basic types`

to work I have to ignore the property on structure

![image](https://user-images.githubusercontent.com/4218738/120912651-0a2f5900-c65f-11eb-837f-be44f8a5742f.png)

and define the file whit Param

![image](https://user-images.githubusercontent.com/4218738/120912682-377c0700-c65f-11eb-931c-7d42586f6e6d.png)

but we should be able to define with type `swaggertype:"file"`
