### ISSUE TITLE
cannot find type definition: multipart.FileHeader

### ISSUE THREAD

**Issue by lzw5399** [swaggo/swag#802]
**Describe the bug**
When I include the `*multipart.FileHeader` typed field in the custom struct and annotate the swag as the following screenshots, `swag init` will return the error msg

**To Reproduce**
1. run `go get  github.com/swaggo/swag/cmd/swag@80b6894b047bd06e970efa3e6dee1c3818811f4d` in order to `support the object for formdata`  ref: #300
2. define custom struct as below screenshot
3. define the swag annotations as below screenshot
4. run `swag init`
5. saw the error

**Expected behavior**
`swag init` should executed successfully

**Screenshots**
![](http://pic.codepie.fun/img/20201005222056.png)
![](http://pic.codepie.fun/img/20201005222152.png)

**Your swag version**
v1.6.8-0.20200921161410-33e4ac3219fa
![](http://pic.codepie.fun/img/20201005221942.png)

**Your go version**
1.15.2

**Desktop (please complete the following information):**
 - OS: WIN 10

**Comment by lzw5399** [comment]
Although it may be a bit late, but I will share my workaround(may not the best practice)
- add `swaggerignore` tag for *multipart.FileHeader 
- add swag comment to `request struct` and `*multipart.FileHeader ` separately

----
![image](https://user-images.githubusercontent.com/45249999/131619830-b80e3c32-a6ee-4d71-b17c-bea788ffd8c2.png)

![image](https://user-images.githubusercontent.com/45249999/131620498-a2ed8e6a-7296-429c-b5ea-95ffc104672f.png)

**Comment by 1c3z** [comment]
This is work for me  (swag v1.8.1)
```
swag init --parseDependency --parseInternal --parseDepth 1
```

https://github.com/swaggo/swag/issues/817

**Comment by jeefs** [comment]
thx,is't worked
