### ISSUE TITLE
Bump Version to 1.6.8 to include all bugfixes since 1.6.7

### ISSUE THREAD

**Issue by Nerzal** [swaggo/swag#807]
**Describe the solution you'd like**
Create new 1.6.8 Tag

So we have a tag to import in go modules, which includes the new features and fixes

**Comment by Nerzal** [comment]
List of commits since last release:

https://github.com/swaggo/swag/compare/v1.6.7...master

**Comment by easonlin404** [comment]
[v1.6.8](https://github.com/swaggo/swag/releases/tag/v1.6.8) is released now.
