### ISSUE TITLE
cannot find type definition: gorm.Model

### ISSUE THREAD

**Issue by ruanhailiang** [swaggo/swag#810]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**swag version**
1.6.7

**go version**
1.15
------------------------------------------------------------
if use:
swag init --parseVendor true
output:
cannot find type definition: sql.NullTime.

**Comment by ruanhailiang** [comment]
if use:
swag init --parseVendor true
output:
cannot find type definition: sql.NullTime.

**Comment by ruanhailiang** [comment]
I see issues 808, but I don't think I should modify Gorm's source code to add "swagger type"

**Comment by ubogdan** [comment]
@ruanhailiang I'm afraid we can't help you if you don't use/fill the bug template so we can use a use case example.

**Comment by zhaojingadmin** [comment]
抓紧解决这个问题

**Comment by guimaraaes** [comment]
I have the same probleme using the web framework fiber. My struct model was like that,
```
type Movie struct {
	title    string `json:"title"`
	tagline  string `json:"tagline"`
	released int    `json:"released"`
}
```

then I put like that,
```
type Movie struct {
	Title    string `json:"title"`
	Tagline  string `json:"tagline"`
	Released int    `json:"released"`
}
```

**Comment by ubogdan** [comment]
@zhaojingadmin 
> 抓紧解决这个问题

Of course, this is an open-source project and contributions are always welcome.

**Comment by ubogdan** [comment]
> I see issues 808, but I don't think I should modify Gorm's source code to add "swagger type"

Well, this is a code design pattern problem, not a swag problem. (You are exposing to the API some data that you are not in control of and this may lead to wrong output when external package API definitions may change)

Solution: You can use a [DTO](https://en.wikipedia.org/wiki/Data_transfer_object) pattern to solve this issue. 
Why: In real-life applications, you don't want to expose your database structure directly to the API for various security reasons so this pattern may be a good approach.

**Comment by markokoen** [comment]
I am having the same issue:

2020/10/28 13:52:34 ParseComment error in file ***/file/path/*.go **:cannot find type definition: gorm.Model**

**Comment by bzyy** [comment]
> I am having the same issue:
> 
> 2020/10/28 13:52:34 ParseComment error in file **_/file/path/_.go **:cannot find type definition: gorm.Model**

try `swag init --parseDependency --parseInternal`

**Comment by markokoen** [comment]
> > I am having the same issue:
> > 2020/10/28 13:52:34 ParseComment error in file **_/file/path/_.go **:cannot find type definition: gorm.Model**
> 
> try `swag init --parseDependency --parseInternal`

Wow thank you! This worked for me.

**Comment by zxln007** [comment]
> > I am having the same issue:
> > 2020/10/28 13:52:34 ParseComment error in file **_/file/path/_.go **:cannot find type definition: gorm.Model**
> 
> try `swag init --parseDependency --parseInternal`

it works ！ thank you very much

**Comment by ubogdan** [comment]
Closing: outdated.

**Comment by trishan9** [comment]
> > I am having the same issue:
> > 2020/10/28 13:52:34 ParseComment error in file **_/file/path/_.go **:cannot find type definition: gorm.Model**
> 
> try `swag init --parseDependency --parseInternal`

Thanks it worked!

**Comment by meowrain** [comment]
> > I am having the same issue:
> > 2020/10/28 13:52:34 ParseComment error in file **_/file/path/_.go **:cannot find type definition: gorm.Model**
> 
> try `swag init --parseDependency --parseInternal`

Thanks,it worked now!
