### ISSUE TITLE
Support for multiple responses

### ISSUE THREAD

**Issue by guiferpa** [swaggo/swag#815]
**Is your feature request related to a problem? Please describe.**

Currently I have a problem that's about multiple response body which one each has a specific Content-Type header.

I can't figure out some doc about that and I'm concluded that this support can be not exists.

Explaing my scene, I have three differents Content-Type header for each response but I can't create a Golang struct for each one.

Follow the code:

```go
// v3alphaGetDocumentById godoc
// @Summary Get Document By Id                                 
// @ID v3alpha-get-document-by-id
// @Produce application/A+json
// @Produce application/B+json                                      
// @Produce application/C+json                                    
// @Success 200 {object} A                                                                                                                  
// @Failure 401 {object} ErrA                           
// @Failure 404 {object} ErrA
// @Failure 500 {object} ErrA
// @Router /v3alpha/documents/{id} [get]
func v3alphaGetDocumentById(bsvc a.PrimaryRestPort) http.HandlerFunc {
 ▸ return func(w http.ResponseWriter, r *http.Request) {
 ▸ ▸ payload := r.Context().Value(UserContextPayloadKey).(map[string]string)

...
```

Looking this code we can figure out that there's no some annotation for describe a different Golang struct for either `application/B+json` nor `application/C+json`

**Describe the solution you'd like**

I'd like that was possible add just one inline attribute like this example below:

```go
// @Success 200 {object} A application/A+json "Structure A"
// @Failure 401 {object} ErrA application/A+json "Structure A Error 401" 
// @Failure 404 {object} ErrA application/A+json "Structure A Error 404"
// @Failure 500 {object} ErrA application/A+json "Structure A Error 500"
// @Success 200 {object} B application/B+json "Structure B"
// @Failure 401 {object} ErrB application/B+json "Structure B Error 401" 
// @Failure 404 {object} ErrB application/B+json "Structure B Error 404"
// @Failure 500 {object} ErrB application/B+json "Structure B Error 500"
// @Success 200 {object} C application/C+json "Structure C"
// @Failure 401 {object} ErrC application/C+json "Structure C Error 401" 
// @Failure 404 {object} ErrC application/C+json "Structure C Error 404"
// @Failure 500 {object} ErrC application/C+json "Structure C Error 500"

```

Sure, it looks like verbose but I don't have a good idea better than it.

**Describe alternatives you've considered**

My workaround will be edit output file manually and include this specs.

**Comment by ubogdan** [comment]
@guiferpa 
Open-API is a standard made to help DEVELOPERS easily consume a REST API. 
Your proposal simply breaks this contract just because you want to define a single source that handle 3 entities.

**Comment by guiferpa** [comment]
@ubogdan 

Too bad, makes sense.

Well, but would you have some approach for this API contract complexity. On practice I have one JSON contract for the same endpoint but this json has some specifics attributes then if I just response with header Content-Type:json my client side wouldn't know how correct way to parse this response body. Maybe I must have a attribute called "type" for works as a signal for say about kind of it.

**PS**: I know that this issue opened have no sense about this subject above but let me know if you or someone already lived this problem and how it was solved using swag on the code, together.

**Comment by lucasbmiguel** [comment]
It seems that what @guiferpa is trying to do is actually mentioned on the openapi documentation and is defined at RFC6838. It would be nice if swaggo could have full support for this part of openapi docs: https://swagger.io/docs/specification/media-types/

**Comment by guiferpa** [comment]
Exactly @lucasbmiguel

**Comment by ubogdan** [comment]
@lucasbmiguel swagger IS OPEN API 2.0. the link you gave me is related to OPEN API 3.0 SPECS.
This is my last response in this matter. It doesn't make sense to have different response models on the same route.
