### ISSUE TITLE
Nested struct with an incorrectly typed example tag (example:"foo" for uint64) is generated as null with a resolver error

### ISSUE THREAD

**Issue by morinagayuka** [swaggo/swag#816]
**Describe the bug**
A nested struct with an incorrectly typed example tag (example:"foo" for uint64) is generated as null.
However a resolver error is generated, the error does not mention the incorrectly typed example tag.
```
Resolver error at paths./main.get.responses.200.schema.properties.foo.items.$ref
Could not resolve reference: #/definitions/main.bar
```

**To Reproduce**
1. Define a struct with a nested struct

> type list struct {
>    Foo []bar `json:"foo,omitempty"`
> }
> 

2. Define the nested struct with an incorrectly typed example tag content (example:"foo" for uint64) 

> type bar struct {
>    ID uint64 `json:"id" "example:"test"`
> }
> 

3. Run swag init
4. See generated swagger

**Expected behavior**
Error about the incorrectly typed example tag content is generated.

**Screenshots**
![スクリーンショット 2020-10-26 16 26 27](https://user-images.githubusercontent.com/50349046/97145222-33bf0280-17a9-11eb-8c00-6ef19c8892cf.png)
<img width="217" alt="スクリーンショット 2020-10-26 16 25 20" src="https://user-images.githubusercontent.com/50349046/97145236-3ae61080-17a9-11eb-9181-2890695b4879.png">

**Your swag version**
e.g. 1.5.1

**Your go version**
e.g. 1.13.0

**Comment by sdghchj** [comment]
Type name of a struct member needs capitalizing.
