### ISSUE TITLE
Cannot find structs within github.com/golang/protobuf/ptypes

### ISSUE THREAD

**Issue by joe-bailey-nomihealth** [swaggo/swag#818]
**Describe the bug**
Our repo has Go and protobufs.  Swag is having issue with the protobufs.  When running `swag init --parseInternal --parseDependency --propertyStrategy camelcase`, it fails to find these protobuf types:

- github.com/golang/protobuf/ptypes/timestamp.Timestamp
- github.com/golang/protobuf/ptypes/wrappers.StringValue

Both of these types reference structs in `google.golang.org/protobuf/types/known`.  

Here is an example of output from swag:
```
2020/10/26 18:00:56 ParseComment error in file our_service/api/v2/data/query/handlers.go :cannot find type definition: timestamp.Timestamp
```
The handler code does not reference timestamp.Timestamp.  We have imported the timestamp package and the package it references into the handle, so swag would have them.  Example of the import is below.
```
import (
...
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/protobuf/types/known/timestamppb"
...
)
```

**To Reproduce**
1. Create code which uses a protobuf and reference it in the swag comments 
2. The protobuf need to import and use one of the protobufs values mentioned above
3. Run swag 

**Expected behavior**
Run with no errors and generate the appropriate swagger files.

**Screenshots**
N/A

**Your swag version**
v1.6.8 and v1.6.9

**Your go version**
go1.14.4 darwin/amd64

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: N/A
 - Version: N/A

**Additional context**
None to add.

**Comment by sdghchj** [comment]
try puting them in main.go
```
//main.go

import (
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)
```

**Comment by joe-bailey-nomihealth** [comment]
@sdghchj Your recommendation worked!  I appreciate your quick response.

Thanks!
