### ISSUE TITLE
timestamp.Timestamp bug

### ISSUE THREAD

**Issue by domgolonka** [swaggo/swag#822]
[Protobuf timestamp ](github.com/golang/protobuf/ptypes/timestamp) shows up as:

```
"due": {
      "nanos": 0,
      "seconds": 0
    },
```
Any way to change it to RFC 3339 format instead

`"due": "2019-10-12T07:20:50.52Z" `

**Comment by sdghchj** [comment]
https://github.com/swaggo/swag#use-swaggertype-tag-to-supported-custom-type
