### ISSUE TITLE
Edit auto-generated protobuf structs

### ISSUE THREAD

**Issue by mehran-prs** [swaggo/swag#823]
We can not set tags on auto-generated structs from protobuf files, how we should change their props, e.g, ignore a field or set custom type?

**Comment by ubogdan** [comment]
Why don't you use a [DTO](https://en.wikipedia.org/wiki/Data_transfer_object) since swag is meant to create documentation for REST service which is HTTP based not GRPC ?

**Comment by mehran-prs** [comment]
@ubogdan we have DTO, but in our communication between our microservices we use gRPC and our gRPC messages are as our DTO objects.

**Comment by ubogdan** [comment]
Maybe I'm missing something but as far as I know, the generated OAS2 specs are useful for REST service, not GRPC. I you call DTO the GRPC generated definitions then, I don't know what else to say.

**Comment by mehran-prs** [comment]
We don't want to use OAS2 for gRPC, this is what we does:

```bash
client send request to gateway  ---> gateway send gRPC request to MicroService

and then the gateway gets the gRPC response which is a protobuf messaged and convert it to HTTP response.
```

This issue is for a couple of months ago, for now, we are using [go-swagger](https://github.com/go-swagger/go-swagger), so thanks to you.
