### ISSUE TITLE
swagger UI trying to fetch third party CSS (fonts.googleapis.com)

### ISSUE THREAD

**Issue by kfirfer** [swaggo/swag#824]
Hello

When I open swagger UI in the browser, the browser trying to fetch this third party CSS:
https://fonts.googleapis.com/css?family=Open+Sans:400,700|Source+Code+Pro:300,600|Titillium+Web:400,600,700

I'm facing 2 problems:
1)
It is forced me not to be able using this response header for security:
ContentSecurityPolicy: "default-src 'self'"
2)
Im using offline environment (No internet) ,most of the time (security reasons)

The swagger rendered alright as well, even without internet

**Comment by ubogdan** [comment]
Please open this issue in the corresponding sub-module you are using as a routing framework. 
To be more specific if you are using it with echo please open the issue on the [echo-swagger](https://github.com/swaggo/echo-swagger) project and so on.
