### ISSUE TITLE
cant find struct not imported

### ISSUE THREAD

**Issue by Abirdcfly** [swaggo/swag#828]
**Describe the bug**
cant find struct not imported

**To Reproduce**
my code is 

    @Success 200 {object} v1.Status

but `k8s.io/apimachinery/pkg/apis/meta/v1` was not import in this file.how can I get the expected result?

**Expected behavior**

**Screenshots**

    ParseComment error in file xxxxx.go :cannot find type definition:v1.Status

It is wrong if I change to k8s.io.apimachinery.pkg.apis.meta.v1.Status

**Your swag version**
1.6.7

**Your go version**
 go1.15.3 darwin/amd64

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by sdghchj** [comment]
import that package in your main.go and add --parseDependency flag when running 'swag init'
