### ISSUE TITLE
Add more examples for post requests

### ISSUE THREAD

**Issue by agzuniverse** [swaggo/swag#831]
Could use some more examples of specifying the parameter for post requests.
For example, all the controllers given [here](https://github.com/swaggo/swag/blob/master/example/celler/controller/examples.go) are for get requests only.

**Comment by ubogdan** [comment]
It's very simple
```
// Create a device
// @Tags User
// @Summary Create Device
// @Description Create Device
// @Accept json
// @Produce json
// @Param message body request.Device true "Device Info"
// @Success 200 {object} request.Device
// @Failure 400 {object} response.Error
// @Failure 503 {object} response.Error
// @Router /device [post]
func (h *device) Create(w http.ResponseWriter, r *http.Request) {
}
```

**Comment by agzuniverse** [comment]
Thank you, perhaps adding it the examples might help future folks looking for the same thing? I've opened a PR #832 .

**Comment by ubogdan** [comment]
I believe more examples should be written into a separate repository ...

**Comment by agzuniverse** [comment]
Closing this since #832 is now merged.
