### ISSUE TITLE
Cannot find type definition

### ISSUE THREAD

**Issue by ericnts** [swaggo/swag#834]
**Describe the bug**

When I run the command "swag init", this exception is thrown:
2020/11/18 20:06:51 ParseComment error in file proc/controller/position_controller.go :cannot find type definition: enum.PositionTypeEnum

I guess it is because the "replace" field in the "go.mod" cannot be parsed.

Please tell me how to solve such a problem.

1、“position_controller.go”：
// @param param body vo.PositionUploadVo true ""
func SavePosition(c *gin.Context) {}

2、“PositionUploadVo”：
package vo
import "epshealth-airobot-common/biz/enum"
type PositionUploadVo struct {
PositionType enum.PositionTypeEnum
}

3、 "go.mod":
require (
epshealth-airobot-common/biz v0.0.0
)
replace epshealth-airobot-common/biz => ../epshealth-airobot-common/biz

**Comment by sdghchj** [comment]
import that 3rd-part package in your main.go and add --parseDependency flag when running 'swag init'

**Comment by nabowler** [comment]
`--parseDependency` was not previously required. It appears this started breaking with v1.6.8

**Comment by MikeCongdon1** [comment]
> `--parseDependency` was not previously required. It appears this started breaking with v1.6.8

This doesn't seem to work for sub-sub types. Maybe I'm doing something wrong here...
I use zero.Int (github.com/guregu/null/zero) which pulls from sql.NullInt & it appears the --parseDependency doesn't chase through the zero package to get to sql.NullInt. It's also unclear as to why it should need to. (Why not just state "zero.Int" as the type needed).


Is there a way to solve this? I'm stuck on 1.6.7 until either --parseDependency works recursively, or that limitation goes away. (There are cool new features I want to take advantage of though)...

**Comment by benwaffle** [comment]
Also seeing something like this. It seems like swaggo isn't handling the local module replacement in go.mod
