### ISSUE TITLE
Release swag for Linux/ARM64

### ISSUE THREAD

**Issue by odidev** [swaggo/swag#841]
Hi Team,

I am working on the project <https://github.com/cloudfoundry/stratos> for adding Linux/ARM64 support. Stratos is using swag, but swag is not available for Linux ARM64 platform. 
I have checked the source code and built it on a 64 bit Linux ARM machine. ‘Swag’ binary gets successfully generated.

It would be really helpful if ‘swag’ binary becomes available for Linux AArch64 platform. If required, I am happy to contribute to this.

**Comment by easonlin404** [comment]
Hi @odidev swag releases the binary by [goreleaser](https://goreleaser.com/) tool. and the archive configuration is [here](https://github.com/swaggo/swag/blob/master/.goreleaser.yml). Welcome to make a PR to support the Linux ARM64 platform.

**Comment by odidev** [comment]
@easonlin404 
I have raised the PR <https://github.com/swaggo/swag/pull/842>. 
Please review and suggest if anything required.
