### ISSUE TITLE
enum struct in @Success 200 {object}

### ISSUE THREAD

**Issue by mainpart** [swaggo/swag#847]
I'm trying to return inherited objects, derived from one base class. I have a object (news text) that consists of multiple blocks. Say, image block, paragraph with header block and many other.\

So i'm describing them as  (simplified)
```
type BlockType uint16
const (
	BASIC BlockType = iota
	IMGBLOCK
)

type BlockBase struct {
	Type BlockType `json:"blocktype"`
}

type ImgBlock struct {
	BlockBase        // inheritance
	Src       string `json:"src"` //image attribute
}

type Block interface {
}

type News struct {
	Body  []Block   `json:"block" enums:"imgblock,blockbase"`
}
```

I want front-end developer to get clear vision of what he can receieve. 
I'm trying to avoid abstract array type in Body

swaggo does not allow me to do so. trying to specify object type of News in return leads to build error

`// @Success 200 {object} News "return"`

```
2020/12/02 21:58:22 Type definition of type '*ast.InterfaceType' is not supported yet. Using 'object' instead.
2020/12/02 21:58:22 ParseComment error in file _______.go :object is unsupported type in enum value
```

What type should i use in @Success to get proper object-oriented result?

**Comment by sdghchj** [comment]
I'm afraid it's not supported
