### ISSUE TITLE
Using code markdown in description.

### ISSUE THREAD

**Issue by tiniyoadmin** [swaggo/swag#857]
I am trying to use markdown in the description like below with code section of xml. swag removes spaces in generates json for <to>, <from>, <body> and <header>. how can I make sure those spaces remain during generation of json? 

// @description # Header1
// @description Header1 description. 
// @description ## Header2
// @description Header2 description. 
// @description ### Header3
// @description Header 3 description. 
// @description ```xml
// @description <?xml version="1.0" encoding="UTF-8"?>
// @description <note>
// @description      <to>Tove</to>
// @description      <from>Jani</from>
// @description      <body>
// @description           <header>
// @description           </header>
// @description      </body>
// @description </note>
// @description ```

Output of swag is like this. 

# Header1\nHeader1 description.\n## Header2\nHeader2 description.\n### Header3\nHeader 3 description.\n```xml\n\u003c?xml version=\"1.0\" encoding=\"UTF-8\"?\u003e\n\u003cnote\u003e\n\u003cto\u003eTove\u003c/to\u003e\n\u003cfrom\u003eJani\u003c/from\u003e\n\u003cbody\u003e\n\u003cheader\u003e\n\u003c/header\u003e\n\u003c/body\u003e\n\u003c/note\u003e\n```

it should remain spaces before the xml tags. 

Swag VERSION: v1.6.9
go version go1.15.2 linux/amd64
OS Version ubuntu 20.04

Note: i am not able to disable markdown. so preview is not good to see. please have look in plain text format.

**Comment by chiptus** [comment]
basically you store the markdown in a separate file and supply it using @description.markdown

https://github.com/swaggo/swag#using-markdown-descriptions

**Comment by tiniyoadmin** [comment]
This works. Thanks.
