### ISSUE TITLE
Add Proof Key for Code Exchange Support

### ISSUE THREAD

**Issue by TBryant13** [swaggo/swag#871]
**Is your feature request related to a problem? Please describe.**
I am not able to authenticate via Okta because Okta only supports Authorization Code Flow with PKCE.

**Describe the solution you'd like**
Add Proof Key for Code Exchange support. There is a flag for it in Swagger UI 3.24.0+. The flag in Swagger UI is usePkceWithAuthorizationCodeGrant.

**Additional context**
Here is a similar issue in Springfox: https://github.com/springfox/springfox/issues/3005

**Comment by td-edge** [comment]
This would be a nice addition since implicit flow is considered antiquated now.

👍

**Comment by ubogdan** [comment]
Since this is a Swagger-UI related issue, I believe you should open a feature request on the proper HTTP handler you need it. https://github.com/swaggo/gin-swagger, https://github.com/swaggo/echo-swagger https://github.com/swaggo/http-swagger
