### ISSUE TITLE
param formData have error (v1.7.0)

### ISSUE THREAD

**Issue by junjie-bianjie** [swaggo/swag#874]
**Describe the bug**
// @Param   file	formData	file  true  "doc_file"

```
I use swag init , but recieve a error
Next is the error
ParseComment error in file rest/controller/file.go :cannot find type definition: file

Then i download swag-cli V1.6.1, it worked, successfully generate the swagger
So I think ther have some problem in V1.7.0
```

**Expected behavior**
parseComment no error

**Your swag version**
e.g. 1.7.0

**Your go version**
e.g. 1.15

**Desktop (please complete the following information):**
 - OS: [macos11.1]

**Comment by ubogdan** [comment]
If you define a variable like `var files []file` somewhere in this source code does your code still compile? :)
