### ISSUE TITLE
swaggerignore on read/write

### ISSUE THREAD

**Issue by kfirfer** [swaggo/swag#875]
Hello

Would be nice to see ability to control wither the swaggerignore will be ignored on read/write

What I mean is that that we could control if its display on the request body/response body examples

e.g. 
```
`json:"name,omitempty" swaggerignore:"read,write"`
```

**Comment by ubogdan** [comment]
I was wondering why don't you use different objects for request and response if you need different definitions?

**Comment by kfirfer** [comment]
I want to make a contract between the db models and the dto(s) , and to avoid duplicate objects in the code

**Comment by ubogdan** [comment]
This is an Open Source project. Feel free to contribute with a PR for this feature and we will be more than happy to do CR for you.
