### ISSUE TITLE
Why not repeat key but separate them with commas when param dataType is array?

### ISSUE THREAD

**Issue by qiangshui** [swaggo/swag#877]
I want to pass a request parameter of type array, like this:
`/project?app=A&app=B`

I defined swagger description like this and use the gin method to get this appList:
```
// @Summary project展示
// @Tags 项目管理
// @Accept json
// @Produce json
// @Param app query []string true "app"
// @Success 200 {object} exception.Response "{"code":0,"data":{},"msg":"success"}"
// @Router /project [get]
func ListProjects(c *gin.Context) {
	appList := c.QueryArray("app")
        fmt.Println(len(appList))
        ...
}
```

The swagger ui as follow:
![image](https://user-images.githubusercontent.com/24819310/105955339-143dbb80-60b1-11eb-8cd3-4c18e791ce50.png)

But when I use swagger to request, the actual curl command is：
`curl -X GET "http://xxx/project?app=A,B" -H "accept: application/json"`

and the length of the appList is 1, app is "A,B", not what I expected [A B].

So why not repeat key but separate them with commas when param dataType is array? The current way of processing does not seem to conform to the meaning of array.

Please forgive my pool English.

**Comment by sdghchj** [comment]
Refer to `readme.md` for `General API Info` part

```
// @query.collection.format multi
```
