### ISSUE TITLE
go mod dependency resolution error

### ISSUE THREAD

**Issue by RoarkeRandall** [swaggo/swag#878]
**Describe the bug**
$ go mod tidy    
go: finding module for package golang.org/x/sys/execabs
gitlab.oc.redacted.com/redacted/experiments/cmd/server imports
        gitlab.oc.zillow.com/redacted/cgserver imports
        github.com/swaggo/http-swagger imports
        github.com/swaggo/swag imports
        golang.org/x/tools/go/loader imports
        golang.org/x/tools/go/internal/cgo imports
        golang.org/x/sys/execabs: module golang.org/x/sys@latest found (v0.0.0-20210124154548-22da62e12c0c, replaced by golang.org/x/sys@v0.0.0-20200826173525-f9321e4c35a6), but does not contain package golang.org/x/sys/execabs

**To Reproduce**
1. use http-swagger 
2. run go mod tidy or go get 

**Expected behavior**
go mod tidy should succeed

**Your swag version**
swaggo/swag -> 1.7.0
swaggo/http-swagger -> 1.0.0
swaggo/files -> v0.0.0-20190704085106-630677cd5c14

**Your go version**
go version go1.15.5 darwin/amd64

**Desktop (please complete the following information):**
 - OS: macOS big sur 11.1

**Comment by ubogdan** [comment]
I don't believe this is a swagger-related issue since we don't have a dependency on "golang.org/x/sys" or "golang.org/x/sys/execabs" on our `go.mod`` files even for `swag` or `http-swagger` packages.

**Comment by RoarkeRandall** [comment]
Oh sorry I forgot to close this. We had a custom override in our go.mod
file that caused this issue.
