### ISSUE TITLE
Not working @x-tagGroups annotation

### ISSUE THREAD

**Issue by donghoon-khan** [swaggo/swag#881]
**Describe the bug**
I am trying to use x-tagGroups to group my APIs under specific categories.
but it is not working.
this is my code:
```go
// @title MyAPI
// @version 0.0.1
// @description This is a api server
// @host localhost:9090
// @BasePath /api/v1
// @x-tagGroups [{"name": "Test", "tags": ["abc", "def"]}]
func main() {}
```

result:
```bash
$ swag init                                                           
2021/02/01 20:42:30 Generate swagger docs....
2021/02/01 20:42:30 Generate general API Info, search dir:./
2021/02/01 20:42:30 annotation @x-taggroups need a value
```

**Your swag version**
1.7.0

**Your go version**
1.15.2

**Desktop (please complete the following information):**
 - OS: macOS Catalina(10.15.7)

**Comment by ubogdan** [comment]
I believe the `x-` annotation is expecting a JSON object as documented [here](https://github.com/swaggo/swag#swag-cli) not an array.

**Comment by donghoon-khan** [comment]
thanks @ubogdan
