### ISSUE TITLE
cannot find type definition: sql.NullInt64

### ISSUE THREAD

**Issue by davisford** [swaggo/swag#882]
**Describe the bug**
We wrap the `sql.Null*` types from Go standard library in our own null types so we can override JSON marsha/unmarshal.

Example:

```go
// NullString is a wrapper around sql.NullString that provides proper json.Marshal
type NullString sql.NullString

// NullInt64 is a wrapper around sql.NullInt64 that provides proper json.Marshal
type NullInt64 sql.NullInt64

// NullInt32 is a wrapper around sql.NullInt32 that provides proper json.Marshal
type NullInt32 sql.NullInt32
```

When I upgraded from `swag` `v1.6.7` to `v1.7.0` this started happening when generating docs:

```
2021/02/08 11:04:31 Generating types.NullInt64
2021/02/08 11:04:31 ParseComment error in file internal/api/v1/routers/foobar/tx.go :cannot find type definition: sql.NullInt64
make: *** [swagger] Error 1
```

With version `v1.6.7` the CLI would not error out but occasionally I would get an error in the web site complaining about not have a definition for those types.  Now the tool is broken it seems.

**To Reproduce**
1. Define types like above.
2. Define a struct that uses it like this:

```go
type Foo struct {
   ID NullInt64 `json:'id"
}
```

3. Create a quick route that uses the type `Foo` 
4. Generate docs and see error

**Expected behavior**
I expect it to understand the type `sql.NullInt64` since it is defined in the standard library.

**Screenshots**

**Your swag version**
1.7.0

**Your go version**
1.15.7

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS
 - Browser: [e.g. chrome, safari] Brave
 - Version: [e.g. 22]

**Additional context**

**Comment by ubogdan** [comment]
`swag --parseDependency [your other params if any]` should do the trick. This super-secret param is actually documented [here](https://github.com/swaggo/swag#swag-cli).

**Comment by davisford** [comment]
Thanks for the tip.  Unfortunately, this is not resolving the issue for me.  If I don't add `--parseDepth 5` it chews up my CPU and eventually fails with it complaining it can't find an internal type (which has not failed before).  If I do add `--parseDepth` it again fails to resolve the go standard library `sql.NullString` type.

**Comment by davisford** [comment]
Resolved with https://github.com/swaggo/swag/issues/817#issuecomment-730962356

**Comment by roppa** [comment]
I had same issue with v1.7.1. None of the flags worked, maybe because we use vendor, not sure. I found a workaround by annotating structh wtih `swaggertype:"string"` which worked fine.

**Comment by smitpatelx** [comment]
```bash
swag init --parseDependency github.com/volatiletech/null/v8
```
This worked for me. for null string
