### ISSUE TITLE
Adding root level tags section

### ISSUE THREAD

**Issue by hylowaker** [swaggo/swag#896]
https://swagger.io/docs/specification/grouping-operations-with-tags/

I'd like to set global `tags` section as described in the link above.
But I couldn't find any feature related to it.

There was a similar issue (#876) but it is closed without any helpful comments.

**Comment by ubogdan** [comment]
Have you tried the `tags` annotation from [api-operation](https://github.com/swaggo/swag#api-operation) ?

**Comment by hylowaker** [comment]
That adds tags object inside _paths > (route) > (method)_.

But what I want is to add tags section in top level so that I can add descriptions or reorder the tags.

**Comment by xiaoxfan** [comment]
Hi, you could add multi root tags like bellow.
// @tag.name tag1
// @tag.description desc1
// @tag.name tag2
// @tag.description desc2
func main(){
}
