### ISSUE TITLE
Is it possible to mark every non pointer field as required?

### ISSUE THREAD

**Issue by sbstp** [swaggo/swag#901]
Hey, I would like swaggo to generate my swagger.json file so that every field which is not a pointer is marked as required. I know that you can add the `validate:"required` tag, but I would prefer to not have to do this explicitly everywhere.

Is it possible to do this?

**Comment by ubogdan** [comment]
well, everything is possible this change should be done in such way it won't alter the old behavior.

**Comment by fr3fou** [comment]
Has anyone found a solution to this yet?

**Comment by ubogdan** [comment]
@fr3fou The recommended way/solution is to use the `validate:"required" ` filed tag. Such a change @sbstp asked will break the backward compatibility and there is no way to go on that path.

**Comment by chiptus** [comment]
I still wish for this to happen. can we make --requiredByDefault be alse something like --requireBy=pointer.

not sure about the api, but this will make pointer fields optional by default and non pointer required
