### ISSUE TITLE
Flag --parseInternal crashed in Docker container

### ISSUE THREAD

**Issue by eduardo-mior** [swaggo/swag#902]
**Describe the bug**
The --parseInternal flag is too slow or does not work in a Docker container.
I'm working with Docker and using Dockerfile to execute the swag command and generate my project's documentation using Swaggo.
I recently had problems with the **postgres.Jsonb** data type, when I tried to generate the documentation it generated the following **cannot find type definition error: json.RawMessage**.
To work around this problem I discovered the --parseInternal flag that solves the problem. On my computer it worked without problems, but when I went to use it in Docker it was more than 1 hour processing and crashed.
On my Windows 10 computer everything works normal, on my AWS t3a.small instance using Amazon Linux 2 AMI with Docker, it doesn't work.

**Expected behavior**
I expected the documentation to be generated correctly without any problems.

**Your swag version**
1.7.0

**Your go version**
1.16.2

**Desktop (please complete the following information):**
 - Docker

**Additional context**
My Dockerfile:

```Dockerfile
FROM golang:alpine
COPY . $GOPATH/src/api
RUN apk add --no-cache bash git
WORKDIR $GOPATH/src/api

RUN go get
RUN go run $GOPATH/pkg/mod/github.com/swaggo/swag@v*/cmd/swag/main.go init --parseDependency --parseInternal
RUN go install

EXPOSE 8080

CMD [ "api" ]
```

My Struct:
```golang
// Company godoc
type Company struct {
	Id     int            `json:"id"    gorm:"primary_key:true; column:id"`
	Flags  postgres.Jsonb `json:"flags" gorm:"column:flags"`
}
```

My Controller (gin):
```golang
// CompanyCreate godoc
// @Tags Company 
// @Summary Create Company 
// @Description Create Company 
// @Accept json
// @Produce json
// @Security ApiKeyAuth
// @Param Request body Company true "Request body"
// @Success 200 {object} DefaultSuccess
// @Failure 400 {object} DefaultError
// @Router /company [post]
```

Command to reproduce the bug:
RUN go run $GOPATH/pkg/mod/github.com/swaggo/swag@v*/cmd/swag/main.go init --parseDependency --parseInternal

This command is equivalent to:
swag init --parseDependency --parseInternal

**Comment by vasia123** [comment]
Try  `--parseDepth 3` - i was able to solve my problem with `json.RawMessage` by specifying this flag.

**Comment by eduardo-mior** [comment]
It worked for me. Thank you very much. 
 
The complete command looks like this: **swag init --parseDependency --parseInternal --parseDepth 3**
