### ISSUE TITLE
Feature Request: Partially parse the dependencies.

### ISSUE THREAD

**Issue by CNLHC** [swaggo/swag#904]
I found that when using the `--parseDependency` flag,  parsing would become very slow in large project.

I believe somebody else is suffering from the same problem, like #515 .

Maybe it is possible to refer the `go test` command. If i want to test a single case, i  can just fire
```
go test -timeout 30s -run ^<SomeRegExp>$ <ModuleName> -v
```

So to the `swag` tool, a flag like `include` will be helpful.  For example, the command below will only parse the `github.com/lib/pq` module instead of scanning all of the dependencies.

```
swag init --parseDependency --include "^github.com/lib/pq/$"
```

Do you think adding a filter mechanism to this feature is a good idea?

**Comment by sdghchj** [comment]
--parseDepth 3

**Comment by CNLHC** [comment]
> --parseDepth 3

Merely setting depth constraint can not solve the problem because the dependencies tree may be fat but shallow.

**Comment by dskyu** [comment]
@CNLHC  can't agree more!

**Comment by zskylark** [comment]
说得太对了，只要注解里引用了外部公共包里的类型定义就解析半天，就算是指定parseDepth也无济于事，经常解析20分钟以上。

**Comment by SilverRainZ** [comment]
Does anyone work on this? This is a useful feature.

**Comment by SilverRainZ** [comment]
I've submitted a [PR](#1582) to fix the issue. If you guys are interested, you can check out the corresponding branch.
