### ISSUE TITLE
Required Go version in readme is wrong

### ISSUE THREAD

**Issue by andymcn** [swaggo/swag#913]
The project README.md clearly states that version 1.9 or newer of Go is needed. However, parser.go uses `strings.ReplaceAll`, which was introduced in 1.12.

Either the use of 1.12 functions should be removed or the readme should be updated to reflect reality.

**Comment by ubogdan** [comment]
the CI doesn't test the code against go 1.9 anymore and I believe updating the docs should be the best approach.
