### ISSUE TITLE
Swagger not parsing the 'Try it out' request body correctly

### ISSUE THREAD

**Issue by lus** [swaggo/swag#922]
**Describe the bug**
I defined an API route which creates an user account and annotated the method with every possible and mandatory body parameter. Howver, if I use the 'Try it out' button in the Swagger UI, it just passes the raw value of one of them into the request body.

**To Reproduce**
1. Annotate a method (I did it like this):
```go
// @description Creates a new account
// @tags accounts
// @summary Creates a new account
// @accept json,xml,x-www-form-urlencoded
// @produce json
// @param username body string true "the username of the account to create"
// @param password body string true "the plain password of the account to create"
// @param invite body string true "the invite code to use for the account creation"
// @success 201 {object} shared.Account
// @failure 400 {object} apiError
// @failure 412 {object} apiError
// @failure 409 {object} apiError
// @failure 500 {object} apiError
// @router /accounts [post]
```
2. Generate the API docs:
`swag init -g internal/api/api.go -o internal/docs --parseDependency`
3. Go to the Swagger UI and try it out.

**Expected behavior**
The JSON request body is assembled and sent correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/46935044/115745906-29ff0c00-a394-11eb-9fde-f36255c2c9c6.png)
![image](https://user-images.githubusercontent.com/46935044/115746087-52870600-a394-11eb-91da-77c5a6dd287d.png)

**Your swag version**
1.7.0

**Your go version**
1.16.3

**Desktop:**
 - OS: Arch Linux
 - Browser: Brave (chrome)
 - Version: 1.24.71

**Additional context**
It is possible that I messed something up while creating the documentation. If this is the case, I am sorry for the circumstances. I am not yet really experienced in creating OpenAPI specs.

**Comment by orionlu0916** [comment]
I just got the same issue today, and spent many hours to dig all the discussions. 
Finally, I got this https://github.com/swaggo/swag/issues/564#issuecomment-640040067

so, you have to create a new struct which just used for generating swagger documents.
In your case, you need to create something like:

```go
package requests

type CreateAccountRequest struct{
   //Note: to keep the "required" field highlighted in "Model" tab of the example block, put validate:"required" in your json tag section
   UserName string  'json:"username" validate:"required"`
   Password string  'json:"password" validate:"required"`
   Invite   string  'json:"invite"   validate:"required"`
}
```
In your swaggo comments section, add a parameter with name "payload", assigning your custom struct requests.CreateAccountRequest (package.structName) as your data type:
`// @Param payload body requests.CreateAccountRequest true "payload"` 

and you will get what you want : )

**Comment by lus** [comment]
Ah, that sounds like a reasonable workaround.
Thanks for your effort!

**Comment by lifegit** [comment]
> I just got the same issue today, and spent many hours to dig all the discussions.
> Finally, I got this [#564 (comment)](https://github.com/swaggo/swag/issues/564#issuecomment-640040067)
> 
> so, you have to create a new struct which just used for generating swagger documents.
> In your case, you need to create something like:
> 
> ```go
> package requests
> 
> type CreateAccountRequest struct{
>    //Note: to keep the "required" field highlighted in "Model" tab of the example block, put validate:"required" in your json tag section
>    UserName string  'json:"username" validate:"required"`
>    Password string  'json:"password" validate:"required"`
>    Invite   string  'json:"invite"   validate:"required"`
> }
> ```
> 
> In your swaggo comments section, add a parameter with name "payload", assigning your custom struct requests.CreateAccountRequest (package.structName) as your data type:
> `// @Param payload body requests.CreateAccountRequest true "payload"`
> 
> and you will get what you want : )


I don't think it's a good suggestion. If only one parameter is in post, Defining structures is cumbersome.
```
// @param username body string true "the username of the account to create"
// @param password body string true "the plain password of the account to create"
// @param invite body string true "the invite code to use for the account creation"
```
It should be automatically parsed into JSON

**Comment by ubogdan** [comment]
@lifegit, please look at the swag generated output when using your way and the struct way.

The following declaration works fine for `@accept: x-www-form-urlencoded `
```go
// @param username body string true "the username of the account to create"
```
You are actually complaining about how swagger-ui understands that parameters, when different accept encodings, are used.

See [doc](https://swagger.io/docs/specification/2-0/describing-request-body/) for future reference.

**Comment by schmuio** [comment]
This is not particularly useful, is it? I have the same issue and it seems the experience with this framework is pretty underwhelming.
