### ISSUE TITLE
swaggerignore only for @Param Request or just for Success Response

### ISSUE THREAD

**Issue by eduardo-mior** [swaggo/swag#924]
**Is your feature request related to a problem? Please describe.**
I have a struct with 30 fields, I receive 28 of these fields in the Body of the request, do a procedure and return the 30 fields in the response. I would like to use the same Struct to document the receipt and return of the data, but I would not like the Body's example to have those 2 fields that are not received.

**Describe the solution you'd like**
I wish there was a TAG that I could exclude this field from the Request or Response example.
I know that today there is a swaggerignore, but it excludes both the request and the response, and I would like to exclude only the request.

**Comment by sdghchj** [comment]
Structs are shared models for all requests and responses.

An alternative way is to wrap request in response.

type  Req struct {
   28 fields
}

type  Resp struct {
   Req
   other 2 fields
}
