### ISSUE TITLE
swag' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Magus370** [swaggo/swag#930]
**Describe the bug**
swag' is not recognized as an internal or external command

**To Reproduce**
Use " go get -u github.com/swaggo/swag/cmd/swag "
Make "swag init" in project
Swag is not ... 

**Your swag version**
The newest

**Your go version**
e.g. 1.15.8 

 - OS: Windows 7 64

GoPath: C:\Program Files\Projects\Go
Path: C:\Program Files\Go\bin;  C:\Program Files\Git\cmd;  C:\Program Files\MySQL\MySQL Server 8.0\bin; 
Project: C:\Program Files\Projects

**Comment by OneCricketeer** [comment]
Is `swag` available in `C:\Program Files\Go\bin` on your PATH?

**Comment by Magus370** [comment]
> Is `swag` available in `C:\Program Files\Go\bin` on your PATH?

No, i dont find him, but find in GoPath
Can i Just copy Go from project in  C:\Program Files\Go with no problem?

**Comment by OneCricketeer** [comment]
I don't think program files is the correct location for your GOBIN, so you should change that to be the correct location based on the GOPATH 

https://github.com/golang/go/issues/18583

**Comment by ubogdan** [comment]
This is not a swagger issue, it's related to GO setup.

**Comment by ShabirGitHub** [comment]
this worked for me
 `go install github.com/swaggo/swag/cmd/swag@latest`
