### ISSUE TITLE
ParseComment error in file src/xx/xx/xx.go :cannot find type definition: error

### ISSUE THREAD

**Issue by nurjamil** [swaggo/swag#932]
**Describe the bug**
the error always change from file to file

2021/05/07 14:46:17 Generate swagger docs....
2021/05/07 14:46:17 Generate general API Info, search dir:./
2021/05/07 14:46:17 warning: failed to get package name in dir: ./, error: execute go list command, exit status 1, stdout:, stderr:no Go files in /home/xxx/xx/xx/svc
2021/05/07 14:46:17 Generating entity.Meta
2021/05/07 14:46:17 ParseComment error in file src/handler/rest/freshdesk.go :cannot find type definition: error
make: *** [Makefile:35: swaggo] Error 1

**To Reproduce**

**Expected behavior**

**Screenshots**

**Your swag version**
e.g. 1.7.0

**Your go version**
e.g. 1.16.3

**Desktop (please complete the following information):**
 - OS: ubuntu 21.04
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
go mod swag version using 1.6.7

**Comment by nurjamil** [comment]
solved, just using the old swag..

**Comment by zoulux** [comment]
What about the new version？

**Comment by nurjamil** [comment]
> 
> 
> What about the new version？

its still not working, and im another mchine now using windows wsl2, how to use an old version, i thoguht it  was using go get -v, but it doesnt work now
