### ISSUE TITLE
If the type is a map, additional Prop1 keeps popping up

### ISSUE THREAD

**Issue by MunDeuksoo** [swaggo/swag#934]
AdditionalProp1 continues to appear in Ui when the above example is added to the properties.

Model

//example="{\"audio_codec\":\"22tcp\",\"audio_sample_rate\":22,\"audio_bitrate\":11111,\"audio_port\":123123}"
type NginxBroadCastOpenRes struct {
	ChannelKey		string						`json:"channel_key"`
	VideoProfiles	[]map[string]interface{}	`json:"video_profiles"`
	AudioProfile	map[string]interface{}		`json:"audio_profile"`
	StreamPluginId	int							`json:"stream_plugin_id"`
	Servers			[]map[string]interface{}	`json:"servers" example:"c1:sdf"`
	ErrorCode	 	string						`json:"error_code"`
}

Swagger Api
// @Success 200 {object} models.NginxBroadCastOpenRes{servers=[]object{ip=string},audio_profile=object{audio_codec=string,audio_sample_rate=int32,audio_bitrate=int32,audio_port=int32},video_profiles=[]object{video_codec=string,video_width=int32,video_height=int32,video_framerate=int32,video_bitrate=int64,video_port=int64}} "The ChannelKey Start Broadcast"

**Expected behavior**

**Screenshots**

**Your swag version**
v1.7.0

**Your go version**
1.16.3

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: chrome

**Additional context**
My goal now is to remove "additional Prop1" from the screen. If you add an example, it doesn't work, and if it's in Object format, the swag init doesn't work. Please do it quickly.

**Comment by ubogdan** [comment]
Hi @MunDeuksoo 
  In order to understand the issue can you please attach a picture with a prettified JSON and start explaining the issue from there.

**Comment by MunDeuksoo** [comment]
Hi @ubogdan 
I solved the problem above.
I'll close the issue now.

**Comment by SpaskeISO** [comment]
Hello @MunDeuksoo  can you please provide the fix I have the same problem.
