### ISSUE TITLE
swag init -d dir 

### ISSUE THREAD

**Issue by small-pineapple** [swaggo/swag#936]
dir must contain main.go? what if main.go and handler functions does not in same dir? 
```
root
   ----dirA
          ----main.go
   ----dirB
          ----handler.go
```
swag init -d ./dirA, there is nothing need parse
swag init -d ./dirB, report cannot find main.go

**Comment by jiurenm** [comment]
swag init -g ./dirA/main.go

**Comment by ubogdan** [comment]
It doesn't look like a bug. Closing.

**Comment by narenaryan** [comment]
I think the original question was misunderstood. If you want to generate Swagger code for dependencies, you can do it using:

`swag init --pd -d dirA`

Where option --pd means Parse go files in dependency folder and is disabled by default. Assuming handler package is a dependency for main package, you need that option to parse and include auto-generated swagger in docs.
