### ISSUE TITLE
Inline response structure definition

### ISSUE THREAD

**Issue by mblasi** [swaggo/swag#938]
**Is your feature request related to a problem? Please describe.**
I have a controller which resposes:

```
c.JSON(http.StatusOk, gin.H{"attr1": model.MyData{"key1":"value1"}, "attr2": model.MyOtherData{"key2":"value2"})
```

**Describe the solution you'd like**

I know that I could model that response in a struct, but I don't have it.
I would like to describe that response in the success annotation:

```
@success 200 {object} map[string]interface{"attr1": model.MayData, "attr2": model.MyOtherData}
```

**Describe alternatives you've considered**

```
@success 200 {json} {"attr1": model.MayData, "attr2": model.MyOtherData}
```

I was also trying with jsonresult, as documentation says:

```
@success 200 {object} jsonresult.JSONResult{"attr1": model.MayData, "attr2": model.MyOtherData}
```

But I understood that it assumes that I have a jsonresult package and a JSONResult struct there...

I'd appreciate to read your comments. :)

**Comment by hoshsadiq** [comment]
Have you tried `object{attr1=model.MayData, attr2=model.MyOtherData}`?

**Comment by mblasi** [comment]
Thank you @hoshsadiq !

I don't see that way in docs, but I tried anyway, like this:

```
// @Success 200 {object} object{'users': []model.User, 'request': model.Request, 'request_id': string}
```

And I get this error:

```
ParseComment error in file controller.go :invalid type: object{
```

Was it your suggestion? Or I missunderstood?

**Comment by hoshsadiq** [comment]
This works for me:
```
// @Success 200 {object} object{users=[]model.User}
```

**Comment by mblasi** [comment]
Thank you @hoshsadiq ! It was the ':' instead of '=', now it's working!

**Comment by mblasi** [comment]
Its me again... now the same issue but with @Param descriptor:

```
// @Param body body object {user=string, roles=string} true "User ID and comma separated roles"
```

Its fails as follows:

```
ParseComment error in file controllers/users.go :missing required param comment parameters "body body object {user=string, roles=string} true "User ID and comma separated roles""
```

What could I've missed?

**Comment by mblasi** [comment]
The issue is with spaces inside the object definition:

´´´
// @Param body body object{user=string,roles=string} true "User ID and comma separated roles"
´´´

Works perfectly!

**Comment by hotrungnhan** [comment]
please make a example , and describe it on document, i take many of hour to find this.
