### ISSUE TITLE
ParseComment error in file test.go :cannot find type definition: error

### ISSUE THREAD

**Issue by dreamsxin** [swaggo/swag#940]
**Describe the bug**

**To Reproduce**

`test.go` code
```go
type Message struct {
	Status   int64   `json:"status"`
	Msg      string  `json:"msg,omitempty"`
	Error     error   `json:"error,omitempty"`
}

// @Summary test
// @Description test
// @Tags test
// @accept json
// @Produce json
// @Success 200 {object} Message {"status":1, "data":null, "msg":"SUCCESS" }
// @Failure 400 {object} Message {"status":0, "data":null, "msg":"FAILD" }
// @Router /api/test [POST]
func test(c *gin.Context) {
}
```

run `swag init`

**Expected behavior**

**Screenshots**

**Your swag version**
e.g. 1.4.1

**Your go version**
e.g. 1.12.0

**Desktop (please complete the following information):**
 - OS: Window10

**Additional context**

**Comment by ubogdan** [comment]
Not sure what do you intend to accomplish, but as soon as an API returns dynamic responses you can't document all possible API response values :). Please notice the 5'ft parameter of `@succcess` or `@Failure` response is meant to describe the reason not the return value of the object.

**Comment by dreamsxin** [comment]
@ubogdan You are right, But the `error` type should be find definition.

**Comment by ubogdan** [comment]
error is an interface no a struct or a type.

**Comment by dreamsxin** [comment]
@ubogdan Thank you very match.
