### ISSUE TITLE
Ignore xml tag

### ISSUE THREAD

**Issue by luckybet100** [swaggo/swag#942]
When I type something like this

```
type User struct {
	XMLName  xml.Name `json:"-" xml:"User"`
	Email    string   `json:"email" xml:"Email"`
	AuthType string   `json:"auth_type" xml:"AuthType"`
}
```

In swagger I see:

<img width="623" alt="Снимок экрана 2021-06-06 в 03 20 01" src="https://user-images.githubusercontent.com/32256246/120908741-1672e080-c676-11eb-9773-55bbc0b13455.png">

I expect that auth_type should become AuthType, when I am opening xml response. As I see it uses json tags in xml

**Comment by ubogdan** [comment]
Well, I see your point but if you look at the generated swagger.json you will figure out the data model is unique (you can't have a different data model for the same resource type).
