### ISSUE TITLE
jsonapi support

### ISSUE THREAD

**Issue by fugkco** [swaggo/swag#946]
**Is your feature request related to a problem? Please describe.**
I'm currently developing an API that uses [jsonapi](https://jsonapi.org/) and I'm having to write extra *unused* boiler plate to support it with swaggo.

**Describe the solution you'd like**
I'd love a way to specify jsonapi as outputs. I'd love to be able to just do:
```go
// @Success 200 {object} models.User
func GetUser(userId string) {
// bla
}
```
instead of:
```go
type User struct {
	ID string `json:"id" example:"123"`
	Type       string              `json:"type" example:"users"`
	Attributes models.User `json:"attributes"`
}

// @Success 200 {object} User
func GetUser(userId string) {
// bla
}
```

Allowed the use of eitehr google/jsonapi or hashicorp/jsonapi would be a much nicer solution, than having to continually define redundant structs.

**Describe alternatives you've considered**
The only alternative is to specifically write otherwise structs that are used *purely* by swaggo that include the necessary properties for swaggo to support jsonapi. This is not idea.

**Additional context**
Ideally hashicorp/jsonapi is used over google/json, as it is slightly ahead.

**Comment by ubogdan** [comment]
Good luck.

**Comment by fugkco** [comment]
Thanks I guess? I was raising a feature request, you could have just said it's out of scope or something.

**Comment by ubogdan** [comment]
I don't think we can accommodate such a complex change any time soon. The scope of swag is to generate the documentation from existing code, and as far as I understand, you may like to be able to generate it from different spec types.
