### ISSUE TITLE
使用go mod以后，swag init 无法正确解析

### ISSUE THREAD

**Issue by zhuzongzhen** [swaggo/swag#947]
sangfor@Windows: spctl (master)✘  swag -v
swag version v1.7.0
sangfor@Windows: spctl (master)✘  swag init  -g cmd/example/apis.go --output ./doc/apis --parseDependency --parseVendor 
2021/06/22 10:59:28 Generate swagger docs....
2021/06/22 10:59:28 Generate general API Info, search dir:./
2021/06/22 10:59:28 warning: failed to get package name in dir: ./, error: execute go list command, exit status 1, stdout:, stderr:no Go files in /mnt/e/work/golang/spctl
2021/06/22 10:59:29 pkg code.sangfor.org/cp/spc/cmd/example cannot find all dependencies, unable to resolve root package
sangfor@Windows: spctl (master)✘  
sangfor@Windows: spctl (master)✘  ls
cmd  doc  go.mod  go.sum  Makefile  _out  pkg  README.md  sgp.json  tools  vendor
sangfor@Windows: spctl (master)✘  ls cmd/
example
sangfor@Windows: spctl (master)✘  ls cmd/example/
apis.go  flags.go  main.go  product.go
sangfor@Windows: spctl (master)✘  ls pkg/ vendor/
pkg/:
chan  cron  errno  i18n  init  product  restful  sdk  task  valid

vendor/:
code.sangfor.org  github.com  golang.org  gopkg.in  modules.txt  
sangfor@Windows: spctl (master)✘
sangfor@Windows: spctl (master)✘  go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/sangfor/.cache/go-build"
GOENV="/home/sangfor/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE="code.sangfor.org"
GOMODCACHE="/home/sangfor/go/pkg/mod"
GONOPROXY="code.sangfor.org"
GONOSUMDB="code.sangfor.org"
GOOS="linux"
GOPATH="/home/sangfor/go"
GOPRIVATE="code.sangfor.org"
GOPROXY="http://mirrors.sangfor.org/nexus/repository/go-proxy"
GOROOT="/home/sangfor/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/home/sangfor/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/mnt/e/work/golang/spctl/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build58076350=/tmp/go-build -gno-record-gcc-switches"

**Comment by sdghchj** [comment]
There must be some go files in your root directory to determine the root package path.
