### ISSUE TITLE
Avoid init() function in docs.go

### ISSUE THREAD

**Issue by ilyakaznacheev** [swaggo/swag#949]
**Is your feature request related to a problem? Please describe.**

I have generated several documentation files for different API versions. They are stored in different packages, and I want to serve the corresponding docs at different routes (`/v1/swagger`, `/v2/swagger`).

Bud due to generated init function I can import only one documentation file, the second import will cause a panic because they both try to register with the same name `swag.Name`.

```go
func init() {
	swag.Register(swag.Name, &s{})
}
```

**Describe the solution you'd like**

Remove `init()` function from autogenerated file at all and replace it with an explicit `Register` function call with a custom name specified.

**Describe alternatives you've considered**
When it is not possible, generate a unique name for each package with `docs.go` file.

**Additional context**
-

**Comment by ubogdan** [comment]
Hi @ilyakaznacheev,
  We are aware of this issue. Unfortunately, the proposed solution will introduce a breaking change to our existing users and this is unacceptable.

**Comment by ubogdan** [comment]
The only way to accommodate this change is to plan a change that may be done in v2.

**Comment by eduardo-mior** [comment]
I have the same problem.
I have internal documentation for my team and I have public documentation for other companies to consume. How can I solve?

**Comment by eduardo-mior** [comment]
I have the same problem.
I have internal documentation for my team and I have public documentation for other companies to consume. How can I solve?

**Comment by ubogdan** [comment]
Ok.

**Comment by ubogdan** [comment]
Update: since swag 1.7.4 there is an option to provide a name to each generated doc instance and this also enables you to import them in the same project.
