### ISSUE TITLE
使用 error interface  定义类型无效

### ISSUE THREAD

**Issue by shuqingzai** [swaggo/swag#951]
如果结构体内定义属性为 error 的interface，无法解析，就算是使用重新定位类型也是无效，我是用 [golang-module/carbon](https://github.com/golang-module/carbon) 定义时间格式
![image](https://user-images.githubusercontent.com/44406033/124430096-50ccbc00-dda1-11eb-993b-cc63fc46e6c7.png)
![image](https://user-images.githubusercontent.com/44406033/124430118-59bd8d80-dda1-11eb-9742-5063586243b1.png)
![image](https://user-images.githubusercontent.com/44406033/124430149-62ae5f00-dda1-11eb-8882-95e8734a8faa.png)
![image](https://user-images.githubusercontent.com/44406033/124430202-75289880-dda1-11eb-806a-c2ff953c9e0d.png)
解析到 error 接口时，无法解析，即使我修改类型tag，一样无效

**Comment by sdghchj** [comment]
一个时间戳不香？

**Comment by shuqingzai** [comment]
不是时间戳的问题，是swaggo不支持解析 error类型，即时指定数据类型，但是无法解析，如果是别的结构体加入error，一样解析不出来，理论上不应该这样

**Comment by sdghchj** [comment]
v1.6.9 swaggertype可行

**Comment by ubogdan** [comment]
Next time try please use english.
