### ISSUE TITLE
About minor errors in the documentation

### ISSUE THREAD

**Issue by kuhsinyv** [swaggo/swag#956]
**Describe the bug**
Cannot jump correctly in the document

**To Reproduce**
1. Go to [API操作](https://github.com/swaggo/swag/blob/master/README_zh-CN.md#api%E6%93%8D%E4%BD%9C)
2. Click on the `安全性` in description of the row `security`.
3. Nothing happens due to jumping to a non-existent anchor point.

**Expected behavior**
 Click on the `安全性` in description of the row `security`, and go to [安全性](https://github.com/swaggo/swag/blob/master/README_zh-CN.md#%E5%AE%89%E5%85%A8%E6%80%A7).

**Desktop (please complete the following information):**
 - OS: [e.g. archlinux]
 - Browser: [e.g. chrome]
 - Version: [e.g. 92.0.4515.107-1]

**Comment by ubogdan** [comment]
Fixed
