### ISSUE TITLE
FormData file array not supported

### ISSUE THREAD

**Issue by fr3fou** [swaggo/swag#965]
The following code doesn't work - 
```go
// meAvatarUpload uploads an avatar
// @ID meAvatarUpload
// @Tags me
// @Summary Uploads an avatar using S3 (by default)
// @Accept multipart/form-data
// @Produce json
// @Security requiredCookieAuth
// @Param image formData []file true "Image to upload"
//                        ^ this thing here
// @Success 200 {object} []mediaUploadResponse
// @Failure 400 {object} errorResponse "Bad Validation."
// @Failure default {object} errorResponse
// @Router /me/media [post]
```
It gives the following error
```console
 ParseComment error in file web/handle_me.go :file is not supported array type for formData
```

**Expected behavior**
To have correct code generated for `[]file`

**Your swag version**
1.7.0

**Your go version**
1.16.6

**Desktop**
 - OS: macOS 11.5

**Comment by Jaasdsa** [comment]
// @Param file formData file true "要上传的文件"

**Comment by fr3fou** [comment]
Why was this closed? `[]string` isn't correct, I want `[]file`

**Comment by ubogdan** [comment]
@fr3fou that parameter can't be a slice of `file` because `file` is not a GO struct or primitive.

**Comment by ddibiasi** [comment]
As I understand it, this is an inherent problem of OpenAPI 2.0. It is not possible to upload an arbitrary number of files.

References: 
- https://github.com/OAI/OpenAPI-Specification/issues/254
- https://swagger.io/docs/specification/2-0/file-upload/

**Comment by Mirobid2003** [comment]
how to fix []file don`t working

**Comment by arifmahmudrana** [comment]
When I tried to use
```go
// GetAllProductCategory godoc
// @Summary Get all product category
// @Tags Product
// @Description Get all product category
// @ID Get all productCategory
// @Accept  json
// @Produce  json
// @Security bearerAuth
// @Param countryID query string false "Country ID"
// @Param onlyActive query string false "Only Active (Default Value: 0)"
// @Param page query string false "Page Number (Default Value: 1)"
// @Param size query string false "Page Size (Default Value: 10)"
// @Param sort query string false "Sort Values [asc/desc] (Default Value: asc)"
// @Param keyword query string false "Search Keyword"
// @Param product_types query []entity.ProductType false "filter by product types 'LISTING', 'WEB_PRESENCE_ANALYSIS', 'WEBSITE', 'ADS', 'MY_BUSINESS', 'OTHER'"
// @Success 200 {object} entity.JSONResult{data=entity.ProductCategoryGetAllResp}
// @Failure 400 {object} entity.JSONResult{}
// @Failure 500 {object} entity.JSONResult{}
// @Router /product-category  [get]
```
Here I am using a custom `entity.ProductType` which is a custom type of string when I try run
```sh
swag init -g server.go --parseDependency --parseInternal
```
It failed with this message `ParseComment error in file /Users/arifmahmudrana/My-Works/billing-backend/controller/product_category_controller.go :entity.ProductType is not supported array type for query`

Then I had to change back to `[]string` then it worked any idea why it should work with any custom type but I wasn't able to
