### ISSUE TITLE
Any support for customized tag?

### ISSUE THREAD

**Issue by WaltCuller** [swaggo/swag#975]
**Is your feature request related to a problem? Please describe.**

Ex:
A resp sturct  added some customized tags: mock and dddddd.
```go
type TimeContainer struct {
	Name      types.StringAlias `json:"name" mock:"dddd" dddddd:"333"`
	Timestamp time.Time         `json:"timestamp" mock:"xxxx"`
	CreatedAt types.DateOnly    `json:"created_at" mock:"cccc"`
}
```
Finally want swagger.json and swagger.yaml like this.

![image](https://user-images.githubusercontent.com/34122242/129168942-524c0b43-467c-49d7-9a54-1b4ebb992232.png)
![image](https://user-images.githubusercontent.com/34122242/129169078-31d9805d-778b-4331-9b19-19dd7dbda7e1.png)

**Describe the solution you'd like**
`go-openapi `defined the  `spec.Schema`, maybe we could use the ExtraProps to store customized tags and tag value.
```go
type Schema struct {
	VendorExtensible
	SchemaProps
	SwaggerSchemaProps
	ExtraProps map[string]interface{} `json:"-"`
}

```

**Comment by ubogdan** [comment]
@WaltCuller I don't see a feature in this. Can you give us more insights and how this kind of change will provide additional value to swag?
