### ISSUE TITLE
Serving swag document without any other GoWebFramework

### ISSUE THREAD

**Issue by hoangtuan151** [swaggo/swag#98]
Hi, could you update the README to show an example of how to using swagger.json(yaml) directly in a Go Web App alone, not with any GoWebFramework?

**Comment by pei0804** [comment]
I already created example.
Do you want to don't use swaggo middleware?

**Comment by hoangtuan151** [comment]
Hi,

I saw that all examples in https://github.com/swaggo/swag/tree/master/example are all using GIN framework.

Suppose that I already run "swag init" and having following folder struct:
```
root_web_folder/
\__ docs
\__ \__ swagger
\__ \__ \__ swagger.json
\__ \__ \__ swagger.yaml
```

I want to use pure Go for my Web App
```
func main() {
	http.HandleFunc("/", HandlerFunc_1)
	http.ListenAndServe(":8080", nil)
}
```

So, how could I provide an API friendly swagger web page to other developer in my team?

**Comment by pei0804** [comment]
Do you want to this? https://github.com/swaggo/http-swagger

**Comment by hoangtuan151** [comment]
Thanks @pei0804 , @easonlin404 
I've got the idea from your help.

**Comment by warent** [comment]
It took me forever to find this... Highly recommend adding https://github.com/swaggo/http-swagger to the readme please!
