### ISSUE TITLE
How to access swagger raw json

### ISSUE THREAD

**Issue by vbisbest** [swaggo/swag#982]
In order to use a tool like "swagger editor", you need to get the raw json file.  Is there a way to access that with this implementation.  I can only seem to get the swagger UI to show.  Thanks!

**Comment by naftulikay** [comment]
Within the Swagger UI, do a <kbd>Ctrl</kbd>+<kbd>F</kbd> and search for `doc.json`. It should be up near the top near your API name and description. You'll see a link to `doc.json`. 

In my application, I have `/swagger/*` mounted for the Swagger UI endpoints, and I'm listening on port 8080. Therefore, for me, the JSON is available at http://localhost:8080/swagger/doc.json

**Comment by vbisbest** [comment]
Perfect, thank you.
