### ISSUE TITLE
go-chi middleware

### ISSUE THREAD

**Issue by jeffreydwalter** [swaggo/swag#993]
Hello, I have ported your `gin-swagger` middleware to `go-chi` and am going to contribute it to the `go-chi` community. Would you like to include a link to it on your README?

**Comment by ubogdan** [comment]
Can you give us more details or a code example so we can understand better what is this middleware do? 

Does this have anything to do with our HTTP [handler](https://github.com/swaggo/http-swagger/blob/master/example/go-chi/main.go)?

**Comment by jeffreydwalter** [comment]
Nevermind, I didn't realize this package had support for the http handler which works with chi. Cheers.
