### ISSUE TITLE
Pull more validations from the validate tag e.g. oneof

### ISSUE THREAD

**Issue by silverark** [swaggo/swag#995]
I'm using playground validator package on my models: https://github.com/go-playground/validator

This puts all validation options in the `validate` field as shown below.
```
PasswordQuality   string    `json:"password_quality" validate:"required,oneof=NONE NUMERIC ALPHANUMERIC" example:"ALPHANUMERIC"`
```

 I can see that you currently read the `required` from the `validate` tag, but nothing else. Is it possible to pull the option of `oneof`, `min`, `max` and `unique` from the validate field for the docs? This will save me having to repeat the options as `enum`, `minimum` and `maximum` tags for example 

If it would be useful and would be accepted, I could attempt a pull request.

**Comment by ubogdan** [comment]
@silverark if you add the necessary unit tests I will be more than happy to do a CR.
