### ISSUE TITLE
Param body isn't parse Struct one by one but object

### ISSUE THREAD

**Issue by hotrungnhan** [swaggo/swag#998]
**Describe the bug**

**To Reproduce**

**Expected behavior**
Param body should parse one by one but object
**Screenshots**
![image](https://user-images.githubusercontent.com/40029631/133851916-6237285b-4e86-4a19-9d01-36699635e4af.png)

**Your swag version**
e.g. 1.4.1

**Your go version**
e.g. 1.17.1

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
```go
// @Param default body models.SignUp true "sign up"
```

**Comment by hotrungnhan** [comment]
it should have another tag for request body.
like @requestbody same as @success

**Comment by hotrungnhan** [comment]
oh i search and know that requestBody key is offical support by OpenAPI 3.0. should you have any plan for this

**Comment by sdghchj** [comment]
Now it takes body as a whole object

**Comment by ubogdan** [comment]
Just because we like to keep it simple, we are good with `@param` annotation.

**Comment by arantesxyz** [comment]
Is there any plans to implement this? Using it as a parameter breaks codegen.
